// Generated by nexgen latest. DO NOT EDIT!

import * as nexus from "nexus-rpc";
import {
  activityOptionsTransferTypeConverter,
  failureContainerTransferTypeConverter,
} from "./models";
import type { ActivityOptions, FailureContainer } from "./models";

export const typeRoundtripService = nexus.service("TypeRoundtripService", {
  activityOptionsOperation: nexus.operation<ActivityOptions, ActivityOptions>({
    name: "ActivityOptionsOperation",
    inputType: { transferTypeConverter: activityOptionsTransferTypeConverter },
    outputType: { transferTypeConverter: activityOptionsTransferTypeConverter },
  }),
  failureOperation: nexus.operation<FailureContainer, FailureContainer>({
    name: "FailureOperation",
    inputType: { transferTypeConverter: failureContainerTransferTypeConverter },
    outputType: { transferTypeConverter: failureContainerTransferTypeConverter },
  }),
});

export const operationRegistry = [
  {
    service: "TypeRoundtripService",
    operation: "ActivityOptionsOperation",
  },
  {
    service: "TypeRoundtripService",
    operation: "FailureOperation",
  },
] as const;
