// Generated by nexgen latest. DO NOT EDIT!

import * as nexus from "nexus-rpc";
import type { temporal } from "@temporalio/proto";
import {
  activityOptionsTransferTypeConverter,
  failureContainerTransferTypeConverter,
} from "./models";
import type { ActivityOptions, FailureContainer } from "./models";

export const typeRoundtripService = nexus.service("TypeRoundtripService", {
  activityOptionsOperation: nexus.operation<
    ActivityOptions,
    temporal.api.activity.v1.IActivityOptions
  >({
    name: "ActivityOptionsOperation",
    inputType: { transferTypeConverter: activityOptionsTransferTypeConverter },
  }),
  failureOperation: nexus.operation<
    FailureContainer,
    temporal.api.command.v1.IFailWorkflowExecutionCommandAttributes
  >({
    name: "FailureOperation",
    inputType: { transferTypeConverter: failureContainerTransferTypeConverter },
  }),
});

export const operationRegistry = [
  {
    service: "TypeRoundtripService",
    operation: "ActivityOptionsOperation",
  },
  {
    service: "TypeRoundtripService",
    operation: "FailureOperation",
  },
] as const;
