// Generated by nexgen latest. DO NOT EDIT!

import * as nexus from "nexus-rpc";
import * as workflow from "@temporalio/workflow";
import {
  getShowcaseInputTransferTypeConverter,
  showcaseTransferTypeConverter,
} from "./models";
import type { GetShowcaseInput, Showcase } from "./models";

/**
 * Fetch the showcase payload. Also exercises the service-level `x-<lang>-name`
 * override: the emitted service code identifier is renamed to the derived name plus a
 * per-language suffix (Go var `ShowcaseServiceGo`, TS const `showcaseServiceTs`, Python
 * class `ShowcaseServicePy`, Java interface `ShowcaseServiceJava`) while the wire
 * service name / `@Service` / `ServiceName` string stays
 * `example.showcase.v1.ShowcaseService`.
 */
export const showcaseServiceTs = nexus.service("example.showcase.v1.ShowcaseService", {
  /**
   * Fetch a showcase by id. Also exercises the operation-level `x-<lang>-name`
   * override: the emitted operation code identifier is renamed to the derived name plus
   * a per-language suffix (Go `GetShowcaseGo`, TS `getShowcaseTs`, Python
   * `get_showcase_py`, Java `getShowcaseJava`) while the wire operation name stays
   * `GetShowcase` and the synthesized I/O type stays `GetShowcaseInput` (derived from
   * the operation key, not the override).
   */
  getShowcaseTs: nexus.operation<GetShowcaseInput, Showcase>({
    name: "GetShowcase",
    inputType: { transferTypeConverter: getShowcaseInputTransferTypeConverter },
    outputType: { transferTypeConverter: showcaseTransferTypeConverter },
  }),
});

/**
 * Fetch the showcase payload. Also exercises the service-level `x-<lang>-name`
 * override: the emitted service code identifier is renamed to the derived name plus a
 * per-language suffix (Go var `ShowcaseServiceGo`, TS const `showcaseServiceTs`, Python
 * class `ShowcaseServicePy`, Java interface `ShowcaseServiceJava`) while the wire
 * service name / `@Service` / `ServiceName` string stays
 * `example.showcase.v1.ShowcaseService`.
 */
export class ShowcaseServiceClient {
  private readonly client: workflow.NexusServiceClient<typeof showcaseServiceTs>;

  public constructor(endpoint: string) {
    this.client = workflow.createNexusServiceClient({
      service: showcaseServiceTs,
      endpoint,
    });
  }

  /**
   * Fetch a showcase by id. Also exercises the operation-level `x-<lang>-name`
   * override: the emitted operation code identifier is renamed to the derived name plus
   * a per-language suffix (Go `GetShowcaseGo`, TS `getShowcaseTs`, Python
   * `get_showcase_py`, Java `getShowcaseJava`) while the wire operation name stays
   * `GetShowcase` and the synthesized I/O type stays `GetShowcaseInput` (derived from
   * the operation key, not the override).
   *
   * @param request - Request for the operation.
   */
  public async getShowcaseTs(
    request: GetShowcaseInput,
  ): Promise<workflow.NexusOperationHandle<Showcase>> {
    return await this.client.startOperation(
      showcaseServiceTs.operations.getShowcaseTs,
      request,
    );
  }
}

export const operationRegistry = [
  {
    service: "example.showcase.v1.ShowcaseService",
    operation: "GetShowcase",
    inputType: "ShowcaseService.GetShowcaseInput",
    outputType: "Showcase",
    inputPayloadVisitor: "walkGetShowcaseInput",
    outputPayloadVisitor: "walkShowcase",
  },
] as const;
