// Generated by nexgen latest. DO NOT EDIT!

import { ApplicationFailure } from "@temporalio/common";

/** A single constraint failure, located by JSON path. */
export interface Violation {
  readonly path: string;
  readonly reason: string;
}

export function isPlainObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

export function memberPath(key: string): string {
  return /^[A-Za-z_][A-Za-z0-9_]*$/u.test(key)
    ? key
    : `["${key.replaceAll("\\", "\\\\").replaceAll('"', '\\"')}"]`;
}

export function collect(violations: Violation[], path: string, error: unknown): void {
  if (
    error instanceof ApplicationFailure &&
    error.type === "PayloadValidationError" &&
    Array.isArray(error.details?.[0])
  ) {
    // Generated failures keep the original array as their first detail; this cast performs no serialization.
    const nestedViolations = error.details?.[0] as Violation[];
    for (const inner of nestedViolations) {
      const nested = !inner.path
        ? path
        : inner.path.startsWith("[")
          ? `${path}${inner.path}`
          : `${path}.${inner.path}`;
      violations.push({ path: nested, reason: inner.reason });
    }
  } else {
    violations.push({ path, reason: String(error) });
  }
}
