// Generated by nexgen latest. DO NOT EDIT!

import * as nexus from "nexus-rpc";
import * as workflow from "@temporalio/workflow";
import {
  getRoomInputTransferTypeConverter,
  roomTransferTypeConverter,
  sendMessageInputTransferTypeConverter,
  sendMessageOutputTransferTypeConverter,
} from "./models";
import type { GetRoomInput, Room, SendMessageInput, SendMessageOutput } from "./models";

/**
 * Send messages and look up rooms.
 */
export const chatService = nexus.service("example.chat.v1.ChatService", {
  /**
   * Post a message to a room.
   */
  sendMessage: nexus.operation<SendMessageInput, SendMessageOutput>({
    name: "SendMessage",
    inputType: { transferTypeConverter: sendMessageInputTransferTypeConverter },
    outputType: { transferTypeConverter: sendMessageOutputTransferTypeConverter },
  }),
  /**
   * Look up a room by id.
   */
  getRoom: nexus.operation<GetRoomInput, Room>({
    name: "GetRoom",
    inputType: { transferTypeConverter: getRoomInputTransferTypeConverter },
    outputType: { transferTypeConverter: roomTransferTypeConverter },
  }),
  /**
   * Liveness probe.
   */
  ping: nexus.operation<void, void>({ name: "Ping" }),
});

/**
 * Send messages and look up rooms.
 */
export class ChatServiceClient {
  private readonly client: workflow.NexusServiceClient<typeof chatService>;

  public constructor(endpoint: string) {
    this.client = workflow.createNexusServiceClient({
      service: chatService,
      endpoint,
    });
  }

  /**
   * Post a message to a room.
   *
   * @param request - Request for the operation.
   */
  public async sendMessage(
    request: SendMessageInput,
  ): Promise<workflow.NexusOperationHandle<SendMessageOutput>> {
    return await this.client.startOperation(
      chatService.operations.sendMessage,
      request,
    );
  }

  /**
   * Look up a room by id.
   *
   * @param request - Request for the operation.
   */
  public async getRoom(
    request: GetRoomInput,
  ): Promise<workflow.NexusOperationHandle<Room>> {
    return await this.client.startOperation(chatService.operations.getRoom, request);
  }

  /**
   * Liveness probe.
   */
  public async ping(): Promise<workflow.NexusOperationHandle<void>> {
    return await this.client.startOperation(chatService.operations.ping, undefined);
  }
}

export const operationRegistry = [
  {
    service: "example.chat.v1.ChatService",
    operation: "SendMessage",
  },
  {
    service: "example.chat.v1.ChatService",
    operation: "GetRoom",
  },
  {
    service: "example.chat.v1.ChatService",
    operation: "Ping",
  },
] as const;
