# Generated by nexgen. DO NOT EDIT!

from __future__ import annotations

import typing
import temporalio.workflow

from ..models import (
    GenericRequest,
    GenericResponse,
    Inner,
)


ContextT = typing.TypeVar("ContextT")


async def _complete(
    request: GenericRequest[ContextT],
) -> temporalio.workflow.NexusOperationHandle[
    GenericResponse[ContextT, object, object],
]:
    nexus_client = temporalio.workflow.create_nexus_client(
        service="GenericModelService",
        endpoint="generic-models",
    )
    return typing.cast(
        temporalio.workflow.NexusOperationHandle[
            GenericResponse[ContextT, object, object],
        ],
        await nexus_client.start_operation(
            operation="Complete",
            input=request,
            output_type=GenericResponse,
        ),
    )


async def complete(
    *,
    context: ContextT,
    contexts: list[ContextT] | None = None,
    by_name: dict[str, ContextT] | None = None,
    nested: Inner[ContextT],
) -> temporalio.workflow.NexusOperationHandle[
    GenericResponse[ContextT, object, object],
]:
    request = GenericRequest(
        context=context,
        contexts=contexts or [],
        by_name=by_name or {},
        nested=nested,
    )
    return await _complete(request)
