# Generated by nexgen. DO NOT EDIT!

from __future__ import annotations

import typing
import temporalio.workflow

from ..models import (
    GenericRequest,
    Inner,
    ReuseCompletionResult,
)


ContextT = typing.TypeVar("ContextT")


async def _reuse_complete(
    request: GenericRequest[ContextT],
) -> temporalio.workflow.NexusOperationHandle[ReuseCompletionResult[object],]:
    nexus_client = temporalio.workflow.create_nexus_client(
        service="GenericModelService",
        endpoint="generic-models",
    )
    return typing.cast(
        temporalio.workflow.NexusOperationHandle[ReuseCompletionResult[object],],
        await nexus_client.start_operation(
            operation="ReuseComplete",
            input=request,
            output_type=ReuseCompletionResult[typing.Any],
        ),
    )


async def reuse_complete(
    *,
    context: ContextT,
    contexts: list[ContextT] | None = None,
    by_name: dict[str, ContextT] | None = None,
    nested: Inner[ContextT],
) -> temporalio.workflow.NexusOperationHandle[ReuseCompletionResult[object],]:
    request = GenericRequest(
        context=context,
        contexts=contexts or [],
        by_name=by_name or {},
        nested=nested,
    )
    return await _reuse_complete(request)
