// Generated by nexgen latest. DO NOT EDIT!

import type { TransferTypeConverter } from "nexus-rpc";
import { createPayloadValidationError } from "@temporalio/common";
import * as __nexgenDefinitions from "../../definitions";
import { blockTransferTypeConverter } from "../block/models";
import type { Block } from "../block/models";

export function requiredField<T>(
  value: T | null | undefined,
  owner: string,
  field: string,
): T {
  if (value == null) {
    throw new Error(`missing required field ${owner}.${field}`);
  }
  return value;
}

/**
 * A page. One half of the Page <-> Block cross-file cycle. Because the cycle spans two
 * input files, Page and Block hoist together into Python's _recursive.py; the
 * non-cyclic PageMeta helper stays in this module.
 */
export interface Page {
  pageId: string;
  title: string;
  meta: PageMeta;
  /**
   * Ordered content blocks. Cross-file `$ref` to block.json (same directory); the array
   * is the terminating edge of the cycle.
   */
  blocks?: Block[];
}

/**
 * Non-cyclic helper. Referenced only by Page, references nothing recursive, so it stays
 * in the content_page module even though Page is hoisted.
 */
export interface PageMeta {
  author: string;
  wordCount?: number;
}

export const pageTransferTypeConverter =
  new (class implements TransferTypeConverter<Page> {
    public fromTransferType(raw: unknown): Page {
      const violations: __nexgenDefinitions.Violation[] = [];
      if (!__nexgenDefinitions.isPlainObject(raw)) {
        throw createPayloadValidationError([{ path: "", reason: "expected object" }]);
      }

      let pageId: string = undefined as unknown as string;
      if (
        !Object.prototype.hasOwnProperty.call(raw, "pageId") ||
        raw["pageId"] === null
      ) {
        violations.push({ path: "pageId", reason: "required" });
      } else {
        if (typeof raw["pageId"] !== "string") {
          violations.push({ path: "pageId", reason: "expected string" });
        } else {
          pageId = raw["pageId"];
        }
      }

      let title: string = undefined as unknown as string;
      if (
        !Object.prototype.hasOwnProperty.call(raw, "title") ||
        raw["title"] === null
      ) {
        violations.push({ path: "title", reason: "required" });
      } else {
        if (typeof raw["title"] !== "string") {
          violations.push({ path: "title", reason: "expected string" });
        } else {
          title = raw["title"];
        }
      }

      let meta: PageMeta = undefined as unknown as PageMeta;
      if (!Object.prototype.hasOwnProperty.call(raw, "meta") || raw["meta"] === null) {
        violations.push({ path: "meta", reason: "required" });
      } else {
        try {
          meta = pageMetaTransferTypeConverter.fromTransferType(raw["meta"]);
        } catch (error) {
          __nexgenDefinitions.collect(violations, "meta", error);
        }
      }

      let blocks: Block[] | undefined = undefined as unknown as Block[] | undefined;
      if (
        Object.prototype.hasOwnProperty.call(raw, "blocks") &&
        raw["blocks"] === null
      ) {
        violations.push({ path: "blocks", reason: "explicit null not allowed" });
      } else if (Object.prototype.hasOwnProperty.call(raw, "blocks")) {
        if (!Array.isArray(raw["blocks"])) {
          violations.push({ path: "blocks", reason: "expected array" });
        } else {
          blocks = [];
          raw["blocks"].forEach((element: unknown, index: number) => {
            let item: Block = undefined as unknown as Block;
            try {
              item = blockTransferTypeConverter.fromTransferType(element);
            } catch (error) {
              __nexgenDefinitions.collect(violations, `blocks[${index}]`, error);
            }
            if (item !== undefined) {
              blocks!.push(item);
            }
          });
        }
      }

      for (const key of Object.keys(raw)) {
        if (key !== "pageId" && key !== "title" && key !== "meta" && key !== "blocks") {
          violations.push({
            path: __nexgenDefinitions.memberPath(key),
            reason: "unknown field",
          });
        }
      }

      if (violations.length) {
        throw createPayloadValidationError(violations);
      }
      const out: Page = { pageId, title, meta };
      if (blocks !== undefined) {
        out.blocks = blocks;
      }
      return out;
    }

    public toTransferType(value: Page): unknown {
      const candidate: unknown = value;
      if (!__nexgenDefinitions.isPlainObject(candidate)) {
        throw createPayloadValidationError([{ path: "", reason: "expected object" }]);
      }
      const violations: __nexgenDefinitions.Violation[] = [];
      const out: Record<string, unknown> = Object.create(null) as Record<
        string,
        unknown
      >;
      if (value.pageId === undefined || value.pageId === null) {
        violations.push({ path: "pageId", reason: "required" });
      } else {
        if (!(typeof value.pageId === "string")) {
          violations.push({ path: "pageId", reason: "expected string" });
        }
        out["pageId"] = value.pageId;
      }
      if (value.title === undefined || value.title === null) {
        violations.push({ path: "title", reason: "required" });
      } else {
        if (!(typeof value.title === "string")) {
          violations.push({ path: "title", reason: "expected string" });
        }
        out["title"] = value.title;
      }
      if (value.meta === undefined || value.meta === null) {
        violations.push({ path: "meta", reason: "required" });
      } else {
        const metaViolationCount = violations.length;
        if (violations.length === metaViolationCount) {
          out["meta"] = (() => {
            try {
              return pageMetaTransferTypeConverter.toTransferType(value.meta);
            } catch (error) {
              __nexgenDefinitions.collect(violations, "meta", error);
              return undefined;
            }
          })();
        }
      }
      if (value.blocks !== undefined) {
        if (value.blocks === null) {
          violations.push({ path: "blocks", reason: "explicit null not allowed" });
        } else {
          const blocksViolationCount = violations.length;
          if (!Array.isArray(value.blocks)) {
            violations.push({ path: "blocks", reason: "expected array" });
          } else {
            value.blocks.forEach((element, index) => {});
          }
          if (violations.length === blocksViolationCount) {
            out["blocks"] = value.blocks.map((element, index) =>
              (() => {
                try {
                  return blockTransferTypeConverter.toTransferType(element);
                } catch (error) {
                  __nexgenDefinitions.collect(violations, `blocks[${index}]`, error);
                  return undefined;
                }
              })(),
            );
          }
        }
      }
      if (violations.length) {
        throw createPayloadValidationError(violations);
      }
      return out;
    }
  })();

export const pageMetaTransferTypeConverter =
  new (class implements TransferTypeConverter<PageMeta> {
    public fromTransferType(raw: unknown): PageMeta {
      const violations: __nexgenDefinitions.Violation[] = [];
      if (!__nexgenDefinitions.isPlainObject(raw)) {
        throw createPayloadValidationError([{ path: "", reason: "expected object" }]);
      }

      let author: string = undefined as unknown as string;
      if (
        !Object.prototype.hasOwnProperty.call(raw, "author") ||
        raw["author"] === null
      ) {
        violations.push({ path: "author", reason: "required" });
      } else {
        if (typeof raw["author"] !== "string") {
          violations.push({ path: "author", reason: "expected string" });
        } else {
          author = raw["author"];
        }
      }

      let wordCount: number | undefined = undefined as unknown as number | undefined;
      if (
        Object.prototype.hasOwnProperty.call(raw, "wordCount") &&
        raw["wordCount"] === null
      ) {
        violations.push({ path: "wordCount", reason: "explicit null not allowed" });
      } else if (Object.prototype.hasOwnProperty.call(raw, "wordCount")) {
        if (
          typeof raw["wordCount"] !== "number" ||
          !Number.isSafeInteger(raw["wordCount"])
        ) {
          violations.push({ path: "wordCount", reason: "expected integer" });
        } else {
          wordCount = raw["wordCount"];
        }
      }

      for (const key of Object.keys(raw)) {
        if (key !== "author" && key !== "wordCount") {
          violations.push({
            path: __nexgenDefinitions.memberPath(key),
            reason: "unknown field",
          });
        }
      }

      if (violations.length) {
        throw createPayloadValidationError(violations);
      }
      const out: PageMeta = { author };
      if (wordCount !== undefined) {
        out.wordCount = wordCount;
      }
      return out;
    }

    public toTransferType(value: PageMeta): unknown {
      const candidate: unknown = value;
      if (!__nexgenDefinitions.isPlainObject(candidate)) {
        throw createPayloadValidationError([{ path: "", reason: "expected object" }]);
      }
      const violations: __nexgenDefinitions.Violation[] = [];
      const out: Record<string, unknown> = Object.create(null) as Record<
        string,
        unknown
      >;
      if (value.author === undefined || value.author === null) {
        violations.push({ path: "author", reason: "required" });
      } else {
        if (!(typeof value.author === "string")) {
          violations.push({ path: "author", reason: "expected string" });
        }
        out["author"] = value.author;
      }
      if (value.wordCount !== undefined) {
        if (value.wordCount === null) {
          violations.push({ path: "wordCount", reason: "explicit null not allowed" });
        } else {
          if (
            !(typeof value.wordCount === "number" && Number.isInteger(value.wordCount))
          ) {
            violations.push({ path: "wordCount", reason: "expected integer" });
          } else {
            if (!Number.isSafeInteger(value.wordCount)) {
              violations.push({
                path: "wordCount",
                reason: "exceeds ±(2^53-1) integer cap",
              });
            }
          }
          out["wordCount"] = value.wordCount;
        }
      }
      if (violations.length) {
        throw createPayloadValidationError(violations);
      }
      return out;
    }
  })();
