# Generated by nexgen v0.2.1. DO NOT EDIT!

from __future__ import annotations

import base64
import collections.abc
import dataclasses
import datetime
import json
import re
import typing
import temporalio.converter


__all__ = [
    "ValidationError",
    "Violation",
    "_check_contains",
    "_check_date_time",
    "_check_duration",
    "_check_time",
    "_check_unique_items",
    "_collect",
    "_json_values_equal",
    "_format_base64",
    "_format_base64url",
    "_format_date",
    "_format_date_time",
    "_format_duration",
    "_format_time",
    "_parse_base64",
    "_parse_base64url",
    "_parse_date",
    "_parse_date_time",
    "_parse_duration",
    "_parse_spec_integer",
    "_parse_time",
    "_quote",
    "_transfer_type_convertible",
]


@dataclasses.dataclass(frozen=True, slots=True)
class Violation:
    """A single constraint failure, located by JSON path."""

    path: str
    reason: str


class ValidationError(Exception):
    """Every constraint failure found in one (de)serialization pass."""

    violations: list[Violation]

    def __init__(self, violations: list[Violation]) -> None:
        self.violations = violations
        detail = "; ".join(f"{item.path}: {item.reason}" for item in violations)
        super().__init__(f"{len(violations)} validation error(s): {detail}")


def _quote(value: object) -> str:
    """Renders a value in the JSON form every target quotes offending values in."""

    try:
        return json.dumps(value, ensure_ascii=False)
    except (TypeError, ValueError):
        return repr(value)


def _collect(violations: list[Violation], path: str, error: ValidationError) -> None:
    """Re-paths a nested model's violations under `path` and appends them."""

    for inner in error.violations:
        # A nested violation about the value *itself* carries no path of its own
        # (a union branch's own constraint, an element-level check), so the
        # prefix is the whole path -- never a dangling separator (P11).
        nested = f"{path}.{inner.path}" if inner.path else path
        violations.append(Violation(path=nested, reason=inner.reason))


_ModelT = typing.TypeVar("_ModelT")


def _transfer_type_convertible(
    converter: type[temporalio.converter.TransferTypeConverter[typing.Any, typing.Any]],
) -> collections.abc.Callable[[type[_ModelT]], type[_ModelT]]:
    """Registers a transfer type converter on a model class.

    Wraps `temporalio.converter.transfer_type_convertible` to erase the
    converter's value-type parameter. Binding it directly on the decorated class
    is circular for a static type checker -- the class's type depends on the
    decorator, whose value type depends on the class -- which degrades the model
    to `Unknown`. Erasing it here keeps the decorator idiomatic at each model and
    resolves the cycle.
    """

    return temporalio.converter.transfer_type_convertible(converter)


_INTEGER_CAP = (1 << 53) - 1


def _parse_spec_integer(
    value: object, path: str, violations: list[Violation]
) -> int | None:
    """Parses a JSON number as a spec integer (`1.0` accepted, `1.5` rejected)."""

    # `bool` is a subclass of `int`, so it must be excluded before the int check.
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        violations.append(Violation(path=path, reason="expected integer"))
        return None
    if isinstance(value, float):
        if not value.is_integer():
            violations.append(Violation(path=path, reason="expected integer"))
            return None
        out = int(value)
    else:
        out = value
    if abs(out) > _INTEGER_CAP:
        violations.append(Violation(path=path, reason="expected integer"))
        return None
    return out


def _json_values_equal(left: typing.Any, right: typing.Any) -> bool:
    """Compares JSON values without Python's bool-as-int equality leak."""

    left_is_number = isinstance(left, (int, float)) and not isinstance(left, bool)
    right_is_number = isinstance(right, (int, float)) and not isinstance(right, bool)
    if left_is_number or right_is_number:
        return left_is_number and right_is_number and left == right
    if type(left) is not type(right):
        return False
    if isinstance(left, list):
        left_list = typing.cast("list[typing.Any]", left)
        right_list = typing.cast("list[typing.Any]", right)
        return len(left_list) == len(right_list) and all(
            _json_values_equal(a, b) for a, b in zip(left_list, right_list)
        )
    if isinstance(left, dict):
        left_dict = typing.cast("dict[typing.Any, typing.Any]", left)
        right_dict = typing.cast("dict[typing.Any, typing.Any]", right)
        return left_dict.keys() == right_dict.keys() and all(
            _json_values_equal(left_dict[key], right_dict[key]) for key in left_dict
        )
    return left == right


def _check_unique_items(
    value: list[typing.Any], path: str, violations: list[Violation]
) -> None:
    """Asserts an array's elements are pairwise distinct."""

    seen: list[typing.Any] = []
    for index, element in enumerate(value):
        for earlier, previous in enumerate(seen):
            if _json_values_equal(previous, element):
                violations.append(
                    Violation(
                        path=path,
                        reason=(
                            f"duplicate items: element at index {index} "
                            f"equals index {earlier}"
                        ),
                    )
                )
                break
        seen.append(element)


def _check_contains(
    value: list[typing.Any],
    matches: typing.Callable[[typing.Any], bool],
    min_contains: int,
    max_contains: int | None,
    bounded_min: bool,
    path: str,
    violations: list[Violation],
) -> None:
    """Asserts how many of an array's elements match the `contains` schema."""

    match_count = sum(1 for element in value if matches(element))
    if match_count < min_contains:
        if bounded_min:
            violations.append(
                Violation(
                    path=path,
                    reason=(
                        f"too few matching items: at least {min_contains}, "
                        f"got {match_count}"
                    ),
                )
            )
        else:
            violations.append(
                Violation(path=path, reason="no element matches the required schema")
            )
    if max_contains is not None and match_count > max_contains:
        violations.append(
            Violation(
                path=path,
                reason=(
                    f"too many matching items: at most {max_contains}, "
                    f"got {match_count}"
                ),
            )
        )


_TEMPORAL_DATE_TIME_RE = re.compile(
    r"^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])[Tt]([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\.[0-9]+)?([Zz]|[+-]([01][0-9]|2[0-3]):[0-5][0-9])$"
)
_TEMPORAL_DATE_RE = re.compile(r"^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])$")
_TEMPORAL_TIME_RE = re.compile(
    r"^([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\.[0-9]+)?([Zz]|[+-]([01][0-9]|2[0-3]):[0-5][0-9])?$"
)
_TEMPORAL_DURATION_RE = re.compile(
    r"^PT(?:[0-9]+H(?:[0-9]+M(?:[0-9]+S)?)?|[0-9]+M(?:[0-9]+S)?|[0-9]+S)$"
)
_TEMPORAL_MAX_DURATION_SECONDS = ((1 << 63) - 1) // 1_000_000_000
# A duration component with more digits than the cap itself is over the cap
# whatever those digits are, which is how the magnitude is bounded before `int()`
# sees it: CPython refuses to convert a string of more than 4300 digits.
_TEMPORAL_MAX_DURATION_DIGITS = len(str(_TEMPORAL_MAX_DURATION_SECONDS))
# `datetime` resolves to microseconds, and `fromisoformat` before Python 3.11
# parses only the fraction widths `isoformat` writes.
_TEMPORAL_FRACTION_DIGITS = 6


def _days_in_month(year: int, month: int) -> int:
    if month in (1, 3, 5, 7, 8, 10, 12):
        return 31
    if month in (4, 6, 9, 11):
        return 30
    if month == 2:
        return 29 if (year % 4 == 0 and year % 100 != 0) or year % 400 == 0 else 28
    return 0


def _valid_temporal_calendar(value: str) -> bool:
    if len(value) < 10:
        return False
    try:
        year, month, day = int(value[0:4]), int(value[5:7]), int(value[8:10])
    except ValueError:
        return False
    # `datetime.MINYEAR` is 1, which is also the shared cross-language floor.
    # Year 0000 is rejected rather than shifted into range, and
    # `_temporal_reason` says so.
    if year < datetime.MINYEAR:
        return False
    maximum = _days_in_month(year, month)
    return maximum > 0 and 1 <= day <= maximum


def _temporal_reason(name: str, value: str) -> str:
    """The reason a rejected temporal string is reported under.

    Year 0000 earns its own clause so the caller sees the shared calendar floor
    rather than only a generic malformed-timestamp reason.
    """

    if value[0:4] == "0000":
        return (
            f"must be a valid {name}, got {_quote(value)}: year 0000 is not"
            f" representable (datetime.MINYEAR is {datetime.MINYEAR})"
        )
    return f"must be a valid {name}, got {_quote(value)}"


def _temporal_isoformat(value: str) -> str:
    """Rewrites a wire temporal into the spelling `fromisoformat` accepts.

    `Z` becomes `+00:00`, and the fractional second is padded or truncated to
    exactly `_TEMPORAL_FRACTION_DIGITS`: before Python 3.11 `fromisoformat`
    parses only what `isoformat` writes, so an RFC 3339 `.1` or `.1234567` --
    which every other target accepts -- would otherwise raise. Digits past the
    sixth are dropped, the loss at `datetime`'s own resolution that P1 allows;
    the canonical output re-trims the padding, so `.1` still writes as `.1`.
    """

    normalized = value.upper()
    if normalized.endswith("Z"):
        normalized = normalized[:-1] + "+00:00"
    dot = normalized.find(".")
    if dot < 0:
        return normalized
    end = dot + 1
    while end < len(normalized) and normalized[end].isdigit():
        end += 1
    fraction = normalized[dot + 1 : end].ljust(_TEMPORAL_FRACTION_DIGITS, "0")
    return (
        normalized[: dot + 1] + fraction[:_TEMPORAL_FRACTION_DIGITS] + normalized[end:]
    )


def _parse_date_time(
    value: str, path: str, violations: list[Violation]
) -> datetime.datetime | None:
    if _TEMPORAL_DATE_TIME_RE.match(value) is None or not _valid_temporal_calendar(
        value
    ):
        violations.append(
            Violation(path=path, reason=_temporal_reason("date-time", value))
        )
        return None
    return datetime.datetime.fromisoformat(_temporal_isoformat(value))


def _parse_date(
    value: str, path: str, violations: list[Violation]
) -> datetime.date | None:
    if _TEMPORAL_DATE_RE.match(value) is None or not _valid_temporal_calendar(value):
        violations.append(Violation(path=path, reason=_temporal_reason("date", value)))
        return None
    return datetime.date.fromisoformat(value)


def _parse_time(
    value: str, path: str, violations: list[Violation]
) -> datetime.time | None:
    if _TEMPORAL_TIME_RE.match(value) is None:
        violations.append(Violation(path=path, reason=_temporal_reason("time", value)))
        return None
    return datetime.time.fromisoformat(_temporal_isoformat(value))


def _parse_duration(
    value: str, path: str, violations: list[Violation]
) -> datetime.timedelta | None:
    if _TEMPORAL_DURATION_RE.match(value) is None:
        violations.append(
            Violation(path=path, reason=_temporal_reason("duration", value))
        )
        return None
    total = 0
    number = ""
    for char in value[2:]:
        if char.isdigit():
            number += char
            continue
        digits = number.lstrip("0")
        number = ""
        if len(digits) > _TEMPORAL_MAX_DURATION_DIGITS:
            # Over the cap by digit count alone (see the constant), so the
            # conversion `int()` would refuse is never attempted.
            total = _TEMPORAL_MAX_DURATION_SECONDS + 1
            break
        total += int(digits or "0") * {"H": 3600, "M": 60, "S": 1}[char]
        if total > _TEMPORAL_MAX_DURATION_SECONDS:
            break
    if total > _TEMPORAL_MAX_DURATION_SECONDS:
        violations.append(
            Violation(path=path, reason=_temporal_reason("duration", value))
        )
        return None
    return datetime.timedelta(seconds=total)


def _check_temporal_offset(
    name: str,
    value: datetime.datetime | datetime.time,
    offset: datetime.timedelta,
    path: str,
    violations: list[Violation],
) -> None:
    """Asserts a UTC offset is a whole number of minutes, the finest the wire
    form spells (`tzinfo` allows seconds, which the offset would silently lose).
    """

    if offset % datetime.timedelta(minutes=1):
        violations.append(
            Violation(
                path=path,
                reason=(
                    f"must be a valid {name}, got {_quote(str(value))}: "
                    f"the UTC offset {offset} is not a whole number of minutes"
                ),
            )
        )


def _check_date_time(
    value: datetime.datetime, path: str, violations: list[Violation]
) -> None:
    """Asserts a datetime is writable as a wire date-time (P12).

    A dataclass is constructed unchecked, so a naive datetime -- with no offset
    the required wire form could carry -- reaches serialize; without this it
    would emit a value this module's own parser rejects.
    """

    offset = value.utcoffset()
    if offset is None:
        violations.append(
            Violation(
                path=path,
                reason=(
                    f"must be a valid date-time, got {_quote(str(value))}: "
                    "a naive datetime carries no UTC offset"
                ),
            )
        )
        return
    _check_temporal_offset("date-time", value, offset, path, violations)


def _check_time(value: datetime.time, path: str, violations: list[Violation]) -> None:
    """Asserts a time is writable as a wire time (P12). The offset is optional in
    the grammar, so only its precision is held to anything."""

    offset = value.utcoffset()
    if offset is not None:
        _check_temporal_offset("time", value, offset, path, violations)


def _check_duration(
    value: datetime.timedelta, path: str, violations: list[Violation]
) -> None:
    """Asserts a timedelta is writable as a wire duration (P12): the grammar is
    unsigned, whole-second and capped, and a `timedelta` is none of those."""

    if value < datetime.timedelta(0):
        reason = "a duration cannot be negative"
    elif value % datetime.timedelta(seconds=1):
        reason = "a duration cannot carry a fraction of a second"
    elif value.total_seconds() > _TEMPORAL_MAX_DURATION_SECONDS:
        reason = f"a duration cannot exceed {_TEMPORAL_MAX_DURATION_SECONDS} seconds"
    else:
        return
    violations.append(
        Violation(
            path=path,
            reason=f"must be a valid duration, got {_quote(str(value))}: {reason}",
        )
    )


def _temporal_frac(microsecond: int) -> str:
    if microsecond == 0:
        return ""
    return "." + f"{microsecond:06d}".rstrip("0")


def _temporal_offset(value: datetime.datetime | datetime.time) -> str:
    offset = value.utcoffset()
    if offset is None:
        return ""
    total = int(offset.total_seconds())
    if total == 0:
        return "Z"
    sign = "+" if total > 0 else "-"
    total = abs(total)
    return f"{sign}{total // 3600:02d}:{(total % 3600) // 60:02d}"


def _format_date_time(value: datetime.datetime) -> str:
    return (
        f"{value.year:04d}-{value.month:02d}-{value.day:02d}"
        f"T{value.hour:02d}:{value.minute:02d}:{value.second:02d}"
        f"{_temporal_frac(value.microsecond)}{_temporal_offset(value)}"
    )


def _format_date(value: datetime.date) -> str:
    return f"{value.year:04d}-{value.month:02d}-{value.day:02d}"


def _format_time(value: datetime.time) -> str:
    return (
        f"{value.hour:02d}:{value.minute:02d}:{value.second:02d}"
        f"{_temporal_frac(value.microsecond)}{_temporal_offset(value)}"
    )


def _format_duration(value: datetime.timedelta) -> str:
    total = int(value.total_seconds())
    if total == 0:
        return "PT0S"
    hours, remainder = divmod(total, 3600)
    minutes, seconds = divmod(remainder, 60)
    out = "PT"
    if hours:
        out += f"{hours}H"
    if minutes:
        out += f"{minutes}M"
    if seconds:
        out += f"{seconds}S"
    return out


_BASE64_RE = re.compile(
    "^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?\\Z", re.ASCII
)
_BASE64URL_RE = re.compile("^(?:[A-Za-z0-9_-]{4})*(?:[A-Za-z0-9_-]{2,3})?\\Z", re.ASCII)


def _parse_base64(value: str, path: str, violations: list[Violation]) -> bytes | None:
    if _BASE64_RE.match(value) is None:
        violations.append(
            Violation(path=path, reason=f"must be base64-encoded, got {_quote(value)}")
        )
        return None
    return base64.b64decode(value, validate=True)


def _format_base64(value: bytes) -> str:
    return base64.b64encode(value).decode("ascii")


def _parse_base64url(
    value: str, path: str, violations: list[Violation]
) -> bytes | None:
    if _BASE64URL_RE.match(value) is None:
        violations.append(
            Violation(
                path=path, reason=f"must be base64url-encoded, got {_quote(value)}"
            )
        )
        return None
    return base64.urlsafe_b64decode(value + "=" * (-len(value) % 4))


def _format_base64url(value: bytes) -> str:
    return base64.urlsafe_b64encode(value).rstrip(b"=").decode("ascii")
