use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::sync::atomic::{AtomicU64, Ordering};
use std::time::{SystemTime, UNIX_EPOCH};

use nexgen::{GenerateRequest, generate_to_file};

mod common;
use common::{json_input_path, write_bare_ref_alias_closure};

static OUTPUT_COUNTER: AtomicU64 = AtomicU64::new(0);

/// A property whose union has one inline structured object branch (named
/// `<Union>Object`) and one scalar branch.
/// Unions in positions with no property of their own: an array element (inline
/// and `$ref`), a map member (inline), plus a nullable element for contrast.
const ELEMENT_UNION_SCHEMA: &str = r##"$schema: https://json-schema.org/draft/2020-12/schema
type: object
properties:
  segments:
    type: array
    items:
      oneOf:
        - { type: string }
        - { type: integer }
  choices:
    type: array
    items: { $ref: "#/$defs/Choice" }
  entries: { $ref: "#/$defs/Entries" }
  slots:
    type: array
    items:
      oneOf:
        - { type: string }
        - { type: "null" }
$defs:
  Choice:
    oneOf:
      - { type: string }
      - { type: boolean }
  Entries:
    type: object
    additionalProperties:
      oneOf:
        - { type: string }
        - { type: integer }
"##;

const INLINE_OBJECT_BRANCH_SCHEMA: &str = r#"$schema: https://json-schema.org/draft/2020-12/schema
type: object
properties:
  payload:
    oneOf:
      - type: object
        required: [text]
        properties:
          text: { type: string, minLength: 1 }
      - { type: string }
"#;

/// A union whose **non-object** branches each declare constraints of their own:
/// once the wire token selects a branch, the value is held to everything that
/// branch declares — including a closed value set — in both directions.
const BRANCH_CONSTRAINT_SCHEMA: &str = r#"$schema: https://json-schema.org/draft/2020-12/schema
type: object
properties:
  value:
    oneOf:
      - { type: string, minLength: 3, pattern: "^[a-z]+$" }
      - { type: integer, minimum: 1 }
  listOrName:
    oneOf:
      - { type: array, items: { type: number }, minItems: 1, uniqueItems: true }
      - { type: string, enum: [auto, manual] }
"#;

/// Plain `number` positions need a serialize-side finiteness check even when
/// they carry no explicit numeric bound. The positions cover a property, a
/// nested array, an unconstrained union branch, and a typed-map member array.
const FINITE_NUMBER_SCHEMA: &str = r##"$schema: https://json-schema.org/draft/2020-12/schema
type: object
required: [scalar, nested, metric, values]
properties:
  scalar: { type: number }
  nested:
    type: array
    items:
      type: array
      items: { type: number }
  metric:
    oneOf:
      - { type: number }
      - { type: string }
  values: { $ref: "#/$defs/Values" }
$defs:
  Values:
    type: object
    additionalProperties:
      type: array
      items: { type: number }
"##;

/// Support-file detection must walk collection and typed-map member schemas;
/// neither feature appears on a direct property here.
const NESTED_RUNTIME_SUPPORT_SCHEMA: &str = r##"$schema: https://json-schema.org/draft/2020-12/schema
type: object
properties:
  dates:
    type: array
    items:
      type: array
      items: { type: string, format: date }
  timestamps:
    type: array
    items: { type: string, format: date-time }
  blobs: { $ref: "#/$defs/Blobs" }
$defs:
  Blobs:
    type: object
    additionalProperties:
      type: string
      contentEncoding: base64
"##;

/// Java-specific focused coverage for the Wave 2 runtime contracts. This is a
/// temporary input generated by the test, so it exercises the real loader and
/// planner without adding another shared showcase schema.
const JAVA_CONFORMANCE_SCHEMA: &str = r##"$schema: https://json-schema.org/draft/2020-12/schema
title: Java conformance
description: Mixed declared and typed catch-all object.
deprecated: true
type: object
maxProperties: 4
properties:
  id:
    type: string
    deprecated: true
  dates:
    type: array
    items: { type: number }
    contains:
      type: integer
      exclusiveMinimum: 1
      exclusiveMaximum: 10
      multipleOf: 2
    minContains: 1
  inclusiveDates:
    type: array
    items: { type: number }
    contains:
      type: integer
      minimum: 2
      maximum: 8
      multipleOf: 2
  payload:
    type: string
    contentEncoding: base64
    minLength: 4
    pattern: "^[A-Za-z0-9+/]+=*$"
  day:
    type: string
    format: date
    enum: ["2025-01-01"]
    default: "2025-01-01"
  maybeDay:
    oneOf:
      - { type: string, format: date }
      - { type: "null" }
    default: "2025-01-02"
  token:
    type: string
    contentEncoding: base64
    const: YQ==
  blobDefault:
    type: string
    contentEncoding: base64
    default: YQ==
  hosts:
    type: array
    items: { type: string }
    contains:
      type: string
      minLength: 3
      maxLength: 12
      pattern: "^api\\."
      format: hostname
      enum: [api.example]
  keyed: { $ref: "#/$defs/Keyed" }
  lists: { $ref: "#/$defs/Lists" }
  nativeExtras: { $ref: "#/$defs/NativeExtras" }
  edgeNumber:
    type: number
    exclusiveMaximum: -1
    multipleOf: 2e1
  zeroChoice:
    type: number
    enum: [0]
  boolChoice:
    type: boolean
    enum: [true]
additionalProperties:
  type: string
  minLength: 2
  pattern: "^[a-z]+$"
$defs:
  Keyed:
    type: object
    additionalProperties: { type: string }
    propertyNames:
      type: string
      minLength: 2
      maxLength: 12
      pattern: "^[a-z][a-z0-9]+$"
      enum: [id, dates, payload, extra]
      format: hostname
  Lists:
    type: object
    additionalProperties:
      type: array
      items:
        type: string
        minLength: 2
        pattern: "^[a-z]+$"
  NativeExtras:
    type: object
    minProperties: 1
    maxProperties: 2
    properties:
      known: { type: string }
    additionalProperties: { type: string, format: date }
"##;

const JAVA_DEPRECATED_SERVICE_SCHEMA: &str = r##"$schema: https://json-schema.org/draft/2020-12/schema
nexusrpc: "1.0.0"
services:
  Legacy:
    fqn: example.legacy.v1.Legacy
    deprecated: true
    description: Legacy API.
    x-java-name: LegacyJava
    operations:
      ping:
        deprecated: true
        description: Ping the service.
        x-java-name: pingJava
      submit:
        input: { $ref: "#/$defs/Input" }
      fetch:
        output: { $ref: "#/$defs/Input" }
$defs:
  Input:
    type: object
    additionalProperties: false
"##;

const JAVA_EMPTY_SERVICE_DESCRIPTION_SCHEMA: &str = r##"$schema: https://json-schema.org/draft/2020-12/schema
nexusrpc: "1.0.0"
services:
  Empty:
    fqn: example.empty.v1.Empty
    description: ""
    operations:
      ping: {}
"##;

fn project_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn unique_output_path(label: &str) -> PathBuf {
    let unique = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap()
        .as_nanos();
    let counter = OUTPUT_COUNTER.fetch_add(1, Ordering::Relaxed);
    std::env::temp_dir().join(format!("nexgen-{label}-{unique}-{counter}"))
}

fn read_java_files(dir: &Path) -> BTreeMap<PathBuf, String> {
    fn visit(root: &Path, dir: &Path, files: &mut BTreeMap<PathBuf, String>) {
        let mut entries = fs::read_dir(dir)
            .unwrap()
            .map(|entry| entry.unwrap().path())
            .collect::<Vec<_>>();
        entries.sort();
        for path in entries {
            if path.is_dir() {
                visit(root, &path, files);
            } else if path.extension().and_then(|extension| extension.to_str()) == Some("java") {
                files.insert(
                    path.strip_prefix(root).unwrap().to_path_buf(),
                    fs::read_to_string(&path).unwrap(),
                );
            }
        }
    }

    let mut files = BTreeMap::new();
    visit(dir, dir, &mut files);
    files
}

/// Checks Java-specific rendering details exercised by the showcase schema.
fn assert_showcase_features(mode: &str, generation_mode: nexgen::generator::GenerationMode) {
    let root = project_root();
    let example_id = "showcase";
    let temp_dir = unique_output_path(&format!("java-json-{mode}-{example_id}"));
    let output_path = temp_dir.join(example_id);

    generate_to_file(&GenerateRequest {
        config: nexgen::nexgen_config::NexgenConfig {
            mode: generation_mode,
            ..Default::default()
        },
        language: nexgen::language::Language::Java,
        input_paths: vec![json_input_path(&root, example_id)],
        support_package: None,
        descriptor_paths: Vec::new(),
        output_path: output_path.clone(),
        format: false,
        java_package_name: Some(format!("json_schema.{mode}.{example_id}")),
        ts_date_time_types: Default::default(),
    })
    .unwrap();

    let rendered = read_java_files(&output_path);
    let all = rendered.values().cloned().collect::<Vec<_>>().join("\n");
    // Scalar defaults surface on read via the generated getter default.
    assert!(all.contains("public String getGreetingOrDefault() {"));
    assert!(all.contains("return greeting != null ? greeting : \"hello\";"));
    assert!(all.contains("public boolean getDebugOrDefault() {"));
    // `deprecated` → @Deprecated + @deprecated javadoc; `title` → summary.
    assert!(all.contains("@Deprecated"));
    assert!(all.contains("@deprecated This field is deprecated."));
    assert!(all.contains("Retry budget"));
    // `x-java-name` override (Stage 4): the emitted field/getter use the
    // override while the wire name (`@JsonProperty`) stays `legacyId`.
    assert!(all.contains("private final @Nullable String legacyIdJava;"));
    assert!(all.contains("public @Nullable String getLegacyIdJava() {"));
    assert!(all.contains("gen.writeStringField(\"legacyId\", value.legacyIdJava);"));
    // An inline free-form object branch: the union declares a nested
    // wrapper holding the members verbatim (a named free-form model gets
    // the same catch-all on its POJO).
    assert!(all.contains("public static final class PayloadObject implements Payload {"));
    assert!(all.contains("private final Map<String, JsonNode> value;"));
    assert!(all.contains("public final class Extras {"));
    // A tagged union whose branches are written inline: each branch names
    // itself with `x-java-name` and implements the union interface.
    assert!(all.contains("public final class TextNote implements Note {"));
    assert!(all.contains("public final class LinkNote implements Note {"));
    // A structured inline object branch of a *property* union: the branch
    // is an ordinary POJO implementing the interface nested in the
    // declaring class, and the union parses through `fromNode` exactly as
    // a named union def does.
    assert!(all.contains("public final class ShowcaseDetailObject implements Showcase.Detail {"));
    assert!(all.contains("return context.readTreeAsValue(node, ShowcaseDetailObject.class);"));
    assert!(all.contains("detail = Detail.fromNode(field, \"detail\", violations, context);"));
    fs::remove_dir_all(temp_dir).unwrap();
}

#[test]
fn java_json_definitions_examples_render_expected_features() {
    assert_showcase_features(
        "definitions",
        nexgen::generator::GenerationMode::DefinitionsOnly,
    );
}

#[test]
fn java_json_api_examples_render_expected_features() {
    assert_showcase_features("api", nexgen::generator::GenerationMode::NativeApi);
}

/// A structured inline object branch of a property-level union is named
/// `<Union>Object` by the load and emitted as an ordinary POJO — implementing the
/// union interface nested in the declaring class, so the interface's `fromNode`
/// dispatcher (the same one a named union def carries) delegates to the branch's
/// own deserializer. See `specs/json-schema/features/oneOf.md`.
#[test]
fn java_json_names_inline_object_union_branch() {
    let temp_dir = unique_output_path("java-json-inline-branch");
    fs::create_dir_all(&temp_dir).unwrap();
    let input_path = temp_dir.join("detail.yaml");
    fs::write(&input_path, INLINE_OBJECT_BRANCH_SCHEMA).unwrap();
    let output_path = temp_dir.join("detail");

    generate_to_file(&GenerateRequest {
        config: Default::default(),
        language: nexgen::language::Language::Java,
        input_paths: vec![input_path],
        support_package: None,
        descriptor_paths: Vec::new(),
        output_path: output_path.clone(),
        format: false,
        java_package_name: Some("detail".to_string()),
        ts_date_time_types: Default::default(),
    })
    .unwrap();

    let rendered = read_java_files(&output_path);
    let branch = &rendered[&PathBuf::from("DetailPayloadObject.java")];
    assert!(
        branch.contains("public final class DetailPayloadObject implements Detail.Payload {"),
        "{branch}"
    );
    // The branch is an ordinary model: its own constraints and catch-all.
    assert!(branch.contains("must have length >= 1"), "{branch}");
    assert!(
        branch.contains("private final Map<String, JsonNode> additionalProperties;"),
        "{branch}"
    );

    let declaring = &rendered[&PathBuf::from("Detail.java")];
    for expected in [
        "public interface Payload {",
        "static @Nullable Payload fromNode(JsonNode node, String path, List<Violation> violations, DeserializationContext context) {",
        "return context.readTreeAsValue(node, DetailPayloadObject.class);",
        "public static final class PayloadString implements Payload {",
        "payload = Payload.fromNode(field, \"payload\", violations, context);",
    ] {
        assert!(declaring.contains(expected), "{expected}\n{declaring}");
    }
    fs::remove_dir_all(temp_dir).unwrap();
}

/// Every constraint a **non-object** branch declares becomes a `validate` on its
/// wrapper class: the `fromNode` dispatcher runs it on the way in, and the
/// enclosing POJO's `Serializer` runs it again through the interface's static
/// `validate` before emit (P12), so a branch violation aggregates with its
/// siblings. See `specs/json-schema/features/oneOf.md` ("Validator mapping").
#[test]
fn java_json_validates_non_object_union_branch_constraints() {
    let temp_dir = unique_output_path("java-json-branch-constraints");
    fs::create_dir_all(&temp_dir).unwrap();
    let input_path = temp_dir.join("bc.yaml");
    fs::write(&input_path, BRANCH_CONSTRAINT_SCHEMA).unwrap();
    let output_path = temp_dir.join("bc");

    generate_to_file(&GenerateRequest {
        config: Default::default(),
        language: nexgen::language::Language::Java,
        input_paths: vec![input_path],
        support_package: None,
        descriptor_paths: Vec::new(),
        output_path: output_path.clone(),
        format: false,
        java_package_name: Some("bc".to_string()),
        ts_date_time_types: Default::default(),
    })
    .unwrap();
    let rendered = read_java_files(&output_path);
    let declaring = &rendered[&PathBuf::from("Bc.java")];

    // The wrapper carries the branch's checks, and its compiled `pattern` — the
    // wrapper's single field is `value`, so the static follows that name.
    assert!(declaring.contains(
        "private static final java.util.regex.Pattern VALUE_PATTERN = java.util.regex.Pattern.compile(\"^[a-z]+\\\\z\");"
    ));
    assert!(declaring.contains("void validate(String path, List<Violation> violations) {"));
    assert!(declaring.contains("must have length >= 3, got "));
    assert!(declaring.contains("if (!VALUE_PATTERN.matcher(value).find()) {"));
    assert!(declaring.contains("must be >= 1, got "));
    assert!(declaring.contains("must have at least 1 items, got "));
    assert!(declaring.contains("duplicate items: element at index "));
    assert!(declaring.contains("must be one of [\\\"auto\\\", \\\"manual\\\"], got "));
    // Parse: the dispatcher validates the wrapper it just built.
    assert!(declaring.contains("ValueString wrapped = new ValueString(node.textValue());"));
    assert!(declaring.contains("wrapped.validate(path, violations);"));
    // Serialize: the interface's runtime-class dispatcher, called by the POJO's
    // Serializer before any member is written.
    assert!(
        declaring.contains(
            "static void validate(Value value, String path, List<Violation> violations) {"
        )
    );
    assert!(declaring.contains("Value.validate(value.value, \"value\", violations);"));
    fs::remove_dir_all(temp_dir).unwrap();
}

#[test]
fn java_json_inline_union_names_follow_the_emitted_member() {
    let temp_dir = unique_output_path("java-json-inline-union-member-name");
    fs::create_dir_all(&temp_dir).unwrap();
    let input_path = temp_dir.join("renamed.yaml");
    fs::write(
        &input_path,
        r#"$schema: https://json-schema.org/draft/2020-12/schema
title: RenamedUnion
type: object
properties:
  serializer:
    x-java-name: payload
    oneOf:
      - { type: string }
      - { type: integer }
"#,
    )
    .unwrap();
    let output_path = temp_dir.join("renamed");
    generate_to_file(&GenerateRequest {
        language: nexgen::language::Language::Java,
        input_paths: vec![input_path],
        support_package: None,
        descriptor_paths: Vec::new(),
        output_path: output_path.clone(),
        format: false,
        config: Default::default(),
        java_package_name: Some("renamed".to_string()),
        ts_date_time_types: Default::default(),
    })
    .unwrap();

    let rendered = read_java_files(&output_path);
    let model = &rendered[&PathBuf::from("Renamed.java")];
    for expected in [
        "public interface Payload {",
        "public static final class PayloadString implements Payload {",
        "private final @Nullable Payload payload;",
        "payload = Payload.fromNode(field, \"serializer\", violations, context);",
    ] {
        assert!(model.contains(expected), "{expected}\n{model}");
    }
    assert!(!model.contains("public interface Serializer {"), "{model}");
    fs::remove_dir_all(temp_dir).unwrap();
}

#[test]
fn java_json_rejects_non_finite_numbers_in_every_serialize_position() {
    let temp_dir = unique_output_path("java-json-finite-numbers");
    fs::create_dir_all(&temp_dir).unwrap();
    let input_path = temp_dir.join("finite.yaml");
    fs::write(&input_path, FINITE_NUMBER_SCHEMA).unwrap();
    let output_path = temp_dir.join("finite");

    generate_to_file(&GenerateRequest {
        config: Default::default(),
        language: nexgen::language::Language::Java,
        input_paths: vec![input_path],
        support_package: None,
        descriptor_paths: Vec::new(),
        output_path: output_path.clone(),
        format: false,
        java_package_name: Some("finite".to_string()),
        ts_date_time_types: Default::default(),
    })
    .unwrap();

    let rendered = read_java_files(&output_path);
    let root = &rendered[&PathBuf::from("Finite.java")];
    for expected in [
        "if (!Double.isFinite(value.scalar)) {",
        "new Violation(\"scalar\", \"must be a finite number, got \" + value.scalar)",
        "for (int finiteIndex0 = 0; finiteIndex0 < value.nested.size(); finiteIndex0++) {",
        "for (int finiteIndex1 = 0; finiteIndex1 < finiteValue0.size(); finiteIndex1++) {",
        "new Violation(\"nested\" + \"[\" + finiteIndex0 + \"]\" + \"[\" + finiteIndex1 + \"]\", \"must be a finite number, got \" + finiteValue1)",
        "if (!Double.isFinite(value)) {",
        "Metric.validate(value.metric, \"metric\", violations);",
    ] {
        assert!(root.contains(expected), "{expected}\n{root}");
    }

    for expected in [
        "SpecNumbers.specDouble(field, \"scalar\", violations)",
        "SpecNumbers.specDouble(node, path, violations)",
    ] {
        assert!(
            rendered.values().any(|source| source.contains(expected)),
            "{expected}"
        );
    }
    assert!(
        root.matches("SpecNumbers.specDouble(").count() >= 2,
        "{root}"
    );

    let map = &rendered[&PathBuf::from("Values.java")];
    for expected in [
        "for (Map.Entry<String, List<Double>> entry : value.additionalProperties.entrySet()) {",
        "for (int finiteIndex0 = 0; finiteIndex0 < entry.getValue().size(); finiteIndex0++) {",
        "new Violation(Violation.memberPath(entry.getKey()) + \"[\" + finiteIndex0 + \"]\", \"must be a finite number, got \" + finiteValue0)",
    ] {
        assert!(map.contains(expected), "{expected}\n{map}");
    }
    assert!(map.contains("SpecNumbers.specDouble("), "{map}");

    let numbers = &rendered[&PathBuf::from("SpecNumbers.java")];
    assert!(numbers.contains("public static @Nullable Double specDouble("));
    assert!(numbers.contains("!Double.isFinite(value)"));
    fs::remove_dir_all(temp_dir).unwrap();
}

#[test]
fn java_json_emits_runtime_support_for_nested_materialized_values() {
    let temp_dir = unique_output_path("java-json-nested-runtime-support");
    fs::create_dir_all(&temp_dir).unwrap();
    let input_path = temp_dir.join("nested.yaml");
    fs::write(&input_path, NESTED_RUNTIME_SUPPORT_SCHEMA).unwrap();
    let output_path = temp_dir.join("nested");

    generate_to_file(&GenerateRequest {
        config: Default::default(),
        language: nexgen::language::Language::Java,
        input_paths: vec![input_path],
        support_package: None,
        descriptor_paths: Vec::new(),
        output_path: output_path.clone(),
        format: false,
        java_package_name: Some("nested".to_string()),
        ts_date_time_types: Default::default(),
    })
    .unwrap();

    let rendered = read_java_files(&output_path);
    assert!(rendered.contains_key(&PathBuf::from("TemporalSupport.java")));
    assert!(rendered.contains_key(&PathBuf::from("Base64Support.java")));
    let temporal = &rendered[&PathBuf::from("TemporalSupport.java")];
    assert!(temporal.contains("if (year < 1) {"), "{temporal}");
    // Every pinned regex baked into a runtime support class carries Java's
    // strict end-of-input anchor, exactly as the value-level `pattern`/`format`
    // path does. `java.util.regex`'s `$` matches *before* a final line
    // terminator, so a bare `$` here would make the oracle's accept set depend
    // on whether the use site calls `matches()` or `find()`.
    let base64 = &rendered[&PathBuf::from("Base64Support.java")];
    for support in [temporal, base64] {
        let pinned = support
            .lines()
            .filter(|line| line.contains("private static final Pattern"))
            .collect::<Vec<_>>();
        assert!(!pinned.is_empty(), "{support}");
        for line in pinned {
            assert!(line.contains("\\\\z\");"), "missing \\z anchor: {line}");
            assert!(!line.contains("$\");"), "bare $ anchor: {line}");
        }
    }
    // The serialize-side representability predicate exists for **every**
    // materialized kind, not just the calendar year floor (`09#3`).
    for expected in [
        "public static void checkDateTime(OffsetDateTime value, String path, List<Violation> violations) {",
        "public static void checkDate(LocalDate value, String path, List<Violation> violations) {",
        "public static void checkTime(String value, String path, List<Violation> violations) {",
        "public static void checkDuration(Duration value, String path, List<Violation> violations) {",
        "\"a duration cannot be negative\"",
        "\"a duration cannot carry a fraction of a second\"",
        "is not a whole number of minutes",
        "year must be <= 9999",
    ] {
        assert!(temporal.contains(expected), "{expected}\n{temporal}");
    }
    let root = &rendered[&PathBuf::from("Nested.java")];
    for expected in [
        "for (int temporalIndex0 = 0; temporalIndex0 < value.dates.size(); temporalIndex0++) {",
        "for (int temporalIndex1 = 0; temporalIndex1 < temporalValue0.size(); temporalIndex1++) {",
        "TemporalSupport.checkDate(temporalValue1, \"dates\" + \"[\" + temporalIndex0 + \"]\" + \"[\" + temporalIndex1 + \"]\", violations);",
        "TemporalSupport.checkDateTime(temporalValue0, \"timestamps\" + \"[\" + temporalIndex0 + \"]\", violations);",
    ] {
        assert!(root.contains(expected), "{expected}\n{root}");
    }
    fs::remove_dir_all(temp_dir).unwrap();
}

#[test]
fn java_json_description_does_not_select_datetime_runtime_imports() {
    let temp_dir = unique_output_path("java-json-datetime-prose");
    fs::create_dir_all(&temp_dir).unwrap();
    let input_path = temp_dir.join("prose.yaml");
    fs::write(
        &input_path,
        r#"$schema: https://json-schema.org/draft/2020-12/schema
title: Prose
description: DateTime is mentioned only as ordinary documentation.
type: object
properties:
  note:
    type: string
    description: Another DateTime prose mention.
"#,
    )
    .unwrap();
    let output_path = temp_dir.join("prose");
    generate_to_file(&GenerateRequest {
        language: nexgen::language::Language::Java,
        input_paths: vec![input_path],
        support_package: None,
        descriptor_paths: Vec::new(),
        output_path: output_path.clone(),
        format: false,
        config: Default::default(),
        java_package_name: Some("example.prose".to_string()),
        ts_date_time_types: Default::default(),
    })
    .unwrap();

    let model = fs::read_to_string(output_path.join("Prose.java")).unwrap();
    assert!(!model.contains("TemporalSupport.DateTime"), "{model}");
    assert!(
        !model.contains("import example.prose.TemporalSupport"),
        "{model}"
    );
    assert!(!output_path.join("TemporalSupport.java").exists());
    fs::remove_dir_all(temp_dir).unwrap();
}

#[test]
fn java_json_authored_datetime_does_not_shadow_offset_date_time() {
    let temp_dir = unique_output_path("java-json-datetime-shadow");
    let gradle_root = temp_dir.join("project");
    fs::create_dir_all(&gradle_root).unwrap();
    fs::copy(
        project_root().join("samples/java/build.gradle"),
        gradle_root.join("build.gradle"),
    )
    .unwrap();
    fs::copy(
        project_root().join("samples/java/settings.gradle"),
        gradle_root.join("settings.gradle"),
    )
    .unwrap();
    let input_path = temp_dir.join("shadow.nexusrpc.yaml");
    fs::write(
        &input_path,
        r##"$schema: https://json-schema.org/draft/2020-12/schema
nexusrpc: "1.0.0"
$defs:
  DateTime:
    type: object
    properties:
      label: { type: string }
  Event:
    type: object
    required: [authored, timestamp, nullableCollection, nullableElement]
    properties:
      authored: { $ref: "#/$defs/DateTime" }
      timestamp: { type: string, format: date-time }
      optionalTimestamp: { type: string, format: date-time }
      optionalCollection:
        type: array
        items: { type: string, format: date-time }
      nullableCollection:
        oneOf:
          - type: array
            items: { type: string, format: date-time }
          - { type: "null" }
      nullableElement:
        type: array
        items:
          oneOf:
            - { type: string, format: date-time }
            - { type: "null" }
      bothCombined:
        oneOf:
          - type: array
            items:
              oneOf:
                - { type: string, format: date-time }
                - { type: "null" }
          - { type: "null" }
"##,
    )
    .unwrap();
    let output_path = gradle_root.join("src/main/java/example/shadow");
    generate_to_file(&GenerateRequest {
        language: nexgen::language::Language::Java,
        input_paths: vec![input_path],
        support_package: None,
        descriptor_paths: Vec::new(),
        output_path: output_path.clone(),
        format: false,
        config: Default::default(),
        java_package_name: Some("example.shadow".to_string()),
        ts_date_time_types: Default::default(),
    })
    .unwrap();

    let event = fs::read_to_string(output_path.join("Event.java")).unwrap();
    assert!(event.contains("OffsetDateTime timestamp"), "{event}");
    assert!(
        event.contains("@Nullable OffsetDateTime optionalTimestamp"),
        "{event}"
    );
    for declaration in [
        "@Nullable List<OffsetDateTime> optionalCollection",
        "@Nullable List<OffsetDateTime> nullableCollection",
        "List<@Nullable OffsetDateTime> nullableElement",
        "@Nullable List<@Nullable OffsetDateTime> bothCombined",
    ] {
        assert!(event.contains(declaration), "{declaration}\n{event}");
    }
    assert!(event.contains("DateTime authored"), "{event}");
    assert!(event.contains("import java.time.OffsetDateTime;"));

    let test_package = gradle_root.join("src/test/java/example/shadow");
    fs::create_dir_all(&test_package).unwrap();
    fs::write(
        test_package.join("DateTimeTypeIdentityTest.java"),
        r#"package example.shadow;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Test;

final class DateTimeTypeIdentityTest {
    @Test
    void authoredAndTemporalDateTimesRemainDistinct() throws Exception {
        assertEquals(DateTime.class, Event.class.getMethod("getAuthored").getReturnType());
        assertEquals(OffsetDateTime.class, Event.class.getMethod("getTimestamp").getReturnType());
    }

    @Test
    void collectionAndElementNullabilityRemainIndependent() throws Exception {
        ObjectMapper mapper = new ObjectMapper();
        Event event = mapper.readValue(
            "{\"authored\":{},\"timestamp\":\"2024-01-02T03:04:05Z\"," +
            "\"nullableCollection\":null," +
            "\"nullableElement\":[null,\"2024-01-02T03:04:05Z\"]," +
            "\"bothCombined\":[null]}",
            Event.class);
        assertNull(event.getOptionalCollection());
        assertNull(event.getNullableCollection());
        assertNull(event.getNullableElement().get(0));
        assertNull(event.getBothCombined().get(0));
        assertEquals(2, mapper.readValue(mapper.writeValueAsString(event), Event.class)
            .getNullableElement().size());
    }
}
"#,
    )
    .unwrap();
    let status = Command::new(project_root().join("samples/java/gradlew"))
        .args(["test", "--no-daemon"])
        .current_dir(&gradle_root)
        .status()
        .expect("run Gradle DateTime identity test");
    assert!(status.success());
    fs::remove_dir_all(temp_dir).unwrap();
}

#[test]
fn java_json_rejects_model_shadowing_schema_dependent_offset_date_time_import() {
    let temp_dir = unique_output_path("java-json-offset-date-time-import");
    fs::create_dir_all(&temp_dir).unwrap();
    let colliding_input = temp_dir.join("colliding.yaml");
    fs::write(
        &colliding_input,
        r##"$schema: https://json-schema.org/draft/2020-12/schema
type: object
properties:
  value: { $ref: "#/$defs/OffsetDateTime" }
$defs:
  OffsetDateTime:
    type: object
    properties:
      timestamp: { type: string, format: date-time }
"##,
    )
    .unwrap();

    let error = generate_to_file(&GenerateRequest {
        config: Default::default(),
        language: nexgen::language::Language::Java,
        input_paths: vec![colliding_input],
        support_package: None,
        descriptor_paths: Vec::new(),
        output_path: temp_dir.join("colliding"),
        format: false,
        java_package_name: Some("example.collision".to_string()),
        ts_date_time_types: Default::default(),
    })
    .unwrap_err()
    .to_string();
    assert!(
        error.contains("type `OffsetDateTime`")
            && error.contains("java.time.OffsetDateTime")
            && error.contains("x-java-name"),
        "{error}"
    );

    let plain_input = temp_dir.join("plain.yaml");
    fs::write(
        &plain_input,
        r##"$schema: https://json-schema.org/draft/2020-12/schema
type: object
properties:
  value: { $ref: "#/$defs/OffsetDateTime" }
$defs:
  OffsetDateTime:
    type: object
    properties:
      timestamp: { type: string }
"##,
    )
    .unwrap();
    let output_path = temp_dir.join("plain");
    generate_to_file(&GenerateRequest {
        config: Default::default(),
        language: nexgen::language::Language::Java,
        input_paths: vec![plain_input],
        support_package: None,
        descriptor_paths: Vec::new(),
        output_path: output_path.clone(),
        format: false,
        java_package_name: Some("example.plain".to_string()),
        ts_date_time_types: Default::default(),
    })
    .expect("a non-temporal OffsetDateTime model emits no conflicting import");
    let plain_model = fs::read_to_string(output_path.join("OffsetDateTime.java")).unwrap();
    assert!(plain_model.contains("public final class OffsetDateTime"));
    assert!(!plain_model.contains("import java.time.OffsetDateTime;"));

    fs::remove_dir_all(temp_dir).unwrap();
}

#[test]
fn java_json_emits_wave2_object_and_matcher_contracts() {
    let temp_dir = unique_output_path("java-json-wave2-contracts");
    fs::create_dir_all(&temp_dir).unwrap();
    let input_path = temp_dir.join("java-conformance.yaml");
    fs::write(&input_path, JAVA_CONFORMANCE_SCHEMA).unwrap();
    let output_path = temp_dir.join("java_conformance");

    generate_to_file(&GenerateRequest {
        config: Default::default(),
        language: nexgen::language::Language::Java,
        input_paths: vec![input_path],
        support_package: None,
        descriptor_paths: Vec::new(),
        output_path: output_path.clone(),
        format: false,
        java_package_name: Some("java_conformance".to_string()),
        ts_date_time_types: Default::default(),
    })
    .unwrap();

    let rendered = read_java_files(&output_path);
    let model = &rendered[&PathBuf::from("JavaConformance.java")];
    for expected in [
        "@Deprecated\n@JsonSerialize(using = JavaConformance.Serializer.class)",
        "@Deprecated\n    public @Nullable String getId()",
        "Map<String, String> additionalProperties",
        "additionalProperties.put(key, value)",
        "for (Map.Entry<String, String> entry : value.additionalProperties.entrySet())",
        "declared property key collision",
        "wireKeys.add(\"id\")",
        "SpecNumbers.isSpecLong(rawElement)",
        "rawElement.doubleValue() % 2.0 == 0",
        "rawElement.doubleValue() >= 2.0",
        "rawElement.doubleValue() <= 8.0",
        "rawElement.doubleValue() > 1.0",
        "rawElement.doubleValue() < 10.0",
        "Double.isFinite(element) && element == Math.rint(element)",
        "String payloadWire = Base64Support.formatBase64(value.payload)",
        "PAYLOAD_PATTERN.matcher(payloadWire).find()",
        "public LocalDate getDayOrDefault()",
        "LocalDate.parse(\"2025-01-01\")",
        "public LocalDate getMaybeDayOrDefault()",
        "LocalDate.parse(\"2025-01-02\")",
        "public byte[] getBlobDefaultOrDefault()",
        "java.util.Base64.getDecoder().decode(\"YQ==\")",
        "must equal \\\"2025-01-01\\\"",
        "Base64Support.formatBase64(value.token)",
        "\"api.example\".equals(element)",
        "element.codePointCount(0, element.length()) >= 3",
        "element.codePointCount(0, element.length()) <= 12",
        "value.edgeNumber >= -1.0",
        "value.edgeNumber % 20.0 != 0",
        "must equal 0",
        "must equal true",
        "java.util.regex.Pattern.compile(\"^api\\\\.\")",
    ] {
        assert!(model.contains(expected), "{expected}\n{model}");
    }
    let keyed = &rendered[&PathBuf::from("Keyed.java")];
    for expected in [
        "PROPERTY_NAME_PATTERN.matcher(pnKey).find()",
        "PROPERTY_NAME_FORMAT.matcher(pnKey).find()",
        "must be one of [\\\"id\\\", \\\"dates\\\", \\\"payload\\\", \\\"extra\\\"]",
    ] {
        assert!(keyed.contains(expected), "{expected}\n{keyed}");
    }
    let lists = &rendered[&PathBuf::from("Lists.java")];
    for expected in [
        "String parsed = item.textValue()",
        "must have length >= 2",
        "java.util.regex.Pattern.compile(\"^[a-z]+\\\\z\")",
        "for (int validationIndex0 = 0; validationIndex0 < entry.getValue().size(); validationIndex0++)",
        "validationValue0.codePointCount(0, validationValue0.length())",
    ] {
        assert!(lists.contains(expected), "{expected}\n{lists}");
    }
    let native_extras = &rendered[&PathBuf::from("NativeExtras.java")];
    for expected in [
        "Map<String, LocalDate> additionalProperties",
        "TemporalSupport.parseDate(element.textValue(), path, violations)",
        "TemporalSupport.formatDate(entry.getValue())",
        "declared property key collision",
        "wireKeys.size() < 1",
        "wireKeys.size() > 2",
    ] {
        assert!(
            native_extras.contains(expected),
            "{expected}\n{native_extras}"
        );
    }
    fs::remove_dir_all(temp_dir).unwrap();
}

#[test]
fn java_json_emits_deprecated_services_and_operations() {
    let temp_dir = unique_output_path("java-json-deprecated-service");
    fs::create_dir_all(&temp_dir).unwrap();
    let input_path = temp_dir.join("legacy.nexusrpc.yaml");
    fs::write(&input_path, JAVA_DEPRECATED_SERVICE_SCHEMA).unwrap();
    let output_path = temp_dir.join("legacy");

    generate_to_file(&GenerateRequest {
        config: Default::default(),
        language: nexgen::language::Language::Java,
        input_paths: vec![input_path],
        support_package: None,
        descriptor_paths: Vec::new(),
        output_path: output_path.clone(),
        format: false,
        java_package_name: Some("legacy".to_string()),
        ts_date_time_types: Default::default(),
    })
    .unwrap();

    let rendered = read_java_files(&output_path);
    let service = &rendered[&PathBuf::from("LegacyJava.java")];
    assert!(
        service.contains("@deprecated This service is deprecated."),
        "{service}"
    );
    assert!(
        service.contains("@Deprecated\npublic interface LegacyJava"),
        "{service}"
    );
    assert!(
        service.contains("@deprecated This operation is deprecated."),
        "{service}"
    );
    assert!(
        service.contains("@Deprecated\n    void pingJava();"),
        "{service}"
    );
    assert!(service.contains("void submit(Input input);"), "{service}");
    assert!(service.contains("Input fetch();"), "{service}");
    fs::remove_dir_all(temp_dir).unwrap();
}

#[test]
fn java_json_rejects_empty_service_descriptions() {
    let temp_dir = unique_output_path("java-json-empty-service-description");
    fs::create_dir_all(&temp_dir).unwrap();
    let input_path = temp_dir.join("empty.nexusrpc.yaml");
    fs::write(&input_path, JAVA_EMPTY_SERVICE_DESCRIPTION_SCHEMA).unwrap();
    let error = generate_to_file(&GenerateRequest {
        config: Default::default(),
        language: nexgen::language::Language::Java,
        input_paths: vec![input_path],
        support_package: None,
        descriptor_paths: Vec::new(),
        output_path: temp_dir.join("empty"),
        format: false,
        java_package_name: Some("empty".to_string()),
        ts_date_time_types: Default::default(),
    })
    .unwrap_err();
    assert!(
        error
            .to_string()
            .contains("`description` must not be empty or whitespace-only"),
        "{error}"
    );
    fs::remove_dir_all(temp_dir).unwrap();
}

/// A union in an element position decodes through the interface's own
/// `fromNode` dispatcher — Jackson cannot instantiate a sealed interface — with
/// the element index / member key in the violation path. A nullable element
/// takes the TYPE_USE annotation instead (the list stays non-null).
/// See `specs/json-schema/features/oneOf.md` ("Unions in element positions").
#[test]
fn java_json_decodes_element_position_unions() {
    let temp_dir = unique_output_path("java-json-element-union");
    fs::create_dir_all(&temp_dir).unwrap();
    let input_path = temp_dir.join("bag.yaml");
    fs::write(&input_path, ELEMENT_UNION_SCHEMA).unwrap();
    let output_path = temp_dir.join("bag");

    generate_to_file(&GenerateRequest {
        config: Default::default(),
        language: nexgen::language::Language::Java,
        input_paths: vec![input_path],
        support_package: None,
        descriptor_paths: Vec::new(),
        output_path: output_path.clone(),
        format: false,
        java_package_name: Some("bag".to_string()),
        ts_date_time_types: Default::default(),
    })
    .unwrap();

    let rendered = read_java_files(&output_path);
    // The inline element union is named after its position and emitted as an
    // ordinary named union def.
    assert!(rendered.contains_key(&PathBuf::from("BagSegmentsItem.java")));
    assert!(rendered.contains_key(&PathBuf::from("EntriesValue.java")));

    let declaring = &rendered[&PathBuf::from("Bag.java")];
    for expected in [
        "private final @Nullable List<BagSegmentsItem> segments;",
        "String elementPath = \"segments\" + \"[\" + index + \"]\";",
        "BagSegmentsItem parsedItems = BagSegmentsItem.fromNode(element, elementPath, violations, context);",
        "Choice parsedItems = Choice.fromNode(element, elementPath, violations, context);",
        "private final @Nullable List<@Nullable String> slots;",
        "items.add(null);",
    ] {
        assert!(declaring.contains(expected), "{expected}\n{declaring}");
    }

    let map = &rendered[&PathBuf::from("Entries.java")];
    for expected in [
        "Map<String, EntriesValue> additionalProperties",
        "EntriesValue parsedAdditionalProperties = EntriesValue.fromNode(element, path, violations, context);",
    ] {
        assert!(map.contains(expected), "{expected}\n{map}");
    }
    fs::remove_dir_all(temp_dir).unwrap();
}

/// The entry file of a two-file closure. `get`'s output is the model the *other*
/// file declares, and `FindOutput.page` `$ref`s it from a property, so both
/// cross-module reference shapes are covered.
const CROSS_MODULE_ENTRY_SCHEMA: &str = r##"$schema: https://json-schema.org/draft/2020-12/schema
nexusrpc: "1.0.0"
services:
  Pages:
    fqn: example.pages.v1.Pages
    operations:
      get:
        input: { $ref: "#/$defs/GetInput" }
        output: { $ref: "content/page.json" }
      find:
        input: { $ref: "#/$defs/GetInput" }
        output: { $ref: "#/$defs/FindOutput" }
$defs:
  GetInput:
    type: object
    additionalProperties: false
    properties:
      id: { type: string }
  FindOutput:
    type: object
    additionalProperties: false
    properties:
      page: { $ref: "content/page.json" }
"##;

/// The referenced file. Its model carries the name override the *consuming*
/// module has to resolve through.
const CROSS_MODULE_PAGE_SCHEMA: &str = r##"$schema: https://json-schema.org/draft/2020-12/schema
type: object
additionalProperties: false
x-java-name: RenamedPage
properties:
  title: { type: string }
"##;

/// Writes the two-file cross-module closure into `dir` and returns the input
/// directory to generate from.
fn write_cross_module_closure(dir: &Path) -> PathBuf {
    let input_dir = dir.join("input");
    fs::create_dir_all(input_dir.join("content")).unwrap();
    fs::write(
        input_dir.join("kb.nexusrpc.yaml"),
        CROSS_MODULE_ENTRY_SCHEMA,
    )
    .unwrap();
    fs::write(
        input_dir.join("content/page.json"),
        CROSS_MODULE_PAGE_SCHEMA,
    )
    .unwrap();
    input_dir
}

/// An `x-java-name` override on a model in *another* input file moves every
/// reference the consuming package emits: the operation's return type, the
/// cross-package import, and the field/getter of a cross-module `$ref` property.
/// The override is declared in the referenced file, so only the tree-wide name
/// manifest can resolve it (P14/P15).
#[test]
fn java_json_cross_module_java_name_override_moves_every_reference() {
    let temp_dir = unique_output_path("java-json-cross-module-override");
    let input_dir = write_cross_module_closure(&temp_dir);
    // The output directory's base name must equal the package's last segment.
    let output_path = temp_dir.join("pages");

    generate_to_file(&GenerateRequest {
        config: Default::default(),
        language: nexgen::language::Language::Java,
        input_paths: vec![input_dir],
        support_package: None,
        descriptor_paths: Vec::new(),
        output_path: output_path.clone(),
        format: false,
        java_package_name: Some("example.pages".to_string()),
        ts_date_time_types: Default::default(),
    })
    .unwrap();

    let rendered = read_java_files(&output_path);
    let declaring = &rendered[&PathBuf::from("content/page/RenamedPage.java")];
    assert!(
        declaring.contains("public final class RenamedPage {"),
        "{declaring}"
    );

    let service = &rendered[&PathBuf::from("kb/Pages.java")];
    for expected in [
        "import example.pages.content.page.RenamedPage;",
        "RenamedPage get(GetInput input);",
    ] {
        assert!(service.contains(expected), "{expected}\n{service}");
    }

    let consuming = &rendered[&PathBuf::from("kb/FindOutput.java")];
    for expected in [
        "import example.pages.content.page.RenamedPage;",
        "private final @Nullable RenamedPage page;",
        "public @Nullable RenamedPage getPage() {",
        "context.readTreeAsValue(field, RenamedPage.class);",
    ] {
        assert!(consuming.contains(expected), "{expected}\n{consuming}");
    }
    // Nothing names the pre-override identifier.
    for stale in [
        ".page.Page;",
        "@Nullable Page ",
        "(field, Page.class)",
        " Page get(",
    ] {
        assert!(!service.contains(stale), "{stale}\n{service}");
        assert!(!consuming.contains(stale), "{stale}\n{consuming}");
    }
    fs::remove_dir_all(temp_dir).unwrap();
}

#[test]
fn java_json_bare_ref_root_alias_collapses_to_the_target_class() {
    let temp_dir = unique_output_path("java-json-bare-ref-alias");
    let input = write_bare_ref_alias_closure(&temp_dir);
    let gradle_root = temp_dir.join("project");
    fs::create_dir_all(&gradle_root).unwrap();
    fs::copy(
        project_root().join("samples/java/build.gradle"),
        gradle_root.join("build.gradle"),
    )
    .unwrap();
    fs::copy(
        project_root().join("samples/java/settings.gradle"),
        gradle_root.join("settings.gradle"),
    )
    .unwrap();
    let output_path = gradle_root.join("src/main/java/example/aliases");
    generate_to_file(&GenerateRequest {
        language: nexgen::language::Language::Java,
        input_paths: vec![input],
        support_package: None,
        descriptor_paths: Vec::new(),
        output_path: output_path.clone(),
        format: false,
        config: Default::default(),
        java_package_name: Some("example.aliases".to_string()),
        ts_date_time_types: Default::default(),
    })
    .unwrap();

    assert!(output_path.join("target/main/Main.java").is_file());
    assert!(
        !output_path.join("alias/alternate/Alternate.java").exists(),
        "Java must not synthesize a class for a bare-ref alias"
    );
    assert!(
        !output_path.join("target/main/Mirror.java").exists(),
        "Java must also collapse a bare-ref `$defs` alias"
    );
    let service = fs::read_to_string(output_path.join("service/AliasService.java")).unwrap();
    assert!(
        service.contains("import example.aliases.target.main.Main;"),
        "{service}"
    );
    assert!(service.contains("Main echo(Main input);"), "{service}");
    assert!(!service.contains("Alternate"), "{service}");
    let holder = fs::read_to_string(output_path.join("service/Holder.java")).unwrap();
    assert!(holder.contains("private final Main item;"), "{holder}");
    assert!(!holder.contains("Alternate"), "{holder}");

    let test_package = gradle_root.join("src/test/java/example/aliases");
    fs::create_dir_all(&test_package).unwrap();
    fs::write(
        test_package.join("BareAliasTest.java"),
        r#"package example.aliases;

import static org.junit.jupiter.api.Assertions.assertEquals;

import com.fasterxml.jackson.databind.ObjectMapper;
import example.aliases.service.Holder;
import example.aliases.target.main.Main;
import org.junit.jupiter.api.Test;

final class BareAliasTest {
    @Test
    void aliasPositionsUseTheTargetClassAtRuntime() throws Exception {
        Main value = new Main("ok");
        Holder holder = new Holder(value);
        assertEquals(value, holder.getItem());

        ObjectMapper mapper = new ObjectMapper();
        Main decoded = mapper.readValue(mapper.writeValueAsBytes(value), Main.class);
        assertEquals(value, decoded);
    }
}
"#,
    )
    .unwrap();
    let status = Command::new(project_root().join("samples/java/gradlew"))
        .args(["--no-daemon", "test"])
        .current_dir(&gradle_root)
        .status()
        .expect("run Gradle alias compile/runtime test");
    assert!(status.success(), "Gradle alias test failed: {status}");
    fs::remove_dir_all(temp_dir).unwrap();
}

/// Java gives each module its own package and one file per class, so re-emitting
/// a `$ref`d type into the referencing service's module wrote `Page.java` twice
/// and the build failed outright with a generated-file conflict. It happened
/// whenever the service module declared no types of its own.
#[test]
fn java_json_service_module_without_own_types_does_not_reemit_refs() {
    let temp_dir = unique_output_path("java-json-service-only-module");
    let input_dir = temp_dir.join("input");
    fs::create_dir_all(input_dir.join("a")).unwrap();
    fs::write(
        input_dir.join("a/page.json"),
        r#"{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","additionalProperties":false,"properties":{"title":{"type":"string"}},"required":["title"]}"#,
    )
    .unwrap();
    fs::write(
        input_dir.join("svc.nexusrpc.yaml"),
        r#"$schema: https://json-schema.org/draft/2020-12/schema
nexusrpc: "1.0.0"
services:
  Svc:
    fqn: example.v1.Svc
    operations:
      one:
        input: { $ref: "a/page.json" }
"#,
    )
    .unwrap();

    let output_path = temp_dir.join("pkg");
    generate_to_file(&GenerateRequest {
        config: Default::default(),
        language: nexgen::language::Language::Java,
        input_paths: vec![input_dir],
        support_package: None,
        descriptor_paths: Vec::new(),
        output_path: output_path.clone(),
        format: false,
        java_package_name: Some("com.example.pkg".to_string()),
        ts_date_time_types: Default::default(),
    })
    .unwrap();

    // `Page` is emitted once, by the module that declares it.
    let paths = read_java_files(&output_path)
        .into_keys()
        .filter(|path| path.file_name().is_some_and(|name| name == "Page.java"))
        .collect::<Vec<_>>();
    assert_eq!(paths, vec![PathBuf::from("a/page/Page.java")]);
    // The service's own package holds only the service.
    let service = fs::read_to_string(output_path.join("svc/Svc.java")).unwrap();
    assert!(
        service.contains("import com.example.pkg.a.page.Page;"),
        "{service}"
    );
    fs::remove_dir_all(temp_dir).unwrap();
}

/// A nullable property is authored as `oneOf: [T, null]`; the wrapper carries no
/// `type` and no keywords, so every read of the member's shape has to go through
/// the non-null branch. Before this, Java silently accepted payloads TypeScript
/// and Python rejected (`13#2`, `07#1`, `11#1`, `06#4`).
const JAVA_NULLABLE_SHAPE_SCHEMA: &str = r##"$schema: https://json-schema.org/draft/2020-12/schema
type: object
properties:
  nullName:
    oneOf:
      - { type: string, minLength: 3, pattern: "^[a-z]+$" }
      - { type: "null" }
  nullEnum:
    oneOf:
      - { type: string, enum: [a, b] }
      - { type: "null" }
  nullEmail:
    oneOf:
      - { type: string, format: email }
      - { type: "null" }
  nullInt:
    oneOf:
      - { type: integer, minimum: 1, maximum: 10 }
      - { type: "null" }
  nullTags:
    oneOf:
      - type: array
        items: { type: string }
        minItems: 2
        contains: { type: string, minLength: 2 }
      - { type: "null" }
"##;

#[test]
fn java_json_nullable_property_keeps_the_branch_constraints() {
    let temp_dir = unique_output_path("java-json-nullable-shape");
    fs::create_dir_all(&temp_dir).unwrap();
    let input_path = temp_dir.join("nullable_shape.yaml");
    fs::write(&input_path, JAVA_NULLABLE_SHAPE_SCHEMA).unwrap();
    let output_path = temp_dir.join("nullable_shape");

    generate_to_file(&GenerateRequest {
        config: Default::default(),
        language: nexgen::language::Language::Java,
        input_paths: vec![input_path],
        support_package: None,
        descriptor_paths: Vec::new(),
        output_path: output_path.clone(),
        format: false,
        java_package_name: Some("nullable_shape".to_string()),
        ts_date_time_types: Default::default(),
    })
    .unwrap();

    let rendered = read_java_files(&output_path);
    let model = &rendered[&PathBuf::from("NullableShape.java")];
    for expected in [
        // A nullable `enum` still becomes a closed value class.
        "public static final class NullEnum {",
        "public static final NullEnum A = new NullEnum(\"a\");",
        "private final @Nullable NullEnum nullEnum;",
        // …and every constraint reaches both directions.
        "NULL_NAME_PATTERN = java.util.regex.Pattern.compile(\"^[a-z]+\\\\z\")",
        "NULL_EMAIL_FORMAT = java.util.regex.Pattern.compile(",
        "must have length >= 3",
        "must be a valid email",
        "must be >= 1",
        "must be <= 10",
        "must have at least 2 items",
        "no element matches the required schema",
        // The nullable array's element type comes from the branch, not the wrapper.
        "private final @Nullable List<String> nullTags;",
    ] {
        assert!(model.contains(expected), "{expected}\n{model}");
    }
    fs::remove_dir_all(temp_dir).unwrap();
}

/// The serialize side is the mirror of the parse side (P12) for every check the
/// in-memory value can still violate: the integer cap (`13#3`), `contains`
/// (`06#gap-8`), `uniqueItems` over materialized values compared on their
/// canonical wire string (`05#2`, `05#3`, decision D10), and every temporal's
/// representability (`09#3`). `byte[]` members also need value equality
/// (`10#5`).
const JAVA_SERIALIZE_GUARD_SCHEMA: &str = r##"$schema: https://json-schema.org/draft/2020-12/schema
type: object
properties:
  count: { type: integer }
  bumps:
    type: array
    items: { type: integer }
    contains: { type: number, minimum: 1.5 }
  stamps:
    type: array
    items: { type: string, format: date-time }
    uniqueItems: true
  blobs:
    type: array
    items: { type: string, contentEncoding: base64 }
    uniqueItems: true
  ratios:
    type: array
    items: { type: number }
    uniqueItems: true
  payload: { type: string, contentEncoding: base64 }
  slot: { type: string, format: time }
  window: { type: string, format: duration }
"##;

#[test]
fn java_json_serialize_side_guards_match_the_parse_side() {
    let temp_dir = unique_output_path("java-json-serialize-guards");
    fs::create_dir_all(&temp_dir).unwrap();
    let input_path = temp_dir.join("guards.yaml");
    fs::write(&input_path, JAVA_SERIALIZE_GUARD_SCHEMA).unwrap();
    let output_path = temp_dir.join("guards");

    generate_to_file(&GenerateRequest {
        config: Default::default(),
        language: nexgen::language::Language::Java,
        input_paths: vec![input_path],
        support_package: None,
        descriptor_paths: Vec::new(),
        output_path: output_path.clone(),
        format: false,
        java_package_name: Some("guards".to_string()),
        ts_date_time_types: Default::default(),
    })
    .unwrap();

    let rendered = read_java_files(&output_path);
    let model = &rendered[&PathBuf::from("Guards.java")];
    let serializer = model.split("class Serializer").nth(1).unwrap();
    let serializer = serializer.split("class Deserializer").next().unwrap();
    for expected in [
        // 13#3 — the +/-(2^53-1) cap exists on the way out too.
        "if (value.count < -SpecNumbers.INTEGER_CAP || value.count > SpecNumbers.INTEGER_CAP)",
        "exceeds \\u00b1(2^53-1) integer cap",
        // 06#gap-8 — `contains` is asserted before emit, and 06#2: a fractional
        // bound over `integer` elements is NOT truncated to `1L`.
        "element >= 1.5",
        "no element matches the required schema",
        // 05#3 / D10 — materialized elements compare on the canonical wire string.
        "Object element = (value.stamps.get(index) == null ? null : TemporalSupport.formatDateTime(value.stamps.get(index)));",
        "Object element = (value.blobs.get(index) == null ? null : Base64Support.formatBase64(value.blobs.get(index)));",
        // 05#2 — `-0.0` and `0.0` are one value on serialize, as on parse.
        "Object element = SpecNumbers.numberKey(value.ratios.get(index));",
        // 09#3 — every temporal has a representability predicate, not just dates.
        "TemporalSupport.checkTime(value.slot, \"slot\", violations);",
        "TemporalSupport.checkDuration(value.window, \"window\", violations);",
    ] {
        assert!(serializer.contains(expected), "{expected}\n{serializer}");
    }
    // 10#5 — `byte[]` has no value equality of its own.
    for expected in [
        "java.util.Arrays.equals(this.payload, that.payload)",
        "Base64Support.listEquals(this.blobs, that.blobs)",
        "java.util.Arrays.hashCode(payload)",
        "java.util.Arrays.toString(payload)",
    ] {
        assert!(model.contains(expected), "{expected}\n{model}");
    }
    fs::remove_dir_all(temp_dir).unwrap();
}

/// A tagged union's discriminant is any scalar the loader admits, not only a
/// string, and it selects a branch by JSON **value** equality — so `1.0` picks
/// the `const: 1` branch (`01#3`). An integer `const` written `1.0` is `1L`,
/// never `0L` (`11#2`).
const JAVA_SCALAR_DISCRIMINANT_SCHEMA: &str = r##"$schema: https://json-schema.org/draft/2020-12/schema
type: object
properties:
  shape: { $ref: "#/$defs/Shape" }
  score: { type: integer, const: 1.0 }
$defs:
  Shape:
    oneOf:
      - $ref: "#/$defs/Circle"
      - $ref: "#/$defs/Square"
  Circle:
    type: object
    required: [kind, r]
    properties:
      kind: { type: integer, const: 1 }
      r: { type: number }
  Square:
    type: object
    required: [kind, side]
    properties:
      kind: { type: integer, const: 2 }
      side: { type: number }
"##;

#[test]
fn java_json_dispatches_a_non_string_discriminant_by_value() {
    let temp_dir = unique_output_path("java-json-scalar-discriminant");
    fs::create_dir_all(&temp_dir).unwrap();
    let input_path = temp_dir.join("tagged.yaml");
    fs::write(&input_path, JAVA_SCALAR_DISCRIMINANT_SCHEMA).unwrap();
    let output_path = temp_dir.join("tagged");

    generate_to_file(&GenerateRequest {
        config: Default::default(),
        language: nexgen::language::Language::Java,
        input_paths: vec![input_path],
        support_package: None,
        descriptor_paths: Vec::new(),
        output_path: output_path.clone(),
        format: false,
        java_package_name: Some("tagged".to_string()),
        ts_date_time_types: Default::default(),
    })
    .unwrap();

    let rendered = read_java_files(&output_path);
    let union = &rendered[&PathBuf::from("Shape.java")];
    for expected in [
        "if (disc == null || disc.isNull() || !disc.isValueNode()) {",
        "if (disc.isNumber() && disc.doubleValue() == 1.0) {",
        "if (disc.isNumber() && disc.doubleValue() == 2.0) {",
        "unknown discriminator kind \" + disc.asText() + \"",
    ] {
        assert!(union.contains(expected), "{expected}\n{union}");
    }
    assert!(!union.contains("switch (disc.textValue())"), "{union}");

    let model = &rendered[&PathBuf::from("Tagged.java")];
    assert!(
        model.contains("public static final Score V_1 = new Score(1L);"),
        "{model}"
    );
    fs::remove_dir_all(temp_dir).unwrap();
}

/// A nested model reports its failures with paths rooted at **its** members;
/// they have to be re-pathed under the owning member and merged into the
/// parent's list, in both directions (`03#8`, P11).
const JAVA_NESTED_PATH_SCHEMA: &str = r##"$schema: https://json-schema.org/draft/2020-12/schema
type: object
required: [address]
properties:
  address: { $ref: "#/$defs/Addr" }
  addresses:
    type: array
    items: { $ref: "#/$defs/Addr" }
  label: { type: string, minLength: 4 }
$defs:
  Addr:
    type: object
    properties:
      zip: { type: string, minLength: 5 }
"##;

#[test]
fn java_json_repaths_nested_violations_on_serialize() {
    let temp_dir = unique_output_path("java-json-nested-path");
    fs::create_dir_all(&temp_dir).unwrap();
    let input_path = temp_dir.join("nested_path.yaml");
    fs::write(&input_path, JAVA_NESTED_PATH_SCHEMA).unwrap();
    let output_path = temp_dir.join("nested_path");

    generate_to_file(&GenerateRequest {
        config: Default::default(),
        language: nexgen::language::Language::Java,
        input_paths: vec![input_path],
        support_package: None,
        descriptor_paths: Vec::new(),
        output_path: output_path.clone(),
        format: false,
        java_package_name: Some("nested_path".to_string()),
        ts_date_time_types: Default::default(),
    })
    .unwrap();

    let rendered = read_java_files(&output_path);
    assert!(!rendered.contains_key(&PathBuf::from("PayloadValidationError.java")));
    let model = &rendered[&PathBuf::from("NestedPath.java")];
    let serializer = model.split("class Serializer").nth(1).unwrap();
    let serializer = serializer.split("class Deserializer").next().unwrap();
    for expected in [
        "if (value.address == null) {",
        "violations.add(new Violation(\"address\", \"required\"));",
        "TokenBuffer pending = new com.fasterxml.jackson.databind.util.TokenBuffer(gen.getCodec(), false);",
        "TokenBuffer nestedBuffer0 = new com.fasterxml.jackson.databind.util.TokenBuffer(gen.getCodec(), false);",
        "nestedBuffer0.serialize(gen);",
        "pending.serialize(target);",
        "} catch (ApplicationFailure nested0) {",
        "if (!\"PayloadValidationError\".equals(nested0.getType()) || nested0.getDetails().getSize() == 0) {",
        "List<Violation> nestedViolations0 = (List<Violation>) nested0.getDetails().get(0, List.class);",
        "for (Violation nestedViolation0 : nestedViolations0) {",
        "violations.add(nestedViolation0.withPathPrefix(\"address\"));",
        "violations.add(nestedViolation1.withPathPrefix(\"addresses\" + \"[\" + nestedIndex0 + \"]\"));",
        // The throw moved past the write so a nested failure joins the parent's
        // own violations rather than escaping alone.
        "// TODO: Use PayloadValidationException.newPayloadValidationException once it is available in an SDK release.",
        "throw ApplicationFailure.newNonRetryableFailure(\"Payload validation failed\", \"PayloadValidationError\", violations);",
    ] {
        assert!(serializer.contains(expected), "{expected}\n{serializer}");
    }
    fs::remove_dir_all(temp_dir).unwrap();
}

/// A `pattern`/`format` inside a `contains` matcher runs once per element in
/// both directions, so it is compiled once at class init like every other
/// pinned regex (`08#7`, `09#11`).
const JAVA_CONTAINS_REGEX_SCHEMA: &str = r##"$schema: https://json-schema.org/draft/2020-12/schema
type: object
properties:
  names:
    type: array
    items: { type: string }
    contains: { type: string, pattern: "^a" }
  emails:
    type: array
    items: { type: string }
    contains: { type: string, format: email }
"##;

#[test]
fn java_json_compiles_contains_matcher_regexes_once() {
    let temp_dir = unique_output_path("java-json-contains-regex");
    fs::create_dir_all(&temp_dir).unwrap();
    let input_path = temp_dir.join("contains_regex.yaml");
    fs::write(&input_path, JAVA_CONTAINS_REGEX_SCHEMA).unwrap();
    let output_path = temp_dir.join("contains_regex");

    generate_to_file(&GenerateRequest {
        config: Default::default(),
        language: nexgen::language::Language::Java,
        input_paths: vec![input_path],
        support_package: None,
        descriptor_paths: Vec::new(),
        output_path: output_path.clone(),
        format: false,
        java_package_name: Some("contains_regex".to_string()),
        ts_date_time_types: Default::default(),
    })
    .unwrap();

    let rendered = read_java_files(&output_path);
    let model = &rendered[&PathBuf::from("ContainsRegex.java")];
    assert!(
        model.contains(
            "private static final java.util.regex.Pattern NAMES_CONTAINS_PATTERN = java.util.regex.Pattern.compile(\"^a\");"
        ),
        "{model}"
    );
    assert!(
        model.contains("private static final java.util.regex.Pattern EMAILS_CONTAINS_FORMAT ="),
        "{model}"
    );
    assert!(
        model.contains("NAMES_CONTAINS_PATTERN.matcher(element).find()"),
        "{model}"
    );
    assert!(
        model.contains("EMAILS_CONTAINS_FORMAT.matcher(rawElement.textValue()).find()"),
        "{model}"
    );
    // No inline compile survives in the matcher loops.
    let matcher_loops = model.matches("java.util.regex.Pattern.compile").count();
    assert_eq!(matcher_loops, 2, "{model}");
    fs::remove_dir_all(temp_dir).unwrap();
}

/// Authored prose lands on the **public getter**, where `javadoc` can see it —
/// never on the private field, and the generated `@deprecated` tag is a trailer
/// of that same block rather than an orphan comment (`12#4`).
const JAVA_MEMBER_DOC_SCHEMA: &str = r##"$schema: https://json-schema.org/draft/2020-12/schema
type: object
properties:
  legacy:
    type: string
    title: Legacy id
    description: Use `id` instead.
    deprecated: true
  plain:
    type: string
    description: A plain member.
"##;

#[test]
fn java_json_member_javadoc_lands_on_the_getter() {
    let temp_dir = unique_output_path("java-json-member-doc");
    fs::create_dir_all(&temp_dir).unwrap();
    let input_path = temp_dir.join("member_doc.yaml");
    fs::write(&input_path, JAVA_MEMBER_DOC_SCHEMA).unwrap();
    let output_path = temp_dir.join("member_doc");

    generate_to_file(&GenerateRequest {
        config: Default::default(),
        language: nexgen::language::Language::Java,
        input_paths: vec![input_path],
        support_package: None,
        descriptor_paths: Vec::new(),
        output_path: output_path.clone(),
        format: false,
        java_package_name: Some("member_doc".to_string()),
        ts_date_time_types: Default::default(),
    })
    .unwrap();

    let rendered = read_java_files(&output_path);
    let model = &rendered[&PathBuf::from("MemberDoc.java")];
    // One block, prose then tag, then the annotation, then the getter.
    assert!(
        model.contains(
            "     * Legacy id\n     *\n     * Use `id` instead.\n     *\n     * @deprecated This field is deprecated.\n     */\n    @Deprecated\n    public @Nullable String getLegacy() {"
        ),
        "{model}"
    );
    assert!(
        model.contains("     * A plain member.\n     */\n    public @Nullable String getPlain() {"),
        "{model}"
    );
    // Nothing is attached to the private field any more.
    assert!(
        model.contains("    private final @Nullable String legacy;\n    private final @Nullable String plain;\n"),
        "{model}"
    );
    fs::remove_dir_all(temp_dir).unwrap();
}

/// A typed-map branch of a typeless `oneOf` is an object model like any other
/// member, so it must carry the union interface. Without the clause the
/// dispatcher's `readTreeAsValue(node, <Branch>.class)` pins `T` to the branch
/// while the return position bounds it by the interface — an unsatisfiable
/// inference constraint, so the package does not compile
/// (`new:java-union-typed-map-branch`).
const JAVA_UNION_TYPED_MAP_BRANCH_SCHEMA: &str = r##"$schema: https://json-schema.org/draft/2020-12/schema
type: object
required: [scalarUnion]
properties:
  scalarUnion:
    oneOf:
      - { type: string }
      - { type: integer }
      - type: array
        items: { type: string }
      - type: object
        additionalProperties: { type: string }
"##;

#[test]
fn java_json_typed_map_union_branch_implements_the_interface() {
    let temp_dir = unique_output_path("java-json-union-typed-map");
    fs::create_dir_all(&temp_dir).unwrap();
    let input_path = temp_dir.join("union_map.yaml");
    fs::write(&input_path, JAVA_UNION_TYPED_MAP_BRANCH_SCHEMA).unwrap();
    let output_path = temp_dir.join("union_map");

    generate_to_file(&GenerateRequest {
        config: Default::default(),
        language: nexgen::language::Language::Java,
        input_paths: vec![input_path],
        support_package: None,
        descriptor_paths: Vec::new(),
        output_path: output_path.clone(),
        format: false,
        java_package_name: Some("union_map".to_string()),
        ts_date_time_types: Default::default(),
    })
    .unwrap();

    let rendered = read_java_files(&output_path);
    let branch = &rendered[&PathBuf::from("UnionMapScalarUnionObject.java")];
    assert!(
        branch.contains(
            "public final class UnionMapScalarUnionObject implements UnionMap.ScalarUnion {"
        ),
        "{branch}"
    );
    // The dispatcher reads the branch through the class literal, which only
    // type-checks because of the clause above.
    let model = &rendered[&PathBuf::from("UnionMap.java")];
    assert!(
        model.contains("return context.readTreeAsValue(node, UnionMapScalarUnionObject.class);"),
        "{model}"
    );
    fs::remove_dir_all(temp_dir).unwrap();
}

/// `items: {oneOf: [T, null]}` is the **element-level** spelling of nullability.
/// The wrapper carries no `type` and no keywords, so reading `schema.items`
/// directly drops the non-null branch's constraints, exactly as the field
/// planner used to at the property level (`13#2`).
const JAVA_NULLABLE_ELEMENT_SCHEMA: &str = r##"$schema: https://json-schema.org/draft/2020-12/schema
type: object
properties:
  slots:
    type: array
    items:
      oneOf:
        - { type: string, minLength: 2 }
        - { type: "null" }
  counts:
    type: array
    items:
      oneOf:
        - { type: integer, minimum: 5 }
        - { type: "null" }
  grid:
    type: array
    items:
      type: array
      items:
        oneOf:
          - { type: string, minLength: 2 }
          - { type: "null" }
  lookup:
    type: object
    additionalProperties:
      type: array
      items:
        oneOf:
          - { type: string, minLength: 2 }
          - { type: "null" }
"##;

#[test]
fn java_json_nullable_element_keeps_the_branch_constraints() {
    let temp_dir = unique_output_path("java-json-nullable-element");
    fs::create_dir_all(&temp_dir).unwrap();
    let input_path = temp_dir.join("nullable_element.yaml");
    fs::write(&input_path, JAVA_NULLABLE_ELEMENT_SCHEMA).unwrap();
    let output_path = temp_dir.join("nullable_element");

    generate_to_file(&GenerateRequest {
        config: Default::default(),
        language: nexgen::language::Language::Java,
        input_paths: vec![input_path],
        support_package: None,
        descriptor_paths: Vec::new(),
        output_path: output_path.clone(),
        format: false,
        java_package_name: Some("nullable_element".to_string()),
        ts_date_time_types: Default::default(),
    })
    .unwrap();

    let rendered = read_java_files(&output_path);
    let model = &rendered[&PathBuf::from("NullableElement.java")];
    let serializer = model.split("class Serializer").nth(1).unwrap();
    let (serializer, deserializer) = {
        let mut parts = serializer.split("class Deserializer");
        (
            parts.next().unwrap().to_string(),
            parts.next().unwrap().to_string(),
        )
    };
    // Serialize side (P12) — every depth.
    for expected in [
        "\"slots\" + \"[\" + validationIndex0 + \"]\", \"must have length >= 2",
        "\"counts\" + \"[\" + validationIndex0 + \"]\", \"must be >= 5",
        "\"grid\" + \"[\" + validationIndex0 + \"]\" + \"[\" + validationIndex1 + \"]\", \"must have length >= 2",
    ] {
        assert!(serializer.contains(expected), "{expected}\n{serializer}");
    }
    // Parse side — the same constraints, keyed by the element path.
    for expected in ["must have length >= 2", "must be >= 5"] {
        assert!(
            deserializer.contains(expected),
            "{expected}\n{deserializer}"
        );
    }
    // A typed-map member whose value is an array of nullable elements.
    let map = &rendered[&PathBuf::from("NullableElementLookup.java")];
    assert!(map.contains("must have length >= 2"), "{map}");
    fs::remove_dir_all(temp_dir).unwrap();
}

/// A materialized value inside a collection must be written by the generator,
/// not handed to Jackson: a stock `ObjectMapper` throws
/// `InvalidDefinitionException` on `java.time.*` without the jsr310 module, and
/// writes `byte[]` in its own base64 variant rather than the canonical form the
/// parser accepts. P3/P4 require the generated code to work with the stock
/// converter and no user wiring.
const JAVA_MATERIALIZED_COLLECTION_SCHEMA: &str = r##"$schema: https://json-schema.org/draft/2020-12/schema
type: object
properties:
  stamps:
    type: array
    items: { type: string, format: date-time }
  urls:
    type: array
    items: { type: string, contentEncoding: base64url }
  days:
    type: array
    items:
      type: array
      items: { type: string, format: date }
  byKey:
    type: object
    additionalProperties:
      type: array
      items: { type: string, format: duration }
"##;

#[test]
fn java_json_writes_materialized_collection_elements_itself() {
    let temp_dir = unique_output_path("java-json-materialized-collection");
    fs::create_dir_all(&temp_dir).unwrap();
    let input_path = temp_dir.join("materialized.yaml");
    fs::write(&input_path, JAVA_MATERIALIZED_COLLECTION_SCHEMA).unwrap();
    let output_path = temp_dir.join("materialized");

    generate_to_file(&GenerateRequest {
        config: Default::default(),
        language: nexgen::language::Language::Java,
        input_paths: vec![input_path],
        support_package: None,
        descriptor_paths: Vec::new(),
        output_path: output_path.clone(),
        format: false,
        java_package_name: Some("materialized".to_string()),
        ts_date_time_types: Default::default(),
    })
    .unwrap();

    let rendered = read_java_files(&output_path);
    let model = &rendered[&PathBuf::from("Materialized.java")];
    for expected in [
        "gen.writeString(TemporalSupport.formatDateTime(wireElement0));",
        "gen.writeString(Base64Support.formatBase64Url(wireElement0));",
        // A nested array recurses, one loop per level.
        "gen.writeString(TemporalSupport.formatDate(wireElement1));",
        // A null element is a JSON null, not a formatter call.
        "gen.writeNull();",
    ] {
        assert!(model.contains(expected), "{expected}\n{model}");
    }
    // Nothing materialized reaches Jackson's defaults any more.
    for leaked in [
        "serializers.defaultSerializeValue(value.stamps, gen);",
        "serializers.defaultSerializeValue(value.urls, gen);",
        "serializers.defaultSerializeValue(value.days, gen);",
    ] {
        assert!(!model.contains(leaked), "{leaked}\n{model}");
    }
    // The typed-map member is written the same way.
    let map = &rendered[&PathBuf::from("MaterializedByKey.java")];
    assert!(
        map.contains("gen.writeString(TemporalSupport.formatDuration(wireElement0));"),
        "{map}"
    );
    assert!(
        !map.contains("serializers.defaultSerializeValue(entry.getValue(), gen);"),
        "{map}"
    );
    fs::remove_dir_all(temp_dir).unwrap();
}

/// `x-java-enum-names` is keyed by the member's canonical **wire spelling**, so
/// it has to reach a numeric or boolean member too. While the lookup gated on
/// `Value::String`, those members silently ignored their override — and this is
/// the only escape hatch P15 offers for a value-constant collision, which P15
/// requires to reach the name it is offered for (`11#11`). The key derivation
/// matches the loader's `enum_names_lookup_key` and Go's copy of it.
const JAVA_ENUM_NAME_OVERRIDE_SCHEMA: &str = r##"$schema: https://json-schema.org/draft/2020-12/schema
type: object
properties:
  tier:
    type: integer
    enum: [1, 2]
    x-java-enum-names: { "1": TIER_BRONZE, "2": TIER_SILVER }
  toggle:
    type: boolean
    enum: [true, false]
    x-java-enum-names: { "true": TOGGLE_ON, "false": TOGGLE_OFF }
  scale:
    type: number
    enum: [1.5, 2.5]
    x-java-enum-names: { "1.5": SCALE_HALF, "2.5": SCALE_TWO_HALF }
  mode:
    type: string
    enum: [fast, slow]
    x-java-enum-names: { fast: MODE_FAST }
"##;

#[test]
fn java_json_enum_name_override_reaches_non_string_members() {
    let temp_dir = unique_output_path("java-json-enum-names");
    fs::create_dir_all(&temp_dir).unwrap();
    let input_path = temp_dir.join("enum_names.yaml");
    fs::write(&input_path, JAVA_ENUM_NAME_OVERRIDE_SCHEMA).unwrap();
    let output_path = temp_dir.join("enum_names");

    generate_to_file(&GenerateRequest {
        config: Default::default(),
        language: nexgen::language::Language::Java,
        input_paths: vec![input_path],
        support_package: None,
        descriptor_paths: Vec::new(),
        output_path: output_path.clone(),
        format: false,
        java_package_name: Some("enum_names".to_string()),
        ts_date_time_types: Default::default(),
    })
    .unwrap();

    let rendered = read_java_files(&output_path);
    let model = &rendered[&PathBuf::from("EnumNames.java")];
    for expected in [
        // integer members
        "public static final Tier TIER_BRONZE = new Tier(1L);",
        "public static final Tier TIER_SILVER = new Tier(2L);",
        // boolean members
        "public static final Toggle TOGGLE_ON = new Toggle(true);",
        "public static final Toggle TOGGLE_OFF = new Toggle(false);",
        // number members, including a fractional wire spelling as the map key
        "public static final Scale SCALE_HALF = new Scale(1.5);",
        "public static final Scale SCALE_TWO_HALF = new Scale(2.5);",
        // a string member still works, and an un-overridden member falls back to
        // the value-derived name (D3): the value token, never the member's.
        "public static final Mode MODE_FAST = new Mode(\"fast\");",
        "public static final Mode SLOW = new Mode(\"slow\");",
    ] {
        assert!(model.contains(expected), "{expected}\n{model}");
    }
    // The value-derived names the lookup falls back to when no override is
    // authored — `V_`-guarded for the numerics, bare for the boolean. Their
    // absence is what proves each override actually reached its member.
    for derived in ["Tier V_1 ", "Toggle TRUE ", "Scale V_1_5 "] {
        assert!(!model.contains(derived), "{derived}\n{model}");
    }
    fs::remove_dir_all(temp_dir).unwrap();
}

/// D3: a Java value constant is named from the **value**, never the member.
///
/// The member-derived spelling (`Kind.KIND`, `Tier.TIER_1`) dropped the value
/// from a single-valued `const` entirely and, worse, made the constant move
/// under `x-java-name` — so a value-constant collision had two remedies while
/// the P15 fix-it named one, and `const: "-"` (whose value token is empty)
/// quietly borrowed a legal name from its member instead of hitting the load
/// reject. Naming from the value alone costs the `V_` guard, which Go does not
/// need because its `{Type}` prefix always supplies a leading letter.
#[test]
fn java_json_names_value_constants_from_the_value() {
    let temp_dir = unique_output_path("java-json-const-naming");
    fs::create_dir_all(&temp_dir).unwrap();
    let input_path = temp_dir.join("naming.yaml");
    fs::write(
        &input_path,
        r##"$schema: https://json-schema.org/draft/2020-12/schema
type: object
properties:
  kind:
    type: string
    const: showcase
  enabled:
    type: boolean
    const: true
  tier:
    type: integer
    enum: [1, -2]
  scale:
    type: number
    enum: [1.5, -2.25]
  status:
    type: string
    enum: [active, "multi-word_ish"]
"##,
    )
    .unwrap();
    let output_path = temp_dir.join("naming");

    generate_to_file(&GenerateRequest {
        config: Default::default(),
        language: nexgen::language::Language::Java,
        input_paths: vec![input_path],
        support_package: None,
        descriptor_paths: Vec::new(),
        output_path: output_path.clone(),
        format: false,
        java_package_name: Some("naming".to_string()),
        ts_date_time_types: Default::default(),
    })
    .unwrap();

    let model = &read_java_files(&output_path)[&PathBuf::from("Naming.java")];
    for expected in [
        // A single-valued `const` names the value, not the member — the member
        // is already the value class's own name, so `Kind.KIND` said nothing.
        "public static final Kind SHOWCASE = new Kind(\"showcase\");",
        "public static final Enabled TRUE = new Enabled(true);",
        // Numerics take the `V_` guard by kind, so the `NEG_` sign word does not
        // let `-2` pass as letter-leading and collide with a string `"neg2"`.
        "public static final Tier V_1 = new Tier(1L);",
        "public static final Tier V_NEG_2 = new Tier(-2L);",
        "public static final Scale V_1_5 = new Scale(1.5);",
        "public static final Scale V_NEG_2_25 = new Scale(-2.25);",
        // Strings word-split on any non-alphanumeric ASCII, then UPPER_SNAKE.
        "public static final Status ACTIVE = new Status(\"active\");",
        "public static final Status MULTI_WORD_ISH = new Status(\"multi-word_ish\");",
    ] {
        assert!(model.contains(expected), "{expected}\n{model}");
    }
    // No constant carries its member's name.
    for member_derived in [
        "Kind KIND ",
        "Enabled ENABLED ",
        "Tier TIER_",
        "Scale SCALE_",
    ] {
        assert!(!model.contains(member_derived), "{member_derived}\n{model}");
    }
    fs::remove_dir_all(temp_dir).unwrap();
}

/// P1 makes `1`, `1.0` and `1e0` one number, so all three must name one
/// constant: re-spelling a `const` is a no-op on the wire and must not rename a
/// public constant out from under callers (P13). The token used to come from
/// `serde_json::Number`'s own spelling, so `const: 1.0` on a `type: integer`
/// emitted `V_1_0` in Java and `Score1_0` in Go while `const: 1` emitted `V_1` /
/// `Score1`.
#[test]
fn java_json_numeric_constant_names_are_spelling_stable() {
    let render = |spelling: &str| {
        let temp_dir = unique_output_path("java-json-const-spelling");
        fs::create_dir_all(&temp_dir).unwrap();
        let input_path = temp_dir.join("spelling.yaml");
        fs::write(
            &input_path,
            format!(
                r##"$schema: https://json-schema.org/draft/2020-12/schema
type: object
properties:
  score:
    type: integer
    const: {spelling}
"##
            ),
        )
        .unwrap();
        let output_path = temp_dir.join("spelling");
        generate_to_file(&GenerateRequest {
            config: Default::default(),
            language: nexgen::language::Language::Java,
            input_paths: vec![input_path],
            support_package: None,
            descriptor_paths: Vec::new(),
            output_path: output_path.clone(),
            format: false,
            java_package_name: Some("spelling".to_string()),
            ts_date_time_types: Default::default(),
        })
        .unwrap();
        let model = read_java_files(&output_path)[&PathBuf::from("Spelling.java")].clone();
        fs::remove_dir_all(temp_dir).unwrap();
        model
    };

    for spelling in ["1", "1.0", "1e0"] {
        let model = render(spelling);
        assert!(
            model.contains("public static final Score V_1 = new Score(1L);"),
            "`const: {spelling}` must name the constant `V_1`\n{model}"
        );
    }
}

/// The P15 collision pass keys `x-java-enum-names` the same way the emitter
/// does, so two numeric members renamed onto one identifier are rejected at
/// load rather than emitted as duplicate constants.
#[test]
fn java_json_rejects_colliding_numeric_enum_name_overrides() {
    let temp_dir = unique_output_path("java-json-enum-names-collision");
    fs::create_dir_all(&temp_dir).unwrap();
    let input_path = temp_dir.join("collide.yaml");
    fs::write(
        &input_path,
        r##"$schema: https://json-schema.org/draft/2020-12/schema
type: object
properties:
  tier:
    type: integer
    enum: [1, 2]
    x-java-enum-names: { "1": SAME, "2": SAME }
"##,
    )
    .unwrap();

    let error = generate_to_file(&GenerateRequest {
        config: Default::default(),
        language: nexgen::language::Language::Java,
        input_paths: vec![input_path],
        support_package: None,
        descriptor_paths: Vec::new(),
        output_path: temp_dir.join("collide"),
        format: false,
        java_package_name: Some("collide".to_string()),
        ts_date_time_types: Default::default(),
    })
    .unwrap_err()
    .to_string();
    assert!(error.contains("both map to `SAME`"), "{error}");
    fs::remove_dir_all(temp_dir).unwrap();
}

#[test]
fn java_json_large_portable_counts_use_long_literals() {
    let temp_dir = unique_output_path("java-json-long-counts");
    fs::create_dir_all(&temp_dir).unwrap();
    let input_path = temp_dir.join("counts.yaml");
    fs::write(
        &input_path,
        r##"$schema: https://json-schema.org/draft/2020-12/schema
type: object
minProperties: 2147483648
maxProperties: 4294967295
properties:
  text:
    type: string
    minLength: 2147483648
    maxLength: 4294967295
  values:
    type: array
    items: { type: string }
    minItems: 2147483648
    maxItems: 4294967295
    contains: { type: string, minLength: 2147483648 }
    minContains: 2147483648
    maxContains: 4294967295
"##,
    )
    .unwrap();
    let output_path = temp_dir.join("counts");

    generate_to_file(&GenerateRequest {
        language: nexgen::language::Language::Java,
        input_paths: vec![input_path],
        support_package: None,
        descriptor_paths: Vec::new(),
        output_path: output_path.clone(),
        format: false,
        config: Default::default(),
        java_package_name: Some("counts".to_string()),
        ts_date_time_types: Default::default(),
    })
    .unwrap();

    let model = &read_java_files(&output_path)[&PathBuf::from("Counts.java")];
    for predicate in [
        "wireKeys.size() < 2147483648L",
        "wireKeys.size() > 4294967295L",
        "length < 2147483648L",
        "length > 4294967295L",
        ".size() < 2147483648L",
        ".size() > 4294967295L",
        "matchCount < 2147483648L",
        "matchCount > 4294967295L",
    ] {
        assert!(model.contains(predicate), "{predicate}\n{model}");
    }
    assert!(
        model.contains("must have at least 2147483648 items")
            && !model.contains("must have at least 2147483648L items"),
        "diagnostic counts must remain plain decimal text\n{model}"
    );
    fs::remove_dir_all(temp_dir).unwrap();
}

/// The pinned temporal grammar admits a fractional second of any width, and
/// every target keeps what its own type can hold rather than rejecting: Go, Java
/// and TypeScript at nanoseconds, Python at microseconds. That is P1's exception
/// (b) — loss only at the target type's genuine capacity limit — and it is what
/// `samples/python/tests/test_temporal.py` already pins. `java.time`'s ISO
/// parser throws past nine digits, so `TemporalSupport` truncates first
/// (`new:java-rejects-12-digit-fraction`).
#[test]
fn java_json_truncates_an_over_long_fractional_second() {
    let temp_dir = unique_output_path("java-json-fractional-second");
    let gradle_root = temp_dir.join("project");
    fs::create_dir_all(&gradle_root).unwrap();
    fs::copy(
        project_root().join("samples/java/build.gradle"),
        gradle_root.join("build.gradle"),
    )
    .unwrap();
    fs::copy(
        project_root().join("samples/java/settings.gradle"),
        gradle_root.join("settings.gradle"),
    )
    .unwrap();
    let input_path = temp_dir.join("fracsec.yaml");
    fs::write(
        &input_path,
        r##"$schema: https://json-schema.org/draft/2020-12/schema
title: Fractional Defaults
type: object
properties:
  ts: { type: string, format: date-time }
  tod: { type: string, format: time }
  wideDefault:
    type: string
    format: date-time
    default: "2021-06-15t12:30:45.123456789012+18:00"
  plusBoundary:
    type: string
    format: date-time
    default: "2021-06-15T12:30:45+18:00"
  minusBoundary:
    type: string
    format: date-time
    default: "2021-06-15T12:30:45-18:00"
"##,
    )
    .unwrap();
    let output_path = gradle_root.join("src/main/java/fracsec");

    generate_to_file(&GenerateRequest {
        config: Default::default(),
        language: nexgen::language::Language::Java,
        input_paths: vec![input_path],
        support_package: None,
        descriptor_paths: Vec::new(),
        output_path: output_path.clone(),
        format: false,
        java_package_name: Some("fracsec".to_string()),
        ts_date_time_types: Default::default(),
    })
    .unwrap();

    let rendered = read_java_files(&output_path);
    let support = &rendered[&PathBuf::from("TemporalSupport.java")];
    // The grammar still admits any width — the cap is not in the regex.
    assert!(
        support.contains("(\\\\.[0-9]+)?"),
        "the pinned fraction must stay unbounded\n{support}"
    );
    // The typed date-time truncates to OffsetDateTime's nanoseconds;
    // string-carried time keeps every digit and uses owned string arithmetic.
    for expected in [
        "private static String truncateFraction(String value) {",
        "public static OffsetDateTime parseDateTimeLiteral(String value) {",
        "return OffsetDateTime.parse(truncateFraction(value).toUpperCase());",
        "return parseDateTimeLiteral(value);",
        "return canonicalTime(value);",
    ] {
        assert!(support.contains(expected), "{expected}\n{support}");
    }
    assert!(
        !support.contains("LocalDate.parse(truncateFraction("),
        "a date carries no fraction\n{support}"
    );

    let model = &rendered[&PathBuf::from("Fracsec.java")];
    assert!(
        model.contains(
            "TemporalSupport.parseDateTimeLiteral(\"2021-06-15T12:30:45.123456789012+18:00\")"
        ),
        "{model}"
    );

    let test_package = gradle_root.join("src/test/java/fracsec");
    fs::create_dir_all(&test_package).unwrap();
    fs::write(
        test_package.join("FractionalDefaultsTest.java"),
        r#"package fracsec;

import static org.junit.jupiter.api.Assertions.assertEquals;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.util.Collections;
import org.junit.jupiter.api.Test;

final class FractionalDefaultsTest {
    @Test
    void dateTimeDefaultsUseTheMaterializedParser() {
        Fracsec value = new Fracsec(null, null, null, null, null, Collections.emptyMap());
        assertEquals(
            OffsetDateTime.parse("2021-06-15T12:30:45.123456789+18:00"),
            value.getWideDefaultOrDefault());
        assertEquals(ZoneOffset.ofHours(18), value.getPlusBoundaryOrDefault().getOffset());
        assertEquals(ZoneOffset.ofHours(-18), value.getMinusBoundaryOrDefault().getOffset());
    }
}
"#,
    )
    .unwrap();
    let status = Command::new(project_root().join("samples/java/gradlew"))
        .args([
            "test",
            "--no-daemon",
            "--tests",
            "fracsec.FractionalDefaultsTest",
        ])
        .current_dir(&gradle_root)
        .status()
        .expect("run Gradle fractional date-time default test");
    assert!(status.success());

    let invalid_input = temp_dir.join("invalid-default.yaml");
    fs::write(
        &invalid_input,
        r#"$schema: https://json-schema.org/draft/2020-12/schema
type: object
properties:
  invalid:
    type: string
    format: date-time
    default: "2021-06-15T12:30:45+18:01"
"#,
    )
    .unwrap();
    let error = generate_to_file(&GenerateRequest {
        config: Default::default(),
        language: nexgen::language::Language::Java,
        input_paths: vec![invalid_input],
        support_package: None,
        descriptor_paths: Vec::new(),
        output_path: temp_dir.join("invalid"),
        format: false,
        java_package_name: Some("invalid".to_string()),
        ts_date_time_types: Default::default(),
    })
    .unwrap_err()
    .to_string();
    assert!(
        error.contains("is not a valid date-time") && error.contains("+18:01"),
        "{error}"
    );
    fs::remove_dir_all(temp_dir).unwrap();
}
