use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicU64, Ordering};
use std::time::{SystemTime, UNIX_EPOCH};

use nexgen::{GenerateRequest, generate_to_file};

mod common;
use common::json_input_path;

static OUTPUT_COUNTER: AtomicU64 = AtomicU64::new(0);

/// A property whose union has one inline structured object branch (named
/// `<Union>Object`) and one scalar branch.
/// Unions in positions with no property of their own: an array element (inline
/// and `$ref`), a map member (inline), plus a nullable element for contrast.
const ELEMENT_UNION_SCHEMA: &str = r##"$schema: https://json-schema.org/draft/2020-12/schema
type: object
properties:
  segments:
    type: array
    items:
      oneOf:
        - { type: string }
        - { type: integer }
  choices:
    type: array
    items: { $ref: "#/$defs/Choice" }
  entries: { $ref: "#/$defs/Entries" }
  slots:
    type: array
    items:
      oneOf:
        - { type: string }
        - { type: "null" }
$defs:
  Choice:
    oneOf:
      - { type: string }
      - { type: boolean }
  Entries:
    type: object
    additionalProperties:
      oneOf:
        - { type: string }
        - { type: integer }
"##;

const INLINE_OBJECT_BRANCH_SCHEMA: &str = r#"$schema: https://json-schema.org/draft/2020-12/schema
type: object
properties:
  payload:
    oneOf:
      - type: object
        required: [text]
        properties:
          text: { type: string, minLength: 1 }
      - { type: string }
"#;

/// A union whose **non-object** branches each declare constraints of their own:
/// once the wire token selects a branch, the value is held to everything that
/// branch declares — including a closed value set — in both directions.
const BRANCH_CONSTRAINT_SCHEMA: &str = r#"$schema: https://json-schema.org/draft/2020-12/schema
type: object
properties:
  value:
    oneOf:
      - { type: string, minLength: 3, pattern: "^[a-z]+$" }
      - { type: integer, minimum: 1 }
  listOrName:
    oneOf:
      - { type: array, items: { type: number }, minItems: 1, uniqueItems: true }
      - { type: string, enum: [auto, manual] }
"#;

/// Plain `number` positions need a serialize-side finiteness check even when
/// they carry no explicit numeric bound. The positions cover a property, a
/// nested array, an unconstrained union branch, and a typed-map member array.
const FINITE_NUMBER_SCHEMA: &str = r##"$schema: https://json-schema.org/draft/2020-12/schema
type: object
required: [scalar, nested, metric, values]
properties:
  scalar: { type: number }
  nested:
    type: array
    items:
      type: array
      items: { type: number }
  metric:
    oneOf:
      - { type: number }
      - { type: string }
  values: { $ref: "#/$defs/Values" }
$defs:
  Values:
    type: object
    additionalProperties:
      type: array
      items: { type: number }
"##;

/// Support-file detection must walk collection and typed-map member schemas;
/// neither feature appears on a direct property here.
const NESTED_RUNTIME_SUPPORT_SCHEMA: &str = r##"$schema: https://json-schema.org/draft/2020-12/schema
type: object
properties:
  dates:
    type: array
    items:
      type: array
      items: { type: string, format: date }
  timestamps:
    type: array
    items: { type: string, format: date-time }
  blobs: { $ref: "#/$defs/Blobs" }
$defs:
  Blobs:
    type: object
    additionalProperties:
      type: string
      contentEncoding: base64
"##;

/// Java-specific focused coverage for the Wave 2 runtime contracts. This is a
/// temporary input generated by the test, so it exercises the real loader and
/// planner without adding another shared showcase schema.
const JAVA_CONFORMANCE_SCHEMA: &str = r##"$schema: https://json-schema.org/draft/2020-12/schema
title: Java conformance
description: Mixed declared and typed catch-all object.
deprecated: true
type: object
minProperties: 1
maxProperties: 4
properties:
  id:
    type: string
    deprecated: true
  dates:
    type: array
    items: { type: number }
    contains:
      type: integer
      minimum: 2
      maximum: 8
      exclusiveMinimum: 1
      exclusiveMaximum: 10
      multipleOf: 2
    minContains: 1
  payload:
    type: string
    contentEncoding: base64
    minLength: 4
    pattern: "^[A-Za-z0-9+/]+=*$"
  day:
    type: string
    format: date
    enum: ["2025-01-01"]
    default: "2025-01-01"
  maybeDay:
    oneOf:
      - { type: string, format: date }
      - { type: "null" }
    default: "2025-01-02"
  token:
    type: string
    contentEncoding: base64
    const: YQ==
  blobDefault:
    type: string
    contentEncoding: base64
    default: YQ==
  hosts:
    type: array
    items: { type: string }
    contains:
      type: string
      minLength: 3
      maxLength: 12
      pattern: "^api\\."
      format: hostname
      enum: [api.example]
  keyed: { $ref: "#/$defs/Keyed" }
  lists: { $ref: "#/$defs/Lists" }
  nativeExtras: { $ref: "#/$defs/NativeExtras" }
  edgeNumber:
    type: number
    exclusiveMaximum: -1
    multipleOf: 2e1
  zeroChoice:
    type: number
    enum: [0]
  boolChoice:
    type: boolean
    enum: [true]
additionalProperties:
  type: string
  minLength: 2
  pattern: "^[a-z]+$"
$defs:
  Keyed:
    type: object
    additionalProperties: { type: string }
    propertyNames:
      type: string
      minLength: 2
      maxLength: 12
      pattern: "^[a-z][a-z0-9]+$"
      enum: [id, dates, payload, extra]
      format: hostname
  Lists:
    type: object
    additionalProperties:
      type: array
      items:
        type: string
        minLength: 2
        pattern: "^[a-z]+$"
  NativeExtras:
    type: object
    minProperties: 1
    maxProperties: 2
    properties:
      known: { type: string }
    additionalProperties: { type: string, format: date }
"##;

const JAVA_DEPRECATED_SERVICE_SCHEMA: &str = r##"$schema: https://json-schema.org/draft/2020-12/schema
nexusrpc: "1.0.0"
services:
  Legacy:
    fqn: example.legacy.v1.Legacy
    deprecated: true
    description: Legacy API.
    x-java-name: LegacyJava
    operations:
      ping:
        deprecated: true
        description: Ping the service.
        x-java-name: pingJava
      submit:
        input: { $ref: "#/$defs/Input" }
      fetch:
        output: { $ref: "#/$defs/Input" }
$defs:
  Input:
    type: object
    additionalProperties: false
"##;

const JAVA_EMPTY_SERVICE_DESCRIPTION_SCHEMA: &str = r##"$schema: https://json-schema.org/draft/2020-12/schema
nexusrpc: "1.0.0"
services:
  Empty:
    fqn: example.empty.v1.Empty
    description: ""
    operations:
      ping: {}
"##;

fn project_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

/// The checked-in Java example root for a given generation mode and example.
/// Definitions are the beginner-facing samples; native-api is snapshot-only in
/// the advanced project.
fn java_example_output_path(root: &Path, mode: &str, example_id: &str) -> PathBuf {
    match mode {
        "definitions" => root
            .join("samples/java/src/main/java/json_schema/definitions")
            .join(example_id),
        _ => root
            .join("advanced/samples/java/src/main/java/json_schema/api")
            .join(example_id),
    }
}

fn unique_output_path(label: &str) -> PathBuf {
    let unique = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap()
        .as_nanos();
    let counter = OUTPUT_COUNTER.fetch_add(1, Ordering::Relaxed);
    std::env::temp_dir().join(format!("nexgen-{label}-{unique}-{counter}"))
}

fn read_java_files(dir: &Path) -> BTreeMap<PathBuf, String> {
    fn visit(root: &Path, dir: &Path, files: &mut BTreeMap<PathBuf, String>) {
        let mut entries = fs::read_dir(dir)
            .unwrap()
            .map(|entry| entry.unwrap().path())
            .collect::<Vec<_>>();
        entries.sort();
        for path in entries {
            if path.is_dir() {
                visit(root, &path, files);
            } else if path.extension().and_then(|extension| extension.to_str()) == Some("java") {
                files.insert(
                    path.strip_prefix(root).unwrap().to_path_buf(),
                    fs::read_to_string(&path).unwrap(),
                );
            }
        }
    }

    let mut files = BTreeMap::new();
    visit(dir, dir, &mut files);
    files
}

/// Regenerates one example into a temp Gradle-shaped tree so the derived Java
/// package matches the checked-in output, then compares the emitted files.
fn assert_regeneration_matches(mode: &str, generate_native_api: bool) {
    let root = project_root();
    for example_id in ["chat", "kb", "showcase", "temporal"] {
        let temp_dir = unique_output_path(&format!("java-json-{mode}-{example_id}"));
        // The output directory's base name must equal the package's last
        // segment; the checked-in package is `json_schema.<mode>.<example>`.
        let output_path = temp_dir.join(example_id);

        generate_to_file(&GenerateRequest {
            language: nexgen::language::Language::Java,
            input_paths: vec![json_input_path(&root, example_id)],
            support_paths: Vec::new(),
            descriptor_paths: Vec::new(),
            output_path: output_path.clone(),
            format: false,
            generate_native_api,
            java_package_name: Some(format!("json_schema.{mode}.{example_id}")),
            ts_date_time_types: Default::default(),
        })
        .unwrap();

        let rendered = read_java_files(&output_path);
        let expected = read_java_files(&java_example_output_path(&root, mode, example_id));
        assert_eq!(
            rendered, expected,
            "snapshot mismatch for {mode}/{example_id}"
        );
        if example_id == "showcase" {
            let all = rendered.values().cloned().collect::<Vec<_>>().join("\n");
            // Scalar defaults surface on read via the generated getter default.
            assert!(all.contains("public String getGreetingOrDefault() {"));
            assert!(all.contains("return greeting != null ? greeting : \"hello\";"));
            assert!(all.contains("public boolean getDebugOrDefault() {"));
            // `deprecated` → @Deprecated + @deprecated javadoc; `title` → summary.
            assert!(all.contains("@Deprecated"));
            assert!(all.contains("@deprecated This field is deprecated."));
            assert!(all.contains("Retry budget"));
            // `x-java-name` override (Stage 4): the emitted field/getter use the
            // override while the wire name (`@JsonProperty`) stays `legacyId`.
            assert!(all.contains("private final @Nullable String legacyIdJava;"));
            assert!(all.contains("public @Nullable String getLegacyIdJava() {"));
            assert!(all.contains("gen.writeStringField(\"legacyId\", value.legacyIdJava);"));
            // An inline free-form object branch: the union declares a nested
            // wrapper holding the members verbatim (a named free-form model gets
            // the same catch-all on its POJO).
            assert!(all.contains("public static final class PayloadObject implements Payload {"));
            assert!(all.contains("private final Map<String, JsonNode> value;"));
            assert!(all.contains("public final class Extras {"));
            // A tagged union whose branches are written inline: each branch names
            // itself with `x-java-name` and implements the union interface.
            assert!(all.contains("public final class TextNote implements Note {"));
            assert!(all.contains("public final class LinkNote implements Note {"));
            // A structured inline object branch of a *property* union: the branch
            // is an ordinary POJO implementing the interface nested in the
            // declaring class, and the union parses through `fromNode` exactly as
            // a named union def does.
            assert!(
                all.contains(
                    "public final class ShowcaseDetailObject implements Showcase.Detail {"
                )
            );
            assert!(
                all.contains("return context.readTreeAsValue(node, ShowcaseDetailObject.class);")
            );
            assert!(
                all.contains("detail = Detail.fromNode(field, \"detail\", violations, context);")
            );
        }
        fs::remove_dir_all(temp_dir).unwrap();
    }
}

#[test]
fn java_json_example_generation_matches_checked_in_output() {
    assert_regeneration_matches("definitions", false);
}

#[test]
fn java_json_api_example_generation_matches_checked_in_output() {
    assert_regeneration_matches("api", true);
}

/// A structured inline object branch of a property-level union is named
/// `<Union>Object` by the load and emitted as an ordinary POJO — implementing the
/// union interface nested in the declaring class, so the interface's `fromNode`
/// dispatcher (the same one a named union def carries) delegates to the branch's
/// own deserializer. See `specs/json-schema/features/oneOf.md`.
#[test]
fn java_json_names_inline_object_union_branch() {
    let temp_dir = unique_output_path("java-json-inline-branch");
    fs::create_dir_all(&temp_dir).unwrap();
    let input_path = temp_dir.join("detail.yaml");
    fs::write(&input_path, INLINE_OBJECT_BRANCH_SCHEMA).unwrap();
    let output_path = temp_dir.join("detail");

    generate_to_file(&GenerateRequest {
        language: nexgen::language::Language::Java,
        input_paths: vec![input_path],
        support_paths: Vec::new(),
        descriptor_paths: Vec::new(),
        output_path: output_path.clone(),
        format: false,
        generate_native_api: false,
        java_package_name: Some("detail".to_string()),
        ts_date_time_types: Default::default(),
    })
    .unwrap();

    let rendered = read_java_files(&output_path);
    let branch = &rendered[&PathBuf::from("DetailPayloadObject.java")];
    assert!(
        branch.contains("public final class DetailPayloadObject implements Detail.Payload {"),
        "{branch}"
    );
    // The branch is an ordinary model: its own constraints and catch-all.
    assert!(branch.contains("must have length >= 1"), "{branch}");
    assert!(
        branch.contains("private final Map<String, JsonNode> additionalProperties;"),
        "{branch}"
    );

    let declaring = &rendered[&PathBuf::from("Detail.java")];
    for expected in [
        "public interface Payload {",
        "static @Nullable Payload fromNode(JsonNode node, String path, List<Violation> violations, DeserializationContext context) {",
        "return context.readTreeAsValue(node, DetailPayloadObject.class);",
        "public static final class PayloadString implements Payload {",
        "payload = Payload.fromNode(field, \"payload\", violations, context);",
    ] {
        assert!(declaring.contains(expected), "{expected}\n{declaring}");
    }
    fs::remove_dir_all(temp_dir).unwrap();
}

/// Every constraint a **non-object** branch declares becomes a `validate` on its
/// wrapper class: the `fromNode` dispatcher runs it on the way in, and the
/// enclosing POJO's `Serializer` runs it again through the interface's static
/// `validate` before emit (P12), so a branch violation aggregates with its
/// siblings. See `specs/json-schema/features/oneOf.md` ("Validator mapping").
#[test]
fn java_json_validates_non_object_union_branch_constraints() {
    let temp_dir = unique_output_path("java-json-branch-constraints");
    fs::create_dir_all(&temp_dir).unwrap();
    let input_path = temp_dir.join("bc.yaml");
    fs::write(&input_path, BRANCH_CONSTRAINT_SCHEMA).unwrap();
    let output_path = temp_dir.join("bc");

    generate_to_file(&GenerateRequest {
        language: nexgen::language::Language::Java,
        input_paths: vec![input_path],
        support_paths: Vec::new(),
        descriptor_paths: Vec::new(),
        output_path: output_path.clone(),
        format: false,
        generate_native_api: false,
        java_package_name: Some("bc".to_string()),
        ts_date_time_types: Default::default(),
    })
    .unwrap();
    let rendered = read_java_files(&output_path);
    let declaring = &rendered[&PathBuf::from("Bc.java")];

    // The wrapper carries the branch's checks, and its compiled `pattern` — the
    // wrapper's single field is `value`, so the static follows that name.
    assert!(declaring.contains(
        "private static final java.util.regex.Pattern VALUE_PATTERN = java.util.regex.Pattern.compile(\"^[a-z]+\\\\z\");"
    ));
    assert!(declaring.contains("void validate(String path, List<Violation> violations) {"));
    assert!(declaring.contains("must have length >= 3, got "));
    assert!(declaring.contains("if (!VALUE_PATTERN.matcher(value).find()) {"));
    assert!(declaring.contains("must be >= 1, got "));
    assert!(declaring.contains("must have at least 1 items, got "));
    assert!(declaring.contains("duplicate items: element at index "));
    assert!(declaring.contains("must be one of [\\\"auto\\\", \\\"manual\\\"], got "));
    // Parse: the dispatcher validates the wrapper it just built.
    assert!(declaring.contains("ValueString wrapped = new ValueString(node.textValue());"));
    assert!(declaring.contains("wrapped.validate(path, violations);"));
    // Serialize: the interface's runtime-class dispatcher, called by the POJO's
    // Serializer before any member is written.
    assert!(
        declaring.contains(
            "static void validate(Value value, String path, List<Violation> violations) {"
        )
    );
    assert!(declaring.contains("Value.validate(value.value, \"value\", violations);"));
    fs::remove_dir_all(temp_dir).unwrap();
}

#[test]
fn java_json_rejects_non_finite_numbers_in_every_serialize_position() {
    let temp_dir = unique_output_path("java-json-finite-numbers");
    fs::create_dir_all(&temp_dir).unwrap();
    let input_path = temp_dir.join("finite.yaml");
    fs::write(&input_path, FINITE_NUMBER_SCHEMA).unwrap();
    let output_path = temp_dir.join("finite");

    generate_to_file(&GenerateRequest {
        language: nexgen::language::Language::Java,
        input_paths: vec![input_path],
        support_paths: Vec::new(),
        descriptor_paths: Vec::new(),
        output_path: output_path.clone(),
        format: false,
        generate_native_api: false,
        java_package_name: Some("finite".to_string()),
        ts_date_time_types: Default::default(),
    })
    .unwrap();

    let rendered = read_java_files(&output_path);
    let root = &rendered[&PathBuf::from("Finite.java")];
    for expected in [
        "if (!Double.isFinite(value.scalar)) {",
        "new Violation(\"scalar\", \"must be a finite number, got \" + value.scalar)",
        "for (int finiteIndex0 = 0; finiteIndex0 < value.nested.size(); finiteIndex0++) {",
        "for (int finiteIndex1 = 0; finiteIndex1 < finiteValue0.size(); finiteIndex1++) {",
        "new Violation(\"nested\" + \"[\" + finiteIndex0 + \"]\" + \"[\" + finiteIndex1 + \"]\", \"must be a finite number, got \" + finiteValue1)",
        "if (!Double.isFinite(value)) {",
        "Metric.validate(value.metric, \"metric\", violations);",
    ] {
        assert!(root.contains(expected), "{expected}\n{root}");
    }

    for expected in [
        "SpecNumbers.specDouble(field, \"scalar\", violations)",
        "SpecNumbers.specDouble(node, path, violations)",
    ] {
        assert!(
            rendered.values().any(|source| source.contains(expected)),
            "{expected}"
        );
    }
    assert!(
        root.matches("SpecNumbers.specDouble(").count() >= 2,
        "{root}"
    );

    let map = &rendered[&PathBuf::from("Values.java")];
    for expected in [
        "for (Map.Entry<String, List<Double>> entry : value.additionalProperties.entrySet()) {",
        "for (int finiteIndex0 = 0; finiteIndex0 < entry.getValue().size(); finiteIndex0++) {",
        "new Violation(entry.getKey() + \"[\" + finiteIndex0 + \"]\", \"must be a finite number, got \" + finiteValue0)",
    ] {
        assert!(map.contains(expected), "{expected}\n{map}");
    }
    assert!(map.contains("SpecNumbers.specDouble("), "{map}");

    let numbers = &rendered[&PathBuf::from("SpecNumbers.java")];
    assert!(numbers.contains("public static @Nullable Double specDouble("));
    assert!(numbers.contains("!Double.isFinite(value)"));
    fs::remove_dir_all(temp_dir).unwrap();
}

#[test]
fn java_json_emits_runtime_support_for_nested_materialized_values() {
    let temp_dir = unique_output_path("java-json-nested-runtime-support");
    fs::create_dir_all(&temp_dir).unwrap();
    let input_path = temp_dir.join("nested.yaml");
    fs::write(&input_path, NESTED_RUNTIME_SUPPORT_SCHEMA).unwrap();
    let output_path = temp_dir.join("nested");

    generate_to_file(&GenerateRequest {
        language: nexgen::language::Language::Java,
        input_paths: vec![input_path],
        support_paths: Vec::new(),
        descriptor_paths: Vec::new(),
        output_path: output_path.clone(),
        format: false,
        generate_native_api: false,
        java_package_name: Some("nested".to_string()),
        ts_date_time_types: Default::default(),
    })
    .unwrap();

    let rendered = read_java_files(&output_path);
    assert!(rendered.contains_key(&PathBuf::from("TemporalSupport.java")));
    assert!(rendered.contains_key(&PathBuf::from("Base64Support.java")));
    let temporal = &rendered[&PathBuf::from("TemporalSupport.java")];
    assert!(temporal.contains("if (year < 1) {"), "{temporal}");
    let root = &rendered[&PathBuf::from("Nested.java")];
    for expected in [
        "for (int calendarIndex0 = 0; calendarIndex0 < value.dates.size(); calendarIndex0++) {",
        "for (int calendarIndex1 = 0; calendarIndex1 < calendarValue0.size(); calendarIndex1++) {",
        "if (calendarValue1.getYear() < 1) {",
        "new Violation(\"dates\" + \"[\" + calendarIndex0 + \"]\" + \"[\" + calendarIndex1 + \"]\", \"must be a valid date, got \" + calendarValue1 + \": year must be >= 0001\")",
        "if (calendarValue0.getYear() < 1) {",
        "new Violation(\"timestamps\" + \"[\" + calendarIndex0 + \"]\", \"must be a valid date-time, got \" + calendarValue0 + \": year must be >= 0001\")",
    ] {
        assert!(root.contains(expected), "{expected}\n{root}");
    }
    fs::remove_dir_all(temp_dir).unwrap();
}

#[test]
fn java_json_emits_wave2_object_and_matcher_contracts() {
    let temp_dir = unique_output_path("java-json-wave2-contracts");
    fs::create_dir_all(&temp_dir).unwrap();
    let input_path = temp_dir.join("java-conformance.yaml");
    fs::write(&input_path, JAVA_CONFORMANCE_SCHEMA).unwrap();
    let output_path = temp_dir.join("java_conformance");

    generate_to_file(&GenerateRequest {
        language: nexgen::language::Language::Java,
        input_paths: vec![input_path],
        support_paths: Vec::new(),
        descriptor_paths: Vec::new(),
        output_path: output_path.clone(),
        format: false,
        generate_native_api: false,
        java_package_name: Some("java_conformance".to_string()),
        ts_date_time_types: Default::default(),
    })
    .unwrap();

    let rendered = read_java_files(&output_path);
    let model = &rendered[&PathBuf::from("JavaConformance.java")];
    for expected in [
        "@Deprecated\n@JsonSerialize(using = JavaConformance.Serializer.class)",
        "@Deprecated\n    public @Nullable String getId()",
        "Map<String, String> additionalProperties",
        "additionalProperties.put(key, value)",
        "for (Map.Entry<String, String> entry : value.additionalProperties.entrySet())",
        "declared property key collision",
        "wireKeys.add(\"id\")",
        "SpecNumbers.isSpecLong(rawElement)",
        "rawElement.doubleValue() % 2.0 == 0",
        "rawElement.doubleValue() <= 8.0",
        "rawElement.doubleValue() > 1.0",
        "rawElement.doubleValue() < 10.0",
        "Double.isFinite(element) && element == Math.rint(element)",
        "String payloadWire = Base64Support.formatBase64(value.payload)",
        "PAYLOAD_PATTERN.matcher(payloadWire).find()",
        "public LocalDate getDayOrDefault()",
        "LocalDate.parse(\"2025-01-01\")",
        "public LocalDate getMaybeDayOrDefault()",
        "LocalDate.parse(\"2025-01-02\")",
        "public byte[] getBlobDefaultOrDefault()",
        "java.util.Base64.getDecoder().decode(\"YQ==\")",
        "must equal \\\"2025-01-01\\\"",
        "Base64Support.formatBase64(value.token)",
        "\"api.example\".equals(element)",
        "element.codePointCount(0, element.length()) >= 3",
        "element.codePointCount(0, element.length()) <= 12",
        "value.edgeNumber >= -1.0",
        "value.edgeNumber % 20.0 != 0",
        "must equal 0",
        "must equal true",
        "java.util.regex.Pattern.compile(\"^api\\\\.\")",
    ] {
        assert!(model.contains(expected), "{expected}\n{model}");
    }
    let keyed = &rendered[&PathBuf::from("Keyed.java")];
    for expected in [
        "PROPERTY_NAME_PATTERN.matcher(pnKey).find()",
        "PROPERTY_NAME_FORMAT.matcher(pnKey).find()",
        "must be one of [\\\"id\\\", \\\"dates\\\", \\\"payload\\\", \\\"extra\\\"]",
    ] {
        assert!(keyed.contains(expected), "{expected}\n{keyed}");
    }
    let lists = &rendered[&PathBuf::from("Lists.java")];
    for expected in [
        "String parsed = item.textValue()",
        "must have length >= 2",
        "java.util.regex.Pattern.compile(\"^[a-z]+\\\\z\")",
        "for (int validationIndex0 = 0; validationIndex0 < entry.getValue().size(); validationIndex0++)",
        "validationValue0.codePointCount(0, validationValue0.length())",
    ] {
        assert!(lists.contains(expected), "{expected}\n{lists}");
    }
    let native_extras = &rendered[&PathBuf::from("NativeExtras.java")];
    for expected in [
        "Map<String, LocalDate> additionalProperties",
        "TemporalSupport.parseDate(element.textValue(), key, violations)",
        "TemporalSupport.formatDate(entry.getValue())",
        "declared property key collision",
        "wireKeys.size() < 1",
        "wireKeys.size() > 2",
    ] {
        assert!(
            native_extras.contains(expected),
            "{expected}\n{native_extras}"
        );
    }
    fs::remove_dir_all(temp_dir).unwrap();
}

#[test]
fn java_json_emits_deprecated_services_and_operations() {
    let temp_dir = unique_output_path("java-json-deprecated-service");
    fs::create_dir_all(&temp_dir).unwrap();
    let input_path = temp_dir.join("legacy.nexusrpc.yaml");
    fs::write(&input_path, JAVA_DEPRECATED_SERVICE_SCHEMA).unwrap();
    let output_path = temp_dir.join("legacy");

    generate_to_file(&GenerateRequest {
        language: nexgen::language::Language::Java,
        input_paths: vec![input_path],
        support_paths: Vec::new(),
        descriptor_paths: Vec::new(),
        output_path: output_path.clone(),
        format: false,
        generate_native_api: true,
        java_package_name: Some("legacy".to_string()),
        ts_date_time_types: Default::default(),
    })
    .unwrap();

    let rendered = read_java_files(&output_path);
    let service = &rendered[&PathBuf::from("LegacyJava.java")];
    assert!(
        service.contains("@deprecated This service is deprecated."),
        "{service}"
    );
    assert!(
        service.contains("@Deprecated\npublic interface LegacyJava"),
        "{service}"
    );
    assert!(
        service.contains("@deprecated This operation is deprecated."),
        "{service}"
    );
    assert!(
        service.contains("@Deprecated\n    void pingJava();"),
        "{service}"
    );
    assert!(service.contains("void submit(Input input);"), "{service}");
    assert!(service.contains("Input fetch();"), "{service}");
    fs::remove_dir_all(temp_dir).unwrap();
}

#[test]
fn java_json_rejects_empty_service_descriptions() {
    let temp_dir = unique_output_path("java-json-empty-service-description");
    fs::create_dir_all(&temp_dir).unwrap();
    let input_path = temp_dir.join("empty.nexusrpc.yaml");
    fs::write(&input_path, JAVA_EMPTY_SERVICE_DESCRIPTION_SCHEMA).unwrap();
    let error = generate_to_file(&GenerateRequest {
        language: nexgen::language::Language::Java,
        input_paths: vec![input_path],
        support_paths: Vec::new(),
        descriptor_paths: Vec::new(),
        output_path: temp_dir.join("empty"),
        format: false,
        generate_native_api: true,
        java_package_name: Some("empty".to_string()),
        ts_date_time_types: Default::default(),
    })
    .unwrap_err();
    assert!(
        error
            .to_string()
            .contains("`description` must not be empty or whitespace-only"),
        "{error}"
    );
    fs::remove_dir_all(temp_dir).unwrap();
}

/// A union in an element position decodes through the interface's own
/// `fromNode` dispatcher — Jackson cannot instantiate a sealed interface — with
/// the element index / member key in the violation path. A nullable element
/// takes the TYPE_USE annotation instead (the list stays non-null).
/// See `specs/json-schema/features/oneOf.md` ("Unions in element positions").
#[test]
fn java_json_decodes_element_position_unions() {
    let temp_dir = unique_output_path("java-json-element-union");
    fs::create_dir_all(&temp_dir).unwrap();
    let input_path = temp_dir.join("bag.yaml");
    fs::write(&input_path, ELEMENT_UNION_SCHEMA).unwrap();
    let output_path = temp_dir.join("bag");

    generate_to_file(&GenerateRequest {
        language: nexgen::language::Language::Java,
        input_paths: vec![input_path],
        support_paths: Vec::new(),
        descriptor_paths: Vec::new(),
        output_path: output_path.clone(),
        format: false,
        generate_native_api: false,
        java_package_name: Some("bag".to_string()),
        ts_date_time_types: Default::default(),
    })
    .unwrap();

    let rendered = read_java_files(&output_path);
    // The inline element union is named after its position and emitted as an
    // ordinary named union def.
    assert!(rendered.contains_key(&PathBuf::from("BagSegmentsItem.java")));
    assert!(rendered.contains_key(&PathBuf::from("EntriesValue.java")));

    let declaring = &rendered[&PathBuf::from("Bag.java")];
    for expected in [
        "private final @Nullable List<BagSegmentsItem> segments;",
        "String elementPath = \"segments\" + \"[\" + index + \"]\";",
        "BagSegmentsItem parsedItems = BagSegmentsItem.fromNode(element, elementPath, violations, context);",
        "Choice parsedItems = Choice.fromNode(element, elementPath, violations, context);",
        "private final @Nullable List<@Nullable String> slots;",
        "items.add(null);",
    ] {
        assert!(declaring.contains(expected), "{expected}\n{declaring}");
    }

    let map = &rendered[&PathBuf::from("Entries.java")];
    for expected in [
        "Map<String, EntriesValue> additionalProperties",
        "EntriesValue parsedAdditionalProperties = EntriesValue.fromNode(element, key, violations, context);",
    ] {
        assert!(map.contains(expected), "{expected}\n{map}");
    }
    fs::remove_dir_all(temp_dir).unwrap();
}

/// The entry file of a two-file closure. `get`'s output is the model the *other*
/// file declares, and `FindOutput.page` `$ref`s it from a property, so both
/// cross-module reference shapes are covered.
const CROSS_MODULE_ENTRY_SCHEMA: &str = r##"$schema: https://json-schema.org/draft/2020-12/schema
nexusrpc: "1.0.0"
services:
  Pages:
    fqn: example.pages.v1.Pages
    operations:
      get:
        input: { $ref: "#/$defs/GetInput" }
        output: { $ref: "content/page.json" }
      find:
        input: { $ref: "#/$defs/GetInput" }
        output: { $ref: "#/$defs/FindOutput" }
$defs:
  GetInput:
    type: object
    additionalProperties: false
    properties:
      id: { type: string }
  FindOutput:
    type: object
    additionalProperties: false
    properties:
      page: { $ref: "content/page.json" }
"##;

/// The referenced file. Its model carries the name override the *consuming*
/// module has to resolve through.
const CROSS_MODULE_PAGE_SCHEMA: &str = r##"$schema: https://json-schema.org/draft/2020-12/schema
type: object
additionalProperties: false
x-java-name: RenamedPage
properties:
  title: { type: string }
"##;

/// Writes the two-file cross-module closure into `dir` and returns the input
/// directory to generate from.
fn write_cross_module_closure(dir: &Path) -> PathBuf {
    let input_dir = dir.join("input");
    fs::create_dir_all(input_dir.join("content")).unwrap();
    fs::write(
        input_dir.join("kb.nexusrpc.yaml"),
        CROSS_MODULE_ENTRY_SCHEMA,
    )
    .unwrap();
    fs::write(
        input_dir.join("content/page.json"),
        CROSS_MODULE_PAGE_SCHEMA,
    )
    .unwrap();
    input_dir
}

/// An `x-java-name` override on a model in *another* input file moves every
/// reference the consuming package emits: the operation's return type, the
/// cross-package import, and the field/getter of a cross-module `$ref` property.
/// The override is declared in the referenced file, so only the tree-wide name
/// manifest can resolve it (P14/P15).
#[test]
fn java_json_cross_module_java_name_override_moves_every_reference() {
    let temp_dir = unique_output_path("java-json-cross-module-override");
    let input_dir = write_cross_module_closure(&temp_dir);
    // The output directory's base name must equal the package's last segment.
    let output_path = temp_dir.join("pages");

    generate_to_file(&GenerateRequest {
        language: nexgen::language::Language::Java,
        input_paths: vec![input_dir],
        support_paths: Vec::new(),
        descriptor_paths: Vec::new(),
        output_path: output_path.clone(),
        format: false,
        generate_native_api: false,
        java_package_name: Some("example.pages".to_string()),
        ts_date_time_types: Default::default(),
    })
    .unwrap();

    let rendered = read_java_files(&output_path);
    let declaring = &rendered[&PathBuf::from("content/page/RenamedPage.java")];
    assert!(
        declaring.contains("public final class RenamedPage {"),
        "{declaring}"
    );

    let service = &rendered[&PathBuf::from("kb/Pages.java")];
    for expected in [
        "import example.pages.content.page.RenamedPage;",
        "RenamedPage get(GetInput input);",
    ] {
        assert!(service.contains(expected), "{expected}\n{service}");
    }

    let consuming = &rendered[&PathBuf::from("kb/FindOutput.java")];
    for expected in [
        "import example.pages.content.page.RenamedPage;",
        "private final @Nullable RenamedPage page;",
        "public @Nullable RenamedPage getPage() {",
        "context.readTreeAsValue(field, RenamedPage.class);",
    ] {
        assert!(consuming.contains(expected), "{expected}\n{consuming}");
    }
    // Nothing names the pre-override identifier.
    for stale in [
        ".page.Page;",
        "@Nullable Page ",
        "(field, Page.class)",
        " Page get(",
    ] {
        assert!(!service.contains(stale), "{stale}\n{service}");
        assert!(!consuming.contains(stale), "{stale}\n{consuming}");
    }
    fs::remove_dir_all(temp_dir).unwrap();
}

/// Java gives each module its own package and one file per class, so re-emitting
/// a `$ref`d type into the referencing service's module wrote `Page.java` twice
/// and the build failed outright with a generated-file conflict. It happened
/// whenever the service module declared no types of its own.
#[test]
fn java_json_service_module_without_own_types_does_not_reemit_refs() {
    let temp_dir = unique_output_path("java-json-service-only-module");
    let input_dir = temp_dir.join("input");
    fs::create_dir_all(input_dir.join("a")).unwrap();
    fs::write(
        input_dir.join("a/page.json"),
        r#"{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","additionalProperties":false,"properties":{"title":{"type":"string"}},"required":["title"]}"#,
    )
    .unwrap();
    fs::write(
        input_dir.join("svc.nexusrpc.yaml"),
        r#"$schema: https://json-schema.org/draft/2020-12/schema
nexusrpc: "1.0.0"
services:
  Svc:
    fqn: example.v1.Svc
    operations:
      one:
        input: { $ref: "a/page.json" }
"#,
    )
    .unwrap();

    let output_path = temp_dir.join("pkg");
    generate_to_file(&GenerateRequest {
        language: nexgen::language::Language::Java,
        input_paths: vec![input_dir],
        support_paths: Vec::new(),
        descriptor_paths: Vec::new(),
        output_path: output_path.clone(),
        format: false,
        generate_native_api: false,
        java_package_name: Some("com.example.pkg".to_string()),
        ts_date_time_types: Default::default(),
    })
    .unwrap();

    // `Page` is emitted once, by the module that declares it.
    let paths = read_java_files(&output_path)
        .into_keys()
        .filter(|path| path.file_name().is_some_and(|name| name == "Page.java"))
        .collect::<Vec<_>>();
    assert_eq!(paths, vec![PathBuf::from("a/page/Page.java")]);
    // The service's own package holds only the service.
    let service = fs::read_to_string(output_path.join("svc/Svc.java")).unwrap();
    assert!(
        service.contains("import com.example.pkg.a.page.Page;"),
        "{service}"
    );
    fs::remove_dir_all(temp_dir).unwrap();
}
