// Code generated by nexgen latest. DO NOT EDIT.

package multioperationservice

import (
	"go.temporal.io/sdk/internal"
	"go.temporal.io/sdk/workflow"
)

// --- Datatypes ---

type request struct {
	ID string
}

// --- Operations (internal) ---

func firstOperation(ctx workflow.Context, request request) workflow.Future {
	c := internal.NewSystemNexusClient("InterceptorService")
	fut := c.ExecuteOperation(ctx, "FirstOperation", request, workflow.NexusOperationOptions{})
	return fut
}

func secondOperation(ctx workflow.Context, request request) workflow.Future {
	c := internal.NewSystemNexusClient("InterceptorService")
	fut := c.ExecuteOperation(ctx, "SecondOperation", request, workflow.NexusOperationOptions{})
	return fut
}

// --- Operations (public API) ---

type Response struct {
	// Value - Required.
	Value string
}

type FirstOperationOptions struct {
	// ID - Required.
	ID string
}

func FirstOperation(ctx workflow.Context, opts FirstOperationOptions) workflow.Future {
	return firstOperation(ctx, request{
		ID: opts.ID,
	})
}

type SecondOperationOptions struct {
	// ID - Required.
	ID string
}

func SecondOperation(ctx workflow.Context, opts SecondOperationOptions) workflow.Future {
	return secondOperation(ctx, request{
		ID: opts.ID,
	})
}
