// <auto-generated />
// Generated by nexgen latest. DO NOT EDIT!
#nullable enable

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;
using Google.Protobuf.WellKnownTypes;
using Temporalio.Workflows;
using Nexgen.Support;

namespace Nexgen.TypeRoundtripService
{

    [GeneratedCode("nexgen", null)]
    public class ActivityOptionsOperationOptions
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ActivityOptionsOperationOptions"/> class.
        /// </summary>
        public ActivityOptionsOperationOptions(Temporalio.Common.RetryPolicy retryPolicy)
        {
            RetryPolicy = retryPolicy;
        }

        public string? TaskQueue { get; set; }
        public Temporalio.Common.RetryPolicy RetryPolicy { get; set; }
        public System.TimeSpan? ScheduleToCloseTimeout { get; set; }
        public Temporalio.Common.Priority? Priority { get; set; }
    }

    [GeneratedCode("nexgen", null)]
    public class FailureOperationOptions
    {
        public System.Exception? Failure { get; set; }
    }

    /// <summary>
    /// Provides generated workflow operation helpers.
    /// </summary>
    [GeneratedCode("nexgen", null)]
    public static class Operations
    {
        [GeneratedCode("nexgen", null)]
        private const string TypeRoundtripServiceEndpoint = "temporal-system";

        [GeneratedCode("nexgen", null)]
        private static async Task<ActivityOptions> ActivityOptionsOperationAsync(ActivityOptions request)
        {
            var client = Workflow.CreateNexusWorkflowClient<ITypeRoundtripService>(TypeRoundtripServiceEndpoint);
            var result = await client.ExecuteNexusOperationAsync<ActivityOptions>(svc => svc.ActivityOptionsOperation(request)).ConfigureAwait(true);
            return result;
        }

        /// <param name="options">Options for the operation.</param>
        [GeneratedCode("nexgen", null)]
        public static Task<ActivityOptions> ActivityOptionsOperationAsync(ActivityOptionsOperationOptions options)
        {
            var request = new ActivityOptions(options.RetryPolicy)
            {
                TaskQueue = options.TaskQueue,
                ScheduleToCloseTimeout = options.ScheduleToCloseTimeout,
                Priority = options.Priority,
            };
            return ActivityOptionsOperationAsync(request);
        }

        [GeneratedCode("nexgen", null)]
        private static async Task<FailureContainer> FailureOperationAsync(FailureContainer request)
        {
            var client = Workflow.CreateNexusWorkflowClient<ITypeRoundtripService>(TypeRoundtripServiceEndpoint);
            var result = await client.ExecuteNexusOperationAsync<FailureContainer>(svc => svc.FailureOperation(request)).ConfigureAwait(true);
            return result;
        }

        /// <param name="options">Options for the operation.</param>
        [GeneratedCode("nexgen", null)]
        public static Task<FailureContainer> FailureOperationAsync(FailureOperationOptions? options = null)
        {
            var request = new FailureContainer()
            {
                Failure = options?.Failure,
            };
            return FailureOperationAsync(request);
        }

    }

}
