// <auto-generated />
// Generated by nexgen latest. DO NOT EDIT!
#nullable enable

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Threading.Tasks;
using NexusRpc;
using Temporalio.Converters;
using Nexgen.Support;

namespace Nexgen.TypeRoundtripService
{

    [GeneratedCode("nexgen", null)]
    [NexusService("TypeRoundtripService")]
    internal interface ITypeRoundtripService
    {
        [GeneratedCode("nexgen", null)]
        [NexusOperation("ActivityOptionsOperation")]
        ActivityOptions ActivityOptionsOperation(ActivityOptions request);

        [GeneratedCode("nexgen", null)]
        [NexusOperation("FailureOperation")]
        FailureContainer FailureOperation(FailureContainer request);

    }

    internal interface INexgenOperationInfo
    {
        OperationDefinition Operation { get; }

        Func<object, ISerializationContext>? SerializationContext { get; }
    }

    internal sealed class NexgenOperationInfo<TRequest, TResponse> : INexgenOperationInfo
    {
        internal NexgenOperationInfo(
            OperationDefinition operation,
            Func<TRequest, ISerializationContext>? serializationContext = null)
        {
            Operation = operation;
            SerializationContext = serializationContext;
        }

        internal OperationDefinition Operation { get; }

        OperationDefinition INexgenOperationInfo.Operation => Operation;

        internal Func<TRequest, ISerializationContext>? SerializationContext { get; }

        Func<object, ISerializationContext>? INexgenOperationInfo.SerializationContext => SerializationContext == null ? null : request => SerializationContext((TRequest)request);
    }

    internal static class NexgenOperationRegistry
    {
        private static readonly ServiceDefinition TypeRoundtripServiceServiceDefinition = ServiceDefinition.FromType<ITypeRoundtripService>();

        internal static IReadOnlyDictionary<(string Service, string Operation), INexgenOperationInfo> Operations { get; } = new Dictionary<(string Service, string Operation), INexgenOperationInfo>
        {
            [("TypeRoundtripService", "ActivityOptionsOperation")] = new NexgenOperationInfo<ActivityOptions, ActivityOptions>(
                TypeRoundtripServiceServiceDefinition.Operations["ActivityOptionsOperation"]),
            [("TypeRoundtripService", "FailureOperation")] = new NexgenOperationInfo<FailureContainer, FailureContainer>(
                TypeRoundtripServiceServiceDefinition.Operations["FailureOperation"]),
        };
    }

}
