// Generated by nexgen v0.2.1. DO NOT EDIT.
package json_schema.api.kb.content.page;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import json_schema.api.kb.SpecNumbers;
import json_schema.api.kb.ValidationException;
import json_schema.api.kb.Violation;
import json_schema.api.kb.content.block.Block;
import org.jspecify.annotations.Nullable;

/**
 * A page. One half of the Page &lt;-&gt; Block cross-file cycle. Because the cycle
 * spans two input files, Page and Block hoist together into Python's _recursive.py; the
 * non-cyclic PageMeta helper stays in this module.
 */
@JsonSerialize(using = Page.Serializer.class)
@JsonDeserialize(using = Page.Deserializer.class)
public final class Page {
    private final String pageId;
    private final String title;
    private final PageMeta meta;
    /**
     * Ordered content blocks. Cross-file `$ref` to block.json (same directory); the
     * array is the terminating edge of the cycle.
     */
    private final @Nullable List<Block> blocks;

    public Page(String pageId, String title, PageMeta meta, @Nullable List<Block> blocks) {
        this.pageId = pageId;
        this.title = title;
        this.meta = meta;
        this.blocks = blocks;
    }

    public String getPageId() {
        return pageId;
    }

    public String getTitle() {
        return title;
    }

    public PageMeta getMeta() {
        return meta;
    }

    public @Nullable List<Block> getBlocks() {
        return blocks;
    }

    @Override
    public boolean equals(@Nullable Object other) {
        if (this == other) {
            return true;
        }
        if (!(other instanceof Page)) {
            return false;
        }
        Page that = (Page) other;
        return Objects.equals(this.pageId, that.pageId)
            && Objects.equals(this.title, that.title)
            && Objects.equals(this.meta, that.meta)
            && Objects.equals(this.blocks, that.blocks);
    }

    @Override
    public int hashCode() {
        return Objects.hash(pageId, title, meta, blocks);
    }

    @Override
    public String toString() {
        return "Page{"
            + "pageId=" + pageId
            + ", title=" + title
            + ", meta=" + meta
            + ", blocks=" + blocks
            + "}";
    }

    public static final class Serializer extends com.fasterxml.jackson.databind.JsonSerializer<Page> {
        @Override
        public void serialize(Page value, JsonGenerator gen, SerializerProvider serializers) throws IOException {
            gen.writeStartObject();
            if (value.pageId != null) {
                gen.writeStringField("pageId", value.pageId);
            }
            if (value.title != null) {
                gen.writeStringField("title", value.title);
            }
            if (value.meta != null) {
                gen.writeFieldName("meta");
                serializers.defaultSerializeValue(value.meta, gen);
            }
            if (value.blocks != null) {
                gen.writeFieldName("blocks");
                serializers.defaultSerializeValue(value.blocks, gen);
            }
            gen.writeEndObject();
        }
    }

    public static final class Deserializer extends com.fasterxml.jackson.databind.JsonDeserializer<Page> {
        @Override
        public Page deserialize(JsonParser parser, DeserializationContext context) throws IOException {
            JsonNode node = parser.readValueAsTree();
            List<Violation> violations = new ArrayList<>();
            if (node == null || !node.isObject()) {
                violations.add(new Violation("", "expected object"));
                throw new ValidationException(violations);
            }
            Iterator<String> fieldNames = node.fieldNames();
            while (fieldNames.hasNext()) {
                String key = fieldNames.next();
                switch (key) {
                    case "blocks":
                    case "meta":
                    case "pageId":
                    case "title":
                        break;
                    default:
                        violations.add(new Violation(key, "unknown field"));
                }
            }
            String pageId = null;
            {
                JsonNode field = node.get("pageId");
                if (field == null) {
                    violations.add(new Violation("pageId", "required"));
                } else if (field.isNull()) {
                    violations.add(new Violation("pageId", "explicit null not allowed"));
                } else {
                    if (!field.isTextual()) {
                        violations.add(new Violation("pageId", "expected string"));
                    } else {
                        pageId = field.textValue();
                    }
                }
            }
            String title = null;
            {
                JsonNode field = node.get("title");
                if (field == null) {
                    violations.add(new Violation("title", "required"));
                } else if (field.isNull()) {
                    violations.add(new Violation("title", "explicit null not allowed"));
                } else {
                    if (!field.isTextual()) {
                        violations.add(new Violation("title", "expected string"));
                    } else {
                        title = field.textValue();
                    }
                }
            }
            PageMeta meta = null;
            {
                JsonNode field = node.get("meta");
                if (field == null) {
                    violations.add(new Violation("meta", "required"));
                } else if (field.isNull()) {
                    violations.add(new Violation("meta", "explicit null not allowed"));
                } else {
                    try {
                        meta = context.readTreeAsValue(field, PageMeta.class);
                    } catch (ValidationException nested) {
                        for (Violation violation : nested.getViolations()) {
                            violations.add(violation.withPathPrefix("meta"));
                        }
                    } catch (IOException nested) {
                        violations.add(new Violation("meta", nested.getMessage()));
                    }
                }
            }
            List<Block> blocks = null;
            {
                JsonNode field = node.get("blocks");
                if (field == null) {
                } else if (field.isNull()) {
                    violations.add(new Violation("blocks", "explicit null not allowed"));
                } else {
                    if (!field.isArray()) {
                        violations.add(new Violation("blocks", "expected array"));
                    } else {
                        List<Block> items = new ArrayList<>();
                        for (int index = 0; index < field.size(); index++) {
                            JsonNode element = field.get(index);
                            String elementPath = "blocks" + "[" + index + "]";
                            try {
                                items.add(context.readTreeAsValue(element, Block.class));
                            } catch (ValidationException nested) {
                                for (Violation violation : nested.getViolations()) {
                                    violations.add(violation.withPathPrefix(elementPath));
                                }
                            } catch (IOException nested) {
                                violations.add(new Violation(elementPath, nested.getMessage()));
                            }
                        }
                        blocks = items;
                    }
                }
            }
            if (!violations.isEmpty()) {
                throw new ValidationException(violations);
            }
            return new Page(pageId, title, meta, blocks);
        }
    }
}
