// Code generated by nexgen. DO NOT EDIT.
package genericmodels

import (
	"go.temporal.io/sdk/workflow"
)

// --- Datatypes ---

type genericRequest[ContextT any] struct {
	Context  ContextT
	Contexts []ContextT
	ByName   map[string]ContextT
	Nested   Inner[ContextT]
}

// --- Operations (internal) ---

func complete[ContextT any](ctx workflow.Context, request genericRequest[ContextT]) workflow.Future {
	c := workflow.NewNexusClient("generic-models", "GenericModelService")
	fut := c.ExecuteOperation(ctx, "Complete", request, workflow.NexusOperationOptions{})
	return fut
}

// --- Operations (public API) ---

type OperationCompletionResult[OutputT any] interface {
	isOperationCompletionResult(OutputT)
}

type OperationCompletionResultSuccess[OutputT any] struct {
	Value OperationCompletionSuccess[OutputT]
}

func (OperationCompletionResultSuccess[OutputT]) isOperationCompletionResult(OutputT) {}

type OperationCompletionResultFailure[OutputT any] struct {
	Value OperationCompletionFailure
}

func (OperationCompletionResultFailure[OutputT]) isOperationCompletionResult(OutputT) {}

type Inner[ContextT any] struct {
	// Required.
	Value ContextT
}

type GenericResponse[ContextT any, OutputT any, MetadataT any] struct {
	// Required.
	Context ContextT
	// Required.
	Completion OperationCompletionResult[OutputT]
	// Optional.
	Metadata *MetadataT
}

type OperationCompletionSuccess[OutputT any] struct {
	// Required.
	Output OutputT
}

type OperationCompletionFailure struct {
	// Required.
	Message string
}

type CompleteOptions[ContextT any] struct {
	// Required.
	Context ContextT
	// Required.
	Contexts []ContextT
	// Required.
	ByName map[string]ContextT
	// Required.
	Nested Inner[ContextT]
}

func Complete[ContextT any](ctx workflow.Context, opts CompleteOptions[ContextT]) workflow.Future {
	return complete(ctx, genericRequest[ContextT]{
		Context:  opts.Context,
		Contexts: opts.Contexts,
		ByName:   opts.ByName,
		Nested:   opts.Nested,
	})
}
