// Generated by nexgen v0.2.1. DO NOT EDIT.
package json_schema.api.showcase;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jspecify.annotations.Nullable;

/**
 * A string map with member-count and key-shape constraints: 1 to 3 entries, each key at
 * most 8 code points (minProperties/maxProperties/propertyNames on a map-shaped
 * object).
 */
@JsonSerialize(using = Attributes.Serializer.class)
@JsonDeserialize(using = Attributes.Deserializer.class)
public final class Attributes {
    private final Map<String, String> additionalProperties;

    public Attributes(Map<String, String> additionalProperties) {
        this.additionalProperties = additionalProperties;
    }

    public Map<String, String> getAdditionalProperties() {
        return additionalProperties;
    }

    @Override
    public boolean equals(@Nullable Object other) {
        if (this == other) {
            return true;
        }
        if (!(other instanceof Attributes)) {
            return false;
        }
        return Objects.equals(this.additionalProperties, ((Attributes) other).additionalProperties);
    }

    @Override
    public int hashCode() {
        return Objects.hash(additionalProperties);
    }

    @Override
    public String toString() {
        return "Attributes{"
            + "additionalProperties=" + additionalProperties
            + "}";
    }

    public static final class Serializer extends com.fasterxml.jackson.databind.JsonSerializer<Attributes> {
        @Override
        public void serialize(Attributes value, JsonGenerator gen, SerializerProvider serializers) throws IOException {
            List<Violation> violations = new ArrayList<>();
            if (value.additionalProperties.size() < 1) {
                violations.add(new Violation("", "must have at least 1 properties, got " + value.additionalProperties.size()));
            }
            if (value.additionalProperties.size() > 3) {
                violations.add(new Violation("", "must have at most 3 properties, got " + value.additionalProperties.size()));
            }
            for (String pnKey : value.additionalProperties.keySet()) {
                int pnLength = pnKey.codePointCount(0, pnKey.length());
                if (pnLength > 8) {
                    violations.add(new Violation(pnKey, "invalid property name \"" + pnKey + "\": must have length <= 8, got " + pnLength));
                }
            }
            if (!violations.isEmpty()) {
                throw new ValidationException(violations);
            }
            gen.writeStartObject();
            for (Map.Entry<String, String> entry : value.additionalProperties.entrySet()) {
                gen.writeStringField(entry.getKey(), entry.getValue());
            }
            gen.writeEndObject();
        }
    }

    public static final class Deserializer extends com.fasterxml.jackson.databind.JsonDeserializer<Attributes> {
        @Override
        public Attributes deserialize(JsonParser parser, DeserializationContext context) throws IOException {
            JsonNode node = parser.readValueAsTree();
            List<Violation> violations = new ArrayList<>();
            if (node == null || !node.isObject()) {
                violations.add(new Violation("", "expected object"));
                throw new ValidationException(violations);
            }
            Map<String, String> additionalProperties = new LinkedHashMap<>();
            Iterator<String> fieldNames = node.fieldNames();
            while (fieldNames.hasNext()) {
                String key = fieldNames.next();
                JsonNode element = node.get(key);
                if (element.isNull()) {
                    violations.add(new Violation(key, "explicit null not allowed"));
                    continue;
                }
                if (!element.isTextual()) {
                    violations.add(new Violation(key, "expected string value"));
                } else {
                    additionalProperties.put(key, element.textValue());
                }
            }
            if (node.size() < 1) {
                violations.add(new Violation("", "must have at least 1 properties, got " + node.size()));
            }
            if (node.size() > 3) {
                violations.add(new Violation("", "must have at most 3 properties, got " + node.size()));
            }
            Iterator<String> propertyNameKeys = node.fieldNames();
            while (propertyNameKeys.hasNext()) {
                String pnKey = propertyNameKeys.next();
                int pnLength = pnKey.codePointCount(0, pnKey.length());
                if (pnLength > 8) {
                    violations.add(new Violation(pnKey, "invalid property name \"" + pnKey + "\": must have length <= 8, got " + pnLength));
                }
            }
            if (!violations.isEmpty()) {
                throw new ValidationException(violations);
            }
            return new Attributes(additionalProperties);
        }
    }
}
