// Generated by nexgen v0.2.1. DO NOT EDIT.
package json_schema.api.showcase;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jspecify.annotations.Nullable;

/**
 * A map whose *member* type is a union written inline in `additionalProperties`. Like
 * an element union it has no name of its own, so it is named after its position —
 * `ChoicesValue` — and moved into `$defs`; each member then decodes through that
 * union's selector, with the member key carrying into the violation path.
 */
@JsonSerialize(using = Choices.Serializer.class)
@JsonDeserialize(using = Choices.Deserializer.class)
public final class Choices {
    private final Map<String, ChoicesValue> additionalProperties;

    public Choices(Map<String, ChoicesValue> additionalProperties) {
        this.additionalProperties = additionalProperties;
    }

    public Map<String, ChoicesValue> getAdditionalProperties() {
        return additionalProperties;
    }

    @Override
    public boolean equals(@Nullable Object other) {
        if (this == other) {
            return true;
        }
        if (!(other instanceof Choices)) {
            return false;
        }
        return Objects.equals(this.additionalProperties, ((Choices) other).additionalProperties);
    }

    @Override
    public int hashCode() {
        return Objects.hash(additionalProperties);
    }

    @Override
    public String toString() {
        return "Choices{"
            + "additionalProperties=" + additionalProperties
            + "}";
    }

    public static final class Serializer extends com.fasterxml.jackson.databind.JsonSerializer<Choices> {
        @Override
        public void serialize(Choices value, JsonGenerator gen, SerializerProvider serializers) throws IOException {
            gen.writeStartObject();
            for (Map.Entry<String, ChoicesValue> entry : value.additionalProperties.entrySet()) {
                gen.writeFieldName(entry.getKey());
                serializers.defaultSerializeValue(entry.getValue(), gen);
            }
            gen.writeEndObject();
        }
    }

    public static final class Deserializer extends com.fasterxml.jackson.databind.JsonDeserializer<Choices> {
        @Override
        public Choices deserialize(JsonParser parser, DeserializationContext context) throws IOException {
            JsonNode node = parser.readValueAsTree();
            List<Violation> violations = new ArrayList<>();
            if (node == null || !node.isObject()) {
                violations.add(new Violation("", "expected object"));
                throw new ValidationException(violations);
            }
            Map<String, ChoicesValue> additionalProperties = new LinkedHashMap<>();
            Iterator<String> fieldNames = node.fieldNames();
            while (fieldNames.hasNext()) {
                String key = fieldNames.next();
                JsonNode element = node.get(key);
                if (element.isNull()) {
                    violations.add(new Violation(key, "explicit null not allowed"));
                    continue;
                }
                ChoicesValue parsedAdditionalProperties = ChoicesValue.fromNode(element, key, violations, context);
                if (parsedAdditionalProperties != null) {
                    additionalProperties.put(key, parsedAdditionalProperties);
                }
            }
            if (!violations.isEmpty()) {
                throw new ValidationException(violations);
            }
            return new Choices(additionalProperties);
        }
    }
}
