// Generated by nexgen v0.2.1. DO NOT EDIT.
package json_schema.api.showcase;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jspecify.annotations.Nullable;

/**
 * A typed map whose members carry their own constraints: every member is a non-negative
 * multiple of 5, at most 100. A member is held to exactly what a declared field of that
 * type is held to, in both directions, with the offending member's key as the violation
 * path.
 */
@JsonSerialize(using = Quotas.Serializer.class)
@JsonDeserialize(using = Quotas.Deserializer.class)
public final class Quotas {
    private final Map<String, Long> additionalProperties;

    public Quotas(Map<String, Long> additionalProperties) {
        this.additionalProperties = additionalProperties;
    }

    public Map<String, Long> getAdditionalProperties() {
        return additionalProperties;
    }

    @Override
    public boolean equals(@Nullable Object other) {
        if (this == other) {
            return true;
        }
        if (!(other instanceof Quotas)) {
            return false;
        }
        return Objects.equals(this.additionalProperties, ((Quotas) other).additionalProperties);
    }

    @Override
    public int hashCode() {
        return Objects.hash(additionalProperties);
    }

    @Override
    public String toString() {
        return "Quotas{"
            + "additionalProperties=" + additionalProperties
            + "}";
    }

    public static final class Serializer extends com.fasterxml.jackson.databind.JsonSerializer<Quotas> {
        @Override
        public void serialize(Quotas value, JsonGenerator gen, SerializerProvider serializers) throws IOException {
            List<Violation> violations = new ArrayList<>();
            for (Map.Entry<String, Long> entry : value.additionalProperties.entrySet()) {
                if (entry.getValue() < 0L) {
                    violations.add(new Violation(entry.getKey(), "must be >= 0, got " + entry.getValue()));
                }
                if (entry.getValue() > 100L) {
                    violations.add(new Violation(entry.getKey(), "must be <= 100, got " + entry.getValue()));
                }
                if (entry.getValue() % 5L != 0) {
                    violations.add(new Violation(entry.getKey(), "must be a multiple of 5, got " + entry.getValue()));
                }
            }
            if (!violations.isEmpty()) {
                throw new ValidationException(violations);
            }
            gen.writeStartObject();
            for (Map.Entry<String, Long> entry : value.additionalProperties.entrySet()) {
                gen.writeNumberField(entry.getKey(), entry.getValue());
            }
            gen.writeEndObject();
        }
    }

    public static final class Deserializer extends com.fasterxml.jackson.databind.JsonDeserializer<Quotas> {
        @Override
        public Quotas deserialize(JsonParser parser, DeserializationContext context) throws IOException {
            JsonNode node = parser.readValueAsTree();
            List<Violation> violations = new ArrayList<>();
            if (node == null || !node.isObject()) {
                violations.add(new Violation("", "expected object"));
                throw new ValidationException(violations);
            }
            Map<String, Long> additionalProperties = new LinkedHashMap<>();
            Iterator<String> fieldNames = node.fieldNames();
            while (fieldNames.hasNext()) {
                String key = fieldNames.next();
                JsonNode element = node.get(key);
                if (element.isNull()) {
                    violations.add(new Violation(key, "explicit null not allowed"));
                    continue;
                }
                Long parsed = SpecNumbers.specLong(element, key, violations);
                if (parsed != null) {
                    if (parsed < 0L) {
                        violations.add(new Violation(key, "must be >= 0, got " + parsed));
                    }
                    if (parsed > 100L) {
                        violations.add(new Violation(key, "must be <= 100, got " + parsed));
                    }
                    if (parsed % 5L != 0) {
                        violations.add(new Violation(key, "must be a multiple of 5, got " + parsed));
                    }
                    additionalProperties.put(key, parsed);
                }
            }
            if (!violations.isEmpty()) {
                throw new ValidationException(violations);
            }
            return new Quotas(additionalProperties);
        }
    }
}
