// Generated by nexgen v0.2.1. DO NOT EDIT.
package json_schema.api.showcase;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jspecify.annotations.Nullable;

/**
 * A base object folded into Widget via allOf. It stays its own type; Widget copies its
 * fields rather than referencing or subtyping it.
 */
@JsonSerialize(using = WidgetBase.Serializer.class)
@JsonDeserialize(using = WidgetBase.Deserializer.class)
public final class WidgetBase {
    private final String id;
    private final @Nullable String kind;
    private final Map<String, JsonNode> additionalProperties;

    public WidgetBase(String id, @Nullable String kind, Map<String, JsonNode> additionalProperties) {
        this.id = id;
        this.kind = kind;
        this.additionalProperties = additionalProperties;
    }

    public String getId() {
        return id;
    }

    public @Nullable String getKind() {
        return kind;
    }

    public Map<String, JsonNode> getAdditionalProperties() {
        return additionalProperties;
    }

    @Override
    public boolean equals(@Nullable Object other) {
        if (this == other) {
            return true;
        }
        if (!(other instanceof WidgetBase)) {
            return false;
        }
        WidgetBase that = (WidgetBase) other;
        return Objects.equals(this.id, that.id)
            && Objects.equals(this.kind, that.kind)
            && Objects.equals(this.additionalProperties, that.additionalProperties);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, kind, additionalProperties);
    }

    @Override
    public String toString() {
        return "WidgetBase{"
            + "id=" + id
            + ", kind=" + kind
            + ", additionalProperties=" + additionalProperties
            + "}";
    }

    public static final class Serializer extends com.fasterxml.jackson.databind.JsonSerializer<WidgetBase> {
        @Override
        public void serialize(WidgetBase value, JsonGenerator gen, SerializerProvider serializers) throws IOException {
            List<Violation> violations = new ArrayList<>();
            java.util.Set<String> wireKeys = new java.util.LinkedHashSet<>();
            if (value.id != null) {
                wireKeys.add("id");
            }
            if (value.kind != null) {
                wireKeys.add("kind");
            }
            if (value.additionalProperties != null) {
                for (String key : value.additionalProperties.keySet()) {
                    if (!wireKeys.add(key)) {
                        violations.add(new Violation(key, "declared property key collision"));
                    }
                }
            }
            if (!violations.isEmpty()) {
                throw new ValidationException(violations);
            }
            gen.writeStartObject();
            if (value.id != null) {
                gen.writeStringField("id", value.id);
            }
            if (value.kind != null) {
                gen.writeStringField("kind", value.kind);
            }
            if (value.additionalProperties != null) {
                for (Map.Entry<String, JsonNode> entry : value.additionalProperties.entrySet()) {
                    gen.writeFieldName(entry.getKey());
                    gen.writeTree(entry.getValue());
                }
            }
            gen.writeEndObject();
        }
    }

    public static final class Deserializer extends com.fasterxml.jackson.databind.JsonDeserializer<WidgetBase> {
        @Override
        public WidgetBase deserialize(JsonParser parser, DeserializationContext context) throws IOException {
            JsonNode node = parser.readValueAsTree();
            List<Violation> violations = new ArrayList<>();
            if (node == null || !node.isObject()) {
                violations.add(new Violation("", "expected object"));
                throw new ValidationException(violations);
            }
            Map<String, JsonNode> additionalProperties = new LinkedHashMap<>();
            Iterator<String> fieldNames = node.fieldNames();
            while (fieldNames.hasNext()) {
                String key = fieldNames.next();
                switch (key) {
                    case "id":
                    case "kind":
                        break;
                    default:
                        additionalProperties.put(key, node.get(key));
                }
            }
            String id = null;
            {
                JsonNode field = node.get("id");
                if (field == null) {
                    violations.add(new Violation("id", "required"));
                } else if (field.isNull()) {
                    violations.add(new Violation("id", "explicit null not allowed"));
                } else {
                    if (!field.isTextual()) {
                        violations.add(new Violation("id", "expected string"));
                    } else {
                        id = field.textValue();
                    }
                }
            }
            String kind = null;
            {
                JsonNode field = node.get("kind");
                if (field == null) {
                } else if (field.isNull()) {
                    violations.add(new Violation("kind", "explicit null not allowed"));
                } else {
                    if (!field.isTextual()) {
                        violations.add(new Violation("kind", "expected string"));
                    } else {
                        kind = field.textValue();
                    }
                }
            }
            if (!violations.isEmpty()) {
                throw new ValidationException(violations);
            }
            return new WidgetBase(id, kind, additionalProperties);
        }
    }
}
