// Generated by nexgen v0.2.1. DO NOT EDIT.
package json_schema.definitions.kb.content.block;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import json_schema.definitions.kb.SpecNumbers;
import json_schema.definitions.kb.ValidationException;
import json_schema.definitions.kb.Violation;
import json_schema.definitions.kb.content.page.Page;
import org.jspecify.annotations.Nullable;

/**
 * A content block. The other half of the Page &lt;-&gt; Block cross-file cycle. The
 * `page` back-reference is optional + nullable, which terminates the cycle so it is
 * satisfiable.
 */
@JsonSerialize(using = Block.Serializer.class)
@JsonDeserialize(using = Block.Deserializer.class)
public final class Block {
    private final String blockId;
    /**
     * Non-negative position within the page. Exercises a numeric `minimum` bound over
     * an integer field.
     */
    private final long order;
    private final @Nullable String text;
    private final @Nullable BlockStyle style;
    /**
     * Optional back-reference to the containing page - closes the Page &lt;-&gt; Block
     * cycle. Optional + nullable, so this edge terminates.
     */
    private final @Nullable Page page;

    public Block(String blockId, long order, @Nullable String text, @Nullable BlockStyle style, @Nullable Page page) {
        this.blockId = blockId;
        this.order = order;
        this.text = text;
        this.style = style;
        this.page = page;
    }

    public String getBlockId() {
        return blockId;
    }

    public long getOrder() {
        return order;
    }

    public @Nullable String getText() {
        return text;
    }

    public @Nullable BlockStyle getStyle() {
        return style;
    }

    public @Nullable Page getPage() {
        return page;
    }

    @Override
    public boolean equals(@Nullable Object other) {
        if (this == other) {
            return true;
        }
        if (!(other instanceof Block)) {
            return false;
        }
        Block that = (Block) other;
        return Objects.equals(this.blockId, that.blockId)
            && this.order == that.order
            && Objects.equals(this.text, that.text)
            && Objects.equals(this.style, that.style)
            && Objects.equals(this.page, that.page);
    }

    @Override
    public int hashCode() {
        return Objects.hash(blockId, order, text, style, page);
    }

    @Override
    public String toString() {
        return "Block{"
            + "blockId=" + blockId
            + ", order=" + order
            + ", text=" + text
            + ", style=" + style
            + ", page=" + page
            + "}";
    }

    public static final class Serializer extends com.fasterxml.jackson.databind.JsonSerializer<Block> {
        @Override
        public void serialize(Block value, JsonGenerator gen, SerializerProvider serializers) throws IOException {
            List<Violation> violations = new ArrayList<>();
            {
                if (value.order < 0L) {
                    violations.add(new Violation("order", "must be >= 0, got " + value.order));
                }
            }
            if (!violations.isEmpty()) {
                throw new ValidationException(violations);
            }
            gen.writeStartObject();
            if (value.blockId != null) {
                gen.writeStringField("blockId", value.blockId);
            }
            gen.writeNumberField("order", value.order);

            if (value.text != null) {
                gen.writeStringField("text", value.text);
            }
            if (value.style != null) {
                gen.writeFieldName("style");
                serializers.defaultSerializeValue(value.style, gen);
            }
            if (value.page != null) {
                gen.writeFieldName("page");
                serializers.defaultSerializeValue(value.page, gen);
            }
            gen.writeEndObject();
        }
    }

    public static final class Deserializer extends com.fasterxml.jackson.databind.JsonDeserializer<Block> {
        @Override
        public Block deserialize(JsonParser parser, DeserializationContext context) throws IOException {
            JsonNode node = parser.readValueAsTree();
            List<Violation> violations = new ArrayList<>();
            if (node == null || !node.isObject()) {
                violations.add(new Violation("", "expected object"));
                throw new ValidationException(violations);
            }
            Iterator<String> fieldNames = node.fieldNames();
            while (fieldNames.hasNext()) {
                String key = fieldNames.next();
                switch (key) {
                    case "blockId":
                    case "order":
                    case "page":
                    case "style":
                    case "text":
                        break;
                    default:
                        violations.add(new Violation(key, "unknown field"));
                }
            }
            String blockId = null;
            {
                JsonNode field = node.get("blockId");
                if (field == null) {
                    violations.add(new Violation("blockId", "required"));
                } else if (field.isNull()) {
                    violations.add(new Violation("blockId", "explicit null not allowed"));
                } else {
                    if (!field.isTextual()) {
                        violations.add(new Violation("blockId", "expected string"));
                    } else {
                        blockId = field.textValue();
                    }
                }
            }
            long order = 0L;
            {
                JsonNode field = node.get("order");
                if (field == null) {
                    violations.add(new Violation("order", "required"));
                } else if (field.isNull()) {
                    violations.add(new Violation("order", "explicit null not allowed"));
                } else {
                    Long numberValue = SpecNumbers.specLong(field, "order", violations);
                    if (numberValue != null) {
                        order = numberValue;
                        if (numberValue < 0L) {
                            violations.add(new Violation("order", "must be >= 0, got " + numberValue));
                        }
                    }
                }
            }
            String text = null;
            {
                JsonNode field = node.get("text");
                if (field == null) {
                } else if (field.isNull()) {
                    violations.add(new Violation("text", "explicit null not allowed"));
                } else {
                    if (!field.isTextual()) {
                        violations.add(new Violation("text", "expected string"));
                    } else {
                        text = field.textValue();
                    }
                }
            }
            BlockStyle style = null;
            {
                JsonNode field = node.get("style");
                if (field == null) {
                } else if (field.isNull()) {
                    violations.add(new Violation("style", "explicit null not allowed"));
                } else {
                    try {
                        style = context.readTreeAsValue(field, BlockStyle.class);
                    } catch (ValidationException nested) {
                        for (Violation violation : nested.getViolations()) {
                            violations.add(violation.withPathPrefix("style"));
                        }
                    } catch (IOException nested) {
                        violations.add(new Violation("style", nested.getMessage()));
                    }
                }
            }
            Page page = null;
            {
                JsonNode field = node.get("page");
                if (field == null) {
                } else if (field.isNull()) {
                } else {
                    try {
                        page = context.readTreeAsValue(field, Page.class);
                    } catch (ValidationException nested) {
                        for (Violation violation : nested.getViolations()) {
                            violations.add(violation.withPathPrefix("page"));
                        }
                    } catch (IOException nested) {
                        violations.add(new Violation("page", nested.getMessage()));
                    }
                }
            }
            if (!violations.isEmpty()) {
                throw new ValidationException(violations);
            }
            return new Block(blockId, order, text, style, page);
        }
    }
}
