// Generated by nexgen latest. DO NOT EDIT!

import type { TransferTypeConverter } from "nexus-rpc";
import { createPayloadValidationError } from "@temporalio/common";
import * as __nexgenDefinitions from "./definitions";

export function requiredField<T>(
  value: T | null | undefined,
  owner: string,
  field: string,
): T {
  if (value == null) {
    throw new Error(`missing required field ${owner}.${field}`);
  }
  return value;
}

/**
 * Temporal
 *
 * Root object materializing the four RFC 3339 temporal formats as native typed fields:
 * date-time (offset & sub-second precision preserved), date, time (offset preserved
 * when present), and duration (time-only, canonicalized). Covers required, optional,
 * and nullable members of each.
 */
export interface Temporal {
  /**
   * Required event timestamp; materialized date-time (offset required, sub-second
   * precision & offset preserved on round-trip).
   */
  createdAt: string;
  /**
   * Required calendar date; materialized date (YYYY-MM-DD, lossless).
   */
  birthday: string;
  /**
   * Required wall-clock time; materialized time (offset preserved when present,
   * otherwise offset-less).
   */
  alarm: string;
  /**
   * Required time-only duration; materialized duration, canonicalized to PT…H…M…S (e.g.
   * PT90M → PT1H30M).
   */
  timeout: string;
  /**
   * Optional date-time.
   */
  updatedAt?: string;
  /**
   * Optional date.
   */
  expiresOn?: string;
  /**
   * Optional time.
   */
  reminder?: string;
  /**
   * Optional duration.
   */
  retryDelay?: string;
  /**
   * Optional and nullable date-time (may be absent or explicitly null).
   */
  deletedAt?: string | null;
  /**
   * Optional and nullable date.
   */
  archivedOn?: string | null;
}

export const temporalTransferTypeConverter =
  new (class implements TransferTypeConverter<Temporal> {
    public fromTransferType(raw: unknown): Temporal {
      const violations: __nexgenDefinitions.Violation[] = [];
      if (!__nexgenDefinitions.isPlainObject(raw)) {
        throw createPayloadValidationError([{ path: "", reason: "expected object" }]);
      }

      let createdAt: string = undefined as unknown as string;
      if (
        !Object.prototype.hasOwnProperty.call(raw, "createdAt") ||
        raw["createdAt"] === null
      ) {
        violations.push({ path: "createdAt", reason: "required" });
      } else {
        if (typeof raw["createdAt"] !== "string") {
          violations.push({ path: "createdAt", reason: "expected string" });
        } else {
          const parsed = __nexgenDefinitions.parseTemporalDateTime(
            raw["createdAt"],
            "createdAt",
            violations,
          );
          if (parsed !== undefined) {
            createdAt = parsed;
          }
        }
      }

      let birthday: string = undefined as unknown as string;
      if (
        !Object.prototype.hasOwnProperty.call(raw, "birthday") ||
        raw["birthday"] === null
      ) {
        violations.push({ path: "birthday", reason: "required" });
      } else {
        if (typeof raw["birthday"] !== "string") {
          violations.push({ path: "birthday", reason: "expected string" });
        } else {
          const parsed = __nexgenDefinitions.parseTemporalDate(
            raw["birthday"],
            "birthday",
            violations,
          );
          if (parsed !== undefined) {
            birthday = parsed;
          }
        }
      }

      let alarm: string = undefined as unknown as string;
      if (
        !Object.prototype.hasOwnProperty.call(raw, "alarm") ||
        raw["alarm"] === null
      ) {
        violations.push({ path: "alarm", reason: "required" });
      } else {
        if (typeof raw["alarm"] !== "string") {
          violations.push({ path: "alarm", reason: "expected string" });
        } else {
          const parsed = __nexgenDefinitions.parseTemporalTime(
            raw["alarm"],
            "alarm",
            violations,
          );
          if (parsed !== undefined) {
            alarm = parsed;
          }
        }
      }

      let timeout: string = undefined as unknown as string;
      if (
        !Object.prototype.hasOwnProperty.call(raw, "timeout") ||
        raw["timeout"] === null
      ) {
        violations.push({ path: "timeout", reason: "required" });
      } else {
        if (typeof raw["timeout"] !== "string") {
          violations.push({ path: "timeout", reason: "expected string" });
        } else {
          const parsed = __nexgenDefinitions.parseTemporalDuration(
            raw["timeout"],
            "timeout",
            violations,
          );
          if (parsed !== undefined) {
            timeout = parsed;
          }
        }
      }

      let updatedAt: string | undefined = undefined as unknown as string | undefined;
      if (
        Object.prototype.hasOwnProperty.call(raw, "updatedAt") &&
        raw["updatedAt"] === null
      ) {
        violations.push({ path: "updatedAt", reason: "explicit null not allowed" });
      } else if (Object.prototype.hasOwnProperty.call(raw, "updatedAt")) {
        if (typeof raw["updatedAt"] !== "string") {
          violations.push({ path: "updatedAt", reason: "expected string" });
        } else {
          const parsed = __nexgenDefinitions.parseTemporalDateTime(
            raw["updatedAt"],
            "updatedAt",
            violations,
          );
          if (parsed !== undefined) {
            updatedAt = parsed;
          }
        }
      }

      let expiresOn: string | undefined = undefined as unknown as string | undefined;
      if (
        Object.prototype.hasOwnProperty.call(raw, "expiresOn") &&
        raw["expiresOn"] === null
      ) {
        violations.push({ path: "expiresOn", reason: "explicit null not allowed" });
      } else if (Object.prototype.hasOwnProperty.call(raw, "expiresOn")) {
        if (typeof raw["expiresOn"] !== "string") {
          violations.push({ path: "expiresOn", reason: "expected string" });
        } else {
          const parsed = __nexgenDefinitions.parseTemporalDate(
            raw["expiresOn"],
            "expiresOn",
            violations,
          );
          if (parsed !== undefined) {
            expiresOn = parsed;
          }
        }
      }

      let reminder: string | undefined = undefined as unknown as string | undefined;
      if (
        Object.prototype.hasOwnProperty.call(raw, "reminder") &&
        raw["reminder"] === null
      ) {
        violations.push({ path: "reminder", reason: "explicit null not allowed" });
      } else if (Object.prototype.hasOwnProperty.call(raw, "reminder")) {
        if (typeof raw["reminder"] !== "string") {
          violations.push({ path: "reminder", reason: "expected string" });
        } else {
          const parsed = __nexgenDefinitions.parseTemporalTime(
            raw["reminder"],
            "reminder",
            violations,
          );
          if (parsed !== undefined) {
            reminder = parsed;
          }
        }
      }

      let retryDelay: string | undefined = undefined as unknown as string | undefined;
      if (
        Object.prototype.hasOwnProperty.call(raw, "retryDelay") &&
        raw["retryDelay"] === null
      ) {
        violations.push({ path: "retryDelay", reason: "explicit null not allowed" });
      } else if (Object.prototype.hasOwnProperty.call(raw, "retryDelay")) {
        if (typeof raw["retryDelay"] !== "string") {
          violations.push({ path: "retryDelay", reason: "expected string" });
        } else {
          const parsed = __nexgenDefinitions.parseTemporalDuration(
            raw["retryDelay"],
            "retryDelay",
            violations,
          );
          if (parsed !== undefined) {
            retryDelay = parsed;
          }
        }
      }

      let deletedAt: string | null | undefined = undefined as unknown as
        | string
        | null
        | undefined;
      if (Object.prototype.hasOwnProperty.call(raw, "deletedAt")) {
        if (raw["deletedAt"] === null) {
          deletedAt = null;
        } else {
          if (typeof raw["deletedAt"] !== "string") {
            violations.push({ path: "deletedAt", reason: "expected string" });
          } else {
            const parsed = __nexgenDefinitions.parseTemporalDateTime(
              raw["deletedAt"],
              "deletedAt",
              violations,
            );
            if (parsed !== undefined) {
              deletedAt = parsed;
            }
          }
        }
      }

      let archivedOn: string | null | undefined = undefined as unknown as
        | string
        | null
        | undefined;
      if (Object.prototype.hasOwnProperty.call(raw, "archivedOn")) {
        if (raw["archivedOn"] === null) {
          archivedOn = null;
        } else {
          if (typeof raw["archivedOn"] !== "string") {
            violations.push({ path: "archivedOn", reason: "expected string" });
          } else {
            const parsed = __nexgenDefinitions.parseTemporalDate(
              raw["archivedOn"],
              "archivedOn",
              violations,
            );
            if (parsed !== undefined) {
              archivedOn = parsed;
            }
          }
        }
      }

      for (const key of Object.keys(raw)) {
        if (
          key !== "createdAt" &&
          key !== "birthday" &&
          key !== "alarm" &&
          key !== "timeout" &&
          key !== "updatedAt" &&
          key !== "expiresOn" &&
          key !== "reminder" &&
          key !== "retryDelay" &&
          key !== "deletedAt" &&
          key !== "archivedOn"
        ) {
          violations.push({
            path: __nexgenDefinitions.memberPath(key),
            reason: "unknown field",
          });
        }
      }

      if (violations.length) {
        throw createPayloadValidationError(violations);
      }
      const out: Temporal = { createdAt, birthday, alarm, timeout };
      if (updatedAt !== undefined) {
        out.updatedAt = updatedAt;
      }
      if (expiresOn !== undefined) {
        out.expiresOn = expiresOn;
      }
      if (reminder !== undefined) {
        out.reminder = reminder;
      }
      if (retryDelay !== undefined) {
        out.retryDelay = retryDelay;
      }
      if (deletedAt !== undefined) {
        out.deletedAt = deletedAt;
      }
      if (archivedOn !== undefined) {
        out.archivedOn = archivedOn;
      }
      return out;
    }

    public toTransferType(value: Temporal): unknown {
      const candidate: unknown = value;
      if (!__nexgenDefinitions.isPlainObject(candidate)) {
        throw createPayloadValidationError([{ path: "", reason: "expected object" }]);
      }
      const violations: __nexgenDefinitions.Violation[] = [];
      const out: Record<string, unknown> = Object.create(null) as Record<
        string,
        unknown
      >;
      if (value.createdAt === undefined || value.createdAt === null) {
        violations.push({ path: "createdAt", reason: "required" });
      } else {
        if (!(typeof value.createdAt === "string")) {
          violations.push({ path: "createdAt", reason: "expected date-time" });
        } else {
          __nexgenDefinitions.validateTemporalDateTime(
            value.createdAt,
            "createdAt",
            violations,
          );
        }
        out["createdAt"] = value.createdAt;
      }
      if (value.birthday === undefined || value.birthday === null) {
        violations.push({ path: "birthday", reason: "required" });
      } else {
        if (!(typeof value.birthday === "string")) {
          violations.push({ path: "birthday", reason: "expected date" });
        } else {
          __nexgenDefinitions.validateTemporalDate(
            value.birthday,
            "birthday",
            violations,
          );
        }
        out["birthday"] = value.birthday;
      }
      if (value.alarm === undefined || value.alarm === null) {
        violations.push({ path: "alarm", reason: "required" });
      } else {
        if (!(typeof value.alarm === "string")) {
          violations.push({ path: "alarm", reason: "expected time" });
        } else {
          __nexgenDefinitions.validateTemporalTime(value.alarm, "alarm", violations);
        }
        out["alarm"] = value.alarm;
      }
      if (value.timeout === undefined || value.timeout === null) {
        violations.push({ path: "timeout", reason: "required" });
      } else {
        if (!(typeof value.timeout === "string")) {
          violations.push({ path: "timeout", reason: "expected duration" });
        } else {
          __nexgenDefinitions.validateTemporalDuration(
            value.timeout,
            "timeout",
            violations,
          );
        }
        out["timeout"] = value.timeout;
      }
      if (value.updatedAt !== undefined) {
        if (value.updatedAt === null) {
          violations.push({ path: "updatedAt", reason: "explicit null not allowed" });
        } else {
          if (!(typeof value.updatedAt === "string")) {
            violations.push({ path: "updatedAt", reason: "expected date-time" });
          } else {
            __nexgenDefinitions.validateTemporalDateTime(
              value.updatedAt,
              "updatedAt",
              violations,
            );
          }
          out["updatedAt"] = value.updatedAt;
        }
      }
      if (value.expiresOn !== undefined) {
        if (value.expiresOn === null) {
          violations.push({ path: "expiresOn", reason: "explicit null not allowed" });
        } else {
          if (!(typeof value.expiresOn === "string")) {
            violations.push({ path: "expiresOn", reason: "expected date" });
          } else {
            __nexgenDefinitions.validateTemporalDate(
              value.expiresOn,
              "expiresOn",
              violations,
            );
          }
          out["expiresOn"] = value.expiresOn;
        }
      }
      if (value.reminder !== undefined) {
        if (value.reminder === null) {
          violations.push({ path: "reminder", reason: "explicit null not allowed" });
        } else {
          if (!(typeof value.reminder === "string")) {
            violations.push({ path: "reminder", reason: "expected time" });
          } else {
            __nexgenDefinitions.validateTemporalTime(
              value.reminder,
              "reminder",
              violations,
            );
          }
          out["reminder"] = value.reminder;
        }
      }
      if (value.retryDelay !== undefined) {
        if (value.retryDelay === null) {
          violations.push({ path: "retryDelay", reason: "explicit null not allowed" });
        } else {
          if (!(typeof value.retryDelay === "string")) {
            violations.push({ path: "retryDelay", reason: "expected duration" });
          } else {
            __nexgenDefinitions.validateTemporalDuration(
              value.retryDelay,
              "retryDelay",
              violations,
            );
          }
          out["retryDelay"] = value.retryDelay;
        }
      }
      if (value.deletedAt !== undefined) {
        const deletedAtViolationCount = violations.length;
        if (value.deletedAt !== null) {
          if (!(typeof value.deletedAt === "string")) {
            violations.push({ path: "deletedAt", reason: "expected date-time" });
          } else {
            __nexgenDefinitions.validateTemporalDateTime(
              value.deletedAt,
              "deletedAt",
              violations,
            );
          }
        }
        if (violations.length === deletedAtViolationCount) {
          out["deletedAt"] = value.deletedAt === null ? null : value.deletedAt;
        }
      }
      if (value.archivedOn !== undefined) {
        const archivedOnViolationCount = violations.length;
        if (value.archivedOn !== null) {
          if (!(typeof value.archivedOn === "string")) {
            violations.push({ path: "archivedOn", reason: "expected date" });
          } else {
            __nexgenDefinitions.validateTemporalDate(
              value.archivedOn,
              "archivedOn",
              violations,
            );
          }
        }
        if (violations.length === archivedOnViolationCount) {
          out["archivedOn"] = value.archivedOn === null ? null : value.archivedOn;
        }
      }
      if (violations.length) {
        throw createPayloadValidationError(violations);
      }
      return out;
    }
  })();
