// Generated by nexgen latest. DO NOT EDIT!

import * as nexus from "nexus-rpc";
import * as workflow from "@temporalio/workflow";
import {
  getCategoryTreeInputTransferTypeConverter,
  getPageInputTransferTypeConverter,
  putBlockOutputTransferTypeConverter,
} from "./models";
import type { GetCategoryTreeInput, GetPageInput, PutBlockOutput } from "./models";
import { blockTransferTypeConverter } from "../content/block/models";
import { pageTransferTypeConverter } from "../content/page/models";
import { categoryTransferTypeConverter } from "../tree/category/models";
import type { Block } from "../content/block/models";
import type { Page } from "../content/page/models";
import type { Category } from "../tree/category/models";

/**
 * Fetch and update pages, blocks, and the category tree.
 */
export const knowledgeBaseService = nexus.service(
  "example.kb.v1.KnowledgeBaseService",
  {
    /**
     * Fetch a page by id.
     */
    getPage: nexus.operation<GetPageInput, Page>({
      name: "GetPage",
      inputType: { transferTypeConverter: getPageInputTransferTypeConverter },
      outputType: { transferTypeConverter: pageTransferTypeConverter },
    }),
    /**
     * Create or update a content block.
     */
    putBlock: nexus.operation<Block, PutBlockOutput>({
      name: "PutBlock",
      inputType: { transferTypeConverter: blockTransferTypeConverter },
      outputType: { transferTypeConverter: putBlockOutputTransferTypeConverter },
    }),
    /**
     * Fetch the category tree rooted at a category.
     */
    getCategoryTree: nexus.operation<GetCategoryTreeInput, Category>({
      name: "GetCategoryTree",
      inputType: { transferTypeConverter: getCategoryTreeInputTransferTypeConverter },
      outputType: { transferTypeConverter: categoryTransferTypeConverter },
    }),
  },
);

/**
 * Fetch and update pages, blocks, and the category tree.
 */
export class KnowledgeBaseServiceClient {
  private readonly client: workflow.NexusServiceClient<typeof knowledgeBaseService>;

  public constructor(endpoint: string) {
    this.client = workflow.createNexusServiceClient({
      service: knowledgeBaseService,
      endpoint,
    });
  }

  /**
   * Fetch a page by id.
   *
   * @param request - Request for the operation.
   */
  public async getPage(
    request: GetPageInput,
  ): Promise<workflow.NexusOperationHandle<Page>> {
    return await this.client.startOperation(
      knowledgeBaseService.operations.getPage,
      request,
    );
  }

  /**
   * Create or update a content block.
   *
   * @param request - Request for the operation.
   */
  public async putBlock(
    request: Block,
  ): Promise<workflow.NexusOperationHandle<PutBlockOutput>> {
    return await this.client.startOperation(
      knowledgeBaseService.operations.putBlock,
      request,
    );
  }

  /**
   * Fetch the category tree rooted at a category.
   *
   * @param request - Request for the operation.
   */
  public async getCategoryTree(
    request: GetCategoryTreeInput,
  ): Promise<workflow.NexusOperationHandle<Category>> {
    return await this.client.startOperation(
      knowledgeBaseService.operations.getCategoryTree,
      request,
    );
  }
}

export const operationRegistry = [
  {
    service: "example.kb.v1.KnowledgeBaseService",
    operation: "GetPage",
  },
  {
    service: "example.kb.v1.KnowledgeBaseService",
    operation: "PutBlock",
  },
  {
    service: "example.kb.v1.KnowledgeBaseService",
    operation: "GetCategoryTree",
  },
] as const;
