// <auto-generated />
// Generated by nexgen latest. DO NOT EDIT!
#nullable enable

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Threading.Tasks;
using Temporalio.Workflows;
using Nexgen.Support;

namespace Nexgen.TypeShowcase
{

    [GeneratedCode("nexgen", null)]
    public class User
    {
        public User(string userId, string email, string displayName, UserStatus status, UserProfile profile)
        {
            UserId = userId;
            Email = email;
            DisplayName = displayName;
            Status = status;
            Profile = profile;
        }

        public string UserId { get; }
        public string Email { get; }
        public string DisplayName { get; }
        public UserStatus Status { get; }
        public UserProfile Profile { get; }

        [GeneratedCode("nexgen", null)]
        public Task<User> UpdateEmailAsync(string email)
        {
            var request = new UpdateEmailOptions(UserId, email);
            return Operations.UpdateEmailAsync(request);
        }

        [GeneratedCode("nexgen", null)]
        public Task<User> RenameAsync(string displayName)
        {
            var request = new RenameOptions(UserId, displayName);
            return Operations.RenameAsync(request);
        }

        [GeneratedCode("nexgen", null)]
        public Task DeactivateAsync(string? reason)
        {
            var request = new DeactivateOptions(UserId) { Reason = reason };
            return Operations.DeactivateAsync(request);
        }

    }

}
