// Code generated by nexgen latest. DO NOT EDIT.

package workflowservice

import (
	converter "go.temporal.io/sdk/converter"
	internal "go.temporal.io/sdk/internal"
	reflect "reflect"
)

var NexusOperationRegistry = map[internal.NexusOperationKey]internal.NexusOperationRegistryEntry{
	{
		Service:   "temporal.api.workflowservice.v1.WorkflowService",
		Operation: "SignalWithStartWorkflowExecution",
	}: {
		InputType: reflect.TypeFor[signalWithStartWorkflowRequest](),
		SerializationContext: func(request any) converter.SerializationContext {
			return signalWithStartWorkflowSerializationContext(request.(signalWithStartWorkflowRequest))
		},
	},
}

func init() {
	internal.RegisterNexusOperationRegistry(NexusOperationRegistry)
}
