// Code generated by nexgen latest. DO NOT EDIT.

package workflowservice

import (
	"go.temporal.io/sdk/converter"
	"go.temporal.io/sdk/internal"
	"go.temporal.io/sdk/workflow"
)

type nexgenSerializationContextKey struct{}

// Keep the inner converter separate from the root used for the Nexus envelope.
// The SDK retains this context for both input and result transfer conversion.
func nexgenWithSerializationContext(ctx workflow.Context, sc converter.SerializationContext) workflow.Context {
	if sc == nil {
		return ctx
	}
	return workflow.WithValue(ctx, nexgenSerializationContextKey{}, internal.WithRootDataConverterSerializationContext(ctx, sc))
}

// Only model conversion uses this derived context; never pass it to ExecuteOperation.
func nexgenPayloadContext(ctx workflow.Context) workflow.Context {
	if dc, ok := ctx.Value(nexgenSerializationContextKey{}).(converter.DataConverter); ok {
		return workflow.WithDataConverter(ctx, dc)
	}
	return ctx
}
