// Code generated by nexgen latest. DO NOT EDIT.

package workflowservice

import (
	"fmt"
	"time"

	enums "go.temporal.io/api/enums/v1"
	sdk "go.temporal.io/api/sdk/v1"
	workflowservice "go.temporal.io/api/workflowservice/v1"
	"go.temporal.io/sdk/client"
	"go.temporal.io/sdk/temporal"
	"go.temporal.io/sdk/workflow"
)

// --- Datatypes ---

type signalWithStartWorkflowRequest struct {
	Workflow                 string
	Args                     []any
	ID                       string
	TaskQueue                string
	Signal                   string
	SignalArgs               []any
	WorkflowExecutionTimeout *time.Duration
	WorkflowRunTimeout       *time.Duration
	WorkflowTaskTimeout      *time.Duration
	WorkflowIDReusePolicy    *enums.WorkflowIdReusePolicy
	WorkflowIDConflictPolicy *enums.WorkflowIdConflictPolicy
	RetryPolicy              *temporal.RetryPolicy
	CronSchedule             *string
	Memo                     map[string]any
	TypedSearchAttributes    temporal.SearchAttributes
	Priority                 *temporal.Priority
	VersioningOverride       client.VersioningOverride
	StartDelay               *time.Duration
	UserMetadata             *UserMetadata
	Headers                  map[string]any
}

func (m signalWithStartWorkflowRequest) toProto(ctx workflow.Context) (*workflowservice.SignalWithStartWorkflowExecutionRequest, error) {
	message := &workflowservice.SignalWithStartWorkflowExecutionRequest{}
	{
		converted, err := workflowTypeToProto(ctx, &m.Workflow)
		if err != nil {
			return nil, err
		}
		message.WorkflowType = converted
	}
	{
		converted, err := payloadsToProto(ctx, m.Args)
		if err != nil {
			return nil, err
		}
		message.Input = converted
	}
	message.WorkflowId = m.ID
	{
		converted, err := taskQueueToProto(ctx, &m.TaskQueue)
		if err != nil {
			return nil, err
		}
		message.TaskQueue = converted
	}
	message.SignalName = m.Signal
	{
		converted, err := payloadsToProto(ctx, m.SignalArgs)
		if err != nil {
			return nil, err
		}
		message.SignalInput = converted
	}
	{
		converted, err := durationToProto(ctx, m.WorkflowExecutionTimeout)
		if err != nil {
			return nil, err
		}
		message.WorkflowExecutionTimeout = converted
	}
	{
		converted, err := durationToProto(ctx, m.WorkflowRunTimeout)
		if err != nil {
			return nil, err
		}
		message.WorkflowRunTimeout = converted
	}
	{
		converted, err := durationToProto(ctx, m.WorkflowTaskTimeout)
		if err != nil {
			return nil, err
		}
		message.WorkflowTaskTimeout = converted
	}
	if m.WorkflowIDReusePolicy != nil {
		message.WorkflowIdReusePolicy = enums.WorkflowIdReusePolicy((*m.WorkflowIDReusePolicy))
	}
	if m.WorkflowIDConflictPolicy != nil {
		message.WorkflowIdConflictPolicy = enums.WorkflowIdConflictPolicy((*m.WorkflowIDConflictPolicy))
	}
	{
		converted, err := retryPolicyToProto(ctx, m.RetryPolicy)
		if err != nil {
			return nil, err
		}
		message.RetryPolicy = converted
	}
	if m.CronSchedule != nil {
		message.CronSchedule = (*m.CronSchedule)
	}
	{
		converted, err := memoToProto(ctx, m.Memo)
		if err != nil {
			return nil, err
		}
		message.Memo = converted
	}
	{
		converted, err := searchAttributesToProto(ctx, &m.TypedSearchAttributes)
		if err != nil {
			return nil, err
		}
		message.SearchAttributes = converted
	}
	{
		converted, err := priorityToProto(ctx, m.Priority)
		if err != nil {
			return nil, err
		}
		message.Priority = converted
	}
	{
		converted, err := versioningOverrideToProto(ctx, &m.VersioningOverride)
		if err != nil {
			return nil, err
		}
		message.VersioningOverride = converted
	}
	{
		converted, err := durationToProto(ctx, m.StartDelay)
		if err != nil {
			return nil, err
		}
		message.WorkflowStartDelay = converted
	}
	if m.UserMetadata != nil {
		converted, err := (*m.UserMetadata).toProto(ctx)
		if err != nil {
			return nil, err
		}
		message.UserMetadata = converted
	}
	{
		converted, err := headerToProto(ctx, m.Headers)
		if err != nil {
			return nil, err
		}
		message.Header = converted
	}
	message.Namespace = workflow.GetInfo(ctx).Namespace
	return message, nil
}

func signalWithStartWorkflowRequestFromProto(ctx workflow.Context, proto *workflowservice.SignalWithStartWorkflowExecutionRequest) (signalWithStartWorkflowRequest, error) {
	value := signalWithStartWorkflowRequest{}
	{
		converted, err := workflowTypeFromProto(ctx, proto.GetWorkflowType())
		if err != nil {
			return value, err
		}
		if converted != nil {
			value.Workflow = *converted
		}
	}
	{
		converted, err := payloadsFromProto(ctx, proto.GetInput())
		if err != nil {
			return value, err
		}
		value.Args = converted
	}
	value.ID = proto.GetWorkflowId()
	{
		converted, err := taskQueueFromProto(ctx, proto.GetTaskQueue())
		if err != nil {
			return value, err
		}
		if converted != nil {
			value.TaskQueue = *converted
		}
	}
	value.Signal = proto.GetSignalName()
	{
		converted, err := payloadsFromProto(ctx, proto.GetSignalInput())
		if err != nil {
			return value, err
		}
		value.SignalArgs = converted
	}
	{
		converted, err := durationFromProto(ctx, proto.GetWorkflowExecutionTimeout())
		if err != nil {
			return value, err
		}
		value.WorkflowExecutionTimeout = converted
	}
	{
		converted, err := durationFromProto(ctx, proto.GetWorkflowRunTimeout())
		if err != nil {
			return value, err
		}
		value.WorkflowRunTimeout = converted
	}
	{
		converted, err := durationFromProto(ctx, proto.GetWorkflowTaskTimeout())
		if err != nil {
			return value, err
		}
		value.WorkflowTaskTimeout = converted
	}
	{
		converted := enums.WorkflowIdReusePolicy(int32(proto.GetWorkflowIdReusePolicy()))
		value.WorkflowIDReusePolicy = &converted
	}
	{
		converted := enums.WorkflowIdConflictPolicy(int32(proto.GetWorkflowIdConflictPolicy()))
		value.WorkflowIDConflictPolicy = &converted
	}
	{
		converted, err := retryPolicyFromProto(ctx, proto.GetRetryPolicy())
		if err != nil {
			return value, err
		}
		value.RetryPolicy = converted
	}
	{
		converted := proto.GetCronSchedule()
		value.CronSchedule = &converted
	}
	{
		converted, err := memoFromProto(ctx, proto.GetMemo())
		if err != nil {
			return value, err
		}
		value.Memo = converted
	}
	{
		converted, err := searchAttributesFromProto(ctx, proto.GetSearchAttributes())
		if err != nil {
			return value, err
		}
		if converted != nil {
			value.TypedSearchAttributes = *converted
		}
	}
	{
		converted, err := priorityFromProto(ctx, proto.GetPriority())
		if err != nil {
			return value, err
		}
		value.Priority = converted
	}
	{
		converted, err := versioningOverrideFromProto(ctx, proto.GetVersioningOverride())
		if err != nil {
			return value, err
		}
		if converted != nil {
			value.VersioningOverride = *converted
		}
	}
	{
		converted, err := durationFromProto(ctx, proto.GetWorkflowStartDelay())
		if err != nil {
			return value, err
		}
		value.StartDelay = converted
	}
	if proto.GetUserMetadata() != nil {
		converted, err := userMetadataFromProto(ctx, proto.GetUserMetadata())
		if err != nil {
			return value, err
		}
		value.UserMetadata = &converted
	}
	{
		converted, err := headerFromProto(ctx, proto.GetHeader())
		if err != nil {
			return value, err
		}
		value.Headers = converted
	}
	return value, nil
}

// --- Operations (internal) ---

func signalWithStartWorkflow(ctx workflow.Context, request signalWithStartWorkflowRequest) workflow.Future {
	requestProto, err := request.toProto(ctx)
	if err != nil {
		result, resultSettable := workflow.NewFuture(ctx)
		resultSettable.SetError(err)
		return result
	}
	c := newSystemNexusClient("temporal.api.workflowservice.v1.WorkflowService")
	fut := c.ExecuteOperation(ctx, "SignalWithStartWorkflowExecution", requestProto, workflow.NexusOperationOptions{})
	result, resultSettable := workflow.NewFuture(ctx)
	workflow.Go(ctx, func(ctx workflow.Context) {
		var result workflowservice.SignalWithStartWorkflowExecutionResponse
		if err := fut.Get(ctx, &result); err != nil {
			resultSettable.SetError(err)
			return
		}
		value, err := signalWithStartWorkflowResponseFromProto(ctx, &result)
		if err != nil {
			resultSettable.SetError(err)
			return
		}
		resultSettable.Set(value, nil)
	})
	return result
}

// --- Operations (public API) ---

type UserMetadata struct {
	// StaticSummary - Single-line fixed summary for the workflow execution that may appear
	// in UI and CLI. This can be in single-line Temporal Markdown format.
	//
	// Optional.
	StaticSummary string
	// StaticDetails - General fixed details for the workflow execution that may appear in
	// UI and CLI. This can be in Temporal Markdown format and can span multiple lines.
	// This value is fixed on the workflow execution and cannot be updated.
	//
	// Optional.
	StaticDetails string
}

func (m UserMetadata) toProto(ctx workflow.Context) (*sdk.UserMetadata, error) {
	message := &sdk.UserMetadata{}
	{
		converted, err := payloadToProto(ctx, m.StaticSummary)
		if err != nil {
			return nil, err
		}
		message.Summary = converted
	}
	{
		converted, err := payloadToProto(ctx, m.StaticDetails)
		if err != nil {
			return nil, err
		}
		message.Details = converted
	}
	return message, nil
}

func userMetadataFromProto(ctx workflow.Context, proto *sdk.UserMetadata) (UserMetadata, error) {
	value := UserMetadata{}
	if proto.GetSummary() != nil {
		converted, err := payloadFromProto(ctx, proto.GetSummary())
		if err != nil {
			return value, err
		}
		typed, ok := converted.(string)
		if !ok {
			return value, fmt.Errorf("nexgen decoded field StaticSummary has unexpected type %T", converted)
		}
		value.StaticSummary = typed
	}
	if proto.GetDetails() != nil {
		converted, err := payloadFromProto(ctx, proto.GetDetails())
		if err != nil {
			return value, err
		}
		typed, ok := converted.(string)
		if !ok {
			return value, fmt.Errorf("nexgen decoded field StaticDetails has unexpected type %T", converted)
		}
		value.StaticDetails = typed
	}
	return value, nil
}

type SignalWithStartWorkflowResponse struct {
	// RunID - Run ID of the started workflow.
	//
	// Optional.
	RunID *string
	// Started - Whether the workflow was started.
	//
	// Optional.
	Started *bool
}

func (m SignalWithStartWorkflowResponse) toProto(ctx workflow.Context) (*workflowservice.SignalWithStartWorkflowExecutionResponse, error) {
	message := &workflowservice.SignalWithStartWorkflowExecutionResponse{}
	if m.RunID != nil {
		message.RunId = (*m.RunID)
	}
	if m.Started != nil {
		message.Started = (*m.Started)
	}
	return message, nil
}

func signalWithStartWorkflowResponseFromProto(ctx workflow.Context, proto *workflowservice.SignalWithStartWorkflowExecutionResponse) (SignalWithStartWorkflowResponse, error) {
	value := SignalWithStartWorkflowResponse{}
	{
		converted := proto.GetRunId()
		value.RunID = &converted
	}
	{
		converted := proto.GetStarted()
		value.Started = &converted
	}
	return value, nil
}

type SignalWithStartWorkflowOptions struct {
	// ID - Unique identifier for the workflow execution. Must be nonempty.
	//
	// Required.
	ID string
	// TaskQueue - Task queue to run the workflow on.
	//
	// Required.
	TaskQueue string
	// WorkflowExecutionTimeout - Total workflow execution timeout, including retries and
	// continue-as-new. Defaults to unlimited.
	//
	// Optional.
	WorkflowExecutionTimeout time.Duration
	// WorkflowRunTimeout - Timeout of a single workflow run. Defaults to the workflow
	// execution timeout.
	//
	// Optional.
	WorkflowRunTimeout time.Duration
	// WorkflowTaskTimeout - Timeout of a single workflow task. Defaults to 10 seconds.
	//
	// Optional.
	WorkflowTaskTimeout time.Duration
	// WorkflowIDReusePolicy - Behavior when a closed workflow with the same ID exists.
	// Default is allow-duplicate.
	//
	// Optional.
	WorkflowIDReusePolicy enums.WorkflowIdReusePolicy
	// WorkflowIDConflictPolicy - Behavior when a workflow is currently running with the
	// same ID. Set to use-existing for idempotent deduplication on workflow ID. Cannot be
	// set if id-reuse-policy is terminate-if-running. Defaults to use-existing.
	//
	// Optional.
	WorkflowIDConflictPolicy enums.WorkflowIdConflictPolicy
	// RetryPolicy - Retry policy for the workflow.
	//
	// Optional.
	RetryPolicy *temporal.RetryPolicy
	// CronSchedule - Cron schedule for recurring workflow executions. See
	// https://docs.temporal.io/cron-job.
	//
	// Optional.
	CronSchedule string
	// Memo - Memo for the workflow.
	//
	// Optional.
	Memo map[string]any
	// TypedSearchAttributes - Typed search attributes for the workflow.
	//
	// Optional.
	TypedSearchAttributes temporal.SearchAttributes
	// Priority - Priority of the workflow execution.
	//
	// Optional.
	Priority *temporal.Priority
	// VersioningOverride - Override for workflow versioning behavior.
	//
	// Optional.
	VersioningOverride client.VersioningOverride
	// StartDelay - Amount of time to wait before starting the workflow. This does not work
	// with cron-schedule.
	//
	// Optional.
	StartDelay time.Duration
	// UserMetadata - Static metadata for the workflow execution.
	//
	// Optional.
	UserMetadata
}

// Signal a workflow, starting it first if needed.
//
// Input signal: Signal name to send with the start request.
// Input signalArg: Arguments for the signal.
// Input workflow: Workflow function identifying the workflow to start.
// Input args: Arguments for the workflow.
//
// Returns: A workflow handle to the started workflow.
func SignalWithStartWorkflow(
	ctx workflow.Context,
	opts SignalWithStartWorkflowOptions,
	signal string,
	signalArg any,
	workflow any,
	args ...any,
) workflow.Future {
	var workflowExecutionTimeout *time.Duration
	if opts.WorkflowExecutionTimeout != 0 {
		workflowExecutionTimeout = &opts.WorkflowExecutionTimeout
	}
	var workflowRunTimeout *time.Duration
	if opts.WorkflowRunTimeout != 0 {
		workflowRunTimeout = &opts.WorkflowRunTimeout
	}
	var workflowTaskTimeout *time.Duration
	if opts.WorkflowTaskTimeout != 0 {
		workflowTaskTimeout = &opts.WorkflowTaskTimeout
	}
	var workflowIDReusePolicy *enums.WorkflowIdReusePolicy
	if opts.WorkflowIDReusePolicy != 0 {
		workflowIDReusePolicy = &opts.WorkflowIDReusePolicy
	}
	var workflowIDConflictPolicy *enums.WorkflowIdConflictPolicy
	if opts.WorkflowIDConflictPolicy != 0 {
		workflowIDConflictPolicy = &opts.WorkflowIDConflictPolicy
	}
	var cronSchedule *string
	if opts.CronSchedule != "" {
		cronSchedule = &opts.CronSchedule
	}
	var startDelay *time.Duration
	if opts.StartDelay != 0 {
		startDelay = &opts.StartDelay
	}
	workflowName := workflowFunctionName(ctx, workflow)
	return signalWithStartWorkflow(ctx, signalWithStartWorkflowRequest{
		Workflow:                 workflowName,
		Args:                     args,
		ID:                       opts.ID,
		TaskQueue:                opts.TaskQueue,
		Signal:                   signal,
		SignalArgs:               []any{signalArg},
		WorkflowExecutionTimeout: workflowExecutionTimeout,
		WorkflowRunTimeout:       workflowRunTimeout,
		WorkflowTaskTimeout:      workflowTaskTimeout,
		WorkflowIDReusePolicy:    workflowIDReusePolicy,
		WorkflowIDConflictPolicy: workflowIDConflictPolicy,
		RetryPolicy:              opts.RetryPolicy,
		CronSchedule:             cronSchedule,
		Memo:                     opts.Memo,
		TypedSearchAttributes:    opts.TypedSearchAttributes,
		Priority:                 opts.Priority,
		VersioningOverride:       opts.VersioningOverride,
		StartDelay:               startDelay,
		UserMetadata:             &opts.UserMetadata,
	})
}

// Signal a workflow, starting it first if needed.
//
// Input signal: Signal name to send with the start request.
// Input signalArg: Arguments for the signal.
// Input workflow: Workflow function identifying the workflow to start.
// Input args: Arguments for the workflow.
//
// Returns: A workflow handle to the started workflow.
func SignalWithStartWorkflowTyped[WorkflowArg any, WorkflowResult any](
	ctx workflow.Context,
	opts SignalWithStartWorkflowOptions,
	signal string,
	signalArg any,
	workflow func(workflow.Context, WorkflowArg) WorkflowResult,
	arg WorkflowArg,
) workflow.Future {
	var workflowExecutionTimeout *time.Duration
	if opts.WorkflowExecutionTimeout != 0 {
		workflowExecutionTimeout = &opts.WorkflowExecutionTimeout
	}
	var workflowRunTimeout *time.Duration
	if opts.WorkflowRunTimeout != 0 {
		workflowRunTimeout = &opts.WorkflowRunTimeout
	}
	var workflowTaskTimeout *time.Duration
	if opts.WorkflowTaskTimeout != 0 {
		workflowTaskTimeout = &opts.WorkflowTaskTimeout
	}
	var workflowIDReusePolicy *enums.WorkflowIdReusePolicy
	if opts.WorkflowIDReusePolicy != 0 {
		workflowIDReusePolicy = &opts.WorkflowIDReusePolicy
	}
	var workflowIDConflictPolicy *enums.WorkflowIdConflictPolicy
	if opts.WorkflowIDConflictPolicy != 0 {
		workflowIDConflictPolicy = &opts.WorkflowIDConflictPolicy
	}
	var cronSchedule *string
	if opts.CronSchedule != "" {
		cronSchedule = &opts.CronSchedule
	}
	var startDelay *time.Duration
	if opts.StartDelay != 0 {
		startDelay = &opts.StartDelay
	}
	workflowName := workflowFunctionName(ctx, workflow)
	return signalWithStartWorkflow(ctx, signalWithStartWorkflowRequest{
		Workflow:                 workflowName,
		Args:                     []any{arg},
		ID:                       opts.ID,
		TaskQueue:                opts.TaskQueue,
		Signal:                   signal,
		SignalArgs:               []any{signalArg},
		WorkflowExecutionTimeout: workflowExecutionTimeout,
		WorkflowRunTimeout:       workflowRunTimeout,
		WorkflowTaskTimeout:      workflowTaskTimeout,
		WorkflowIDReusePolicy:    workflowIDReusePolicy,
		WorkflowIDConflictPolicy: workflowIDConflictPolicy,
		RetryPolicy:              opts.RetryPolicy,
		CronSchedule:             cronSchedule,
		Memo:                     opts.Memo,
		TypedSearchAttributes:    opts.TypedSearchAttributes,
		Priority:                 opts.Priority,
		VersioningOverride:       opts.VersioningOverride,
		StartDelay:               startDelay,
		UserMetadata:             &opts.UserMetadata,
	})
}
