<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <Nullable>enable</Nullable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Nexgen.DotNetExamples.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="../wit/workflow-service/Models.cs" Link="GeneratedWorkflowService/Models.cs" />
    <Compile Include="../wit/workflow-service/Operations.cs" Link="GeneratedWorkflowService/Operations.cs" />
    <Compile Include="../wit/workflow-service/Services.cs" Link="GeneratedWorkflowService/Services.cs" />
    <Compile Include="../TemporalSupport/*.cs" Link="TemporalSupport/%(Filename)%(Extension)" />
    <Compile Include="../wit/type-roundtrip/Models.cs" Link="GeneratedTypeRoundtrip/Models.cs" />
    <Compile Include="../wit/notification-service/Models.cs" Link="GeneratedNotificationService/Models.cs" />
    <Compile Include="../wit/proto-oneof/Models.cs" Link="GeneratedProtoOneof/Models.cs" />
    <Compile Include="../wit/proto-generic/Models.cs" Link="GeneratedProtoGeneric/Models.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>
</Project>
