// Generated by nexgen latest. DO NOT EDIT!

export function requiredField<T>(
  value: T | null | undefined,
  owner: string,
  field: string,
): T {
  if (value == null) {
    throw new Error(`missing required field ${owner}.${field}`);
  }
  return value;
}

export interface ExecuteFunctionResult {
  value: string;
}

export interface ExecuteFunctionRequest<
  FunctionFn extends (name: string, enabled: boolean) => string = (
    name: string,
    enabled: boolean,
  ) => string,
> {
  function_: FunctionFn;
  /**
   * The name argument for the function.
   */
  name: string;
  /**
   * The enabled argument for the function.
   */
  enabled: boolean;
}

export interface ExecuteCountedFunctionResult {
  value: string;
}

export interface ExecuteCountedFunctionRequest<
  FunctionFn extends (name: string, count: number) => string = (
    name: string,
    count: number,
  ) => string,
> {
  function_: FunctionFn;
  /**
   * The name argument for the function.
   */
  name: string;
  /**
   * The count argument for the function.
   */
  count: number;
}

export interface ExecuteNamedFunctionResult {
  value: string;
}

export interface ExecuteNamedFunctionRequest<
  FunctionFn extends (name: string, enabled: boolean) => string = (
    name: string,
    enabled: boolean,
  ) => string,
> {
  function_: string | FunctionFn;
  /**
   * The name argument for the function.
   */
  name: string;
  /**
   * The enabled argument for the function.
   */
  enabled: boolean;
}

export interface ExecuteVarargsFunctionResult {
  value: string;
}

export type ReplaceExecuteVarargsFunctionRequest<Base, New> = Omit<
  Base,
  "args" | "function_"
> &
  New;

export type ExecuteVarargsFunctionRequest<
  FunctionFn extends (...args: any[]) => string = (...args: any[]) => string,
> = ReplaceExecuteVarargsFunctionRequest<
  {
    function_: FunctionFn;
    /**
     * Arguments for function_.
     */
    args?: ReadonlyArray<unknown> | Readonly<Parameters<FunctionFn>>;
  },
  {
    function_: FunctionFn;
  } & (Parameters<FunctionFn> extends [any, ...any[]]
    ? {
        /**
         * Arguments for function_.
         */
        args: Parameters<FunctionFn> | Readonly<Parameters<FunctionFn>>;
      }
    : {
        /**
         * Arguments for function_.
         */
        args?: Parameters<FunctionFn> | Readonly<Parameters<FunctionFn>>;
      })
>;

export interface ExecuteNamedVarargsFunctionResult {
  value: string;
}

export type ReplaceExecuteNamedVarargsFunctionRequest<Base, New> = Omit<
  Base,
  "args" | "function_"
> &
  New;

export type ExecuteNamedVarargsFunctionRequest<
  FunctionFn extends (...args: any[]) => string = (...args: any[]) => string,
> = ReplaceExecuteNamedVarargsFunctionRequest<
  {
    function_: string | FunctionFn;
    /**
     * Arguments for function_.
     */
    args?: ReadonlyArray<unknown> | Readonly<Parameters<FunctionFn>>;
  },
  | {
      function_: string;
      /**
       * Arguments for function_.
       */
      args?: ReadonlyArray<unknown>;
    }
  | ({
      function_: FunctionFn;
    } & (Parameters<FunctionFn> extends [any, ...any[]]
      ? {
          /**
           * Arguments for function_.
           */
          args: Parameters<FunctionFn> | Readonly<Parameters<FunctionFn>>;
        }
      : {
          /**
           * Arguments for function_.
           */
          args?: Parameters<FunctionFn> | Readonly<Parameters<FunctionFn>>;
        }))
>;
