// Generated by nexgen latest. DO NOT EDIT!

import * as nexus from "nexus-rpc";
import type {
  ExecuteFunctionResult,
  ExecuteFunctionRequest,
  ExecuteCountedFunctionResult,
  ExecuteCountedFunctionRequest,
  ExecuteNamedFunctionResult,
  ExecuteNamedFunctionRequest,
  ExecuteVarargsFunctionResult,
  ExecuteVarargsFunctionRequest,
  ExecuteNamedVarargsFunctionResult,
  ExecuteNamedVarargsFunctionRequest,
} from "./models";

export const functionExecution = nexus.service("FunctionExecution", {
  executeFunction: nexus.operation<ExecuteFunctionRequest, ExecuteFunctionResult>({
    name: "ExecuteFunction",
  }),
  executeCountedFunction: nexus.operation<
    ExecuteCountedFunctionRequest,
    ExecuteCountedFunctionResult
  >({ name: "ExecuteCountedFunction" }),
  executeNamedFunction: nexus.operation<
    ExecuteNamedFunctionRequest,
    ExecuteNamedFunctionResult
  >({ name: "ExecuteNamedFunction" }),
  executeVarargsFunction: nexus.operation<
    ExecuteVarargsFunctionRequest,
    ExecuteVarargsFunctionResult
  >({ name: "ExecuteVarargsFunction" }),
  executeNamedVarargsFunction: nexus.operation<
    ExecuteNamedVarargsFunctionRequest,
    ExecuteNamedVarargsFunctionResult
  >({ name: "ExecuteNamedVarargsFunction" }),
});

export const operationRegistry = [
  {
    service: "FunctionExecution",
    operation: "ExecuteFunction",
  },
  {
    service: "FunctionExecution",
    operation: "ExecuteCountedFunction",
  },
  {
    service: "FunctionExecution",
    operation: "ExecuteNamedFunction",
  },
  {
    service: "FunctionExecution",
    operation: "ExecuteVarargsFunction",
  },
  {
    service: "FunctionExecution",
    operation: "ExecuteNamedVarargsFunction",
  },
] as const;
