// Generated by nexgen latest. DO NOT EDIT!

import * as nexus from "nexus-rpc";
import type { GenericResponse, GenericRequest } from "./models";

export const genericModelService = nexus.service("GenericModelService", {
  complete: nexus.operation<GenericRequest, GenericResponse<any, any, any>>({
    name: "Complete",
  }),
});

export const operationRegistry = [
  {
    service: "GenericModelService",
    operation: "Complete",
  },
] as const;
