// Generated by nexgen latest. DO NOT EDIT!

import * as nexus from "nexus-rpc";
import type { GenericResponse, GenericRequest } from "./models";

export const genericModelService = nexus.service("GenericModelService", {
  complete: nexus.operation<GenericRequest, GenericResponse<any, any, any>>({
    name: "Complete",
  }),
});

export const operationRegistry = [
  {
    service: "GenericModelService",
    operation: "Complete",
    inputType: "generic-model-service.generic-request",
    outputType: "generic-model-service.generic-response",
    inputPayloadVisitor: "walkgeneric-request",
    outputPayloadVisitor: "walkgeneric-response",
  },
] as const;
