# Generated by nexgen. DO NOT EDIT!

from __future__ import annotations

from nexusrpc import Operation, service
import typing

from .models import (
    GenericRequest,
    GenericResponse,
    ReuseCompletionResult,
)


@service
class GenericModelService:
    complete: Operation[
        GenericRequest[typing.Any],
        GenericResponse[typing.Any, typing.Any, typing.Any],
    ] = Operation(name="Complete")

    reuse_complete: Operation[
        GenericRequest[typing.Any],
        ReuseCompletionResult[typing.Any],
    ] = Operation(name="ReuseComplete")
