// Code generated by nexgen latest. DO NOT EDIT.

package typeroundtrip

import (
	"context"
	"errors"
	"time"

	activity "go.temporal.io/api/activity/v1"
	command "go.temporal.io/api/command/v1"
	"go.temporal.io/sdk/converter"
	"go.temporal.io/sdk/temporal"
	"go.temporal.io/sdk/workflow"
)

// --- Operations (internal) ---

func activityOptionsOperation(ctx workflow.Context, request ActivityOptions) workflow.Future {
	c := workflow.NewNexusClient("temporal-system", "TypeRoundtripService")
	fut := c.ExecuteOperation(ctx, "ActivityOptionsOperation", request, workflow.NexusOperationOptions{})
	result, resultSettable := workflow.NewFuture(ctx)
	workflow.Go(ctx, func(ctx workflow.Context) {
		var value ActivityOptions
		if err := fut.Get(ctx, &value); err != nil {
			resultSettable.SetError(err)
			return
		}
		resultSettable.Set(value, nil)
	})
	return result
}

func failureOperation(ctx workflow.Context, request FailureContainer) workflow.Future {
	c := workflow.NewNexusClient("temporal-system", "TypeRoundtripService")
	fut := c.ExecuteOperation(ctx, "FailureOperation", request, workflow.NexusOperationOptions{})
	result, resultSettable := workflow.NewFuture(ctx)
	workflow.Go(ctx, func(ctx workflow.Context) {
		var value FailureContainer
		if err := fut.Get(ctx, &value); err != nil {
			resultSettable.SetError(err)
			return
		}
		resultSettable.Set(value, nil)
	})
	return result
}

// --- Operations (public API) ---

type ActivityOptions struct {
	// TaskQueue - Optional.
	TaskQueue *string
	// RetryPolicy - Required.
	RetryPolicy temporal.RetryPolicy
	// ScheduleToCloseTimeout - Optional.
	ScheduleToCloseTimeout *time.Duration
	// Priority - Optional.
	Priority *temporal.Priority
}

func (m ActivityOptions) toProto(ctx workflow.Context) (*activity.ActivityOptions, error) {
	message := &activity.ActivityOptions{}
	{
		converted, err := taskQueueToProto(ctx, m.TaskQueue)
		if err != nil {
			return nil, err
		}
		message.TaskQueue = converted
	}
	{
		converted, err := retryPolicyToProto(ctx, &m.RetryPolicy)
		if err != nil {
			return nil, err
		}
		message.RetryPolicy = converted
	}
	{
		converted, err := durationToProto(ctx, m.ScheduleToCloseTimeout)
		if err != nil {
			return nil, err
		}
		message.ScheduleToCloseTimeout = converted
	}
	{
		converted, err := priorityToProto(ctx, m.Priority)
		if err != nil {
			return nil, err
		}
		message.Priority = converted
	}
	return message, nil
}

func activityOptionsFromProto(ctx workflow.Context, proto *activity.ActivityOptions) (ActivityOptions, error) {
	value := ActivityOptions{}
	{
		converted, err := taskQueueFromProto(ctx, proto.GetTaskQueue())
		if err != nil {
			return value, err
		}
		value.TaskQueue = converted
	}
	{
		converted, err := retryPolicyFromProto(ctx, proto.GetRetryPolicy())
		if err != nil {
			return value, err
		}
		if converted != nil {
			value.RetryPolicy = *converted
		}
	}
	{
		converted, err := durationFromProto(ctx, proto.GetScheduleToCloseTimeout())
		if err != nil {
			return value, err
		}
		value.ScheduleToCloseTimeout = converted
	}
	{
		converted, err := priorityFromProto(ctx, proto.GetPriority())
		if err != nil {
			return value, err
		}
		value.Priority = converted
	}
	return value, nil
}

var errActivityOptionsNeedsWorkflowContext = errors.New("nexgen: ActivityOptions can only be converted inside a workflow")

var activityOptionsTransferTypeConverter, activityOptionsTransferTypeConverterErr = converter.NewContextualTransferTypeConverter[ActivityOptions, activity.ActivityOptions](
	func(context.Context, *ActivityOptions) (*activity.ActivityOptions, error) {
		return nil, errActivityOptionsNeedsWorkflowContext
	},
	func(context.Context, *activity.ActivityOptions, *ActivityOptions) error {
		return errActivityOptionsNeedsWorkflowContext
	},
	func(ctx workflow.Context, m *ActivityOptions) (*activity.ActivityOptions, error) {
		return m.toProto(ctx)
	},
	func(ctx workflow.Context, message *activity.ActivityOptions, out *ActivityOptions) error {
		value, err := activityOptionsFromProto(ctx, message)
		if err != nil {
			return err
		}
		*out = value
		return nil
	},
)

func (ActivityOptions) TransferTypeConverter() (converter.TransferTypeConverter, error) {
	return activityOptionsTransferTypeConverter, activityOptionsTransferTypeConverterErr
}

type FailureContainer struct {
	// Failure - Optional.
	Failure error
}

func (m FailureContainer) toProto(ctx workflow.Context) (*command.FailWorkflowExecutionCommandAttributes, error) {
	message := &command.FailWorkflowExecutionCommandAttributes{}
	{
		converted, err := failureToProto(ctx, m.Failure)
		if err != nil {
			return nil, err
		}
		message.Failure = converted
	}
	return message, nil
}

func failureContainerFromProto(ctx workflow.Context, proto *command.FailWorkflowExecutionCommandAttributes) (FailureContainer, error) {
	value := FailureContainer{}
	{
		converted, err := failureFromProto(ctx, proto.GetFailure())
		if err != nil {
			return value, err
		}
		value.Failure = converted
	}
	return value, nil
}

var errFailureContainerNeedsWorkflowContext = errors.New("nexgen: FailureContainer can only be converted inside a workflow")

var failureContainerTransferTypeConverter, failureContainerTransferTypeConverterErr = converter.NewContextualTransferTypeConverter[FailureContainer, command.FailWorkflowExecutionCommandAttributes](
	func(context.Context, *FailureContainer) (*command.FailWorkflowExecutionCommandAttributes, error) {
		return nil, errFailureContainerNeedsWorkflowContext
	},
	func(context.Context, *command.FailWorkflowExecutionCommandAttributes, *FailureContainer) error {
		return errFailureContainerNeedsWorkflowContext
	},
	func(ctx workflow.Context, m *FailureContainer) (*command.FailWorkflowExecutionCommandAttributes, error) {
		return m.toProto(ctx)
	},
	func(ctx workflow.Context, message *command.FailWorkflowExecutionCommandAttributes, out *FailureContainer) error {
		value, err := failureContainerFromProto(ctx, message)
		if err != nil {
			return err
		}
		*out = value
		return nil
	},
)

func (FailureContainer) TransferTypeConverter() (converter.TransferTypeConverter, error) {
	return failureContainerTransferTypeConverter, failureContainerTransferTypeConverterErr
}

type ActivityOptionsOperationOptions struct {
	// TaskQueue - Optional.
	TaskQueue string
	// RetryPolicy - Required.
	RetryPolicy temporal.RetryPolicy
	// ScheduleToCloseTimeout - Optional.
	ScheduleToCloseTimeout time.Duration
	// Priority - Optional.
	Priority *temporal.Priority
}

func ActivityOptionsOperation(ctx workflow.Context, opts ActivityOptionsOperationOptions) workflow.Future {
	var taskQueue *string
	if opts.TaskQueue != "" {
		taskQueue = &opts.TaskQueue
	}
	var scheduleToCloseTimeout *time.Duration
	if opts.ScheduleToCloseTimeout != 0 {
		scheduleToCloseTimeout = &opts.ScheduleToCloseTimeout
	}
	return activityOptionsOperation(ctx, ActivityOptions{
		TaskQueue:              taskQueue,
		RetryPolicy:            opts.RetryPolicy,
		ScheduleToCloseTimeout: scheduleToCloseTimeout,
		Priority:               opts.Priority,
	})
}

type FailureOperationOptions struct {
	// Failure - Optional.
	Failure error
}

func FailureOperation(ctx workflow.Context, opts FailureOperationOptions) workflow.Future {
	return failureOperation(ctx, FailureContainer{
		Failure: opts.Failure,
	})
}
