# Generated by nexgen latest. DO NOT EDIT!

from __future__ import annotations

import dataclasses
import typing_extensions
import datetime
import temporalio.api.common.v1.message_pb2
import temporalio.api.workflowservice.v1.request_response_pb2
import temporalio.converter

import temporal_support as _support


@dataclasses.dataclass(slots=True)
class StartWorkflowRequest:
    workflow: str
    workflow_id: str
    task_queue: str
    workflow_start_delay: datetime.timedelta | None = None
    namespace: str = dataclasses.field(default_factory=_support.workflow_namespace)


class _StartWorkflowRequestTransferTypeConverter(
    temporalio.converter.TransferTypeConverter[
        StartWorkflowRequest,
        temporalio.api.workflowservice.v1.request_response_pb2.StartWorkflowExecutionRequest,
    ]
):
    transfer_type: (
        type[
            temporalio.api.workflowservice.v1.request_response_pb2.StartWorkflowExecutionRequest
        ]
        | None
    ) = temporalio.api.workflowservice.v1.request_response_pb2.StartWorkflowExecutionRequest

    @typing_extensions.override
    def from_transfer_type(
        self,
        value: temporalio.api.workflowservice.v1.request_response_pb2.StartWorkflowExecutionRequest,
        type_hint: type[StartWorkflowRequest],
    ) -> StartWorkflowRequest:
        if not value.HasField("workflow_type"):
            raise ValueError("missing required field StartWorkflowRequest.workflow")
        workflow = _support.workflow_type_from_proto(value.workflow_type)
        if not value.workflow_id:
            raise ValueError("missing required field StartWorkflowRequest.workflow_id")
        workflow_id = value.workflow_id
        if not value.HasField("task_queue"):
            raise ValueError("missing required field StartWorkflowRequest.task_queue")
        task_queue = _support.task_queue_from_proto(value.task_queue)
        return StartWorkflowRequest(
            workflow=workflow,
            workflow_id=workflow_id,
            task_queue=task_queue,
            workflow_start_delay=_support.duration_from_proto(
                value.workflow_start_delay
            )
            if value.HasField("workflow_start_delay")
            else None,
            namespace=value.namespace,
        )

    @typing_extensions.override
    def to_transfer_type(
        self,
        value: StartWorkflowRequest,
    ) -> temporalio.api.workflowservice.v1.request_response_pb2.StartWorkflowExecutionRequest:
        message = temporalio.api.workflowservice.v1.request_response_pb2.StartWorkflowExecutionRequest()
        message.workflow_type.CopyFrom(_support.workflow_type_to_proto(value.workflow))
        message.workflow_id = value.workflow_id
        message.task_queue.CopyFrom(_support.task_queue_to_proto(value.task_queue))
        if value.workflow_start_delay is not None:
            message.workflow_start_delay.CopyFrom(
                _support.duration_to_proto(value.workflow_start_delay)
            )
        message.namespace = value.namespace
        return message


temporalio.converter.transfer_type_convertible(
    _StartWorkflowRequestTransferTypeConverter
)(StartWorkflowRequest)  # pyright: ignore[reportUnusedCallResult]


@dataclasses.dataclass(slots=True)
class StartWorkflowResult:
    run_id: str | None = None


class _StartWorkflowResultTransferTypeConverter(
    temporalio.converter.TransferTypeConverter[
        StartWorkflowResult,
        temporalio.api.workflowservice.v1.request_response_pb2.StartWorkflowExecutionResponse,
    ]
):
    transfer_type: (
        type[
            temporalio.api.workflowservice.v1.request_response_pb2.StartWorkflowExecutionResponse
        ]
        | None
    ) = temporalio.api.workflowservice.v1.request_response_pb2.StartWorkflowExecutionResponse

    @typing_extensions.override
    def from_transfer_type(
        self,
        value: temporalio.api.workflowservice.v1.request_response_pb2.StartWorkflowExecutionResponse,
        type_hint: type[StartWorkflowResult],
    ) -> StartWorkflowResult:
        return StartWorkflowResult(
            run_id=value.run_id if bool(value.run_id) else None,
        )

    @typing_extensions.override
    def to_transfer_type(
        self,
        value: StartWorkflowResult,
    ) -> temporalio.api.workflowservice.v1.request_response_pb2.StartWorkflowExecutionResponse:
        message = temporalio.api.workflowservice.v1.request_response_pb2.StartWorkflowExecutionResponse()
        if value.run_id is not None:
            message.run_id = value.run_id
        return message


temporalio.converter.transfer_type_convertible(
    _StartWorkflowResultTransferTypeConverter
)(StartWorkflowResult)  # pyright: ignore[reportUnusedCallResult]


@dataclasses.dataclass(slots=True, kw_only=True)
class CancelWorkflowRequest:
    namespace: str = dataclasses.field(default_factory=_support.workflow_namespace)
    workflow_execution: WorkflowExecution
    reason: str | None = None


class _CancelWorkflowRequestTransferTypeConverter(
    temporalio.converter.TransferTypeConverter[
        CancelWorkflowRequest,
        temporalio.api.workflowservice.v1.request_response_pb2.RequestCancelWorkflowExecutionRequest,
    ]
):
    transfer_type: (
        type[
            temporalio.api.workflowservice.v1.request_response_pb2.RequestCancelWorkflowExecutionRequest
        ]
        | None
    ) = temporalio.api.workflowservice.v1.request_response_pb2.RequestCancelWorkflowExecutionRequest

    @typing_extensions.override
    def from_transfer_type(
        self,
        value: temporalio.api.workflowservice.v1.request_response_pb2.RequestCancelWorkflowExecutionRequest,
        type_hint: type[CancelWorkflowRequest],
    ) -> CancelWorkflowRequest:
        if not value.HasField("workflow_execution"):
            raise ValueError(
                "missing required field CancelWorkflowRequest.workflow_execution"
            )
        workflow_execution = (
            _WorkflowExecutionTransferTypeConverter().from_transfer_type(
                value.workflow_execution, WorkflowExecution
            )
        )
        return CancelWorkflowRequest(
            namespace=value.namespace,
            workflow_execution=workflow_execution,
            reason=value.reason if bool(value.reason) else None,
        )

    @typing_extensions.override
    def to_transfer_type(
        self,
        value: CancelWorkflowRequest,
    ) -> temporalio.api.workflowservice.v1.request_response_pb2.RequestCancelWorkflowExecutionRequest:
        message = temporalio.api.workflowservice.v1.request_response_pb2.RequestCancelWorkflowExecutionRequest()
        message.namespace = value.namespace
        message.workflow_execution.CopyFrom(
            _WorkflowExecutionTransferTypeConverter().to_transfer_type(
                value.workflow_execution
            )
        )
        if value.reason is not None:
            message.reason = value.reason
        return message


temporalio.converter.transfer_type_convertible(
    _CancelWorkflowRequestTransferTypeConverter
)(CancelWorkflowRequest)  # pyright: ignore[reportUnusedCallResult]


@dataclasses.dataclass(slots=True)
class WorkflowExecution:
    workflow_id: str
    run_id: str | None = None


class _WorkflowExecutionTransferTypeConverter(
    temporalio.converter.TransferTypeConverter[
        WorkflowExecution, temporalio.api.common.v1.message_pb2.WorkflowExecution
    ]
):
    transfer_type: (
        type[temporalio.api.common.v1.message_pb2.WorkflowExecution] | None
    ) = temporalio.api.common.v1.message_pb2.WorkflowExecution

    @typing_extensions.override
    def from_transfer_type(
        self,
        value: temporalio.api.common.v1.message_pb2.WorkflowExecution,
        type_hint: type[WorkflowExecution],
    ) -> WorkflowExecution:
        if not value.workflow_id:
            raise ValueError("missing required field WorkflowExecution.workflow_id")
        workflow_id = value.workflow_id
        return WorkflowExecution(
            workflow_id=workflow_id,
            run_id=value.run_id if bool(value.run_id) else None,
        )

    @typing_extensions.override
    def to_transfer_type(
        self,
        value: WorkflowExecution,
    ) -> temporalio.api.common.v1.message_pb2.WorkflowExecution:
        message = temporalio.api.common.v1.message_pb2.WorkflowExecution()
        message.workflow_id = value.workflow_id
        if value.run_id is not None:
            message.run_id = value.run_id
        return message


temporalio.converter.transfer_type_convertible(_WorkflowExecutionTransferTypeConverter)(
    WorkflowExecution
)  # pyright: ignore[reportUnusedCallResult]


@dataclasses.dataclass(slots=True)
class CancelWorkflowResponse:
    pass


class _CancelWorkflowResponseTransferTypeConverter(
    temporalio.converter.TransferTypeConverter[
        CancelWorkflowResponse,
        temporalio.api.workflowservice.v1.request_response_pb2.RequestCancelWorkflowExecutionResponse,
    ]
):
    transfer_type: (
        type[
            temporalio.api.workflowservice.v1.request_response_pb2.RequestCancelWorkflowExecutionResponse
        ]
        | None
    ) = temporalio.api.workflowservice.v1.request_response_pb2.RequestCancelWorkflowExecutionResponse

    @typing_extensions.override
    def from_transfer_type(
        self,
        value: temporalio.api.workflowservice.v1.request_response_pb2.RequestCancelWorkflowExecutionResponse,
        type_hint: type[CancelWorkflowResponse],
    ) -> CancelWorkflowResponse:
        return CancelWorkflowResponse()

    @typing_extensions.override
    def to_transfer_type(
        self,
        value: CancelWorkflowResponse,
    ) -> temporalio.api.workflowservice.v1.request_response_pb2.RequestCancelWorkflowExecutionResponse:
        message = temporalio.api.workflowservice.v1.request_response_pb2.RequestCancelWorkflowExecutionResponse()
        return message


temporalio.converter.transfer_type_convertible(
    _CancelWorkflowResponseTransferTypeConverter
)(CancelWorkflowResponse)  # pyright: ignore[reportUnusedCallResult]
