// Generated by nexgen latest. DO NOT EDIT!

export function requiredField<T>(
  value: T | null | undefined,
  owner: string,
  field: string,
): T {
  if (value == null) {
    throw new Error(`missing required field ${owner}.${field}`);
  }
  return value;
}

export enum UserStatus {
  Active = 0,
  Suspended = 1,
  Deleted = 2,
}

export enum UserCapability {
  ReadProfile = 2 ** 0,
  UpdateEmail = 2 ** 1,
  Deactivate = 2 ** 2,
}

export type NotificationTarget =
  { tag: "email"; value: string } | { tag: "sms"; value: string } | { tag: "none" };

export interface GetUserRequest {
  userId: string;
  consistencyToken?: string;
}

export interface UpdateEmailRequest {
  userId: string;
  email: string;
}

export interface RenameRequest {
  userId: string;
  displayName: string;
}

export interface SetProfileRequest {
  userId: string;
  profile: UserProfile;
}

export interface UserProfile {
  tags?: string[];
  metadata?: Record<string, string>;
  capabilities: UserCapability;
  syncState: { tag: "ok"; value: string } | { tag: "err"; value: string };
  notificationTarget: NotificationTarget;
  address?: PostalAddress;
}

export interface PostalAddress {
  street: string;
  city: string;
  country: string;
  coordinates?: [number, number];
}

export interface RecordSyncRequest {
  userId: string;
  report: SyncReport;
}

export interface SyncReport {
  route?: [number, number][];
  attempts?: ({ tag: "ok"; value: string } | { tag: "err"; value: string })[];
  regionStatus?: Record<
    string,
    { tag: "ok"; value: string } | { tag: "err"; value: string }
  >;
}

export interface DeactivateRequest {
  userId: string;
  reason?: string;
}
