// Generated by nexgen latest. DO NOT EDIT!

import * as nexus from "nexus-rpc";
import type {
  GetUserRequest,
  UpdateEmailRequest,
  RenameRequest,
  SetProfileRequest,
  RecordSyncRequest,
  DeactivateRequest,
} from "./models";
import type { User } from "./resources";

export const typeShowcase = nexus.service("TypeShowcase", {
  getUser: nexus.operation<GetUserRequest, User>({ name: "GetUser" }),
  updateEmail: nexus.operation<UpdateEmailRequest, User>({ name: "UpdateEmail" }),
  rename: nexus.operation<RenameRequest, User>({ name: "Rename" }),
  setProfile: nexus.operation<SetProfileRequest, User>({ name: "SetProfile" }),
  recordSync: nexus.operation<RecordSyncRequest, void>({ name: "RecordSync" }),
  deactivate: nexus.operation<DeactivateRequest, void>({ name: "Deactivate" }),
});

export const operationRegistry = [
  {
    service: "TypeShowcase",
    operation: "GetUser",
    inputType: "type-showcase.get-user-request",
    outputType: "User",
    inputPayloadVisitor: "walkget-user-request",
    outputPayloadVisitor: "walkUser",
  },
  {
    service: "TypeShowcase",
    operation: "UpdateEmail",
    inputType: "type-showcase.update-email-request",
    outputType: "User",
    inputPayloadVisitor: "walkupdate-email-request",
    outputPayloadVisitor: "walkUser",
  },
  {
    service: "TypeShowcase",
    operation: "Rename",
    inputType: "type-showcase.rename-request",
    outputType: "User",
    inputPayloadVisitor: "walkrename-request",
    outputPayloadVisitor: "walkUser",
  },
  {
    service: "TypeShowcase",
    operation: "SetProfile",
    inputType: "type-showcase.set-profile-request",
    outputType: "User",
    inputPayloadVisitor: "walkset-profile-request",
    outputPayloadVisitor: "walkUser",
  },
  {
    service: "TypeShowcase",
    operation: "RecordSync",
    inputType: "type-showcase.record-sync-request",
    outputType: "void",
    inputPayloadVisitor: "walkrecord-sync-request",
    outputPayloadVisitor: "walkvoid",
  },
  {
    service: "TypeShowcase",
    operation: "Deactivate",
    inputType: "type-showcase.deactivate-request",
    outputType: "void",
    inputPayloadVisitor: "walkdeactivate-request",
    outputPayloadVisitor: "walkvoid",
  },
] as const;
