// Generated by nexgen latest. DO NOT EDIT!

import * as nexus from "nexus-rpc";
import type {
  GetUserRequest,
  UpdateEmailRequest,
  RenameRequest,
  SetProfileRequest,
  RecordSyncRequest,
  DeactivateRequest,
} from "./models";
import type { User } from "./resources";

export const typeShowcase = nexus.service("TypeShowcase", {
  getUser: nexus.operation<GetUserRequest, User>({ name: "GetUser" }),
  updateEmail: nexus.operation<UpdateEmailRequest, User>({ name: "UpdateEmail" }),
  rename: nexus.operation<RenameRequest, User>({ name: "Rename" }),
  setProfile: nexus.operation<SetProfileRequest, User>({ name: "SetProfile" }),
  recordSync: nexus.operation<RecordSyncRequest, void>({ name: "RecordSync" }),
  deactivate: nexus.operation<DeactivateRequest, void>({ name: "Deactivate" }),
});

export const operationRegistry = [
  {
    service: "TypeShowcase",
    operation: "GetUser",
  },
  {
    service: "TypeShowcase",
    operation: "UpdateEmail",
  },
  {
    service: "TypeShowcase",
    operation: "Rename",
  },
  {
    service: "TypeShowcase",
    operation: "SetProfile",
  },
  {
    service: "TypeShowcase",
    operation: "RecordSync",
  },
  {
    service: "TypeShowcase",
    operation: "Deactivate",
  },
] as const;
