// Generated by nexgen latest. DO NOT EDIT!

import * as workflow from "@temporalio/workflow";
import { typeShowcase } from "../services";
import type { RenameRequest } from "../models";
import { User } from "../resources";

/**
 * @param request - Request for the operation.
 */
export async function rename(request: RenameRequest): Promise<User> {
  const client = workflow.createNexusServiceClient({
    service: typeShowcase,
    endpoint: "type-showcase",
  });
  const handle = await client.startOperation(typeShowcase.operations.rename, request);
  const resource = await handle.result();
  return new User(
    resource.userId,
    resource.email,
    resource.displayName,
    resource.status,
    resource.profile,
  );
}
