// Code generated by nexgen. DO NOT EDIT.

package typeshowcase

import (
	"go.temporal.io/sdk/workflow"
)

// --- Datatypes ---

type getUserRequest struct {
	UserID           string
	ConsistencyToken *string
}

type updateEmailRequest struct {
	UserID string
	Email  string
}

type renameRequest struct {
	UserID      string
	DisplayName string
}

type setProfileRequest struct {
	UserID  string
	Profile UserProfile
}

type recordSyncRequest struct {
	UserID string
	Report SyncReport
}

type deactivateRequest struct {
	UserID string
	Reason *string
}

// --- Resources ---

type User struct {
	// UserID - Required.
	UserID string
	// Email - Required.
	Email string
	// DisplayName - Required.
	DisplayName string
	// Status - Required.
	Status UserStatus
	// Profile - Required.
	Profile UserProfile
}

func NewUser(userID string, email string, displayName string, status UserStatus, profile UserProfile) *User {
	return &User{
		UserID:      userID,
		Email:       email,
		DisplayName: displayName,
		Status:      status,
		Profile:     profile,
	}
}

func (u *User) UpdateEmail(ctx workflow.Context, email string) workflow.Future {
	return updateEmail(ctx, updateEmailRequest{UserID: u.UserID, Email: email})
}

func (u *User) Rename(ctx workflow.Context, displayName string) workflow.Future {
	return rename(ctx, renameRequest{UserID: u.UserID, DisplayName: displayName})
}

func (u *User) Deactivate(ctx workflow.Context, reason string) workflow.Future {
	var reasonPtr *string
	if reason != "" {
		reasonPtr = &reason
	}
	return deactivate(ctx, deactivateRequest{UserID: u.UserID, Reason: reasonPtr})
}

// --- Operations (internal) ---

func getUser(ctx workflow.Context, request getUserRequest) workflow.Future {
	c := workflow.NewNexusClient("type-showcase", "TypeShowcase")
	fut := c.ExecuteOperation(ctx, "GetUser", request, workflow.NexusOperationOptions{})
	return fut
}

func updateEmail(ctx workflow.Context, request updateEmailRequest) workflow.Future {
	c := workflow.NewNexusClient("type-showcase", "TypeShowcase")
	fut := c.ExecuteOperation(ctx, "UpdateEmail", request, workflow.NexusOperationOptions{})
	return fut
}

func rename(ctx workflow.Context, request renameRequest) workflow.Future {
	c := workflow.NewNexusClient("type-showcase", "TypeShowcase")
	fut := c.ExecuteOperation(ctx, "Rename", request, workflow.NexusOperationOptions{})
	return fut
}

func setProfile(ctx workflow.Context, request setProfileRequest) workflow.Future {
	c := workflow.NewNexusClient("type-showcase", "TypeShowcase")
	fut := c.ExecuteOperation(ctx, "SetProfile", request, workflow.NexusOperationOptions{})
	return fut
}

func recordSync(ctx workflow.Context, request recordSyncRequest) workflow.Future {
	c := workflow.NewNexusClient("type-showcase", "TypeShowcase")
	fut := c.ExecuteOperation(ctx, "RecordSync", request, workflow.NexusOperationOptions{})
	return fut
}

func deactivate(ctx workflow.Context, request deactivateRequest) workflow.Future {
	c := workflow.NewNexusClient("type-showcase", "TypeShowcase")
	fut := c.ExecuteOperation(ctx, "Deactivate", request, workflow.NexusOperationOptions{})
	return fut
}

// --- Operations (public API) ---

type UserStatus int32

const (
	UserStatusActive    UserStatus = 0
	UserStatusSuspended UserStatus = 1
	UserStatusDeleted   UserStatus = 2
)

type UserCapability int32

const (
	UserCapabilityReadProfile UserCapability = 1 << 0
	UserCapabilityUpdateEmail UserCapability = 1 << 1
	UserCapabilityDeactivate  UserCapability = 1 << 2
)

type NotificationTarget interface {
	isNotificationTarget()
}

type NotificationTargetEmail struct {
	Value string
}

func (NotificationTargetEmail) isNotificationTarget() {}

type NotificationTargetSms struct {
	Value string
}

func (NotificationTargetSms) isNotificationTarget() {}

type NotificationTargetNone struct{}

func (NotificationTargetNone) isNotificationTarget() {}

type UserProfile struct {
	// Tags - Required.
	Tags []string
	// Metadata - Required.
	Metadata map[string]string
	// Capabilities - Required.
	Capabilities UserCapability
	// SyncState - Required.
	SyncState Result[string, string]
	// NotificationTarget - Required.
	NotificationTarget NotificationTarget
	// Address - Optional.
	Address *PostalAddress
}

type Result[T, E any] struct {
	// Result - Optional.
	Result T
	// Error - Optional.
	Error E
}

type PostalAddress struct {
	// Street - Required.
	Street string
	// City - Required.
	City string
	// Country - Required.
	Country string
	// Coordinates - Optional.
	Coordinates *Tuple2[float64, float64]
}

type Tuple2[T1, T2 any] struct {
	// First - Required.
	First T1
	// Second - Required.
	Second T2
}

type SyncReport struct {
	// Route - Required.
	Route []Tuple2[float64, float64]
	// Attempts - Required.
	Attempts []Result[string, string]
	// RegionStatus - Required.
	RegionStatus map[string]Result[string, string]
}

type GetUserOptions struct {
	// UserID - Required.
	UserID string
	// ConsistencyToken - Optional.
	ConsistencyToken string
}

func GetUser(ctx workflow.Context, opts GetUserOptions) workflow.Future {
	var consistencyToken *string
	if opts.ConsistencyToken != "" {
		consistencyToken = &opts.ConsistencyToken
	}
	return getUser(ctx, getUserRequest{
		UserID:           opts.UserID,
		ConsistencyToken: consistencyToken,
	})
}

type UpdateEmailOptions struct {
	// UserID - Required.
	UserID string
	// Email - Required.
	Email string
}

func UpdateEmail(ctx workflow.Context, opts UpdateEmailOptions) workflow.Future {
	return updateEmail(ctx, updateEmailRequest{
		UserID: opts.UserID,
		Email:  opts.Email,
	})
}

type RenameOptions struct {
	// UserID - Required.
	UserID string
	// DisplayName - Required.
	DisplayName string
}

func Rename(ctx workflow.Context, opts RenameOptions) workflow.Future {
	return rename(ctx, renameRequest{
		UserID:      opts.UserID,
		DisplayName: opts.DisplayName,
	})
}

type SetProfileOptions struct {
	// UserID - Required.
	UserID string
	// Profile - Required.
	Profile UserProfile
}

func SetProfile(ctx workflow.Context, opts SetProfileOptions) workflow.Future {
	return setProfile(ctx, setProfileRequest{
		UserID:  opts.UserID,
		Profile: opts.Profile,
	})
}

type RecordSyncOptions struct {
	// UserID - Required.
	UserID string
	// Report - Required.
	Report SyncReport
}

func RecordSync(ctx workflow.Context, opts RecordSyncOptions) workflow.Future {
	return recordSync(ctx, recordSyncRequest{
		UserID: opts.UserID,
		Report: opts.Report,
	})
}

type DeactivateOptions struct {
	// UserID - Required.
	UserID string
	// Reason - Optional.
	Reason string
}

func Deactivate(ctx workflow.Context, opts DeactivateOptions) workflow.Future {
	var reason *string
	if opts.Reason != "" {
		reason = &opts.Reason
	}
	return deactivate(ctx, deactivateRequest{
		UserID: opts.UserID,
		Reason: reason,
	})
}
