// Generated by nexgen latest. DO NOT EDIT!

import * as workflow from "@temporalio/workflow";
import { typeRoundtripService } from "../services";
import { activityOptionsToProto } from "../models";
import type { ActivityOptions } from "../models";

/**
 * @param request - Request for the operation.
 */
export async function activityOptionsOperation(
  request: ActivityOptions,
): Promise<workflow.NexusOperationHandle<ActivityOptions>> {
  const client = workflow.createNexusServiceClient({
    service: typeRoundtripService,
    endpoint: "temporal-system",
  });
  return await client.startOperation(
    typeRoundtripService.operations.activityOptionsOperation,
    activityOptionsToProto(request) ?? {},
  );
}
