// Generated by nexgen latest. DO NOT EDIT!

import * as workflow from "@temporalio/workflow";
import { typeRoundtripService } from "../services";
import type { FailureContainer } from "../models";

/**
 * @param request - Request for the operation.
 */
export async function failureOperation(
  request: FailureContainer,
): Promise<workflow.NexusOperationHandle<FailureContainer>> {
  const client = workflow.createNexusServiceClient({
    service: typeRoundtripService,
    endpoint: "temporal-system",
  });
  return await client.startOperation(
    typeRoundtripService.operations.failureOperation,
    request,
  );
}
