// Generated by nexgen latest. DO NOT EDIT!

import * as nexus from "nexus-rpc";
import * as workflow from "@temporalio/workflow";
import type { GetUserRequest, UpdateEmailRequest } from "./models";
import type { User } from "./resources";
import { bindUserClient } from "./resources";

export const userService = nexus.service("UserService", {
  getUser: nexus.operation<GetUserRequest, User>({ name: "GetUser" }),
  updateEmail: nexus.operation<UpdateEmailRequest, User>({ name: "UpdateEmail" }),
});

export class UserServiceClient {
  private readonly client: workflow.NexusServiceClient<typeof userService>;

  public constructor(endpoint: string) {
    this.client = workflow.createNexusServiceClient({
      service: userService,
      endpoint,
    });
  }

  /**
   * @param request - Request for the operation.
   */
  public async getUser(request: GetUserRequest): Promise<User> {
    const requestProto = request;
    const handle = await this.client.startOperation(
      userService.operations.getUser,
      requestProto,
    );
    const resource = await handle.result();
    return bindUserClient(resource, this.client);
  }

  /**
   * @param request - Request for the operation.
   */
  public async updateEmail(request: UpdateEmailRequest): Promise<User> {
    const requestProto = request;
    const handle = await this.client.startOperation(
      userService.operations.updateEmail,
      requestProto,
    );
    const resource = await handle.result();
    return bindUserClient(resource, this.client);
  }
}

export const operationRegistry = [
  {
    service: "UserService",
    operation: "GetUser",
  },
  {
    service: "UserService",
    operation: "UpdateEmail",
  },
] as const;
