// Generated by nexgen latest. DO NOT EDIT!

import type * as common from "@temporalio/common";
import type { temporal } from "@temporalio/proto";
import * as support from "../../support/temporal_model_converters";

export function requiredField<T>(
  value: T | null | undefined,
  owner: string,
  field: string,
): T {
  if (value == null) {
    throw new Error(`missing required field ${owner}.${field}`);
  }
  return value;
}

export interface StartWorkflowResult {
  runId?: string;
}

function startWorkflowResultFromProto(
  proto:
    | temporal.api.workflowservice.v1.IStartWorkflowExecutionResponse
    | null
    | undefined,
): StartWorkflowResult | undefined {
  if (proto == null) {
    return undefined;
  }
  return {
    runId: proto.runId ?? undefined,
  };
}

function startWorkflowResultToProto(
  model: StartWorkflowResult | null | undefined,
): temporal.api.workflowservice.v1.IStartWorkflowExecutionResponse | undefined {
  if (model == null) {
    return undefined;
  }
  return {
    runId: model.runId,
  };
}

export const startWorkflowResultTransferTypeConverter = {
  fromTransferType(
    value: temporal.api.workflowservice.v1.IStartWorkflowExecutionResponse,
  ): StartWorkflowResult {
    return startWorkflowResultFromProto(value)!;
  },

  toTransferType(
    value: StartWorkflowResult,
  ): temporal.api.workflowservice.v1.IStartWorkflowExecutionResponse {
    return startWorkflowResultToProto(value) ?? {};
  },
};
export interface StartWorkflowRequest {
  workflow: string;
  workflowId: string;
  taskQueue: string;
  workflowStartDelay?: common.Duration;
  namespace: string;
}

function startWorkflowRequestFromProto(
  proto:
    | temporal.api.workflowservice.v1.IStartWorkflowExecutionRequest
    | null
    | undefined,
): StartWorkflowRequest | undefined {
  if (proto == null) {
    return undefined;
  }
  return {
    workflow: requiredField(
      support.workflowTypeFromProto(
        requiredField(proto.workflowType, "StartWorkflowRequest", "workflow"),
      ),
      "StartWorkflowRequest",
      "workflow",
    ),
    workflowId: requiredField(
      proto.workflowId === "" ? undefined : proto.workflowId,
      "StartWorkflowRequest",
      "workflowId",
    ),
    taskQueue: requiredField(
      support.taskQueueFromProto(
        requiredField(proto.taskQueue, "StartWorkflowRequest", "taskQueue"),
      ),
      "StartWorkflowRequest",
      "taskQueue",
    ),
    workflowStartDelay:
      proto.workflowStartDelay == null
        ? undefined
        : support.durationFromProto(proto.workflowStartDelay),
    namespace: requiredField(
      proto.namespace === "" ? undefined : proto.namespace,
      "sourced field",
      "namespace",
    ),
  };
}

function startWorkflowRequestToProto(
  model: StartWorkflowRequest | null | undefined,
): temporal.api.workflowservice.v1.IStartWorkflowExecutionRequest | undefined {
  if (model == null) {
    return undefined;
  }
  return {
    workflowType: support.workflowTypeToProto(
      requiredField(model.workflow, "StartWorkflowRequest", "workflow"),
    ),
    workflowId: requiredField(model.workflowId, "StartWorkflowRequest", "workflowId"),
    taskQueue: support.taskQueueToProto(
      requiredField(model.taskQueue, "StartWorkflowRequest", "taskQueue"),
    ),
    workflowStartDelay:
      model.workflowStartDelay == null
        ? undefined
        : support.durationToProto(model.workflowStartDelay),
    namespace: model.namespace ?? support.workflowNamespace(),
  };
}

export const startWorkflowRequestTransferTypeConverter = {
  fromTransferType(
    value: temporal.api.workflowservice.v1.IStartWorkflowExecutionRequest,
  ): StartWorkflowRequest {
    return startWorkflowRequestFromProto(value)!;
  },

  toTransferType(
    value: StartWorkflowRequest,
  ): temporal.api.workflowservice.v1.IStartWorkflowExecutionRequest {
    return startWorkflowRequestToProto(value) ?? {};
  },
};
export type CancelWorkflowResponse = Record<string, never>;

function cancelWorkflowResponseFromProto(
  proto:
    | temporal.api.workflowservice.v1.IRequestCancelWorkflowExecutionResponse
    | null
    | undefined,
): CancelWorkflowResponse | undefined {
  if (proto == null) {
    return undefined;
  }
  return {};
}

function cancelWorkflowResponseToProto(
  model: CancelWorkflowResponse | null | undefined,
): temporal.api.workflowservice.v1.IRequestCancelWorkflowExecutionResponse | undefined {
  if (model == null) {
    return undefined;
  }
  return {};
}

export const cancelWorkflowResponseTransferTypeConverter = {
  fromTransferType(
    value: temporal.api.workflowservice.v1.IRequestCancelWorkflowExecutionResponse,
  ): CancelWorkflowResponse {
    return cancelWorkflowResponseFromProto(value)!;
  },

  toTransferType(
    value: CancelWorkflowResponse,
  ): temporal.api.workflowservice.v1.IRequestCancelWorkflowExecutionResponse {
    return cancelWorkflowResponseToProto(value) ?? {};
  },
};
export interface CancelWorkflowRequest {
  workflowExecution: WorkflowExecution;
  reason?: string;
  namespace: string;
}

function cancelWorkflowRequestFromProto(
  proto:
    | temporal.api.workflowservice.v1.IRequestCancelWorkflowExecutionRequest
    | null
    | undefined,
): CancelWorkflowRequest | undefined {
  if (proto == null) {
    return undefined;
  }
  return {
    workflowExecution: requiredField(
      workflowExecutionFromProto(
        requiredField(
          proto.workflowExecution,
          "CancelWorkflowRequest",
          "workflowExecution",
        ),
      ),
      "CancelWorkflowRequest",
      "workflowExecution",
    ),
    reason: proto.reason ?? undefined,
    namespace: requiredField(
      proto.namespace === "" ? undefined : proto.namespace,
      "sourced field",
      "namespace",
    ),
  };
}

function cancelWorkflowRequestToProto(
  model: CancelWorkflowRequest | null | undefined,
): temporal.api.workflowservice.v1.IRequestCancelWorkflowExecutionRequest | undefined {
  if (model == null) {
    return undefined;
  }
  return {
    workflowExecution:
      workflowExecutionToProto(
        requiredField(
          model.workflowExecution,
          "CancelWorkflowRequest",
          "workflowExecution",
        ),
      ) ?? {},
    reason: model.reason,
    namespace: model.namespace ?? support.workflowNamespace(),
  };
}

export const cancelWorkflowRequestTransferTypeConverter = {
  fromTransferType(
    value: temporal.api.workflowservice.v1.IRequestCancelWorkflowExecutionRequest,
  ): CancelWorkflowRequest {
    return cancelWorkflowRequestFromProto(value)!;
  },

  toTransferType(
    value: CancelWorkflowRequest,
  ): temporal.api.workflowservice.v1.IRequestCancelWorkflowExecutionRequest {
    return cancelWorkflowRequestToProto(value) ?? {};
  },
};
export interface WorkflowExecution {
  workflowId: string;
  runId?: string;
}

function workflowExecutionFromProto(
  proto: temporal.api.common.v1.IWorkflowExecution | null | undefined,
): WorkflowExecution | undefined {
  if (proto == null) {
    return undefined;
  }
  return {
    workflowId: requiredField(
      proto.workflowId === "" ? undefined : proto.workflowId,
      "WorkflowExecution",
      "workflowId",
    ),
    runId: proto.runId ?? undefined,
  };
}

function workflowExecutionToProto(
  model: WorkflowExecution | null | undefined,
): temporal.api.common.v1.IWorkflowExecution | undefined {
  if (model == null) {
    return undefined;
  }
  return {
    workflowId: requiredField(model.workflowId, "WorkflowExecution", "workflowId"),
    runId: model.runId,
  };
}

export const workflowExecutionTransferTypeConverter = {
  fromTransferType(
    value: temporal.api.common.v1.IWorkflowExecution,
  ): WorkflowExecution {
    return workflowExecutionFromProto(value)!;
  },

  toTransferType(value: WorkflowExecution): temporal.api.common.v1.IWorkflowExecution {
    return workflowExecutionToProto(value) ?? {};
  },
};
