// Generated by nexgen latest. DO NOT EDIT!

import * as nexus from "nexus-rpc";
import {
  startWorkflowResultTransferTypeConverter,
  startWorkflowRequestTransferTypeConverter,
  cancelWorkflowResponseTransferTypeConverter,
  cancelWorkflowRequestTransferTypeConverter,
} from "./models";
import type {
  StartWorkflowResult,
  StartWorkflowRequest,
  CancelWorkflowResponse,
  CancelWorkflowRequest,
} from "./models";

export const startWorkflowService = nexus.service("StartWorkflowService", {
  startWorkflow: nexus.operation<StartWorkflowRequest, StartWorkflowResult>({
    name: "StartWorkflow",
    inputType: { transferTypeConverter: startWorkflowRequestTransferTypeConverter },
    outputType: { transferTypeConverter: startWorkflowResultTransferTypeConverter },
  }),
  restartWorkflow: nexus.operation<StartWorkflowRequest, StartWorkflowResult>({
    name: "RestartWorkflow",
    inputType: { transferTypeConverter: startWorkflowRequestTransferTypeConverter },
    outputType: { transferTypeConverter: startWorkflowResultTransferTypeConverter },
  }),
  cancelWorkflow: nexus.operation<CancelWorkflowRequest, CancelWorkflowResponse>({
    name: "CancelWorkflow",
    inputType: { transferTypeConverter: cancelWorkflowRequestTransferTypeConverter },
    outputType: { transferTypeConverter: cancelWorkflowResponseTransferTypeConverter },
  }),
});

export const operationRegistry = [
  {
    service: "StartWorkflowService",
    operation: "StartWorkflow",
  },
  {
    service: "StartWorkflowService",
    operation: "RestartWorkflow",
  },
  {
    service: "StartWorkflowService",
    operation: "CancelWorkflow",
  },
] as const;
