// Generated by nexgen latest. DO NOT EDIT!

import * as nexus from "nexus-rpc";
import type { temporal } from "@temporalio/proto";
import {
  startWorkflowRequestTransferTypeConverter,
  cancelWorkflowRequestTransferTypeConverter,
} from "./models";
import type { StartWorkflowRequest, CancelWorkflowRequest } from "./models";

export const startWorkflowService = nexus.service("StartWorkflowService", {
  startWorkflow: nexus.operation<
    StartWorkflowRequest,
    temporal.api.workflowservice.v1.IStartWorkflowExecutionResponse
  >({
    name: "StartWorkflow",
    inputType: { transferTypeConverter: startWorkflowRequestTransferTypeConverter },
  }),
  restartWorkflow: nexus.operation<
    StartWorkflowRequest,
    temporal.api.workflowservice.v1.IStartWorkflowExecutionResponse
  >({
    name: "RestartWorkflow",
    inputType: { transferTypeConverter: startWorkflowRequestTransferTypeConverter },
  }),
  cancelWorkflow: nexus.operation<
    CancelWorkflowRequest,
    temporal.api.workflowservice.v1.IRequestCancelWorkflowExecutionResponse
  >({
    name: "CancelWorkflow",
    inputType: { transferTypeConverter: cancelWorkflowRequestTransferTypeConverter },
  }),
});

export const operationRegistry = [
  {
    service: "StartWorkflowService",
    operation: "StartWorkflow",
  },
  {
    service: "StartWorkflowService",
    operation: "RestartWorkflow",
  },
  {
    service: "StartWorkflowService",
    operation: "CancelWorkflow",
  },
] as const;
