// Generated by nexgen latest. DO NOT EDIT!

import type { TransferTypeConverter } from "nexus-rpc";
import { createPayloadValidationError } from "@temporalio/common";
import * as __nexgenDefinitions from "../../definitions";
import { pageTransferTypeConverter } from "../page/models";
import type { Page } from "../page/models";

export function requiredField<T>(
  value: T | null | undefined,
  owner: string,
  field: string,
): T {
  if (value == null) {
    throw new Error(`missing required field ${owner}.${field}`);
  }
  return value;
}

/**
 * A content block. The other half of the Page <-> Block cross-file cycle. The `page`
 * back-reference is optional + nullable, which terminates the cycle so it is
 * satisfiable.
 */
export interface Block {
  blockId: string;
  /**
   * Non-negative position within the page. Exercises a numeric `minimum` bound over an
   * integer field.
   */
  order: number;
  text?: string;
  style?: BlockStyle;
  /**
   * Optional back-reference to the containing page - closes the Page <-> Block cycle.
   * Optional + nullable, so this edge terminates.
   */
  page?: Page | null;
}

/**
 * Non-cyclic helper; stays in the content_block module. All members optional.
 */
export interface BlockStyle {
  bold?: boolean;
  indent?: number;
}

export const blockTransferTypeConverter =
  new (class implements TransferTypeConverter<Block> {
    public fromTransferType(raw: unknown): Block {
      const violations: __nexgenDefinitions.Violation[] = [];
      if (!__nexgenDefinitions.isPlainObject(raw)) {
        throw createPayloadValidationError([{ path: "", reason: "expected object" }]);
      }

      let blockId: string = undefined as unknown as string;
      if (
        !Object.prototype.hasOwnProperty.call(raw, "blockId") ||
        raw["blockId"] === null
      ) {
        violations.push({ path: "blockId", reason: "required" });
      } else {
        if (typeof raw["blockId"] !== "string") {
          violations.push({ path: "blockId", reason: "expected string" });
        } else {
          blockId = raw["blockId"];
        }
      }

      let order: number = undefined as unknown as number;
      if (
        !Object.prototype.hasOwnProperty.call(raw, "order") ||
        raw["order"] === null
      ) {
        violations.push({ path: "order", reason: "required" });
      } else {
        if (typeof raw["order"] !== "number" || !Number.isSafeInteger(raw["order"])) {
          violations.push({ path: "order", reason: "expected integer" });
        } else {
          order = raw["order"];
          if (raw["order"] < 0) {
            violations.push({
              path: "order",
              reason: `must be >= 0, got ${raw["order"]}`,
            });
          }
        }
      }

      let text: string | undefined = undefined as unknown as string | undefined;
      if (Object.prototype.hasOwnProperty.call(raw, "text") && raw["text"] === null) {
        violations.push({ path: "text", reason: "explicit null not allowed" });
      } else if (Object.prototype.hasOwnProperty.call(raw, "text")) {
        if (typeof raw["text"] !== "string") {
          violations.push({ path: "text", reason: "expected string" });
        } else {
          text = raw["text"];
        }
      }

      let style: BlockStyle | undefined = undefined as unknown as
        | BlockStyle
        | undefined;
      if (Object.prototype.hasOwnProperty.call(raw, "style") && raw["style"] === null) {
        violations.push({ path: "style", reason: "explicit null not allowed" });
      } else if (Object.prototype.hasOwnProperty.call(raw, "style")) {
        try {
          style = blockStyleTransferTypeConverter.fromTransferType(raw["style"]);
        } catch (error) {
          __nexgenDefinitions.collect(violations, "style", error);
        }
      }

      let page: Page | null | undefined = undefined as unknown as
        | Page
        | null
        | undefined;
      if (Object.prototype.hasOwnProperty.call(raw, "page")) {
        if (raw["page"] === null) {
          page = null;
        } else {
          try {
            page = pageTransferTypeConverter.fromTransferType(raw["page"]);
          } catch (error) {
            __nexgenDefinitions.collect(violations, "page", error);
          }
        }
      }

      for (const key of Object.keys(raw)) {
        if (
          key !== "blockId" &&
          key !== "order" &&
          key !== "text" &&
          key !== "style" &&
          key !== "page"
        ) {
          violations.push({
            path: __nexgenDefinitions.memberPath(key),
            reason: "unknown field",
          });
        }
      }

      if (violations.length) {
        throw createPayloadValidationError(violations);
      }
      const out: Block = { blockId, order };
      if (text !== undefined) {
        out.text = text;
      }
      if (style !== undefined) {
        out.style = style;
      }
      if (page !== undefined) {
        out.page = page;
      }
      return out;
    }

    public toTransferType(value: Block): unknown {
      const candidate: unknown = value;
      if (!__nexgenDefinitions.isPlainObject(candidate)) {
        throw createPayloadValidationError([{ path: "", reason: "expected object" }]);
      }
      const violations: __nexgenDefinitions.Violation[] = [];
      const out: Record<string, unknown> = Object.create(null) as Record<
        string,
        unknown
      >;
      if (value.blockId === undefined || value.blockId === null) {
        violations.push({ path: "blockId", reason: "required" });
      } else {
        if (!(typeof value.blockId === "string")) {
          violations.push({ path: "blockId", reason: "expected string" });
        }
        out["blockId"] = value.blockId;
      }
      if (value.order === undefined || value.order === null) {
        violations.push({ path: "order", reason: "required" });
      } else {
        if (!(typeof value.order === "number" && Number.isInteger(value.order))) {
          violations.push({ path: "order", reason: "expected integer" });
        } else {
          if (!Number.isSafeInteger(value.order)) {
            violations.push({ path: "order", reason: "exceeds ±(2^53-1) integer cap" });
          } else {
            if (value.order < 0) {
              violations.push({
                path: "order",
                reason: `must be >= 0, got ${value.order}`,
              });
            }
          }
        }
        out["order"] = value.order;
      }
      if (value.text !== undefined) {
        if (value.text === null) {
          violations.push({ path: "text", reason: "explicit null not allowed" });
        } else {
          if (!(typeof value.text === "string")) {
            violations.push({ path: "text", reason: "expected string" });
          }
          out["text"] = value.text;
        }
      }
      if (value.style !== undefined) {
        if (value.style === null) {
          violations.push({ path: "style", reason: "explicit null not allowed" });
        } else {
          const styleViolationCount = violations.length;
          if (violations.length === styleViolationCount) {
            out["style"] = (() => {
              try {
                return blockStyleTransferTypeConverter.toTransferType(value.style);
              } catch (error) {
                __nexgenDefinitions.collect(violations, "style", error);
                return undefined;
              }
            })();
          }
        }
      }
      if (value.page !== undefined) {
        const pageViolationCount = violations.length;
        if (violations.length === pageViolationCount) {
          out["page"] =
            value.page === null
              ? null
              : (() => {
                  try {
                    return pageTransferTypeConverter.toTransferType(value.page);
                  } catch (error) {
                    __nexgenDefinitions.collect(violations, "page", error);
                    return undefined;
                  }
                })();
        }
      }
      if (violations.length) {
        throw createPayloadValidationError(violations);
      }
      return out;
    }
  })();

export const blockStyleTransferTypeConverter =
  new (class implements TransferTypeConverter<BlockStyle> {
    public fromTransferType(raw: unknown): BlockStyle {
      const violations: __nexgenDefinitions.Violation[] = [];
      if (!__nexgenDefinitions.isPlainObject(raw)) {
        throw createPayloadValidationError([{ path: "", reason: "expected object" }]);
      }

      let bold: boolean | undefined = undefined as unknown as boolean | undefined;
      if (Object.prototype.hasOwnProperty.call(raw, "bold") && raw["bold"] === null) {
        violations.push({ path: "bold", reason: "explicit null not allowed" });
      } else if (Object.prototype.hasOwnProperty.call(raw, "bold")) {
        if (typeof raw["bold"] !== "boolean") {
          violations.push({ path: "bold", reason: "expected boolean" });
        } else {
          bold = raw["bold"];
        }
      }

      let indent: number | undefined = undefined as unknown as number | undefined;
      if (
        Object.prototype.hasOwnProperty.call(raw, "indent") &&
        raw["indent"] === null
      ) {
        violations.push({ path: "indent", reason: "explicit null not allowed" });
      } else if (Object.prototype.hasOwnProperty.call(raw, "indent")) {
        if (typeof raw["indent"] !== "number" || !Number.isSafeInteger(raw["indent"])) {
          violations.push({ path: "indent", reason: "expected integer" });
        } else {
          indent = raw["indent"];
          if (raw["indent"] < 0) {
            violations.push({
              path: "indent",
              reason: `must be >= 0, got ${raw["indent"]}`,
            });
          }
        }
      }

      for (const key of Object.keys(raw)) {
        if (key !== "bold" && key !== "indent") {
          violations.push({
            path: __nexgenDefinitions.memberPath(key),
            reason: "unknown field",
          });
        }
      }

      if (violations.length) {
        throw createPayloadValidationError(violations);
      }
      const out: BlockStyle = {};
      if (bold !== undefined) {
        out.bold = bold;
      }
      if (indent !== undefined) {
        out.indent = indent;
      }
      return out;
    }

    public toTransferType(value: BlockStyle): unknown {
      const candidate: unknown = value;
      if (!__nexgenDefinitions.isPlainObject(candidate)) {
        throw createPayloadValidationError([{ path: "", reason: "expected object" }]);
      }
      const violations: __nexgenDefinitions.Violation[] = [];
      const out: Record<string, unknown> = Object.create(null) as Record<
        string,
        unknown
      >;
      if (value.bold !== undefined) {
        if (value.bold === null) {
          violations.push({ path: "bold", reason: "explicit null not allowed" });
        } else {
          if (!(typeof value.bold === "boolean")) {
            violations.push({ path: "bold", reason: "expected boolean" });
          }
          out["bold"] = value.bold;
        }
      }
      if (value.indent !== undefined) {
        if (value.indent === null) {
          violations.push({ path: "indent", reason: "explicit null not allowed" });
        } else {
          if (!(typeof value.indent === "number" && Number.isInteger(value.indent))) {
            violations.push({ path: "indent", reason: "expected integer" });
          } else {
            if (!Number.isSafeInteger(value.indent)) {
              violations.push({
                path: "indent",
                reason: "exceeds ±(2^53-1) integer cap",
              });
            } else {
              if (value.indent < 0) {
                violations.push({
                  path: "indent",
                  reason: `must be >= 0, got ${value.indent}`,
                });
              }
            }
          }
          out["indent"] = value.indent;
        }
      }
      if (violations.length) {
        throw createPayloadValidationError(violations);
      }
      return out;
    }
  })();
