// <auto-generated />
// Generated by nexgen latest. DO NOT EDIT!
#nullable enable

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;

namespace Nexgen.GenericModelService
{

    [GeneratedCode("nexgen", null)]
    public abstract record OperationCompletionResult<TOutput>
    {
        private OperationCompletionResult() { }

        [GeneratedCode("nexgen", null)]
        public sealed record Success(OperationCompletionSuccess<TOutput> Value) : OperationCompletionResult<TOutput>;

        [GeneratedCode("nexgen", null)]
        public sealed record Failure(OperationCompletionFailure Value) : OperationCompletionResult<TOutput>;
    }

    [GeneratedCode("nexgen", null)]
    public record GenericRequest<TContext>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GenericRequest{TContext}"/> class.
        /// </summary>
        public GenericRequest(TContext context, IReadOnlyList<TContext> contexts, IReadOnlyDictionary<string, TContext> byName, Inner<TContext> nested)
        {
            Context = context;
            Contexts = contexts;
            ByName = byName;
            Nested = nested;
        }

        public TContext Context { get; init; }
        public IReadOnlyList<TContext> Contexts { get; init; }
        public IReadOnlyDictionary<string, TContext> ByName { get; init; }
        public Inner<TContext> Nested { get; init; }
    }

    [GeneratedCode("nexgen", null)]
    public record GenericResponse<TContext, TOutput, TMetadata>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GenericResponse{TContext, TOutput, TMetadata}"/> class.
        /// </summary>
        public GenericResponse(TContext context, OperationCompletionResult<TOutput> completion)
        {
            Context = context;
            Completion = completion;
        }

        public TContext Context { get; init; }
        public OperationCompletionResult<TOutput> Completion { get; init; }
        public TMetadata? Metadata { get; init; }
    }

    [GeneratedCode("nexgen", null)]
    public record Inner<TContext>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Inner{TContext}"/> class.
        /// </summary>
        public Inner(TContext value)
        {
            Value = value;
        }

        public TContext Value { get; init; }
    }

    [GeneratedCode("nexgen", null)]
    public record OperationCompletionFailure
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OperationCompletionFailure"/> class.
        /// </summary>
        public OperationCompletionFailure(string message)
        {
            Message = message;
        }

        public string Message { get; init; }
    }

    [GeneratedCode("nexgen", null)]
    public record OperationCompletionSuccess<TOutput>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OperationCompletionSuccess{TOutput}"/> class.
        /// </summary>
        public OperationCompletionSuccess(TOutput output)
        {
            Output = output;
        }

        public TOutput Output { get; init; }
    }

}
