// <auto-generated />
// Generated by nexgen. DO NOT EDIT!
#nullable enable
#pragma warning disable CS1591

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;

namespace Nexgen.GenericModelService
{

    [GeneratedCode("nexgen", null)]
    public abstract record OperationCompletionResult<OutputT>
    {
        private OperationCompletionResult() { }

        [GeneratedCode("nexgen", null)]
        public sealed record Success(OperationCompletionSuccess<OutputT> Value) : OperationCompletionResult<OutputT>;

        [GeneratedCode("nexgen", null)]
        public sealed record Failure(OperationCompletionFailure Value) : OperationCompletionResult<OutputT>;
    }

    [GeneratedCode("nexgen", null)]
    public class GenericRequest<ContextT>
    {
        public GenericRequest(ContextT context, IReadOnlyList<ContextT> contexts, IReadOnlyDictionary<string, ContextT> byName, Inner<ContextT> nested)
        {
            Context = context;
            Contexts = contexts;
            ByName = byName;
            Nested = nested;
        }

        public ContextT Context { get; }
        public IReadOnlyList<ContextT> Contexts { get; }
        public IReadOnlyDictionary<string, ContextT> ByName { get; }
        public Inner<ContextT> Nested { get; }
    }

    [GeneratedCode("nexgen", null)]
    public class GenericResponse<ContextT, OutputT, MetadataT>
    {
        public GenericResponse(ContextT context, OperationCompletionResult<OutputT> completion)
        {
            Context = context;
            Completion = completion;
        }

        public ContextT Context { get; }
        public OperationCompletionResult<OutputT> Completion { get; }
        public MetadataT? Metadata { get; init; }
    }

    [GeneratedCode("nexgen", null)]
    public class Inner<ContextT>
    {
        public Inner(ContextT value)
        {
            Value = value;
        }

        public ContextT Value { get; }
    }

    [GeneratedCode("nexgen", null)]
    public class OperationCompletionFailure
    {
        public OperationCompletionFailure(string message)
        {
            Message = message;
        }

        public string Message { get; }
    }

    [GeneratedCode("nexgen", null)]
    public class OperationCompletionSuccess<OutputT>
    {
        public OperationCompletionSuccess(OutputT output)
        {
            Output = output;
        }

        public OutputT Output { get; }
    }

}
