[workflow-service]
system_nexus = true

[multi-operation-service]
system_nexus = true

[proto-generic]
languages = ["python", "dotnet"]

[proto-oneof]
languages = ["python", "dotnet"]

[notification-service]
languages = ["python", "dotnet"]
