[workflow-service]
system_nexus = true

[multi-operation-service]
system_nexus = true

[proto-generic-python]
languages = ["python"]

[proto-oneof]
languages = ["python"]

[notification-service]
languages = ["python"]
