// <auto-generated />
// Generated by nexgen latest. DO NOT EDIT!
#nullable enable

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Threading.Tasks;
using Temporalio.Workflows;
using Nexgen.Support;

namespace Nexgen.UserService
{

    [GeneratedCode("nexgen", null)]
    public class User
    {
        public User(string userId, string email)
        {
            UserId = userId;
            Email = email;
        }

        public string UserId { get; }
        public string Email { get; }

        internal NexusWorkflowClient<IUserService>? NexgenClient { get; set; }

        internal static User BindClient(User resource, NexusWorkflowClient<IUserService> client)
        {
            resource.NexgenClient = client;
            return resource;
        }

        private NexusWorkflowClient<IUserService> RequireNexgenClient()
        {
            return NexgenClient ?? throw new InvalidOperationException("User methods require a service endpoint.");
        }

        [GeneratedCode("nexgen", null)]
        public async Task<User> UpdateEmailAsync(string email)
        {
            var request = new UpdateEmailRequest(UserId, email);
            var result = await RequireNexgenClient().ExecuteNexusOperationAsync<User>(svc => svc.UpdateEmail(request)).ConfigureAwait(true);
            return User.BindClient(result, RequireNexgenClient());
        }

    }

}
