// <auto-generated />
// Generated by nexgen latest. DO NOT EDIT!
#nullable enable

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Threading.Tasks;
using NexusRpc;
using Temporalio.Workflows;
using Nexgen.Support;

namespace Nexgen.UserService
{

    [GeneratedCode("nexgen", null)]
    [NexusService("UserService")]
    internal interface IUserService
    {
        [GeneratedCode("nexgen", null)]
        [NexusOperation("GetUser")]
        User GetUser(GetUserRequest request);

        [GeneratedCode("nexgen", null)]
        [NexusOperation("UpdateEmail")]
        User UpdateEmail(UpdateEmailRequest request);

    }

    [GeneratedCode("nexgen", null)]
    public class GetUserOptions
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetUserOptions"/> class.
        /// </summary>
        public GetUserOptions(string userId)
        {
            UserId = userId;
        }

        public string UserId { get; set; }
    }

    [GeneratedCode("nexgen", null)]
    public class UpdateEmailOptions
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateEmailOptions"/> class.
        /// </summary>
        public UpdateEmailOptions(string userId, string email)
        {
            UserId = userId;
            Email = email;
        }

        public string UserId { get; set; }
        public string Email { get; set; }
    }

    [GeneratedCode("nexgen", null)]
    public class UserServiceClient
    {
        private readonly NexusWorkflowClient<IUserService> _client;

        public UserServiceClient(string endpoint)
        {
            _client = Workflow.CreateNexusWorkflowClient<IUserService>(endpoint);
        }

        [GeneratedCode("nexgen", null)]
        private async Task<User> GetUserAsync(GetUserRequest request)
        {
            var result = await _client.ExecuteNexusOperationAsync<User>(svc => svc.GetUser(request)).ConfigureAwait(true);
            return User.BindClient(result, _client);
        }

        /// <param name="options">Options for the operation.</param>
        [GeneratedCode("nexgen", null)]
        public Task<User> GetUserAsync(GetUserOptions options)
        {
            var request = new GetUserRequest(options.UserId);
            return GetUserAsync(request);
        }

        [GeneratedCode("nexgen", null)]
        private async Task<User> UpdateEmailAsync(UpdateEmailRequest request)
        {
            var result = await _client.ExecuteNexusOperationAsync<User>(svc => svc.UpdateEmail(request)).ConfigureAwait(true);
            return User.BindClient(result, _client);
        }

        /// <param name="options">Options for the operation.</param>
        [GeneratedCode("nexgen", null)]
        public Task<User> UpdateEmailAsync(UpdateEmailOptions options)
        {
            var request = new UpdateEmailRequest(options.UserId, options.Email);
            return UpdateEmailAsync(request);
        }

    }

}
