// Code generated by nexgen v0.2.1. DO NOT EDIT.
package kb

import (
	"encoding/json"
	"fmt"
)

// Page A page. One half of the Page <-> Block cross-file cycle. Because the cycle spans
// two input files, Page and Block hoist together into Python's _recursive.py; the
// non-cyclic PageMeta helper stays in this module.
type Page struct {
	// PageId corresponds to the "pageId" JSON property.
	PageId string `json:"pageId"`
	// Title corresponds to the "title" JSON property.
	Title string `json:"title"`
	// Meta corresponds to the "meta" JSON property.
	Meta PageMeta `json:"meta"`
	// Blocks Ordered content blocks. Cross-file `$ref` to block.json (same directory); the
	// array is the terminating edge of the cycle.
	Blocks []Block `json:"blocks,omitempty"`
}

// Validate checks m against every constraint and returns a *ValidationError
// listing any violations.
func (m Page) Validate() error {
	var errs []Violation
	mergeNested(&errs, "meta", m.Meta.Validate())
	for i0, v0 := range m.Blocks {
		p0 := fmt.Sprintf("%s[%d]", "blocks", i0)
		mergeNested(&errs, p0, v0.Validate())
	}
	if len(errs) > 0 {
		return &ValidationError{Violations: errs}
	}
	return nil
}

// UnmarshalJSON parses data into m and validates it, returning a
// *ValidationError listing any violations.
func (m *Page) UnmarshalJSON(data []byte) error {
	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	var errs []Violation
	for k := range all {
		switch k {
		case "pageId", "title", "meta", "blocks":
		default:
			errs = append(errs, Violation{k, "unknown field"})
		}
	}
	get := func(k string) *json.RawMessage {
		if v, ok := all[k]; ok {
			return &v
		}
		return nil
	}
	_ = get
	if v, ok := parseStringField(get("pageId"), "pageId", true, false, &errs); ok {
		m.PageId = v
	}
	if v, ok := parseStringField(get("title"), "title", true, false, &errs); ok {
		m.Title = v
	}
	if raw := get("meta"); raw == nil {
		errs = append(errs, Violation{"meta", "required"})
	} else if isNull(*raw) {
		errs = append(errs, Violation{"meta", "explicit null not allowed"})
	} else {
		mergeNested(&errs, "meta", json.Unmarshal(*raw, &m.Meta))
	}
	if raw := get("blocks"); raw == nil {
	} else if isNull(*raw) {
		errs = append(errs, Violation{"blocks", "explicit null not allowed"})
	} else {
		var elems0 []json.RawMessage
		if err := json.Unmarshal(*raw, &elems0); err != nil {
			errs = append(errs, Violation{"blocks", "expected array"})
		} else {
			m.Blocks = make([]Block, 0, len(elems0))
			for i0, e0 := range elems0 {
				p0 := fmt.Sprintf("%s[%d]", "blocks", i0)
				if isNull(e0) {
					errs = append(errs, Violation{p0, "explicit null not allowed"})
					continue
				}
				var value0 Block
				if err := json.Unmarshal(e0, &value0); err != nil {
					mergeNested(&errs, p0, err)
				} else {
					m.Blocks = append(m.Blocks, value0)
				}
			}
		}
	}
	if len(errs) > 0 {
		return &ValidationError{Violations: errs}
	}
	return nil
}

// MarshalJSON validates m, then serializes it to JSON, returning a
// *ValidationError if validation fails.
func (m Page) MarshalJSON() ([]byte, error) {
	var errs []Violation
	addViolations(&errs, m.Validate())
	out := map[string]json.RawMessage{}
	marshalField(out, "pageId", m.PageId, &errs)
	marshalField(out, "title", m.Title, &errs)
	marshalField(out, "meta", m.Meta, &errs)
	if m.Blocks != nil {
		marshalField(out, "blocks", m.Blocks, &errs)
	}
	if len(errs) > 0 {
		return nil, &ValidationError{Violations: errs}
	}
	return json.Marshal(out)
}

// PageMeta Non-cyclic helper. Referenced only by Page, references nothing recursive, so
// it stays in the content_page module even though Page is hoisted.
type PageMeta struct {
	// Author corresponds to the "author" JSON property.
	Author string `json:"author"`
	// WordCount corresponds to the "wordCount" JSON property.
	WordCount *int64 `json:"wordCount,omitempty"`
}

// Validate checks m against every constraint and returns a *ValidationError
// listing any violations.
func (m PageMeta) Validate() error {
	var errs []Violation
	if m.WordCount != nil && (*m.WordCount < -integerCap || *m.WordCount > integerCap) {
		errs = append(errs, Violation{"wordCount", "exceeds ±(2^53-1) integer cap"})
	}
	if len(errs) > 0 {
		return &ValidationError{Violations: errs}
	}
	return nil
}

// UnmarshalJSON parses data into m and validates it, returning a
// *ValidationError listing any violations.
func (m *PageMeta) UnmarshalJSON(data []byte) error {
	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	var errs []Violation
	for k := range all {
		switch k {
		case "author", "wordCount":
		default:
			errs = append(errs, Violation{k, "unknown field"})
		}
	}
	get := func(k string) *json.RawMessage {
		if v, ok := all[k]; ok {
			return &v
		}
		return nil
	}
	_ = get
	if v, ok := parseStringField(get("author"), "author", true, false, &errs); ok {
		m.Author = v
	}
	if v, ok := parseIntegerField(get("wordCount"), "wordCount", false, false, &errs); ok {
		m.WordCount = &v
	}
	if len(errs) > 0 {
		return &ValidationError{Violations: errs}
	}
	return nil
}

// MarshalJSON validates m, then serializes it to JSON, returning a
// *ValidationError if validation fails.
func (m PageMeta) MarshalJSON() ([]byte, error) {
	var errs []Violation
	addViolations(&errs, m.Validate())
	out := map[string]json.RawMessage{}
	marshalField(out, "author", m.Author, &errs)
	if m.WordCount != nil {
		marshalField(out, "wordCount", *m.WordCount, &errs)
	}
	if len(errs) > 0 {
		return nil, &ValidationError{Violations: errs}
	}
	return json.Marshal(out)
}
