// Code generated by nexgen v0.2.1. DO NOT EDIT.
package kb

import (
	"encoding/json"
	"fmt"
)

// Category A node in a self-recursive category tree. The root of this file is itself a
// type (pure JSON Schema file), named Category from the basename.
type Category struct {
	// Id corresponds to the "id" JSON property.
	Id string `json:"id"`
	// Name corresponds to the "name" JSON property.
	Name string `json:"name"`
	// Children Sub-categories. A within-file self-cycle via `$ref: '#'`; the
	// possibly-empty array is the terminating edge, so it stays in this module.
	Children []Category `json:"children,omitempty"`
}

// Validate checks m against every constraint and returns a *ValidationError
// listing any violations.
func (m Category) Validate() error {
	var errs []Violation
	for i0, v0 := range m.Children {
		p0 := fmt.Sprintf("%s[%d]", "children", i0)
		mergeNested(&errs, p0, v0.Validate())
	}
	if len(errs) > 0 {
		return &ValidationError{Violations: errs}
	}
	return nil
}

// UnmarshalJSON parses data into m and validates it, returning a
// *ValidationError listing any violations.
func (m *Category) UnmarshalJSON(data []byte) error {
	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	var errs []Violation
	for k := range all {
		switch k {
		case "id", "name", "children":
		default:
			errs = append(errs, Violation{k, "unknown field"})
		}
	}
	get := func(k string) *json.RawMessage {
		if v, ok := all[k]; ok {
			return &v
		}
		return nil
	}
	_ = get
	if v, ok := parseStringField(get("id"), "id", true, false, &errs); ok {
		m.Id = v
	}
	if v, ok := parseStringField(get("name"), "name", true, false, &errs); ok {
		m.Name = v
	}
	if raw := get("children"); raw == nil {
	} else if isNull(*raw) {
		errs = append(errs, Violation{"children", "explicit null not allowed"})
	} else {
		var elems0 []json.RawMessage
		if err := json.Unmarshal(*raw, &elems0); err != nil {
			errs = append(errs, Violation{"children", "expected array"})
		} else {
			m.Children = make([]Category, 0, len(elems0))
			for i0, e0 := range elems0 {
				p0 := fmt.Sprintf("%s[%d]", "children", i0)
				if isNull(e0) {
					errs = append(errs, Violation{p0, "explicit null not allowed"})
					continue
				}
				var value0 Category
				if err := json.Unmarshal(e0, &value0); err != nil {
					mergeNested(&errs, p0, err)
				} else {
					m.Children = append(m.Children, value0)
				}
			}
		}
	}
	if len(errs) > 0 {
		return &ValidationError{Violations: errs}
	}
	return nil
}

// MarshalJSON validates m, then serializes it to JSON, returning a
// *ValidationError if validation fails.
func (m Category) MarshalJSON() ([]byte, error) {
	var errs []Violation
	addViolations(&errs, m.Validate())
	out := map[string]json.RawMessage{}
	marshalField(out, "id", m.Id, &errs)
	marshalField(out, "name", m.Name, &errs)
	if m.Children != nil {
		marshalField(out, "children", m.Children, &errs)
	}
	if len(errs) > 0 {
		return nil, &ValidationError{Violations: errs}
	}
	return json.Marshal(out)
}

// Palette A dead $def - defined but never referenced anywhere. Still generated and
// exported as intended reusable API surface (see the $ref spec).
type Palette struct {
	// Swatches corresponds to the "swatches" JSON property.
	Swatches []string `json:"swatches"`
}

// Validate checks m against every constraint and returns a *ValidationError
// listing any violations.
func (m Palette) Validate() error {
	var errs []Violation
	if len(errs) > 0 {
		return &ValidationError{Violations: errs}
	}
	return nil
}

// UnmarshalJSON parses data into m and validates it, returning a
// *ValidationError listing any violations.
func (m *Palette) UnmarshalJSON(data []byte) error {
	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	var errs []Violation
	for k := range all {
		switch k {
		case "swatches":
		default:
			errs = append(errs, Violation{k, "unknown field"})
		}
	}
	get := func(k string) *json.RawMessage {
		if v, ok := all[k]; ok {
			return &v
		}
		return nil
	}
	_ = get
	if raw := get("swatches"); raw == nil {
		errs = append(errs, Violation{"swatches", "required"})
	} else if isNull(*raw) {
		errs = append(errs, Violation{"swatches", "explicit null not allowed"})
	} else {
		var elems0 []json.RawMessage
		if err := json.Unmarshal(*raw, &elems0); err != nil {
			errs = append(errs, Violation{"swatches", "expected array"})
		} else {
			m.Swatches = make([]string, 0, len(elems0))
			for i0, e0 := range elems0 {
				p0 := fmt.Sprintf("%s[%d]", "swatches", i0)
				if isNull(e0) {
					errs = append(errs, Violation{p0, "explicit null not allowed"})
					continue
				}
				if value0, ok := parseStringField(&e0, p0, true, false, &errs); ok {
					m.Swatches = append(m.Swatches, value0)
				}
			}
		}
	}
	if len(errs) > 0 {
		return &ValidationError{Violations: errs}
	}
	return nil
}

// MarshalJSON validates m, then serializes it to JSON, returning a
// *ValidationError if validation fails.
func (m Palette) MarshalJSON() ([]byte, error) {
	var errs []Violation
	addViolations(&errs, m.Validate())
	out := map[string]json.RawMessage{}
	marshalField(out, "swatches", m.Swatches, &errs)
	if len(errs) > 0 {
		return nil, &ValidationError{Violations: errs}
	}
	return json.Marshal(out)
}
