// Code generated by nexgen. DO NOT EDIT.

package startworkflow

import (
	"time"

	common "go.temporal.io/api/common/v1"
	workflowservice "go.temporal.io/api/workflowservice/v1"
	"go.temporal.io/sdk/workflow"
)

// --- Datatypes ---

type startWorkflowRequest struct {
	Workflow           string
	WorkflowID         string
	TaskQueue          string
	WorkflowStartDelay *time.Duration
}

func (m startWorkflowRequest) toProto(ctx workflow.Context) (*workflowservice.StartWorkflowExecutionRequest, error) {
	message := &workflowservice.StartWorkflowExecutionRequest{}
	{
		converted, err := workflowTypeToProto(ctx, &m.Workflow)
		if err != nil {
			return nil, err
		}
		message.WorkflowType = converted
	}
	message.WorkflowId = m.WorkflowID
	{
		converted, err := taskQueueToProto(ctx, &m.TaskQueue)
		if err != nil {
			return nil, err
		}
		message.TaskQueue = converted
	}
	{
		converted, err := durationToProto(ctx, m.WorkflowStartDelay)
		if err != nil {
			return nil, err
		}
		message.WorkflowStartDelay = converted
	}
	message.Namespace = workflow.GetInfo(ctx).Namespace
	return message, nil
}

func startWorkflowRequestFromProto(ctx workflow.Context, proto *workflowservice.StartWorkflowExecutionRequest) (startWorkflowRequest, error) {
	value := startWorkflowRequest{}
	{
		converted, err := workflowTypeFromProto(ctx, proto.GetWorkflowType())
		if err != nil {
			return value, err
		}
		if converted != nil {
			value.Workflow = *converted
		}
	}
	value.WorkflowID = proto.GetWorkflowId()
	{
		converted, err := taskQueueFromProto(ctx, proto.GetTaskQueue())
		if err != nil {
			return value, err
		}
		if converted != nil {
			value.TaskQueue = *converted
		}
	}
	{
		converted, err := durationFromProto(ctx, proto.GetWorkflowStartDelay())
		if err != nil {
			return value, err
		}
		value.WorkflowStartDelay = converted
	}
	return value, nil
}

type cancelWorkflowRequest struct {
	WorkflowExecution WorkflowExecution
	Reason            *string
}

func (m cancelWorkflowRequest) toProto(ctx workflow.Context) (*workflowservice.RequestCancelWorkflowExecutionRequest, error) {
	message := &workflowservice.RequestCancelWorkflowExecutionRequest{}
	{
		converted, err := m.WorkflowExecution.toProto(ctx)
		if err != nil {
			return nil, err
		}
		message.WorkflowExecution = converted
	}
	if m.Reason != nil {
		message.Reason = (*m.Reason)
	}
	message.Namespace = workflow.GetInfo(ctx).Namespace
	return message, nil
}

func cancelWorkflowRequestFromProto(ctx workflow.Context, proto *workflowservice.RequestCancelWorkflowExecutionRequest) (cancelWorkflowRequest, error) {
	value := cancelWorkflowRequest{}
	{
		converted, err := workflowExecutionFromProto(ctx, proto.GetWorkflowExecution())
		if err != nil {
			return value, err
		}
		value.WorkflowExecution = converted
	}
	{
		converted := proto.GetReason()
		value.Reason = &converted
	}
	return value, nil
}

type startWorkflowResult struct {
	RunID *string
}

func (m startWorkflowResult) toProto(ctx workflow.Context) (*workflowservice.StartWorkflowExecutionResponse, error) {
	message := &workflowservice.StartWorkflowExecutionResponse{}
	if m.RunID != nil {
		message.RunId = (*m.RunID)
	}
	return message, nil
}

func startWorkflowResultFromProto(ctx workflow.Context, proto *workflowservice.StartWorkflowExecutionResponse) (startWorkflowResult, error) {
	value := startWorkflowResult{}
	{
		converted := proto.GetRunId()
		value.RunID = &converted
	}
	return value, nil
}

// --- Resources ---

type StartedWorkflow struct {
	// Namespace - Required.
	Namespace string
	// WorkflowID - Required.
	WorkflowID string
	// RunID - Optional.
	RunID *string
}

func NewStartedWorkflow(namespace string, workflowID string, runID string) StartedWorkflow {
	var runIDPtr *string
	if runID != "" {
		runIDPtr = &runID
	}
	return StartedWorkflow{
		Namespace:  namespace,
		WorkflowID: workflowID,
		RunID:      runIDPtr,
	}
}

func (u *StartedWorkflow) Cancel(ctx workflow.Context, reason string) workflow.Future {
	var reasonPtr *string
	if reason != "" {
		reasonPtr = &reason
	}
	return cancelWorkflow(ctx, cancelWorkflowRequest{WorkflowExecution: WorkflowExecution{WorkflowID: u.WorkflowID, RunID: u.RunID}, Reason: reasonPtr})
}

func (u *StartedWorkflow) RestartWorkflow(ctx workflow.Context, workflow string, taskQueue string) workflow.Future {
	return restartWorkflow(ctx, startWorkflowRequest{WorkflowID: u.WorkflowID, Workflow: workflow, TaskQueue: taskQueue})
}

func (u *StartedWorkflow) GetResult(ctx workflow.Context) workflow.Future {
	panic("StartedWorkflow.GetResult is not yet implemented")
}

// --- Operations (internal) ---

func startWorkflow(ctx workflow.Context, request startWorkflowRequest) workflow.Future {
	requestProto, err := request.toProto(ctx)
	if err != nil {
		result, resultSettable := workflow.NewFuture(ctx)
		resultSettable.SetError(err)
		return result
	}
	c := workflow.NewNexusClient("temporal-system", "StartWorkflowService")
	fut := c.ExecuteOperation(ctx, "StartWorkflow", requestProto, workflow.NexusOperationOptions{})
	result, resultSettable := workflow.NewFuture(ctx)
	workflow.Go(ctx, func(ctx workflow.Context) {
		var result workflowservice.StartWorkflowExecutionResponse
		if err := fut.Get(ctx, &result); err != nil {
			resultSettable.SetError(err)
			return
		}
		value := NewStartedWorkflow(requestProto.GetNamespace(), request.WorkflowID, result.GetRunId())
		resultSettable.Set(value, nil)
	})
	return result
}

func restartWorkflow(ctx workflow.Context, request startWorkflowRequest) workflow.Future {
	requestProto, err := request.toProto(ctx)
	if err != nil {
		result, resultSettable := workflow.NewFuture(ctx)
		resultSettable.SetError(err)
		return result
	}
	c := workflow.NewNexusClient("temporal-system", "StartWorkflowService")
	fut := c.ExecuteOperation(ctx, "RestartWorkflow", requestProto, workflow.NexusOperationOptions{})
	result, resultSettable := workflow.NewFuture(ctx)
	workflow.Go(ctx, func(ctx workflow.Context) {
		var result workflowservice.StartWorkflowExecutionResponse
		if err := fut.Get(ctx, &result); err != nil {
			resultSettable.SetError(err)
			return
		}
		value := NewStartedWorkflow(requestProto.GetNamespace(), request.WorkflowID, result.GetRunId())
		resultSettable.Set(value, nil)
	})
	return result
}

func cancelWorkflow(ctx workflow.Context, request cancelWorkflowRequest) workflow.Future {
	requestProto, err := request.toProto(ctx)
	if err != nil {
		result, resultSettable := workflow.NewFuture(ctx)
		resultSettable.SetError(err)
		return result
	}
	c := workflow.NewNexusClient("temporal-system", "StartWorkflowService")
	fut := c.ExecuteOperation(ctx, "CancelWorkflow", requestProto, workflow.NexusOperationOptions{})
	result, resultSettable := workflow.NewFuture(ctx)
	workflow.Go(ctx, func(ctx workflow.Context) {
		var result workflowservice.RequestCancelWorkflowExecutionResponse
		if err := fut.Get(ctx, &result); err != nil {
			resultSettable.SetError(err)
			return
		}
		value, err := cancelWorkflowResponseFromProto(ctx, &result)
		if err != nil {
			resultSettable.SetError(err)
			return
		}
		resultSettable.Set(value, nil)
	})
	return result
}

// --- Operations (public API) ---

type WorkflowExecution struct {
	// WorkflowID - Required.
	WorkflowID string
	// RunID - Optional.
	RunID *string
}

func (m WorkflowExecution) toProto(ctx workflow.Context) (*common.WorkflowExecution, error) {
	message := &common.WorkflowExecution{}
	message.WorkflowId = m.WorkflowID
	if m.RunID != nil {
		message.RunId = (*m.RunID)
	}
	return message, nil
}

func workflowExecutionFromProto(ctx workflow.Context, proto *common.WorkflowExecution) (WorkflowExecution, error) {
	value := WorkflowExecution{}
	value.WorkflowID = proto.GetWorkflowId()
	{
		converted := proto.GetRunId()
		value.RunID = &converted
	}
	return value, nil
}

type CancelWorkflowResponse struct {
}

func (m CancelWorkflowResponse) toProto(ctx workflow.Context) (*workflowservice.RequestCancelWorkflowExecutionResponse, error) {
	message := &workflowservice.RequestCancelWorkflowExecutionResponse{}
	return message, nil
}

func cancelWorkflowResponseFromProto(ctx workflow.Context, proto *workflowservice.RequestCancelWorkflowExecutionResponse) (CancelWorkflowResponse, error) {
	value := CancelWorkflowResponse{}
	return value, nil
}

type StartWorkflowOptions struct {
	// Workflow - Required.
	Workflow string
	// WorkflowID - Required.
	WorkflowID string
	// TaskQueue - Required.
	TaskQueue string
	// WorkflowStartDelay - Optional.
	WorkflowStartDelay time.Duration
}

func StartWorkflow(ctx workflow.Context, opts StartWorkflowOptions) workflow.Future {
	var workflowStartDelay *time.Duration
	if opts.WorkflowStartDelay != 0 {
		workflowStartDelay = &opts.WorkflowStartDelay
	}
	return startWorkflow(ctx, startWorkflowRequest{
		Workflow:           opts.Workflow,
		WorkflowID:         opts.WorkflowID,
		TaskQueue:          opts.TaskQueue,
		WorkflowStartDelay: workflowStartDelay,
	})
}

type RestartWorkflowOptions struct {
	// Workflow - Required.
	Workflow string
	// WorkflowID - Required.
	WorkflowID string
	// TaskQueue - Required.
	TaskQueue string
	// WorkflowStartDelay - Optional.
	WorkflowStartDelay time.Duration
}

func RestartWorkflow(ctx workflow.Context, opts RestartWorkflowOptions) workflow.Future {
	var workflowStartDelay *time.Duration
	if opts.WorkflowStartDelay != 0 {
		workflowStartDelay = &opts.WorkflowStartDelay
	}
	return restartWorkflow(ctx, startWorkflowRequest{
		Workflow:           opts.Workflow,
		WorkflowID:         opts.WorkflowID,
		TaskQueue:          opts.TaskQueue,
		WorkflowStartDelay: workflowStartDelay,
	})
}

type CancelWorkflowOptions struct {
	// WorkflowExecution - Required.
	WorkflowExecution WorkflowExecution
	// Reason - Optional.
	Reason string
}

func CancelWorkflow(ctx workflow.Context, opts CancelWorkflowOptions) workflow.Future {
	var reason *string
	if opts.Reason != "" {
		reason = &opts.Reason
	}
	return cancelWorkflow(ctx, cancelWorkflowRequest{
		WorkflowExecution: opts.WorkflowExecution,
		Reason:            reason,
	})
}
