// Code generated by nexgen latest. DO NOT EDIT.

package startworkflow

import (
	"context"
	"errors"
	"time"

	common "go.temporal.io/api/common/v1"
	workflowservice "go.temporal.io/api/workflowservice/v1"
	"go.temporal.io/sdk/converter"
	"go.temporal.io/sdk/internal"
	"go.temporal.io/sdk/workflow"
)

// --- Datatypes ---

type startWorkflowRequest struct {
	Workflow           string
	WorkflowID         string
	TaskQueue          string
	WorkflowStartDelay *time.Duration
	namespace          string
}

func startWorkflowRequestToProto(ctx workflow.Context, m *startWorkflowRequest) (*workflowservice.StartWorkflowExecutionRequest, error) {
	message := &workflowservice.StartWorkflowExecutionRequest{}
	{
		converted, err := workflowTypeToProto(ctx, &m.Workflow)
		if err != nil {
			return nil, err
		}
		message.WorkflowType = converted
	}
	message.WorkflowId = m.WorkflowID
	{
		converted, err := taskQueueToProto(ctx, &m.TaskQueue)
		if err != nil {
			return nil, err
		}
		message.TaskQueue = converted
	}
	{
		converted, err := durationToProto(ctx, m.WorkflowStartDelay)
		if err != nil {
			return nil, err
		}
		message.WorkflowStartDelay = converted
	}
	message.Namespace = m.namespace
	return message, nil
}

func startWorkflowRequestFromProto(ctx workflow.Context, proto *workflowservice.StartWorkflowExecutionRequest, out *startWorkflowRequest) error {
	*out = startWorkflowRequest{}
	{
		converted, err := workflowTypeFromProto(ctx, proto.GetWorkflowType())
		if err != nil {
			return err
		}
		if converted != nil {
			out.Workflow = *converted
		}
	}
	out.WorkflowID = proto.GetWorkflowId()
	{
		converted, err := taskQueueFromProto(ctx, proto.GetTaskQueue())
		if err != nil {
			return err
		}
		if converted != nil {
			out.TaskQueue = *converted
		}
	}
	{
		converted, err := durationFromProto(ctx, proto.GetWorkflowStartDelay())
		if err != nil {
			return err
		}
		out.WorkflowStartDelay = converted
	}
	out.namespace = proto.GetNamespace()
	return nil
}

func (startWorkflowRequest) TransferTypeConverter() (converter.TransferTypeConverter, error) {
	return converter.NewContextualTransferTypeConverter(
		func(context.Context, *startWorkflowRequest) (*workflowservice.StartWorkflowExecutionRequest, error) {
			return nil, errors.New("nexgen: transfer type converter outside a workflow")
		},
		func(context.Context, *workflowservice.StartWorkflowExecutionRequest, *startWorkflowRequest) error {
			return errors.New("nexgen: transfer type converter outside a workflow")
		},
		startWorkflowRequestToProto,
		startWorkflowRequestFromProto,
	)
}

type cancelWorkflowRequest struct {
	WorkflowExecution WorkflowExecution
	Reason            *string
	namespace         string
}

func cancelWorkflowRequestToProto(ctx workflow.Context, m *cancelWorkflowRequest) (*workflowservice.RequestCancelWorkflowExecutionRequest, error) {
	message := &workflowservice.RequestCancelWorkflowExecutionRequest{}
	{
		converted, err := workflowExecutionToProto(ctx, &m.WorkflowExecution)
		if err != nil {
			return nil, err
		}
		message.WorkflowExecution = converted
	}
	if m.Reason != nil {
		message.Reason = (*m.Reason)
	}
	message.Namespace = m.namespace
	return message, nil
}

func cancelWorkflowRequestFromProto(ctx workflow.Context, proto *workflowservice.RequestCancelWorkflowExecutionRequest, out *cancelWorkflowRequest) error {
	*out = cancelWorkflowRequest{}
	if err := workflowExecutionFromProto(ctx, proto.GetWorkflowExecution(), &out.WorkflowExecution); err != nil {
		return err
	}
	{
		converted := proto.GetReason()
		out.Reason = &converted
	}
	out.namespace = proto.GetNamespace()
	return nil
}

func (cancelWorkflowRequest) TransferTypeConverter() (converter.TransferTypeConverter, error) {
	return converter.NewContextualTransferTypeConverter(
		func(context.Context, *cancelWorkflowRequest) (*workflowservice.RequestCancelWorkflowExecutionRequest, error) {
			return nil, errors.New("nexgen: transfer type converter outside a workflow")
		},
		func(context.Context, *workflowservice.RequestCancelWorkflowExecutionRequest, *cancelWorkflowRequest) error {
			return errors.New("nexgen: transfer type converter outside a workflow")
		},
		cancelWorkflowRequestToProto,
		cancelWorkflowRequestFromProto,
	)
}

type startWorkflowResult struct {
	RunID *string
}

func startWorkflowResultToProto(ctx workflow.Context, m *startWorkflowResult) (*workflowservice.StartWorkflowExecutionResponse, error) {
	message := &workflowservice.StartWorkflowExecutionResponse{}
	if m.RunID != nil {
		message.RunId = (*m.RunID)
	}
	return message, nil
}

func startWorkflowResultFromProto(ctx workflow.Context, proto *workflowservice.StartWorkflowExecutionResponse, out *startWorkflowResult) error {
	*out = startWorkflowResult{}
	{
		converted := proto.GetRunId()
		out.RunID = &converted
	}
	return nil
}

// --- Resources ---

type StartedWorkflow struct {
	// Namespace - Required.
	Namespace string
	// WorkflowID - Required.
	WorkflowID string
	// RunID - Optional.
	RunID *string
}

func NewStartedWorkflow(namespace string, workflowID string, runID string) StartedWorkflow {
	var runIDPtr *string
	if runID != "" {
		runIDPtr = &runID
	}
	return StartedWorkflow{
		Namespace:  namespace,
		WorkflowID: workflowID,
		RunID:      runIDPtr,
	}
}

func (u *StartedWorkflow) Cancel(ctx workflow.Context, reason string) workflow.Future {
	var reasonPtr *string
	if reason != "" {
		reasonPtr = &reason
	}
	return cancelWorkflow(ctx, cancelWorkflowRequest{WorkflowExecution: WorkflowExecution{WorkflowID: u.WorkflowID, RunID: u.RunID}, Reason: reasonPtr})
}

func (u *StartedWorkflow) RestartWorkflow(ctx workflow.Context, workflow string, taskQueue string) workflow.Future {
	return restartWorkflow(ctx, startWorkflowRequest{WorkflowID: u.WorkflowID, Workflow: workflow, TaskQueue: taskQueue})
}

func (u *StartedWorkflow) GetResult(ctx workflow.Context) workflow.Future {
	panic("StartedWorkflow.GetResult is not yet implemented")
}

// --- Operations (internal) ---

func startWorkflow(ctx workflow.Context, request startWorkflowRequest) workflow.Future {
	request.namespace = workflow.GetInfo(ctx).Namespace
	c := workflow.NewNexusClient("temporal-system", "StartWorkflowService")
	fut := c.ExecuteOperation(ctx, "StartWorkflow", request, workflow.NexusOperationOptions{})
	result, resultSettable := workflow.NewFuture(ctx)
	workflow.Go(ctx, func(ctx workflow.Context) {
		var result workflowservice.StartWorkflowExecutionResponse
		if err := fut.Get(ctx, &result); err != nil {
			resultSettable.SetError(err)
			return
		}
		ctx = internal.NexusOperationPayloadContext(ctx, fut)
		value := NewStartedWorkflow(request.namespace, request.WorkflowID, result.GetRunId())
		resultSettable.Set(value, nil)
	})
	return result
}

func restartWorkflow(ctx workflow.Context, request startWorkflowRequest) workflow.Future {
	request.namespace = workflow.GetInfo(ctx).Namespace
	c := workflow.NewNexusClient("temporal-system", "StartWorkflowService")
	fut := c.ExecuteOperation(ctx, "RestartWorkflow", request, workflow.NexusOperationOptions{})
	result, resultSettable := workflow.NewFuture(ctx)
	workflow.Go(ctx, func(ctx workflow.Context) {
		var result workflowservice.StartWorkflowExecutionResponse
		if err := fut.Get(ctx, &result); err != nil {
			resultSettable.SetError(err)
			return
		}
		ctx = internal.NexusOperationPayloadContext(ctx, fut)
		value := NewStartedWorkflow(request.namespace, request.WorkflowID, result.GetRunId())
		resultSettable.Set(value, nil)
	})
	return result
}

func cancelWorkflow(ctx workflow.Context, request cancelWorkflowRequest) workflow.Future {
	request.namespace = workflow.GetInfo(ctx).Namespace
	c := workflow.NewNexusClient("temporal-system", "StartWorkflowService")
	fut := c.ExecuteOperation(ctx, "CancelWorkflow", request, workflow.NexusOperationOptions{})
	result, resultSettable := workflow.NewFuture(ctx)
	workflow.Go(ctx, func(ctx workflow.Context) {
		var value CancelWorkflowResponse
		if err := fut.Get(ctx, &value); err != nil {
			resultSettable.SetError(err)
			return
		}
		resultSettable.Set(value, nil)
	})
	return result
}

// --- Operations (public API) ---

type WorkflowExecution struct {
	// WorkflowID - Required.
	WorkflowID string
	// RunID - Optional.
	RunID *string
}

func workflowExecutionToProto(ctx workflow.Context, m *WorkflowExecution) (*common.WorkflowExecution, error) {
	message := &common.WorkflowExecution{}
	message.WorkflowId = m.WorkflowID
	if m.RunID != nil {
		message.RunId = (*m.RunID)
	}
	return message, nil
}

func workflowExecutionFromProto(ctx workflow.Context, proto *common.WorkflowExecution, out *WorkflowExecution) error {
	*out = WorkflowExecution{}
	out.WorkflowID = proto.GetWorkflowId()
	{
		converted := proto.GetRunId()
		out.RunID = &converted
	}
	return nil
}

type CancelWorkflowResponse struct {
}

func cancelWorkflowResponseToProto(ctx workflow.Context, m *CancelWorkflowResponse) (*workflowservice.RequestCancelWorkflowExecutionResponse, error) {
	message := &workflowservice.RequestCancelWorkflowExecutionResponse{}
	return message, nil
}

func cancelWorkflowResponseFromProto(ctx workflow.Context, proto *workflowservice.RequestCancelWorkflowExecutionResponse, out *CancelWorkflowResponse) error {
	*out = CancelWorkflowResponse{}
	return nil
}

func (CancelWorkflowResponse) TransferTypeConverter() (converter.TransferTypeConverter, error) {
	return converter.NewContextualTransferTypeConverter(
		func(context.Context, *CancelWorkflowResponse) (*workflowservice.RequestCancelWorkflowExecutionResponse, error) {
			return nil, errors.New("nexgen: transfer type converter outside a workflow")
		},
		func(context.Context, *workflowservice.RequestCancelWorkflowExecutionResponse, *CancelWorkflowResponse) error {
			return errors.New("nexgen: transfer type converter outside a workflow")
		},
		cancelWorkflowResponseToProto,
		cancelWorkflowResponseFromProto,
	)
}

type StartWorkflowOptions struct {
	// Workflow - Required.
	Workflow string
	// WorkflowID - Required.
	WorkflowID string
	// TaskQueue - Required.
	TaskQueue string
	// WorkflowStartDelay - Optional.
	WorkflowStartDelay time.Duration
}

func StartWorkflow(ctx workflow.Context, opts StartWorkflowOptions) workflow.Future {
	var workflowStartDelay *time.Duration
	if opts.WorkflowStartDelay != 0 {
		workflowStartDelay = &opts.WorkflowStartDelay
	}
	return startWorkflow(ctx, startWorkflowRequest{
		Workflow:           opts.Workflow,
		WorkflowID:         opts.WorkflowID,
		TaskQueue:          opts.TaskQueue,
		WorkflowStartDelay: workflowStartDelay,
	})
}

type RestartWorkflowOptions struct {
	// Workflow - Required.
	Workflow string
	// WorkflowID - Required.
	WorkflowID string
	// TaskQueue - Required.
	TaskQueue string
	// WorkflowStartDelay - Optional.
	WorkflowStartDelay time.Duration
}

func RestartWorkflow(ctx workflow.Context, opts RestartWorkflowOptions) workflow.Future {
	var workflowStartDelay *time.Duration
	if opts.WorkflowStartDelay != 0 {
		workflowStartDelay = &opts.WorkflowStartDelay
	}
	return restartWorkflow(ctx, startWorkflowRequest{
		Workflow:           opts.Workflow,
		WorkflowID:         opts.WorkflowID,
		TaskQueue:          opts.TaskQueue,
		WorkflowStartDelay: workflowStartDelay,
	})
}

type CancelWorkflowOptions struct {
	// WorkflowExecution - Required.
	WorkflowExecution WorkflowExecution
	// Reason - Optional.
	Reason string
}

func CancelWorkflow(ctx workflow.Context, opts CancelWorkflowOptions) workflow.Future {
	var reason *string
	if opts.Reason != "" {
		reason = &opts.Reason
	}
	return cancelWorkflow(ctx, cancelWorkflowRequest{
		WorkflowExecution: opts.WorkflowExecution,
		Reason:            reason,
	})
}
