// Generated by nexgen latest. DO NOT EDIT!

import * as workflow from "@temporalio/workflow";
import { startWorkflowService } from "../services";
import { requiredField } from "../models";
import type { StartWorkflowRequest } from "../models";
import { workflowNamespace } from "../support";
import { StartedWorkflow } from "../resources";

type StartWorkflowInput = StartWorkflowRequest extends infer Input
  ? Input extends unknown
    ? Omit<Input, "namespace"> & { namespace?: never }
    : never
  : never;

/**
 * @param request - Request for the operation.
 */
export async function startWorkflow(
  requestInput: StartWorkflowInput,
): Promise<StartedWorkflow> {
  const request = {
    ...requestInput,
    namespace: workflowNamespace(),
  } as StartWorkflowRequest;
  const client = workflow.createNexusServiceClient({
    service: startWorkflowService,
    endpoint: "temporal-system",
  });
  const handle = await client.startOperation(
    startWorkflowService.operations.startWorkflow,
    request,
  );
  const result = await handle.result();
  return new StartedWorkflow(
    requiredField(request.namespace, "resource", "namespace"),
    request.workflowId,
    result.runId ?? undefined,
  );
}
