// Generated by nexgen latest. DO NOT EDIT!

import * as workflow from "@temporalio/workflow";
import { startWorkflowService } from "../services";
import { requiredField, startWorkflowRequestToProto } from "../models";
import type { StartWorkflowRequest } from "../models";
import { workflowNamespace } from "../support";
import { StartedWorkflow } from "../resources";

type StartWorkflowInput = Omit<StartWorkflowRequest, "namespace"> & {
  namespace?: never;
};

/**
 * @param request - Request for the operation.
 */
export async function startWorkflow(
  requestInput: StartWorkflowInput,
): Promise<StartedWorkflow> {
  const request = {
    ...requestInput,
    namespace: workflowNamespace(),
  } as StartWorkflowRequest;
  const client = workflow.createNexusServiceClient({
    service: startWorkflowService,
    endpoint: "temporal-system",
  });
  const requestProto = startWorkflowRequestToProto(request) ?? {};
  const handle = await client.startOperation(
    startWorkflowService.operations.startWorkflow,
    requestProto,
  );
  const result = await handle.result();
  return new StartedWorkflow(
    requiredField(requestProto.namespace, "resource", "namespace"),
    request.workflowId,
    result.runId ?? undefined,
  );
}
