// Code generated by nexgen v0.2.1. DO NOT EDIT.
package kb

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"math"
	"math/big"
	"reflect"
	"strconv"
	"strings"
)

// Violation is a single constraint failure. Path is the JSON member path
// (dotted for nested members); Reason is a human-readable message.
type Violation struct {
	Path   string
	Reason string
}

// String implements fmt.Stringer, returning "Path: Reason", or just Reason
// when Path is empty.
func (v Violation) String() string {
	if v.Path == "" {
		return v.Reason
	}
	return v.Path + ": " + v.Reason
}

// ValidationError aggregates every Violation found while (de)serializing a
// value, surfacing them all in one error (never a partial first-failure).
type ValidationError struct {
	Violations []Violation
}

// Error implements the error interface, joining every Violation into one
// message.
func (e *ValidationError) Error() string {
	parts := make([]string, len(e.Violations))
	for i, v := range e.Violations {
		parts[i] = v.String()
	}
	return fmt.Sprintf("%d validation error(s): %s", len(e.Violations), strings.Join(parts, "; "))
}

func addViolations(errs *[]Violation, err error) {
	if err == nil {
		return
	}
	var ve *ValidationError
	if errors.As(err, &ve) {
		*errs = append(*errs, ve.Violations...)
		return
	}
	*errs = append(*errs, Violation{"", err.Error()})
}

func mergeNested(errs *[]Violation, path string, err error) {
	if err == nil {
		return
	}
	var ve *ValidationError
	if errors.As(err, &ve) {
		for _, v := range ve.Violations {
			p := v.Path
			if p == "" {
				p = path
			} else {
				p = path + "." + v.Path
			}
			if strings.HasPrefix(v.Path, "[") {
				p = path + v.Path
			}
			*errs = append(*errs, Violation{p, v.Reason})
		}
		return
	}
	*errs = append(*errs, Violation{path, err.Error()})
}

const integerCap = 1<<53 - 1

func isJSONMultiple(value float64, divisor string) bool {
	v, ok := new(big.Rat).SetString(strconv.FormatFloat(value, 'g', -1, 64))
	if !ok {
		return false
	}
	d, ok := new(big.Rat).SetString(divisor)
	if !ok || d.Sign() == 0 {
		return false
	}
	return new(big.Rat).Quo(v, d).IsInt()
}

var (
	errFractional = errors.New("not an integer")
	errRange      = errors.New("exceeds ±(2^53-1) integer cap")
)

func parseSpecInteger(n json.Number) (int64, error) {
	s := n.String()
	negative := strings.HasPrefix(s, "-")
	if negative {
		s = s[1:]
	}
	exponentText := ""
	if i := strings.IndexAny(s, "eE"); i >= 0 {
		exponentText = s[i+1:]
		s = s[:i]
	}
	fractionalDigits := int64(0)
	if i := strings.IndexByte(s, '.'); i >= 0 {
		fractionalDigits = int64(len(s) - i - 1)
		s = s[:i] + s[i+1:]
	}
	digits := strings.TrimLeft(s, "0")
	if digits == "" {
		return 0, nil
	}
	var exponent int64
	if exponentText != "" {
		var err error
		exponent, err = strconv.ParseInt(exponentText, 10, 64)
		if err != nil {
			if strings.HasPrefix(exponentText, "-") {
				return 0, errFractional
			}
			return 0, errRange
		}
	}
	if exponent < -int64(len(digits)) {
		return 0, errFractional
	}
	scale := exponent - fractionalDigits
	if scale < 0 {
		trim := -scale
		if trim > int64(len(digits)) || strings.Trim(digits[len(digits)-int(trim):], "0") != "" {
			return 0, errFractional
		}
		digits = digits[:len(digits)-int(trim)]
	} else {
		if scale > int64(len("9007199254740991")) {
			return 0, errRange
		}
		digits += strings.Repeat("0", int(scale))
	}
	const capText = "9007199254740991"
	if len(digits) > len(capText) || len(digits) == len(capText) && digits > capText {
		return 0, errRange
	}
	v, err := strconv.ParseInt(digits, 10, 64)
	if err != nil {
		return 0, errRange
	}
	if negative {
		v = -v
	}
	return v, nil
}

func isNilValue(v any) bool {
	if v == nil {
		return true
	}
	rv := reflect.ValueOf(v)
	switch rv.Kind() {
	case reflect.Chan, reflect.Func, reflect.Interface, reflect.Map, reflect.Pointer, reflect.Slice:
		return rv.IsNil()
	default:
		return false
	}
}

func isNull(raw json.RawMessage) bool {
	return bytes.Equal(bytes.TrimSpace(raw), []byte("null"))
}

func parseStringField(raw *json.RawMessage, path string, required, nullable bool, errs *[]Violation) (string, bool) {
	if raw == nil {
		if required {
			*errs = append(*errs, Violation{path, "required"})
		}
		return "", false
	}
	if isNull(*raw) {
		if !nullable {
			*errs = append(*errs, Violation{path, "explicit null not allowed"})
		}
		return "", false
	}
	var s string
	if err := json.Unmarshal(*raw, &s); err != nil {
		*errs = append(*errs, Violation{path, "expected string"})
		return "", false
	}
	return s, true
}

func parseIntegerField(raw *json.RawMessage, path string, required, nullable bool, errs *[]Violation) (int64, bool) {
	if raw == nil {
		if required {
			*errs = append(*errs, Violation{path, "required"})
		}
		return 0, false
	}
	if isNull(*raw) {
		if !nullable {
			*errs = append(*errs, Violation{path, "explicit null not allowed"})
		}
		return 0, false
	}
	dec := json.NewDecoder(bytes.NewReader(*raw))
	dec.UseNumber()
	var n json.Number
	if err := dec.Decode(&n); err != nil {
		*errs = append(*errs, Violation{path, "expected integer"})
		return 0, false
	}
	v, err := parseSpecInteger(n)
	if err != nil {
		*errs = append(*errs, Violation{path, err.Error()})
		return 0, false
	}
	return v, true
}

func parseNumberField(raw *json.RawMessage, path string, required, nullable bool, errs *[]Violation) (float64, bool) {
	if raw == nil {
		if required {
			*errs = append(*errs, Violation{path, "required"})
		}
		return 0, false
	}
	if isNull(*raw) {
		if !nullable {
			*errs = append(*errs, Violation{path, "explicit null not allowed"})
		}
		return 0, false
	}
	dec := json.NewDecoder(bytes.NewReader(*raw))
	dec.UseNumber()
	var n json.Number
	if err := dec.Decode(&n); err != nil {
		*errs = append(*errs, Violation{path, "expected number"})
		return 0, false
	}
	f, err := n.Float64()
	if err != nil || math.IsNaN(f) || math.IsInf(f, 0) {
		*errs = append(*errs, Violation{path, "expected finite number"})
		return 0, false
	}
	return f, true
}

func parseBoolField(raw *json.RawMessage, path string, required, nullable bool, errs *[]Violation) (bool, bool) {
	if raw == nil {
		if required {
			*errs = append(*errs, Violation{path, "required"})
		}
		return false, false
	}
	if isNull(*raw) {
		if !nullable {
			*errs = append(*errs, Violation{path, "explicit null not allowed"})
		}
		return false, false
	}
	var b bool
	if err := json.Unmarshal(*raw, &b); err != nil {
		*errs = append(*errs, Violation{path, "expected boolean"})
		return false, false
	}
	return b, true
}

func marshalField(out map[string]json.RawMessage, key string, v any, errs *[]Violation) {
	if len(*errs) > 0 {
		out[key] = json.RawMessage("null")
		return
	}
	b, err := json.Marshal(v)
	if err != nil {
		mergeNested(errs, key, err)
		return
	}
	out[key] = b
}
