// Code generated by nexgen. DO NOT EDIT.

package kb

import (
	"encoding/json"

	"github.com/nexus-rpc/sdk-go/nexus"
)

// Fetch and update pages, blocks, and the category tree.
var KnowledgeBaseService = struct {
	ServiceName string
	// Fetch a page by id.
	GetPage nexus.OperationReference[GetPageInput, Page]
	// Create or update a content block.
	PutBlock nexus.OperationReference[Block, PutBlockOutput]
	// Fetch the category tree rooted at a category.
	GetCategoryTree nexus.OperationReference[GetCategoryTreeInput, Category]
}{
	ServiceName:     "example.kb.v1.KnowledgeBaseService",
	GetPage:         nexus.NewOperationReference[GetPageInput, Page]("GetPage"),
	PutBlock:        nexus.NewOperationReference[Block, PutBlockOutput]("PutBlock"),
	GetCategoryTree: nexus.NewOperationReference[GetCategoryTreeInput, Category]("GetCategoryTree"),
}

// GetCategoryTreeInput is generated from the corresponding JSON Schema definition.
type GetCategoryTreeInput struct {
	// RootID corresponds to the "rootId" JSON property.
	RootID string `json:"rootId"`
}

// Validate checks m against every constraint and returns a *ValidationError
// listing any violations.
func (m GetCategoryTreeInput) Validate() error {
	var errs []Violation
	if len(errs) > 0 {
		return &ValidationError{Violations: errs}
	}
	return nil
}

// UnmarshalJSON parses data into m and validates it, returning a
// *ValidationError listing any violations.
func (m *GetCategoryTreeInput) UnmarshalJSON(data []byte) error {
	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	var errs []Violation
	for k := range all {
		switch k {
		case "rootId":
		default:
			errs = append(errs, Violation{k, "unknown field"})
		}
	}
	get := func(k string) *json.RawMessage {
		if v, ok := all[k]; ok {
			return &v
		}
		return nil
	}
	_ = get
	if v, ok := parseStringField(get("rootId"), "rootId", true, false, &errs); ok {
		m.RootID = v
	}
	if len(errs) > 0 {
		return &ValidationError{Violations: errs}
	}
	return nil
}

// MarshalJSON validates m, then serializes it to JSON, returning a
// *ValidationError if validation fails.
func (m GetCategoryTreeInput) MarshalJSON() ([]byte, error) {
	var errs []Violation
	addViolations(&errs, m.Validate())
	out := map[string]json.RawMessage{}
	marshalField(out, "rootId", m.RootID, &errs)
	if len(errs) > 0 {
		return nil, &ValidationError{Violations: errs}
	}
	return json.Marshal(out)
}

// GetPageInput is generated from the corresponding JSON Schema definition.
type GetPageInput struct {
	// PageID corresponds to the "pageId" JSON property.
	PageID string `json:"pageId"`
}

// Validate checks m against every constraint and returns a *ValidationError
// listing any violations.
func (m GetPageInput) Validate() error {
	var errs []Violation
	if len(errs) > 0 {
		return &ValidationError{Violations: errs}
	}
	return nil
}

// UnmarshalJSON parses data into m and validates it, returning a
// *ValidationError listing any violations.
func (m *GetPageInput) UnmarshalJSON(data []byte) error {
	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	var errs []Violation
	for k := range all {
		switch k {
		case "pageId":
		default:
			errs = append(errs, Violation{k, "unknown field"})
		}
	}
	get := func(k string) *json.RawMessage {
		if v, ok := all[k]; ok {
			return &v
		}
		return nil
	}
	_ = get
	if v, ok := parseStringField(get("pageId"), "pageId", true, false, &errs); ok {
		m.PageID = v
	}
	if len(errs) > 0 {
		return &ValidationError{Violations: errs}
	}
	return nil
}

// MarshalJSON validates m, then serializes it to JSON, returning a
// *ValidationError if validation fails.
func (m GetPageInput) MarshalJSON() ([]byte, error) {
	var errs []Violation
	addViolations(&errs, m.Validate())
	out := map[string]json.RawMessage{}
	marshalField(out, "pageId", m.PageID, &errs)
	if len(errs) > 0 {
		return nil, &ValidationError{Violations: errs}
	}
	return json.Marshal(out)
}

// PutBlockOutput is generated from the corresponding JSON Schema definition.
type PutBlockOutput struct {
	// BlockID corresponds to the "blockId" JSON property.
	BlockID string `json:"blockId"`
	// Revision corresponds to the "revision" JSON property.
	Revision int64 `json:"revision"`
}

// Validate checks m against every constraint and returns a *ValidationError
// listing any violations.
func (m PutBlockOutput) Validate() error {
	var errs []Violation
	if m.Revision < -integerCap || m.Revision > integerCap {
		errs = append(errs, Violation{"revision", "exceeds ±(2^53-1) integer cap"})
	}
	if len(errs) > 0 {
		return &ValidationError{Violations: errs}
	}
	return nil
}

// UnmarshalJSON parses data into m and validates it, returning a
// *ValidationError listing any violations.
func (m *PutBlockOutput) UnmarshalJSON(data []byte) error {
	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	var errs []Violation
	for k := range all {
		switch k {
		case "blockId", "revision":
		default:
			errs = append(errs, Violation{k, "unknown field"})
		}
	}
	get := func(k string) *json.RawMessage {
		if v, ok := all[k]; ok {
			return &v
		}
		return nil
	}
	_ = get
	if v, ok := parseStringField(get("blockId"), "blockId", true, false, &errs); ok {
		m.BlockID = v
	}
	if v, ok := parseIntegerField(get("revision"), "revision", true, false, &errs); ok {
		m.Revision = v
	}
	if len(errs) > 0 {
		return &ValidationError{Violations: errs}
	}
	return nil
}

// MarshalJSON validates m, then serializes it to JSON, returning a
// *ValidationError if validation fails.
func (m PutBlockOutput) MarshalJSON() ([]byte, error) {
	var errs []Violation
	addViolations(&errs, m.Validate())
	out := map[string]json.RawMessage{}
	marshalField(out, "blockId", m.BlockID, &errs)
	marshalField(out, "revision", m.Revision, &errs)
	if len(errs) > 0 {
		return nil, &ValidationError{Violations: errs}
	}
	return json.Marshal(out)
}
