// <auto-generated />
// Generated by nexgen latest. DO NOT EDIT!
#nullable enable

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using Temporalio.Converters;
using Nexgen.Support;

namespace Nexgen.ProtoGeneric
{

    [Temporalio.Converters.TemporalTransferTypeConverter(typeof(PayloadBackedContext<>.TransferTypeConverter))]
    [GeneratedCode("nexgen", null)]
    public record PayloadBackedContext<TContext>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PayloadBackedContext{TContext}"/> class.
        /// </summary>
        public PayloadBackedContext(TContext details)
        {
            Details = details;
        }

        public TContext Details { get; init; }

        internal static PayloadBackedContext<TContext> FromTransferType(Temporalio.Api.Compute.V1.ComputeScaler wire)
        {
            if (wire.Details == null)
            {
                throw new System.InvalidOperationException("missing required field PayloadBackedContext.Details");
            }

            return new PayloadBackedContext<TContext>(Nexgen.Support.ProtoExtensions.FromPayload<TContext>(wire.Details));
        }

        internal Temporalio.Api.Compute.V1.ComputeScaler ToTransferType()
        {
            var proto = new Temporalio.Api.Compute.V1.ComputeScaler();
            proto.Details = Nexgen.Support.ProtoExtensions.ToPayload(Details);
            return proto;
        }

        /// <summary>
        /// Converts this model to and from its generated transfer type.
        /// </summary>
        public sealed class TransferTypeConverter : Temporalio.Converters.ITemporalTransferTypeConverter
        {
            /// <summary>Gets the generated transfer type.</summary>
            public System.Type TransferType => typeof(Temporalio.Api.Compute.V1.ComputeScaler);

            /// <summary>Converts a model value to its transfer type.</summary>
            public object? ToTransferType(object? value) => value is null ? null : ((PayloadBackedContext<TContext>)value).ToTransferType();

            /// <summary>Converts a transfer-type value to this model.</summary>
            public object? FromTransferType(object? transferType) => transferType is null ? null : PayloadBackedContext<TContext>.FromTransferType((Temporalio.Api.Compute.V1.ComputeScaler)transferType);
        }

    }

    [Temporalio.Converters.TemporalTransferTypeConverter(typeof(PayloadBackedEnvelope<,>.TransferTypeConverter))]
    [GeneratedCode("nexgen", null)]
    public record PayloadBackedEnvelope<TOutput, TContext>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PayloadBackedEnvelope{TOutput, TContext}"/> class.
        /// </summary>
        public PayloadBackedEnvelope(PayloadBackedOutput<TOutput> provider, PayloadBackedContext<TContext> scaler)
        {
            Provider = provider;
            Scaler = scaler;
        }

        public PayloadBackedOutput<TOutput> Provider { get; init; }
        public PayloadBackedContext<TContext> Scaler { get; init; }

        internal static PayloadBackedEnvelope<TOutput, TContext> FromTransferType(Temporalio.Api.Compute.V1.ComputeConfigScalingGroup wire)
        {
            return new PayloadBackedEnvelope<TOutput, TContext>(PayloadBackedOutput<TOutput>.FromTransferType(wire.Provider), PayloadBackedContext<TContext>.FromTransferType(wire.Scaler));
        }

        internal Temporalio.Api.Compute.V1.ComputeConfigScalingGroup ToTransferType()
        {
            var proto = new Temporalio.Api.Compute.V1.ComputeConfigScalingGroup();
            proto.Provider = (Temporalio.Api.Compute.V1.ComputeProvider)Provider.ToTransferType();
            proto.Scaler = (Temporalio.Api.Compute.V1.ComputeScaler)Scaler.ToTransferType();
            return proto;
        }

        /// <summary>
        /// Converts this model to and from its generated transfer type.
        /// </summary>
        public sealed class TransferTypeConverter : Temporalio.Converters.ITemporalTransferTypeConverter
        {
            /// <summary>Gets the generated transfer type.</summary>
            public System.Type TransferType => typeof(Temporalio.Api.Compute.V1.ComputeConfigScalingGroup);

            /// <summary>Converts a model value to its transfer type.</summary>
            public object? ToTransferType(object? value) => value is null ? null : ((PayloadBackedEnvelope<TOutput, TContext>)value).ToTransferType();

            /// <summary>Converts a transfer-type value to this model.</summary>
            public object? FromTransferType(object? transferType) => transferType is null ? null : PayloadBackedEnvelope<TOutput, TContext>.FromTransferType((Temporalio.Api.Compute.V1.ComputeConfigScalingGroup)transferType);
        }

    }

    [Temporalio.Converters.TemporalTransferTypeConverter(typeof(PayloadBackedOutput<>.TransferTypeConverter))]
    [GeneratedCode("nexgen", null)]
    public record PayloadBackedOutput<TOutput>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PayloadBackedOutput{TOutput}"/> class.
        /// </summary>
        public PayloadBackedOutput(TOutput details)
        {
            Details = details;
        }

        public TOutput Details { get; init; }

        internal static PayloadBackedOutput<TOutput> FromTransferType(Temporalio.Api.Compute.V1.ComputeProvider wire)
        {
            if (wire.Details == null)
            {
                throw new System.InvalidOperationException("missing required field PayloadBackedOutput.Details");
            }

            return new PayloadBackedOutput<TOutput>(Nexgen.Support.ProtoExtensions.FromPayload<TOutput>(wire.Details));
        }

        internal Temporalio.Api.Compute.V1.ComputeProvider ToTransferType()
        {
            var proto = new Temporalio.Api.Compute.V1.ComputeProvider();
            proto.Details = Nexgen.Support.ProtoExtensions.ToPayload(Details);
            return proto;
        }

        /// <summary>
        /// Converts this model to and from its generated transfer type.
        /// </summary>
        public sealed class TransferTypeConverter : Temporalio.Converters.ITemporalTransferTypeConverter
        {
            /// <summary>Gets the generated transfer type.</summary>
            public System.Type TransferType => typeof(Temporalio.Api.Compute.V1.ComputeProvider);

            /// <summary>Converts a model value to its transfer type.</summary>
            public object? ToTransferType(object? value) => value is null ? null : ((PayloadBackedOutput<TOutput>)value).ToTransferType();

            /// <summary>Converts a transfer-type value to this model.</summary>
            public object? FromTransferType(object? transferType) => transferType is null ? null : PayloadBackedOutput<TOutput>.FromTransferType((Temporalio.Api.Compute.V1.ComputeProvider)transferType);
        }

    }

}
