// <auto-generated />
// Generated by nexgen latest. DO NOT EDIT!
#nullable enable

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using Temporalio.Converters;
using Nexgen.Support;

namespace Nexgen.ProtoGeneric
{

    [Temporalio.Converters.TemporalTransferTypeConverter(typeof(PayloadBackedContext<>.TransferTypeConverter))]
    [GeneratedCode("nexgen", null)]
    public record PayloadBackedContext<ContextT>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PayloadBackedContext"/> class.
        /// </summary>
        public PayloadBackedContext(ContextT details)
        {
            Details = details;
        }

        public ContextT Details { get; init; }

        internal static PayloadBackedContext<ContextT> FromTransferType(Temporalio.Api.Compute.V1.ComputeScaler wire)
        {
            if (wire.Details == null)
            {
                throw new System.InvalidOperationException("missing required field PayloadBackedContext.Details");
            }

            return new PayloadBackedContext<ContextT>(Nexgen.Support.ProtoExtensions.FromPayload<ContextT>(wire.Details));
        }

        internal Temporalio.Api.Compute.V1.ComputeScaler ToTransferType()
        {
            var proto = new Temporalio.Api.Compute.V1.ComputeScaler();
            proto.Details = Nexgen.Support.ProtoExtensions.ToPayload(Details);
            return proto;
        }

        /// <summary>
        /// Converts this model to and from its generated transfer type.
        /// </summary>
        public sealed class TransferTypeConverter : Temporalio.Converters.ITemporalTransferTypeConverter
        {
            /// <summary>Gets the generated transfer type.</summary>
            public System.Type TransferType => typeof(Temporalio.Api.Compute.V1.ComputeScaler);

            /// <summary>Converts a model value to its transfer type.</summary>
            public object? ToTransferType(object? value) => value is null ? null : ((PayloadBackedContext<ContextT>)value).ToTransferType();

            /// <summary>Converts a transfer-type value to this model.</summary>
            public object? FromTransferType(object? transferType) => transferType is null ? null : PayloadBackedContext<ContextT>.FromTransferType((Temporalio.Api.Compute.V1.ComputeScaler)transferType);
        }

    }

    [Temporalio.Converters.TemporalTransferTypeConverter(typeof(PayloadBackedEnvelope<,>.TransferTypeConverter))]
    [GeneratedCode("nexgen", null)]
    public record PayloadBackedEnvelope<OutputT, ContextT>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PayloadBackedEnvelope"/> class.
        /// </summary>
        public PayloadBackedEnvelope(PayloadBackedOutput<OutputT> provider, PayloadBackedContext<ContextT> scaler)
        {
            Provider = provider;
            Scaler = scaler;
        }

        public PayloadBackedOutput<OutputT> Provider { get; init; }
        public PayloadBackedContext<ContextT> Scaler { get; init; }

        internal static PayloadBackedEnvelope<OutputT, ContextT> FromTransferType(Temporalio.Api.Compute.V1.ComputeConfigScalingGroup wire)
        {
            return new PayloadBackedEnvelope<OutputT, ContextT>(PayloadBackedOutput<OutputT>.FromTransferType(wire.Provider), PayloadBackedContext<ContextT>.FromTransferType(wire.Scaler));
        }

        internal Temporalio.Api.Compute.V1.ComputeConfigScalingGroup ToTransferType()
        {
            var proto = new Temporalio.Api.Compute.V1.ComputeConfigScalingGroup();
            proto.Provider = (Temporalio.Api.Compute.V1.ComputeProvider)Provider.ToTransferType();
            proto.Scaler = (Temporalio.Api.Compute.V1.ComputeScaler)Scaler.ToTransferType();
            return proto;
        }

        /// <summary>
        /// Converts this model to and from its generated transfer type.
        /// </summary>
        public sealed class TransferTypeConverter : Temporalio.Converters.ITemporalTransferTypeConverter
        {
            /// <summary>Gets the generated transfer type.</summary>
            public System.Type TransferType => typeof(Temporalio.Api.Compute.V1.ComputeConfigScalingGroup);

            /// <summary>Converts a model value to its transfer type.</summary>
            public object? ToTransferType(object? value) => value is null ? null : ((PayloadBackedEnvelope<OutputT, ContextT>)value).ToTransferType();

            /// <summary>Converts a transfer-type value to this model.</summary>
            public object? FromTransferType(object? transferType) => transferType is null ? null : PayloadBackedEnvelope<OutputT, ContextT>.FromTransferType((Temporalio.Api.Compute.V1.ComputeConfigScalingGroup)transferType);
        }

    }

    [Temporalio.Converters.TemporalTransferTypeConverter(typeof(PayloadBackedOutput<>.TransferTypeConverter))]
    [GeneratedCode("nexgen", null)]
    public record PayloadBackedOutput<OutputT>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PayloadBackedOutput"/> class.
        /// </summary>
        public PayloadBackedOutput(OutputT details)
        {
            Details = details;
        }

        public OutputT Details { get; init; }

        internal static PayloadBackedOutput<OutputT> FromTransferType(Temporalio.Api.Compute.V1.ComputeProvider wire)
        {
            if (wire.Details == null)
            {
                throw new System.InvalidOperationException("missing required field PayloadBackedOutput.Details");
            }

            return new PayloadBackedOutput<OutputT>(Nexgen.Support.ProtoExtensions.FromPayload<OutputT>(wire.Details));
        }

        internal Temporalio.Api.Compute.V1.ComputeProvider ToTransferType()
        {
            var proto = new Temporalio.Api.Compute.V1.ComputeProvider();
            proto.Details = Nexgen.Support.ProtoExtensions.ToPayload(Details);
            return proto;
        }

        /// <summary>
        /// Converts this model to and from its generated transfer type.
        /// </summary>
        public sealed class TransferTypeConverter : Temporalio.Converters.ITemporalTransferTypeConverter
        {
            /// <summary>Gets the generated transfer type.</summary>
            public System.Type TransferType => typeof(Temporalio.Api.Compute.V1.ComputeProvider);

            /// <summary>Converts a model value to its transfer type.</summary>
            public object? ToTransferType(object? value) => value is null ? null : ((PayloadBackedOutput<OutputT>)value).ToTransferType();

            /// <summary>Converts a transfer-type value to this model.</summary>
            public object? FromTransferType(object? transferType) => transferType is null ? null : PayloadBackedOutput<OutputT>.FromTransferType((Temporalio.Api.Compute.V1.ComputeProvider)transferType);
        }

    }

}
