// Generated by nexgen v0.2.1. DO NOT EDIT.
package json_schema.definitions.showcase;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jspecify.annotations.Nullable;

/**
 * A closed sum type (discriminated union) of Circle | Square, tagged by the shared
 * required `kind` const. Selection reads `kind` and routes to the matching branch; an
 * unknown tag is a Violation.
 */
public interface Shape {
    static @Nullable Shape fromNode(JsonNode node, String path, List<Violation> violations, DeserializationContext context) {
        if (node.isObject()) {
            JsonNode disc = node.get("kind");
            if (disc == null || !disc.isTextual()) {
                violations.add(new Violation(path, "discriminator \"kind\" is required"));
                return null;
            }
            switch (disc.textValue()) {
                case "circle":
                    try {
                        return context.readTreeAsValue(node, Circle.class);
                    } catch (ValidationException nested) {
                        for (Violation violation : nested.getViolations()) {
                            violations.add(violation.withPathPrefix(path));
                        }
                        return null;
                    } catch (IOException nested) {
                        violations.add(new Violation(path, nested.getMessage()));
                        return null;
                    }
                case "square":
                    try {
                        return context.readTreeAsValue(node, Square.class);
                    } catch (ValidationException nested) {
                        for (Violation violation : nested.getViolations()) {
                            violations.add(violation.withPathPrefix(path));
                        }
                        return null;
                    } catch (IOException nested) {
                        violations.add(new Violation(path, nested.getMessage()));
                        return null;
                    }
                default:
                    violations.add(new Violation(path, "unknown discriminator kind " + disc.textValue() + ": expected one of [circle, square]"));
                    return null;
            }
        }
        violations.add(new Violation(path, "expected one of: Circle, Square"));
        return null;
    }
}
