// Generated by nexgen v0.2.1. DO NOT EDIT.
package json_schema.definitions.showcase;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jspecify.annotations.Nullable;

@JsonSerialize(using = ShowcaseDetailObject.Serializer.class)
@JsonDeserialize(using = ShowcaseDetailObject.Deserializer.class)
public final class ShowcaseDetailObject implements Showcase.Detail {
    private final String code;
    private final @Nullable String hint;
    private final Map<String, JsonNode> additionalProperties;

    public ShowcaseDetailObject(String code, @Nullable String hint, Map<String, JsonNode> additionalProperties) {
        this.code = code;
        this.hint = hint;
        this.additionalProperties = additionalProperties;
    }

    public String getCode() {
        return code;
    }

    public @Nullable String getHint() {
        return hint;
    }

    public Map<String, JsonNode> getAdditionalProperties() {
        return additionalProperties;
    }

    @Override
    public boolean equals(@Nullable Object other) {
        if (this == other) {
            return true;
        }
        if (!(other instanceof ShowcaseDetailObject)) {
            return false;
        }
        ShowcaseDetailObject that = (ShowcaseDetailObject) other;
        return Objects.equals(this.code, that.code)
            && Objects.equals(this.hint, that.hint)
            && Objects.equals(this.additionalProperties, that.additionalProperties);
    }

    @Override
    public int hashCode() {
        return Objects.hash(code, hint, additionalProperties);
    }

    @Override
    public String toString() {
        return "ShowcaseDetailObject{"
            + "code=" + code
            + ", hint=" + hint
            + ", additionalProperties=" + additionalProperties
            + "}";
    }

    public static final class Serializer extends com.fasterxml.jackson.databind.JsonSerializer<ShowcaseDetailObject> {
        @Override
        public void serialize(ShowcaseDetailObject value, JsonGenerator gen, SerializerProvider serializers) throws IOException {
            List<Violation> violations = new ArrayList<>();
            if (value.code != null) {
                int length = value.code.codePointCount(0, value.code.length());
                if (length < 1) {
                    violations.add(new Violation("code", "must have length >= 1, got " + length));
                }
            }
            java.util.Set<String> wireKeys = new java.util.LinkedHashSet<>();
            if (value.code != null) {
                wireKeys.add("code");
            }
            if (value.hint != null) {
                wireKeys.add("hint");
            }
            if (value.additionalProperties != null) {
                for (String key : value.additionalProperties.keySet()) {
                    if (!wireKeys.add(key)) {
                        violations.add(new Violation(key, "declared property key collision"));
                    }
                }
            }
            if (!violations.isEmpty()) {
                throw new ValidationException(violations);
            }
            gen.writeStartObject();
            if (value.code != null) {
                gen.writeStringField("code", value.code);
            }
            if (value.hint != null) {
                gen.writeStringField("hint", value.hint);
            }
            if (value.additionalProperties != null) {
                for (Map.Entry<String, JsonNode> entry : value.additionalProperties.entrySet()) {
                    gen.writeFieldName(entry.getKey());
                    gen.writeTree(entry.getValue());
                }
            }
            gen.writeEndObject();
        }
    }

    public static final class Deserializer extends com.fasterxml.jackson.databind.JsonDeserializer<ShowcaseDetailObject> {
        @Override
        public ShowcaseDetailObject deserialize(JsonParser parser, DeserializationContext context) throws IOException {
            JsonNode node = parser.readValueAsTree();
            List<Violation> violations = new ArrayList<>();
            if (node == null || !node.isObject()) {
                violations.add(new Violation("", "expected object"));
                throw new ValidationException(violations);
            }
            Map<String, JsonNode> additionalProperties = new LinkedHashMap<>();
            Iterator<String> fieldNames = node.fieldNames();
            while (fieldNames.hasNext()) {
                String key = fieldNames.next();
                switch (key) {
                    case "code":
                    case "hint":
                        break;
                    default:
                        additionalProperties.put(key, node.get(key));
                }
            }
            String code = null;
            {
                JsonNode field = node.get("code");
                if (field == null) {
                    violations.add(new Violation("code", "required"));
                } else if (field.isNull()) {
                    violations.add(new Violation("code", "explicit null not allowed"));
                } else {
                    if (!field.isTextual()) {
                        violations.add(new Violation("code", "expected string"));
                    } else {
                        code = field.textValue();
                        int length = code.codePointCount(0, code.length());
                        if (length < 1) {
                            violations.add(new Violation("code", "must have length >= 1, got " + length));
                        }
                    }
                }
            }
            String hint = null;
            {
                JsonNode field = node.get("hint");
                if (field == null) {
                } else if (field.isNull()) {
                    violations.add(new Violation("hint", "explicit null not allowed"));
                } else {
                    if (!field.isTextual()) {
                        violations.add(new Violation("hint", "expected string"));
                    } else {
                        hint = field.textValue();
                    }
                }
            }
            if (!violations.isEmpty()) {
                throw new ValidationException(violations);
            }
            return new ShowcaseDetailObject(code, hint, additionalProperties);
        }
    }
}
