// Generated by nexgen v0.2.1. DO NOT EDIT.
package json_schema.definitions.showcase;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jspecify.annotations.Nullable;

/**
 * A typed map written inline on the property: the map itself is named `ShowcaseLedger`
 * and its inline member shape `ShowcaseLedgerValue`, so both the map and its members
 * are ordinary named models. Also exercises the member-name override on a hoisted
 * property — `x-&lt;lang&gt;-name` keeps naming the *member* (Go `LedgerGo`, TS
 * `ledgerTs`, Python `ledger_py`, Java `ledgerJava`) while the type keeps its
 * position-derived name.
 */
@JsonSerialize(using = ShowcaseLedger.Serializer.class)
@JsonDeserialize(using = ShowcaseLedger.Deserializer.class)
public final class ShowcaseLedger {
    private final Map<String, ShowcaseLedgerValue> additionalProperties;

    public ShowcaseLedger(Map<String, ShowcaseLedgerValue> additionalProperties) {
        this.additionalProperties = additionalProperties;
    }

    public Map<String, ShowcaseLedgerValue> getAdditionalProperties() {
        return additionalProperties;
    }

    @Override
    public boolean equals(@Nullable Object other) {
        if (this == other) {
            return true;
        }
        if (!(other instanceof ShowcaseLedger)) {
            return false;
        }
        return Objects.equals(this.additionalProperties, ((ShowcaseLedger) other).additionalProperties);
    }

    @Override
    public int hashCode() {
        return Objects.hash(additionalProperties);
    }

    @Override
    public String toString() {
        return "ShowcaseLedger{"
            + "additionalProperties=" + additionalProperties
            + "}";
    }

    public static final class Serializer extends com.fasterxml.jackson.databind.JsonSerializer<ShowcaseLedger> {
        @Override
        public void serialize(ShowcaseLedger value, JsonGenerator gen, SerializerProvider serializers) throws IOException {
            gen.writeStartObject();
            for (Map.Entry<String, ShowcaseLedgerValue> entry : value.additionalProperties.entrySet()) {
                gen.writeFieldName(entry.getKey());
                serializers.defaultSerializeValue(entry.getValue(), gen);
            }
            gen.writeEndObject();
        }
    }

    public static final class Deserializer extends com.fasterxml.jackson.databind.JsonDeserializer<ShowcaseLedger> {
        @Override
        public ShowcaseLedger deserialize(JsonParser parser, DeserializationContext context) throws IOException {
            JsonNode node = parser.readValueAsTree();
            List<Violation> violations = new ArrayList<>();
            if (node == null || !node.isObject()) {
                violations.add(new Violation("", "expected object"));
                throw new ValidationException(violations);
            }
            Map<String, ShowcaseLedgerValue> additionalProperties = new LinkedHashMap<>();
            Iterator<String> fieldNames = node.fieldNames();
            while (fieldNames.hasNext()) {
                String key = fieldNames.next();
                JsonNode element = node.get(key);
                if (element.isNull()) {
                    violations.add(new Violation(key, "explicit null not allowed"));
                    continue;
                }
                try {
                    additionalProperties.put(key, context.readTreeAsValue(element, ShowcaseLedgerValue.class));
                } catch (ValidationException nested) {
                    for (Violation violation : nested.getViolations()) {
                        violations.add(violation.withPathPrefix(key));
                    }
                } catch (IOException nested) {
                    violations.add(new Violation(key, nested.getMessage()));
                }
            }
            if (!violations.isEmpty()) {
                throw new ValidationException(violations);
            }
            return new ShowcaseLedger(additionalProperties);
        }
    }
}
