// Generated by nexgen latest. DO NOT EDIT.
package json_schema.definitions.showcase;

import org.jspecify.annotations.Nullable;

/** A single constraint failure: a JSON member path and a human-readable reason. */
public final class Violation {
    private final String path;
    private final String reason;

    public Violation(String path, String reason) {
        this.path = path;
        this.reason = reason;
    }

    public String getPath() {
        return path;
    }

    public String getReason() {
        return reason;
    }

    public static String memberPath(String key) {
        if (key.matches("[A-Za-z_][A-Za-z0-9_]*")) {
            return key;
        }
        return "[\"" + key.replace("\\", "\\\\").replace("\"", "\\\"") + "\"]";
    }

    /** Quotes {@code value} as a JSON string literal for a violation reason. */
    public static String quote(String value) {
        StringBuilder out = new StringBuilder(value.length() + 2).append('"');
        for (int i = 0; i < value.length(); i++) {
            char c = value.charAt(i);
            if (c == '"') {
                out.append("\\\"");
            } else if (c == '\\') {
                out.append("\\\\");
            } else if (c == '\b') {
                out.append("\\b");
            } else if (c == '\f') {
                out.append("\\f");
            } else if (c == '\n') {
                out.append("\\n");
            } else if (c == '\r') {
                out.append("\\r");
            } else if (c == '\t') {
                out.append("\\t");
            } else if (c < 0x20) {
                out.append(String.format("\\u%04x", (int) c));
            } else {
                out.append(c);
            }
        }
        return out.append('"').toString();
    }

    public Violation withPathPrefix(String prefix) {
        if (path == null || path.isEmpty()) {
            return new Violation(prefix, reason);
        }
        return new Violation(path.startsWith("[") ? prefix + path : prefix + "." + path, reason);
    }

    @Override
    public String toString() {
        if (path == null || path.isEmpty()) {
            return reason;
        }
        return path + ": " + reason;
    }

    @Override
    public boolean equals(@Nullable Object other) {
        if (this == other) {
            return true;
        }
        if (!(other instanceof Violation)) {
            return false;
        }
        Violation that = (Violation) other;
        return java.util.Objects.equals(path, that.path) && java.util.Objects.equals(reason, that.reason);
    }

    @Override
    public int hashCode() {
        return java.util.Objects.hash(path, reason);
    }
}
