# Generated by nexgen. DO NOT EDIT!

from __future__ import annotations

import dataclasses
import typing
import typing_extensions
import temporalio.api.compute.v1.config_pb2
import temporalio.api.compute.v1.provider_pb2
import temporalio.api.compute.v1.scaler_pb2
import temporalio.converter

from ._support import (
    payload_from_proto,
    payload_to_proto,
)


ContextT = typing.TypeVar("ContextT")
OutputT = typing.TypeVar("OutputT")


@dataclasses.dataclass(slots=True)
class PayloadBackedContext(typing.Generic[ContextT]):
    details: ContextT


class _PayloadBackedContextTransferTypeConverter(
    temporalio.converter.TransferTypeConverter[
        "PayloadBackedContext[typing.Any]",
        temporalio.api.compute.v1.scaler_pb2.ComputeScaler,
    ]
):
    transfer_type: type[temporalio.api.compute.v1.scaler_pb2.ComputeScaler] | None = (
        temporalio.api.compute.v1.scaler_pb2.ComputeScaler
    )

    @typing_extensions.override
    def from_transfer_type(
        self,
        value: temporalio.api.compute.v1.scaler_pb2.ComputeScaler,
        type_hint: type["PayloadBackedContext[typing.Any]"],
    ) -> "PayloadBackedContext[typing.Any]":
        (context_type,) = typing.get_args(type_hint) or (typing.Any,)
        if not value.HasField("details"):
            raise ValueError("missing required field PayloadBackedContext.details")
        details = payload_from_proto(value.details, context_type)
        return PayloadBackedContext(
            details=details,
        )

    @typing_extensions.override
    def to_transfer_type(
        self,
        value: "PayloadBackedContext[typing.Any]",
    ) -> temporalio.api.compute.v1.scaler_pb2.ComputeScaler:
        runtime_value: typing.Any = value
        message = temporalio.api.compute.v1.scaler_pb2.ComputeScaler()
        message.details.CopyFrom(payload_to_proto(runtime_value.details))
        return message


# Registration stores the converter on the model; the returned class is unused.
temporalio.converter.transfer_type_convertible(
    _PayloadBackedContextTransferTypeConverter
)(PayloadBackedContext)  # pyright: ignore[reportUnusedCallResult]


@dataclasses.dataclass(slots=True)
class PayloadBackedEnvelope(typing.Generic[OutputT, ContextT]):
    provider: PayloadBackedOutput[OutputT]
    scaler: PayloadBackedContext[ContextT]


class _PayloadBackedEnvelopeTransferTypeConverter(
    temporalio.converter.TransferTypeConverter[
        "PayloadBackedEnvelope[typing.Any, typing.Any]",
        temporalio.api.compute.v1.config_pb2.ComputeConfigScalingGroup,
    ]
):
    transfer_type: (
        type[temporalio.api.compute.v1.config_pb2.ComputeConfigScalingGroup] | None
    ) = temporalio.api.compute.v1.config_pb2.ComputeConfigScalingGroup

    @typing_extensions.override
    def from_transfer_type(
        self,
        value: temporalio.api.compute.v1.config_pb2.ComputeConfigScalingGroup,
        type_hint: type["PayloadBackedEnvelope[typing.Any, typing.Any]"],
    ) -> "PayloadBackedEnvelope[typing.Any, typing.Any]":
        output_type, context_type = typing.get_args(type_hint) or (
            typing.Any,
            typing.Any,
        )
        if not value.HasField("provider"):
            raise ValueError("missing required field PayloadBackedEnvelope.provider")
        provider = _PayloadBackedOutputTransferTypeConverter().from_transfer_type(
            value.provider, PayloadBackedOutput[output_type]
        )
        if not value.HasField("scaler"):
            raise ValueError("missing required field PayloadBackedEnvelope.scaler")
        scaler = _PayloadBackedContextTransferTypeConverter().from_transfer_type(
            value.scaler, PayloadBackedContext[context_type]
        )
        return PayloadBackedEnvelope(
            provider=provider,
            scaler=scaler,
        )

    @typing_extensions.override
    def to_transfer_type(
        self,
        value: "PayloadBackedEnvelope[typing.Any, typing.Any]",
    ) -> temporalio.api.compute.v1.config_pb2.ComputeConfigScalingGroup:
        runtime_value: typing.Any = value
        message = temporalio.api.compute.v1.config_pb2.ComputeConfigScalingGroup()
        message.provider.CopyFrom(
            _PayloadBackedOutputTransferTypeConverter().to_transfer_type(
                runtime_value.provider
            )
        )
        message.scaler.CopyFrom(
            _PayloadBackedContextTransferTypeConverter().to_transfer_type(
                runtime_value.scaler
            )
        )
        return message


# Registration stores the converter on the model; the returned class is unused.
temporalio.converter.transfer_type_convertible(
    _PayloadBackedEnvelopeTransferTypeConverter
)(PayloadBackedEnvelope)  # pyright: ignore[reportUnusedCallResult]


@dataclasses.dataclass(slots=True)
class PayloadBackedOutput(typing.Generic[OutputT]):
    details: OutputT


class _PayloadBackedOutputTransferTypeConverter(
    temporalio.converter.TransferTypeConverter[
        "PayloadBackedOutput[typing.Any]",
        temporalio.api.compute.v1.provider_pb2.ComputeProvider,
    ]
):
    transfer_type: (
        type[temporalio.api.compute.v1.provider_pb2.ComputeProvider] | None
    ) = temporalio.api.compute.v1.provider_pb2.ComputeProvider

    @typing_extensions.override
    def from_transfer_type(
        self,
        value: temporalio.api.compute.v1.provider_pb2.ComputeProvider,
        type_hint: type["PayloadBackedOutput[typing.Any]"],
    ) -> "PayloadBackedOutput[typing.Any]":
        (output_type,) = typing.get_args(type_hint) or (typing.Any,)
        if not value.HasField("details"):
            raise ValueError("missing required field PayloadBackedOutput.details")
        details = payload_from_proto(value.details, output_type)
        return PayloadBackedOutput(
            details=details,
        )

    @typing_extensions.override
    def to_transfer_type(
        self,
        value: "PayloadBackedOutput[typing.Any]",
    ) -> temporalio.api.compute.v1.provider_pb2.ComputeProvider:
        runtime_value: typing.Any = value
        message = temporalio.api.compute.v1.provider_pb2.ComputeProvider()
        message.details.CopyFrom(payload_to_proto(runtime_value.details))
        return message


# Registration stores the converter on the model; the returned class is unused.
temporalio.converter.transfer_type_convertible(
    _PayloadBackedOutputTransferTypeConverter
)(PayloadBackedOutput)  # pyright: ignore[reportUnusedCallResult]
