// Code generated by nexgen v0.2.1. DO NOT EDIT.
package temporal

import (
	"encoding/json"
	"fmt"
	"regexp"
	"strconv"
	"strings"
	"time"
)

var jsonTemporalDateTimeRE = regexp.MustCompile(`^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])[Tt]([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\.[0-9]+)?([Zz]|[+-]([01][0-9]|2[0-3]):[0-5][0-9])$`)
var jsonTemporalDateRE = regexp.MustCompile(`^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])$`)
var jsonTemporalTimeRE = regexp.MustCompile(`^([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\.[0-9]+)?([Zz]|[+-]([01][0-9]|2[0-3]):[0-5][0-9])?$`)
var jsonTemporalDurationRE = regexp.MustCompile(`^PT(?:[0-9]+H(?:[0-9]+M(?:[0-9]+S)?)?|[0-9]+M(?:[0-9]+S)?|[0-9]+S)$`)

// daysInTemporalMonth returns the Gregorian day count of a 1-based month.
func daysInTemporalMonth(year, month int) int {
	switch month {
	case 1, 3, 5, 7, 8, 10, 12:
		return 31
	case 4, 6, 9, 11:
		return 30
	case 2:
		if (year%4 == 0 && year%100 != 0) || year%400 == 0 {
			return 29
		}
		return 28
	}
	return 0
}

// validTemporalCalendar checks day-in-month over a YYYY-MM-DD prefix; the regex
// has already fixed the digit shape and the month/day ranges.
func validTemporalCalendar(s string) bool {
	if len(s) < 10 {
		return false
	}
	year, err1 := strconv.Atoi(s[0:4])
	month, err2 := strconv.Atoi(s[5:7])
	day, err3 := strconv.Atoi(s[8:10])
	if err1 != nil || err2 != nil || err3 != nil {
		return false
	}
	if year < 1 {
		return false
	}
	max := daysInTemporalMonth(year, month)
	return max > 0 && day >= 1 && day <= max
}

func temporalFracNanos(nanos int) string {
	if nanos == 0 {
		return ""
	}
	return "." + strings.TrimRight(fmt.Sprintf("%09d", nanos), "0")
}

func temporalOffset(secs int) string {
	if secs == 0 {
		return "Z"
	}
	sign := "+"
	if secs < 0 {
		sign = "-"
		secs = -secs
	}
	return fmt.Sprintf("%s%02d:%02d", sign, secs/3600, (secs%3600)/60)
}

// parseDateTime validates the wire string (narrowed regex + calendar) then parses
// it into a time.Time, uppercasing the case-insensitive T/Z first (Go's parser
// rejects lowercase). Offset and nanoseconds are preserved; no truncation.
func parseDateTime(path, s string, errs *[]Violation) (time.Time, bool) {
	if !jsonTemporalDateTimeRE.MatchString(s) || !validTemporalCalendar(s) {
		*errs = append(*errs, Violation{path, fmt.Sprintf("must be a valid date-time, got %q", s)})
		return time.Time{}, false
	}
	t, err := time.Parse(time.RFC3339Nano, strings.ToUpper(s))
	if err != nil {
		*errs = append(*errs, Violation{path, fmt.Sprintf("must be a valid date-time, got %q", s)})
		return time.Time{}, false
	}
	return t, true
}

// formatDateTime re-serializes via time.RFC3339Nano, which matches the
// generator-owned form exactly (offset preserved, Z for zero offset, trailing
// fractional zeros trimmed).
func formatDateTime(t time.Time) string {
	return t.Format(time.RFC3339Nano)
}

func parseDate(path, s string, errs *[]Violation) (time.Time, bool) {
	if !jsonTemporalDateRE.MatchString(s) || !validTemporalCalendar(s) {
		*errs = append(*errs, Violation{path, fmt.Sprintf("must be a valid date, got %q", s)})
		return time.Time{}, false
	}
	t, _ := time.Parse("2006-01-02", s)
	return t, true
}

func formatDate(t time.Time) string {
	return t.Format("2006-01-02")
}

// Go has no time-of-day type; time.Time carries a phantom date. An offset-less
// value is stored with a sentinel year so the serializer can distinguish it from
// an explicit Z/offset (whose offset parse yields year 0).
const temporalNoOffsetYear = 1

func parseTime(path, s string, errs *[]Violation) (time.Time, bool) {
	if !jsonTemporalTimeRE.MatchString(s) {
		*errs = append(*errs, Violation{path, fmt.Sprintf("must be a valid time, got %q", s)})
		return time.Time{}, false
	}
	w := strings.ToUpper(s)
	if t, err := time.Parse("15:04:05.999999999Z07:00", w); err == nil {
		return t, true
	}
	t, err := time.Parse("15:04:05.999999999", w)
	if err != nil {
		*errs = append(*errs, Violation{path, fmt.Sprintf("must be a valid time, got %q", s)})
		return time.Time{}, false
	}
	return time.Date(temporalNoOffsetYear, 1, 1, t.Hour(), t.Minute(), t.Second(), t.Nanosecond(), time.UTC), true
}

func formatTime(t time.Time) string {
	s := fmt.Sprintf("%02d:%02d:%02d%s", t.Hour(), t.Minute(), t.Second(), temporalFracNanos(t.Nanosecond()))
	if t.Year() != temporalNoOffsetYear {
		_, off := t.Zone()
		s += temporalOffset(off)
	}
	return s
}

// parseDuration validates the time-only wire string then sums it into a
// time.Duration, rejecting an overflow of the int64-nanosecond capacity.
func parseDuration(path, s string, errs *[]Violation) (time.Duration, bool) {
	fail := func() (time.Duration, bool) {
		*errs = append(*errs, Violation{path, fmt.Sprintf("must be a valid duration, got %q", s)})
		return 0, false
	}
	if !jsonTemporalDurationRE.MatchString(s) {
		return fail()
	}
	const maxSeconds = int64(9223372036854775807) / 1000000000
	var totalSeconds int64
	num := ""
	for _, ch := range s[2:] {
		if ch >= '0' && ch <= '9' {
			num += string(ch)
			continue
		}
		mag, err := strconv.ParseInt(num, 10, 64)
		if err != nil {
			return fail()
		}
		num = ""
		var unit int64
		switch ch {
		case 'H':
			unit = 3600
		case 'M':
			unit = 60
		case 'S':
			unit = 1
		}
		prod := mag * unit
		if unit != 0 && prod/unit != mag {
			return fail()
		}
		totalSeconds += prod
		if totalSeconds < 0 || totalSeconds > maxSeconds {
			return fail()
		}
	}
	return time.Duration(totalSeconds) * time.Second, true
}

// formatDuration canonicalizes to time-only PT…H…M…S (PT0S for zero); a
// non-canonical input collapses (PT90M → PT1H30M).
func formatDuration(d time.Duration) string {
	total := int64(d / time.Second)
	if total == 0 {
		return "PT0S"
	}
	out := "PT"
	if h := total / 3600; h != 0 {
		out += fmt.Sprintf("%dH", h)
	}
	if m := (total % 3600) / 60; m != 0 {
		out += fmt.Sprintf("%dM", m)
	}
	if sec := total % 60; sec != 0 {
		out += fmt.Sprintf("%dS", sec)
	}
	return out
}

func mustParseDateTime(s string) time.Time {
	var errs []Violation
	v, ok := parseDateTime("", s, &errs)
	if !ok {
		panic(errs[0].Reason)
	}
	return v
}

func mustParseDate(s string) time.Time {
	var errs []Violation
	v, ok := parseDate("", s, &errs)
	if !ok {
		panic(errs[0].Reason)
	}
	return v
}

func mustParseTime(s string) time.Time {
	var errs []Violation
	v, ok := parseTime("", s, &errs)
	if !ok {
		panic(errs[0].Reason)
	}
	return v
}

func mustParseDuration(s string) time.Duration {
	var errs []Violation
	v, ok := parseDuration("", s, &errs)
	if !ok {
		panic(errs[0].Reason)
	}
	return v
}

// Temporal
//
// Root object materializing the four RFC 3339 temporal formats as native typed fields:
// date-time (offset & sub-second precision preserved), date, time (offset preserved
// when present), and duration (time-only, canonicalized). Covers required, optional,
// and nullable members of each.
type Temporal struct {
	// CreatedAt Required event timestamp; materialized date-time (offset required,
	// sub-second precision & offset preserved on round-trip).
	CreatedAt time.Time `json:"createdAt"`
	// Birthday Required calendar date; materialized date (YYYY-MM-DD, lossless).
	Birthday time.Time `json:"birthday"`
	// Alarm Required wall-clock time; materialized time (offset preserved when present,
	// otherwise offset-less).
	Alarm time.Time `json:"alarm"`
	// Timeout Required time-only duration; materialized duration, canonicalized to
	// PT…H…M…S (e.g. PT90M → PT1H30M).
	Timeout time.Duration `json:"timeout"`
	// UpdatedAt Optional date-time.
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	// ExpiresOn Optional date.
	ExpiresOn *time.Time `json:"expiresOn,omitempty"`
	// Reminder Optional time.
	Reminder *time.Time `json:"reminder,omitempty"`
	// RetryDelay Optional duration.
	RetryDelay *time.Duration `json:"retryDelay,omitempty"`
	// DeletedAt Optional and nullable date-time (may be absent or explicitly null).
	DeletedAt *time.Time `json:"deletedAt,omitempty"`
	// ArchivedOn Optional and nullable date.
	ArchivedOn *time.Time `json:"archivedOn,omitempty"`
}

// Validate checks m against every constraint and returns a *ValidationError
// listing any violations.
func (m Temporal) Validate() error {
	var errs []Violation
	if m.CreatedAt.Year() < 1 {
		errs = append(errs, Violation{"createdAt", "year must be >= 1"})
	}
	if m.Birthday.Year() < 1 {
		errs = append(errs, Violation{"birthday", "year must be >= 1"})
	}
	if m.UpdatedAt != nil {
		if (*m.UpdatedAt).Year() < 1 {
			errs = append(errs, Violation{"updatedAt", "year must be >= 1"})
		}
	}
	if m.ExpiresOn != nil {
		if (*m.ExpiresOn).Year() < 1 {
			errs = append(errs, Violation{"expiresOn", "year must be >= 1"})
		}
	}
	if m.Reminder != nil {
	}
	if m.RetryDelay != nil {
	}
	if m.DeletedAt != nil {
		if (*m.DeletedAt).Year() < 1 {
			errs = append(errs, Violation{"deletedAt", "year must be >= 1"})
		}
	}
	if m.ArchivedOn != nil {
		if (*m.ArchivedOn).Year() < 1 {
			errs = append(errs, Violation{"archivedOn", "year must be >= 1"})
		}
	}
	if len(errs) > 0 {
		return &ValidationError{Violations: errs}
	}
	return nil
}

// UnmarshalJSON parses data into m and validates it, returning a
// *ValidationError listing any violations.
func (m *Temporal) UnmarshalJSON(data []byte) error {
	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	var errs []Violation
	for k := range all {
		switch k {
		case "createdAt", "birthday", "alarm", "timeout", "updatedAt", "expiresOn", "reminder", "retryDelay", "deletedAt", "archivedOn":
		default:
			errs = append(errs, Violation{k, "unknown field"})
		}
	}
	get := func(k string) *json.RawMessage {
		if v, ok := all[k]; ok {
			return &v
		}
		return nil
	}
	_ = get
	if s, ok := parseStringField(get("createdAt"), "createdAt", true, false, &errs); ok {
		if v, ok := parseDateTime("createdAt", s, &errs); ok {
			m.CreatedAt = v
		}
	}
	if s, ok := parseStringField(get("birthday"), "birthday", true, false, &errs); ok {
		if v, ok := parseDate("birthday", s, &errs); ok {
			m.Birthday = v
		}
	}
	if s, ok := parseStringField(get("alarm"), "alarm", true, false, &errs); ok {
		if v, ok := parseTime("alarm", s, &errs); ok {
			m.Alarm = v
		}
	}
	if s, ok := parseStringField(get("timeout"), "timeout", true, false, &errs); ok {
		if v, ok := parseDuration("timeout", s, &errs); ok {
			m.Timeout = v
		}
	}
	if s, ok := parseStringField(get("updatedAt"), "updatedAt", false, false, &errs); ok {
		if v, ok := parseDateTime("updatedAt", s, &errs); ok {
			m.UpdatedAt = &v
		}
	}
	if s, ok := parseStringField(get("expiresOn"), "expiresOn", false, false, &errs); ok {
		if v, ok := parseDate("expiresOn", s, &errs); ok {
			m.ExpiresOn = &v
		}
	}
	if s, ok := parseStringField(get("reminder"), "reminder", false, false, &errs); ok {
		if v, ok := parseTime("reminder", s, &errs); ok {
			m.Reminder = &v
		}
	}
	if s, ok := parseStringField(get("retryDelay"), "retryDelay", false, false, &errs); ok {
		if v, ok := parseDuration("retryDelay", s, &errs); ok {
			m.RetryDelay = &v
		}
	}
	if s, ok := parseStringField(get("deletedAt"), "deletedAt", false, true, &errs); ok {
		if v, ok := parseDateTime("deletedAt", s, &errs); ok {
			m.DeletedAt = &v
		}
	}
	if s, ok := parseStringField(get("archivedOn"), "archivedOn", false, true, &errs); ok {
		if v, ok := parseDate("archivedOn", s, &errs); ok {
			m.ArchivedOn = &v
		}
	}
	if len(errs) > 0 {
		return &ValidationError{Violations: errs}
	}
	return nil
}

// MarshalJSON validates m, then serializes it to JSON, returning a
// *ValidationError if validation fails.
func (m Temporal) MarshalJSON() ([]byte, error) {
	var errs []Violation
	addViolations(&errs, m.Validate())
	out := map[string]json.RawMessage{}
	marshalField(out, "createdAt", formatDateTime(m.CreatedAt), &errs)
	marshalField(out, "birthday", formatDate(m.Birthday), &errs)
	marshalField(out, "alarm", formatTime(m.Alarm), &errs)
	marshalField(out, "timeout", formatDuration(m.Timeout), &errs)
	if m.UpdatedAt != nil {
		marshalField(out, "updatedAt", formatDateTime(*m.UpdatedAt), &errs)
	}
	if m.ExpiresOn != nil {
		marshalField(out, "expiresOn", formatDate(*m.ExpiresOn), &errs)
	}
	if m.Reminder != nil {
		marshalField(out, "reminder", formatTime(*m.Reminder), &errs)
	}
	if m.RetryDelay != nil {
		marshalField(out, "retryDelay", formatDuration(*m.RetryDelay), &errs)
	}
	if m.DeletedAt != nil {
		marshalField(out, "deletedAt", formatDateTime(*m.DeletedAt), &errs)
	}
	if m.ArchivedOn != nil {
		marshalField(out, "archivedOn", formatDate(*m.ArchivedOn), &errs)
	}
	if len(errs) > 0 {
		return nil, &ValidationError{Violations: errs}
	}
	return json.Marshal(out)
}
